### ISSUE TITLE
Add Windows to Compatibility matrix

### ISSUE THREAD

**Issue by marcprux** [SwiftPackageIndex/SwiftPackageIndex-Server#1002]
The nascent Swift support for Windows is maturing to the point where it can be reliably included in CI. E.g.,: 

 • https://github.com/SwiftGFX/SwiftMath/blob/master/.github/workflows/swift.yml
 • https://github.com/glimpseio/BricBrac/actions/runs/685566445

It would be great if Windows could be added to the Compatibility matrix.

**Comment by daveverwer** [comment]
Thanks very much for the suggestion, Marc. It's funny you should bring this up now as @finestructure and I discussed this just a couple of weeks ago.

My biggest hesitance is that the matrix is already quite information-dense, and I'm not sure that the number of people using Swift on Windows is sufficient to warrant more data being added to that matrix. There's also the issue of needing Windows builder machines, which is a solvable problem but does increase maintenance and complexity of the build system.

We concluded that the time wasn't quite right now, but that we'd look at it again later.

I'll leave this issue open so we can track it through here in the future.
