### ISSUE TITLE
XprobePlugin raises 404

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1003]
Just noticed this on the new deployment but it's actually a live problem:

https://swiftpackageindex.com/johnno1962/XprobePlugin

<img width="736" alt="CleanShot 2021-03-26 at 11 25 43@2x" src="https://user-images.githubusercontent.com/65520/112618043-03e25c80-8e26-11eb-8278-bfeaed89e8ef.png">

**Comment by finestructure** [comment]
It's back now. There's #1022 with a similar issue which might allow us to see why this is happening - closing this one.

**Comment by finestructure** [comment]
Have a db snapshot and can repro this one locally.

**Comment by finestructure** [comment]
Actually, I can't reproduce it. I was getting a different error (500) because my local db hadn't been updated to the latest schema.

My best guess is that it was an issue with a `Package.swift` file that got resolved in the upstream repositories.

**Comment by daveverwer** [comment]
https://swiftpackageindex.com/SwiftyBeaver/SwiftyBeaver might be facing the same issue. Everything looks fine with a `dump-package` but it's showing a 404 right now.

<img width="897" alt="Screen Shot 2021-04-13 at 15 50 26@2x" src="https://user-images.githubusercontent.com/5180/114573089-f9babd80-9c6f-11eb-9b72-8e067338ba45.png">

I've just taken a DB dump in the current state.

**Comment by finestructure** [comment]
Some notes from debugging this:

Fails in `PackageShow+Model.init?`:
```swift
            guard let title = package.name() else { return nil }
```
wich is from
```swift
    func name() → String? { latestVersion(for: .defaultBranch)?.packageName }
```
and returns nil, because the default branch version has no package name:

![CleanShot 2021-04-14 at 11 02 42@2x](https://user-images.githubusercontent.com/65520/114687403-0264cf80-9d14-11eb-8862-feec19acd68b.png)

- 6 affected packages:
```sql
select created_at, package_id, url from versions
where latest = 'default_branch'
and package_name is null
```

```
2021-02-23 19:33:17.339539+00	bd073441-a63d-46d6-9621-898b4356132d	https://github.com/christopherweems/Resultto/tree/main
2021-02-02 23:21:45.902597+00	d3e68637-d4e2-46ee-afca-54a8c5a36bf1	https://github.com/christopherweems/Sight/tree/main
2021-04-03 22:14:43.919267+00	34aeb60a-cd7e-4810-9953-42a808925827	https://github.com/christopherweems/unstandard/tree/main
2021-03-25 12:58:12.415448+00	65e76dd9-467c-4ec8-8df2-3b74180dda04	https://github.com/SwiftyBeaver/SwiftyBeaver/tree/master
2021-03-13 14:39:00.734617+00	7abe0a5a-d4d8-42db-b196-0320291d5cf8	https://github.com/Balancingrock/BRBON/tree/master
2021-03-25 12:27:59.972468+00	11cfe4e4-bf9f-4f80-8f9e-43442486b824	https://github.com/adam-fowler/mqtt-nio/tree/main
```

- neither re-ingestion nor re-analysis picks up the package name (because the version diff sees the version as already parsed)
- `re-analyze-versions` fixes the problem
- best guess is something went wrong during the initial analysis pass
We should:
- log an error when `manifest.name` is null for the default version
- consider populating `package.name` from the latest non-nil `version.packageName`

**Comment by finestructure** [comment]
Some of these remain with package name `nil`, because they're using `swift-tools-version:5.4`, for instance https://github.com/christopherweems/Resultto/blob/main/Package.swift

**Comment by finestructure** [comment]
https://github.com/Balancingrock/BRBON has no Package.swift at all and I'm not sure how we acquired it. I'll remove it.

**Comment by finestructure** [comment]
Keeping this open for now as a reminder to:

- [ ] log an error when manifest.name is null for the default version
- [ ] consider populating package.name from the latest non-nil version.packageName

**Comment by finestructure** [comment]
We’ve got another 404: https://staging.swiftpackageindex.com/Building42/HTTPParserC

At first I thought it might be related to the 5.4 analysis change but it’s also a 404 on prod.

**Comment by finestructure** [comment]
Just retriggered this package on staging and the change didn't stick:

```
root@ecc180394cb2:/run# ./Run re-analyze-versions --id 524bb480-584f-4eca-b3f3-d7ad045ef514
[ INFO ] Re-analyzing versions (id: 524BB480-584F-4ECA-B3F3-D7AD045EF514) ... [component: re-analyze-versions]
[ INFO ] listing tags for package https://github.com/Building42/HTTPParserC.git [component: re-analyze-versions]
[ INFO ] throttled 1 incoming revisions [component: re-analyze-versions]
[ INFO ] updating 8 versions (id: 524BB480-584F-4ECA-B3F3-D7AD045EF514) ... [component: re-analyze-versions]
[ INFO ] done. [component: re-analyze-versions]
[ ERROR ] Channel error caught. [psql_connection_id: 8D408064-FE9F-4044-824A-386A41B4C0BB, psql_error: uncleanShutdown]
[ ERROR ] Channel error caught. Closing connection. [psql_connection_id: 8D408064-FE9F-4044-824A-386A41B4C0BB, psql_error: PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOSSL.NIOSSLError.uncleanShutdown))]
root@ecc180394cb2:/run# ls /
```

I have the suspicion that the missing packages might be related to these SSL errors.

**Comment by finestructure** [comment]
HTTPParserC has now recovered and I’ve just seen the latest diff:

![466C9D0B-B7A5-4200-B157-490FB48367F5](https://user-images.githubusercontent.com/65520/115136223-c5078700-a01e-11eb-95fe-0cc778a20448.jpeg)

I suspect the issue is that when there’s a default branch change we now have a 24h window of delayed update due to the default branch throttling. So these are auto-correcting, just not as fast as they used to.

**Comment by daveverwer** [comment]
That makes sense

I wonder if a better way to handle this would be to not 404 for packages that we have data for.

We currently have this slightly vague message about "if you were expecting to see a package" when we serve a 404:

<img width="864" alt="Screenshot 2021-04-19 at 09 06 36" src="https://user-images.githubusercontent.com/5180/115202715-9527b480-a0ee-11eb-89a7-0caf59d0ea3f.png">

I wonder if we should make pages where we know we have a package return something more concrete rather than falling back to a 404. If it's a missing package name, for example, we could put "Unknown Package Name" or something like that rather than failing the request.

That way a 404 would (more often) genuinely be a 404.

**Comment by finestructure** [comment]
Yes, erroring out entirely just because a package name is missing is unnecessarily harsh. I think we've got a few options here:

- "Unknown Package Name"
- look for the latest non-nil package name across all versions
- fall back to the URL (which should be available at the point where we're erroring out) and use the repo name

1 and 3 are easy, 2 is nicer but might be a bit trickier to weave in. I'm not sure we've got a db context where this is being raised.

Given how rare this is in the grand scheme of things, 3 might be a simple enough fix that's not too terrible and slightly better than "unknown".

**Comment by daveverwer** [comment]
> * look for the latest non-nil package name across all versions

Yea, I almost suggested that but then thought better of it due to the difficulty of implementing it.

Option 3 is the right way to go for package name, but we should find the other bits of information that could cause a 404 and do the same for those while we do this.
