### ISSUE TITLE
Bring back nightly db snapshots from new hosted db

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1005]

**Comment by daveverwer** [comment]
I just did a prod database dump this morning and happened to hit the site at the same time, and contrary to what we originally though, it does take the site down 😬

Very slow response, followed by:

<img width="354" alt="Screenshot 2021-05-10 at 09 29 56@2x" src="https://user-images.githubusercontent.com/5180/117629920-8cb51d80-b172-11eb-8e3a-90cf31c69772.png">

**Comment by finestructure** [comment]
If this is indeed impacting the db then I don't think we want to set up an automatic backup.

We also can't use the previous process of a file system based copy. As I see it we've got the following options:

- carefully pull copies as we do and be mindful of when we do it
- research if `pgdump` can be run without taking down the db (this must be possible?)
- increase the db size so it can handle the dump while serving queries
- automate creating an Azure snapshot, `pgdump` from that, and delete it afterwards

**Comment by finestructure** [comment]
I tempted to close this as I can't see how we'd actually automate this. Any objections/thoughts?

**Comment by daveverwer** [comment]
I take the production site down for a minute or two every few days when I take a new database dump which isn't ideal. 😬

There must be a way to dump a Postgres database without killing it. I think we should persevere with this.

**Comment by finestructure** [comment]
In that case I think it's best if we only pull down prod in cases where we need its exact data for debugging. Staging should have all the data we need for layout and design work. The only really difference is the extent and recency of builds.

To pull down prod we should create a snapshot in Azure and pull from that instead.

**Comment by finestructure** [comment]
Just to add a data point: I've just dumped the prod db to do the NIO analysis and the site was browsable the whole time without any issues. I went through all the recent packages, clicking through to the pages, did searches and clicked through to packages - no 500s at all, no slow-downs.

**Comment by daveverwer** [comment]
I also just did a prod dump and monitored the site for slowdowns and it was fine. Closing this.
