### ISSUE TITLE
Web site still showing most recently added packages from 4 days ago.

### ISSUE THREAD

**Issue by chipjarred** [SwiftPackageIndex/SwiftPackageIndex-Server#1014]
It's not a big deal, at least for me, but since I added my package yesterday and it's been merged, I looked at SwiftPackageIndex.com to see if it showed up as recently added.  The Recently Added still shows packages from 4-7 days ago.  The Recent Releases does seem to up to date.  Since there are no open issues, I thought I'd mention it just in case no one else had noticed.  I could see it being more of an issue for developers actively wanting to get as much exposure for their package as they can.

**Comment by finestructure** [comment]
That's odd and it seems to coincide with our move of the backend to new hosting. It's not clear to me how that would affect this but there certainly seems to be something wrong. Thanks for reporting it!

**Comment by finestructure** [comment]
Just for reference, this is the current view:

<img width="429" alt="CleanShot 2021-04-02 at 07 22 43@2x" src="https://user-images.githubusercontent.com/65520/113383721-cc733300-9384-11eb-8212-d7f800b2b17d.png">

**Comment by finestructure** [comment]
Our RSS feed shows the same:

<img width="313" alt="CleanShot 2021-04-02 at 07 27 45@2x" src="https://user-images.githubusercontent.com/65520/113383804-fb89a480-9384-11eb-8bf9-eafa5ba36b89.png">

**Comment by finestructure** [comment]
Staging picked this up correctly:

<img width="222" alt="CleanShot 2021-04-02 at 08 11 55@2x" src="https://user-images.githubusercontent.com/65520/113386727-2119ac80-938b-11eb-8aa5-17f388ff09ed.png">

**Comment by finestructure** [comment]
Reconcile is failing to connect to the db:

```
[ INFO ] Reconciling ... [component: reconcile]
[ ERROR ] Channel error caught. [psql_connection_id: EBB34917-47DC-40F9-8EF4-207ECC928E9B, psql_error: uncleanShutdown]
[ ERROR ] Channel error caught. Closing connection. [psql_connection_id: EBB34917-47DC-40F9-8EF4-207ECC928E9B, psql_error: PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOSSL.NIOSSLError.uncleanShutdown))]
```

**Comment by finestructure** [comment]
This is the case for all services running on `p3`. It doesn't seem to be able to connect to the db.

**Comment by finestructure** [comment]
What's odd is that `app_server` is connecting just fine from the job on `p3`:

```
[ INFO ] GET /marinofelipe/swift-package-info [component: server, request-id: 858996AA-35CF-4962-9648-31D1492F13E1]
[ INFO ] POST /api/versions/78A72B11-A475-478B-9189-F3AD5B3411DC/builds [component: server, request-id: B6103D4D-7C59-44F4-BAFD-6F6C7FA543FA]
```

**Comment by finestructure** [comment]
The new packages are now showing up:

<img width="176" alt="CleanShot 2021-04-02 at 08 36 48@2x" src="https://user-images.githubusercontent.com/65520/113388481-99ce3800-938e-11eb-8a62-6aaaf0adcd5f.png">

I'll resolve this issue and track the `p3` issue separately. Thanks again for the bug report, @chipjarred !
