### ISSUE TITLE
Reset Github API tokens

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1017]
Github updated their API auth token format: https://developer.github.com/changes/2021-04-05-behind-githubs-new-authentication-token-formats

> Hello there!
>
> We noticed that, at April 5th, 2021 at 23:07 (UTC) your application (spi-ingestor-prod, with a user-agent header of SPI-Server) accessed the GitHub API with a token that has an outdated format.
>
> In order to provide additional security benefits to all our customers, we recently updated the format of our API authentication tokens. Please update your authentication tokens to take advantage of these benefits. You can reset your token with this API endpoint: https://docs.github.com/en/rest/reference/apps#reset-a-token.
>
> To understand more about this change, and why it's important, visit https://developer.github.com/changes/2021-04-05-behind-githubs-new-authentication-token-formats.
>
> Thanks,
> The GitHub Team

- [ ] dev token updated
- [ ] prod token updated

**Comment by finestructure** [comment]
That developer.github.com link is a 404 at the moment, so maybe this email went out in error/too early.

**Comment by finestructure** [comment]
There's no indication that tokens in the old format will be deprecated. I'm not sure we need to act on this at all, certainly not straight away. Setting these tokens up with our extended quota was a bit of a hassle and I'm not keen on touching this.

**Comment by daveverwer** [comment]
I agree, let's leave it until we have to do it.

They'll give *plenty* of warning before deprecating the old ones.

**Comment by finestructure** [comment]
The emails have stopped, I don't think this anything we need to act on anymore. Will close the issue for now, can reopen if it comes up again.
