### ISSUE TITLE
Create AASA file for universal link

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1031]
From previous setup: add AASA file to be served from `.well-known/apple-app-site-association` with content:

```json
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "A42K5AU657.com.swiftpackageindex.playgrounds",
                "paths": ["/app/*"]
            }
        ]
    }
}
```

I don't quite remember the significance of `/app/*` in `paths`. I think that might be the deep link to open the app from `swiftpackageindex.com/app/`.

**Comment by finestructure** [comment]
Yes, this is how this was set up on my test domain:

* https://swifthub.site/app
* https://swifthub.site/app/
* https://swifthub.site/app?dependencies=finestructure/gala
* https://swifthub.site/app?dependencies=finestructure/gala@0.1.0
* https://swifthub.site/app?dependencies=finestructure/gala@from:0.1.0

**Comment by daveverwer** [comment]
Re-opening to track this as it's not working

**Comment by finestructure** [comment]
I've found this Apple site https://search.developer.apple.com/appsearch-validation-tool/ claiming

<img width="674" alt="CleanShot 2021-04-20 at 07 22 39@2x" src="https://user-images.githubusercontent.com/65520/115341647-43903000-a1a9-11eb-8585-75e5368f4197.png">

Things I've tried:

- change back to `path` based syntax
- use single `appID` key (instead of `appIDs`) (this was another difference)
- change back to the same AASA file I used to use (except bundle id)
- change back to exact same AASA file with `co.finestructure.Slide` bundle id + app bundle id changed

None worked.

**Comment by finestructure** [comment]
![CleanShot 2021-04-20 at 07 26 04@2x](https://user-images.githubusercontent.com/65520/115341937-ba2d2d80-a1a9-11eb-8c3a-e7d7d53f3e7f.png)

**Comment by finestructure** [comment]
More things to try:

- [ ] paste AASA file syntax straight from Apple's example, updating just the appID (i.e. path: "*")
- [ ] create a new app and bundle id to see if anything is "stale" (doesn't look like it's the app though, if the above is to be believed)

**Comment by finestructure** [comment]
Mmm, using `"paths": ["*"]` (6f3d854c4fbe2f4684e1e0a92a5e90f9f44221a3) changed something:

<img width="797" alt="CleanShot 2021-04-20 at 07 46 53@2x" src="https://user-images.githubusercontent.com/65520/115343780-b64eda80-a1ac-11eb-95cd-5c6978748339.png">

**Comment by finestructure** [comment]
https://stackoverflow.com/a/33304998/1444152

> Though Xcode created an entitlements file for me, it did not include in my build: I had to click that box manually.

I suspected something like this yesterday but the problem is that the entitlements can't be added to the App target - all the checkboxes are greyed out:

<img width="258" alt="CleanShot 2021-04-20 at 12 21 58@2x" src="https://user-images.githubusercontent.com/65520/115380629-0f316980-a1d3-11eb-96de-61b1b9f6546c.png">

The post is referring to an iOS app, so maybe it's different there. Although I do notice that there's no entitlements file in the app bundle and I'm beginning to wonder if there should be.

**Comment by finestructure** [comment]
Might be relevant: https://developer.apple.com/forums/thread/123554

**Comment by finestructure** [comment]
Also this:

> Hi,We have same problem. In the Safari universal link doesn't work only forwards to the store.But in the Notes or iMessage it works.Aslo https://search.developer.apple.com/appsearch-validation-tool/ we cannot past verification. But it worked before iOS 13 release.

from this thread: https://developer.apple.com/forums/thread/123554

That's exactly what's happening right now (except download page instead of store and obv macOS).

**Comment by finestructure** [comment]
Duplicate of #1035 , technically. We've got the file, it's just not working. Let's track these issues in a single place.
