### ISSUE TITLE
Support analysis of Swift 5.4 packages

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1037]
Swift 5.4 is imminent, and there are a few things we need to do.

This ticket tracks the progress towards being able to analyse Swift 5.4 packages, which will mean using a beta docker image, for now, upgrading to the release as it becomes available.

I'll open another ticket for updating the build system to support 5.4

**Comment by finestructure** [comment]
Just checked and for some reason the 5.4 change didn't deploy to staging. Will retry now.

**Comment by finestructure** [comment]
The problem was that the build failed with 

```
Error response from daemon: Get https://registry.gitlab.com/v2/: Get https://gitlab.com/jwt/auth?account=gitlab-ci-token&client_id=docker&offline_token=true&service=container_registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)
```

which sometimes happens.

**Comment by finestructure** [comment]
I've just re-processed the three 5.4 packages we've already got in the index on staging and it's worked fine:

https://staging.swiftpackageindex.com/search?query=christopherweems

- unstandard
- Resultto
- Sight

These were previously 404s and are fixed now.

**Comment by finestructure** [comment]
This is deployed with 2.26.0
