### ISSUE TITLE
Ingestion candidates reporting a 0 on prod

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1044]
<img width="162" alt="CleanShot 2021-04-22 at 09 27 36@2x" src="https://user-images.githubusercontent.com/65520/115673497-fea4fe80-a34c-11eb-8d00-053b5b3f7ced.png">

This should be 100 in normal operations.

**Comment by finestructure** [comment]
<img width="768" alt="CleanShot 2021-04-22 at 09 32 36@2x" src="https://user-images.githubusercontent.com/65520/115674209-b5a17a00-a34d-11eb-9e55-18353b85b66a.png">

Dropped off Tuesday morning.

**Comment by finestructure** [comment]
And we're not reporting updates due to this, I presume:

<img width="531" alt="CleanShot 2021-04-22 at 09 34 28@2x" src="https://user-images.githubusercontent.com/65520/115674468-f7cabb80-a34d-11eb-8ce5-2c09531d1327.png">

**Comment by daveverwer** [comment]
This is very strange. We definitely didn't deploy anything at 12:30am on Tuesday (unless those timestamps are in a strange timezone) so it's unlikely to be a change we deployed.

**Comment by finestructure** [comment]
The ingestion candidates query correctly selects records:

```sql
SELECT "packages"."id" AS "packages_id", "packages"."created_at" AS "packages_created_at", "packages"."updated_at" AS "packages_updated_at", "packages"."processing_stage" AS "packages_processing_stage", "packages"."score" AS "packages_score", "packages"."status" AS "packages_status", "packages"."url" AS "packages_url"
FROM "packages"
WHERE "packages"."processing_stage" = 'ingestion'
ORDER BY status != 'new', "packages"."updated_at" ASC LIMIT 10
```

→ this returns 10 rows in prod, as it should.

**Comment by finestructure** [comment]
I've restarted `p3` in case it's a connectivity issue again with that node but it had no effect.

**Comment by finestructure** [comment]
Manually running ingestion on prod shows that we're really not finding any packages to ingest:

```
[ INFO ] Ingesting (limit: 1) ... [component: ingest] (App/Commands/Ingest.swift:30)
[ DEBUG ] query read packages filters=[or [packages[processing_stage] = reconciliation, and [packages[processing_stage] = analysis, packages[updated_at] < Optional(2021-04-22 06:53:35 +0000)]]] limits=[count(1)] [component: server, database-id: psql] (FluentKit/Query/Builder/QueryBuilder.swift:297)
[ DEBUG ] No available connections on this event loop, creating a new one [component: server, database-id: psql] (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:202)
[ DEBUG ] Ingesting [] [component: ingest] (App/Commands/Ingest.swift:93)
```

Note: `Ingesting []`. This is consistent with the reported 0 candidates but inconsistent with the query result when running manually.

**Comment by finestructure** [comment]
I'll pull prod data to repro locally.

**Comment by finestructure** [comment]
Can repro locally, there are no ingestion candidates and the problem is likely that analysis wasn't updating records. The deployment 2.26.1 seems to have kicked things into gear again:

<img width="945" alt="CleanShot 2021-04-22 at 10 52 03@2x" src="https://user-images.githubusercontent.com/65520/115685941-ffdc2880-a358-11eb-8db3-48c87e3a797e.png">

Ingestion candidates still 0 but that's very likely because we don't re-ingest within the re-ingestion dead time window of 90mins.

**Comment by finestructure** [comment]
Todo:

- [ ] set alert on ingestion candidates dropping to 0
- [ ] set alert on analysis candidate dropping to 0
- [ ] set alert on GH rate limit dropping below 5k or so

**Comment by finestructure** [comment]
I can see from the terminal history that analysis was running on `p2` before 2.26.1 went up (and it is also now, on 2.26.2). So if it was another connectivity issue, it wasn't `p3`.

What's concerning is that prod is less reliable WRT processing that staging. The 3 node cluster bought us zero downtime deployments but seems to be causing us batch processing issues. May need to reconsider this.

**Comment by finestructure** [comment]
Ingestion candidates back to normal now, build backlog recovering.

<img width="946" alt="CleanShot 2021-04-22 at 12 59 05@2x" src="https://user-images.githubusercontent.com/65520/115703553-8c431700-a36a-11eb-89b2-473e72822425.png">

**Comment by finestructure** [comment]
Actually, I kept this open as a reminder to set up the alerts.

**Comment by finestructure** [comment]
I'd actually already set alerts for the three straightforward ones, and the ingestion on just fired...

**Comment by finestructure** [comment]
It's dropped from 100 → 75 → 50, it must be analysis having issues again

![Uploading CleanShot 2021-05-14 at 14.21.23@2x.png…]()

**Comment by finestructure** [comment]
I think I know what happened, and good thing I set up those alerts.

The health check I added is health checking the `app_server` container but because we run the batch jobs with the same base image - and they don't run the app service - they now fail their health checks and get restarted.

The faster ones probably manage to finish their cycle before restart but analysis apparently doesn't. I'll roll back that healthcheck change.

![CleanShot 2021-05-14 at 14 25 10@2x](https://user-images.githubusercontent.com/65520/118270401-4fc58f80-b4c0-11eb-9394-66bbcef6eae3.png)

**Comment by finestructure** [comment]
That also explains the many blue deployment annotations: it's the fast restarting of containers.

<img width="230" alt="CleanShot 2021-05-14 at 14 31 01@2x" src="https://user-images.githubusercontent.com/65520/118270996-06c20b00-b4c1-11eb-89c2-8fec2c886e1d.png">

**Comment by finestructure** [comment]
I've pulled the remaining alert into its own issue (#1099) and will close this one.
