### ISSUE TITLE
JavaScript Not Running on Async README

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1051]
I believe this may have been caused by loading it in asynchronously, I assume the JS library is not being activated on the dynamically loaded content?

Example: https://swiftpackageindex.com/Sherlouk/AccessibilitySnapshotColorBlindness

**Comment by Sherlouk** [comment]
I've also noticed a relative image URL on the same page is broken - I believe we fixed this with some JS too. So probably need to wrap it all in a function which we can call after the README has loaded.

**Comment by daveverwer** [comment]
Thanks for reporting these James!

Yea this is all a bit broken at the moment. I was halfway through the README changes and then we switched to getting the app pushed out. These will all be fixed as I implement the rest of the changes that started with the README loading becoming async.
