### ISSUE TITLE
Add backtrace

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1071]
Add backtrace https://github.com/swift-server/swift-backtrace so we can symbolicate stack traces.

**Comment by daveverwer** [comment]
Will this mean useful Rollbar notifications? 🤞

**Comment by finestructure** [comment]
No, it'll symbolicate these stack traces: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1065#issuecomment-831826415

**Comment by daveverwer** [comment]
One step closer 👍

**Comment by elfenlaid** [comment]
Seems that the new Swift 5.4 version automatically includes filename identifier along with the line number in release traces. So, only that fact should be helpful in the original issue debugging.

Also, I've failed to figure out why Backtrace doesn't affect our case's end trace.
