### ISSUE TITLE
5.4 builders running into timeouts

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1076]
Lots of 5.4 builds are timing out after 1h. We see repeated logs like:

<img width="687" alt="CleanShot 2021-05-09 at 09 13 40@2x" src="https://user-images.githubusercontent.com/65520/117563529-e5b77f80-b0a6-11eb-9f9a-2d9aa469ce52.png">

https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1247309906

or jobs that just sit there doing nothing:

- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1247589014
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1247589018
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1247589019

Then there's this job that passed just fine:

- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1247589233

So it doesn't look like a builder problem per se, if some jobs pass (plus we obviously saw working builds before we deployed this).

**Comment by finestructure** [comment]
Some more observations:

- running a build that timed out locally (CombineRealm, 2.0.1, macoc-xcodebuild) worked fine (well, it completed in a minute but failed, 5.3 succeeds)
- so far I've only seen xcodebuild based 5.4 builds timing out, i.e. no linux or spm builds. Doesn't mean they don't hang but they not surfaced

**Comment by finestructure** [comment]
The change between 5.3 and 5.4 that immediately springs to mind as the root cause of this is the new dependency cache. I've looked for a flag to disable it but couldn't find anything.

The easiest way to test this would be to set the concurrency on the 12.5 builders to 1 and re-enable 5.4 builds. We probably don't want them limited to 1 in the long run but it'd be helpful to debug this.

**Comment by finestructure** [comment]
Looks like the last package that was being processed when we rolled back to stop 5.4 is actually one that is very slow to build. We've just re-deployed 5.4 builds with concurrency 1 and both builders are about 30mins into their builds:

- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1248890395
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1248890400

There's build output and cpu consumption but output is either very slow or has ceased (line count 182 and 184). I'm running this in parallel on my M1 MBA and I'm getting the same behaviour: output + cpu activity but output slow or stuck.

**Comment by finestructure** [comment]
5.4 SPM builds for this package passed:

<img width="641" alt="CleanShot 2021-05-10 at 10 29 22@2x" src="https://user-images.githubusercontent.com/65520/117629578-9a6ea100-b17a-11eb-8040-ad752dabf507.png">

5.3 builds look as follows:

<img width="642" alt="CleanShot 2021-05-10 at 10 30 03@2x" src="https://user-images.githubusercontent.com/65520/117629721-c0944100-b17a-11eb-95cd-f9f0b24ae1d0.png">

The initial builds of this package on 5.3 are from last August, so we don't have a job url to check how fast they failed. I'll re-run locally to see if this is a build time regression.

**Comment by finestructure** [comment]
I'm disabling 5.4 again and will bump concurrency back up. Crust (the slow package from the previous comment) is still compiling on my MBA and the two builder jobs have timed out after 1h. We cannot proceed unless we exclude this package (and others like it) or find a way to report back timeouts.

Ideally, we'd set a much lower timeout (10-15min) and report back a timeout error to `app_server` so it doesn't re-trigger. This would fix the problem of having to manually downscale or exclude slow builds.

Unfortunately, Gitlab [doesn't appear to support](https://gitlab.com/gitlab-org/gitlab/-/issues/15603) a way to run a stage on timeout. I.e. it's not straightforward to implement this.

**Comment by finestructure** [comment]
I can actually reproduce the issue with endless `Resolve Package Graph` when I manually run our builder on the build machine. Perhaps something's messed up with the cache to cause a circular reference or something?

**Comment by finestructure** [comment]
Actually, just seen the M1 Mac mini is on 11.3 as well, so that can't be the reason.

**Comment by tomerd** [comment]
@finestructure for dialing the manifest cache (if you still suspect that):

```
  --manifest-cache <manifest-cache>
                          Caching mode of Package.swift manifests (shared: shared cache, local: package's build directory, none: disabled (default: shared)
```

**Comment by abertelrud** [comment]
Thank you very much for all the details, @finestructure, and the steps to reproduce it.  I can reproduce this locally, and this certainly looks like a bug.  Filing a Radar to track this would be great; that way you should get notified of progress.  Would you mind pasting the FB number here when you have done so, so I can make sure it gets routed correctly?  Meanwhile I'll look at what's going on and see if there is any immediate workaround.

**Comment by abertelrud** [comment]
I actually think I know already what's going on, and I think it's related to overriding the derived data path and the clones to write inside the package source directory.  If I located the derived data and dependencies next to the source directory instead of inside, then the resolution completes.  So that's an immediate workaround while this is fixed.

**Comment by finestructure** [comment]
Thanks a lot, Anders! I've submitted this as FB9103250.

Thanks also for finding a work-around, that's very helpful!

**Comment by finestructure** [comment]
Going to close this. In summary, we've found two separate issues:

- the build issue on Intel outlined above, which we're not currently working around but just reporting back as `timeout`
- an issue where git submodule checkouts were waiting at a prompt for host key verification on the newly setup builders
