### ISSUE TITLE
Move build log storage from AWS to Azure

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1094]
This is the only part of our infrastructure that's hosted with AWS, and now that we [have the Azure hosting](https://blog.swiftpackageindex.com/posts/hosting-the-swift-package-index/) we should consolidate our log file storage.

**Comment by finestructure** [comment]
API: https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api

The most economical way of doing this is to simply start writing new logs to Azure's Blob Storage and then in 6 - 12 months close down the S3 bucket (when we would have started expiring the old logs anyway).

For our own purposes we can still see all logs via the Gitlab link and for users a 6+ older log won't be missed. If we _do_ need a publicly visible log for an old build we can simply reschedule it.

**Comment by daveverwer** [comment]
> The most economical way of doing this is to simply start writing new logs to Azure's Blob Storage and then in 6 - 12 months close down the S3 bucket (when we would have started expiring the old logs anyway).

This sounds very sensible 👍

**Comment by finestructure** [comment]
I'm going to close this for now, since we've just actually _increased_ our commitment to S3.
