### ISSUE TITLE
Check Linux compatibility 

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1115]
Package mentions SwiftUI: https://swiftpackageindex.com/diniska/swiftui-system-colors

![C7668D19-3CF1-450F-A527-37E71DB13BFB](https://user-images.githubusercontent.com/65520/118927262-cf7caf80-b941-11eb-9412-de291b707432.png)

**Comment by finestructure** [comment]
Ok, this is _technically_ Linux compatible. It's also a no-op :)

```swift
#if canImport(SwiftUI) &amp;&amp; canImport(Combine)import SwiftUI
/// ... whole package ...
#endif
```

**Comment by finestructure** [comment]
We may want to add the ability for authors to declare incompatibility via the `.spi.yml` in such cases.

**Comment by daveverwer** [comment]
> We may want to add the ability for authors to declare incompatibility via the `.spi.yml` file in such cases.

Maaaaaybe... The other way to declare it as incompatible is to make it incompatible 😂
