### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1126]
* Cover the re-licensing
* Include some information about PR process from [here](https://discord.com/channels/844491846452379649/844491846914539554/846297540080566293)

**Comment by elfenlaid** [comment]
The follow up from the discussion:

## Merge requirements

- One+ approve
- Passing tests
- Rebased to the latest target branch

## PR’s life cycle

- Issue/Discussion
- PR’s Draft
   - Discussing
   - Resolving Comments
- PR’s RC
   - PR is ready from the author’s perspective
   - Revert to the draft stage if necessary
- Merging
   - Requirements are met
   - Maintainers press merge / schedule auto-merge
