### ISSUE TITLE
Compute `Constants.latestMajorSwiftVersion` automatically

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1136]
Just noticed this constant that's being using in computing package scores:

```swift
enum Constants {
    ...
    static let latestMajorSwiftVersion = 5
    ...
}
```

We've since added `SwiftVersion.allActive` and can compute this automatically:

```swift
    /// Currently supported swift versions for building
    static var allActive: [Self] {
        [v5_0, v5_1, v5_2, v5_3, v5_4]
    }
```

**Comment by daveverwer** [comment]
You're right, but now that we've dropped 4.2 testing it might be a good idea to increase that.

I'd say that Swift 5.2 is a good baseline for this score boost now. Or maybe we should even make it "current version - 2".

**Comment by finestructure** [comment]
But why even fiddle with that? The idea here was that once Swift 6 gets added we only need to add it in one place (`SwiftVersion`) and it'll all sort itself out automatically.

**Comment by finestructure** [comment]
Right, what I meant was - whatever the mechanism is it's orthogonal to deriving it from the list of Swift versions we maintain. If we change the rule from "latest major version" that should be reflected in how it's automatically derived rather than hardcoding a revision that'll drift if we add new ones.

I.e., once we have `SwiftVersion.latestMajor` we can change it subsequently to `SwiftVersion.latestMajor - 2`.

**Comment by daveverwer** [comment]
I agree, but think this ticket should cover both tasks. If we implement this ticket as it's specified here, it gives every package we have in the index the same boost as we don't test against Swift 4.x anymore.

**Comment by finestructure** [comment]
This issue doesn't make any changes at all, it just encodes what we're doing right now differently :)

**Comment by daveverwer** [comment]
True, but what I was trying to say is that what we're doing right now doesn't make sense now that we don't support Swift 4.x anymore, and that as we're doing this change (which I agree with), we should also bring the rule itself up to date.
