### ISSUE TITLE
Make version bullet optional

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#114]
<img width="380" alt="Screenshot 2020-05-22 at 16 05 13" src="https://user-images.githubusercontent.com/65520/82676188-40618c80-9c46-11ea-9238-e6c59ebe211b.png">

**Comment by finestructure** [comment]
We could at some point experiment here with a low key link "Why is this empy?" leading to instructions for the package maintainer to provide this info.

**Comment by daveverwer** [comment]
Yea I don't think making this disappear is the right approach, this is where we tell people to fill in `swiftLanguageVersions`. I'll throw a design together for what we do here.
