### ISSUE TITLE
Add a collection overview to package collections

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1159]
It currently says "This collection does not have an overview" when adding a collection to Xcode.

<img width="495" alt="Screenshot 2021-06-08 at 12 59 46@2x" src="https://user-images.githubusercontent.com/5180/121181016-770e4300-c859-11eb-9cf8-2b652cc79e4a.png">

It should say "A collection of packages authored by Vapor from the Swift Package Index"

**Note:** Use the full owner name rather than just the owner username when building this description

**Comment by at-syot** [comment]
Hi, this should relate with [this task](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1160), so i can take both.
