### ISSUE TITLE
Make the archived status of repositories more obvious

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1175]
Inspired by #1174.

If we do this, we should add another list item at the top of the `main_metadata` section. The icon can be a yellow warning sign, like the emoji suggested in the original PR, but should be in the same style as the other icons in the list.

**Comment by selichter** [comment]
I can take this issue.

**Comment by daveverwer** [comment]
Sounds good, thanks Sarah!

**Comment by daveverwer** [comment]
Closed by #1220 and #1221
