### ISSUE TITLE
Smoke test failure since 2.41.0

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1204]
For some reason I'm not consistently getting failure emails from Gitlab. Our smoke test has been failing since the 2.41.0 deployment:

<img width="438" alt="CleanShot 2021-06-30 at 08 12 01@2x" src="https://user-images.githubusercontent.com/65520/123910548-e4a22080-d97a-11eb-9db4-d591393528ce.png">

The reason is the change in JSON format our search API returns:

<img width="681" alt="CleanShot 2021-06-30 at 08 13 26@2x" src="https://user-images.githubusercontent.com/65520/123910660-12876500-d97b-11eb-88b1-dc0f5f22f0a4.png">

It clearly doesn't affect our search itself but I think this will impact @helje5's SwiftPM Catalog app.

**Comment by finestructure** [comment]
The format change is that `Search.Result` has changed from a plain struct to an enum with associated values:

```swift
    enum Result: Equatable {
        case keyword(KeywordResult)
        case package(PackageResult)
```

where `PackageResult` is the previous struct. The `Codable` format is current custom but such that it'll match Swift 5.5 autogenerated conformance.

The smoke test diff shows it best:

<img width="533" alt="CleanShot 2021-06-30 at 08 26 01@2x" src="https://user-images.githubusercontent.com/65520/123912045-d523d700-d97c-11eb-85c7-2a3e77a1c29c.png">

**Comment by daveverwer** [comment]
I still _never_ receive the smoke test results, so you're one step ahead still 😂
