### ISSUE TITLE
Keyword route error page

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1219]
We use the same 404 error page on any route which cannot be found.

I think it would be nice, for some routes, to offer a more helpful message.

Take this keyboard route: https://staging.swiftpackageindex.com/keywords/james-is-awesome

>Something went wrong. Sorry!
>404 - Not Found
>
>If you were expecting to see a page here, the site might be in the process of re-indexing this package. Please try again in an hour or two.

I think this would be nicer if this instead returned something like

> No packages were found with the keyword 'james-is-awesome'.

**Comment by daveverwer** [comment]
Fixed

![Screenshot 2021-07-06 at 16 50 10@2x](https://user-images.githubusercontent.com/5180/124630404-4e8a6080-de7a-11eb-9d9a-11cdfe748ec3.png)

**Comment by Sherlouk** [comment]
😂 😂  Thanks Dave! (actually made me chuckle)

**Comment by daveverwer** [comment]
To be serious, though. I never liked this wording on the package page 404. I think I'd like the fix to this to be to remove that wording rather than to add more special case wording.

@finestructure I'm not sure packages disappear from the index now we have better safety around missing package names etc... Do you remember if there were other cases where the package would disappear, or if this was the only one?

**Comment by Sherlouk** [comment]
I don't think this is just a case of adding more special wording though, but more making errors more context aware.

Though I'd be interested to know how you think we should be handling errors on this and the author page.

**Comment by finestructure** [comment]
There were cases when a package had no package name but I'm pretty sure that that particular issue can't occur anymore (we substitute something sensible IIRC).

One case we can't fix is an invalid `Package.swift`. I think that'll still make a package drop from search even if it's still in the index.

**Comment by daveverwer** [comment]
I made the error message more generic in #1243. I don't think we need to do more than that, or at least I think there are higher priorities. I think this solves the immediate problem so I'm closing this with that PR.

<img width="894" alt="Screenshot 2021-09-06 at 16 59 57@2x" src="https://user-images.githubusercontent.com/5180/132242191-044b52ff-c8a8-44ee-8aa8-ba79331556bf.png">
