### ISSUE TITLE
Display feedback about any filters have been applied during a search

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1228]
To enable better debugging of filtered search, and a better explanation of what happened for people searching we need to describe what the results are in a better way.

Currently, above the search results, it shows this:

<img width="857" alt="Screenshot 2021-07-12 at 09 11 08@2x" src="https://user-images.githubusercontent.com/5180/125255911-d269a000-e2f3-11eb-98cd-4dc470a76413.png">

We should break down what's being searched for and display a readable explanation of it. Something along the lines of this:

> Results for “test” where [Last commit date] [is >] [2021-01-01], [Number of stars] [is >] [500], and [Platform] [is compatible with] [iOS and macOS]

We should use styling to separate the different bits of that sentence surrounded by square brackets, so make sure each clause is wrapped in a span. I can help with the styling when it comes to that.

We could either display this in a sentence format or as a set of rows below the results line. Something along the lines of this:

<img width="1366" alt="Swift Package Index - 2021-07-12 09 26 06" src="https://user-images.githubusercontent.com/5180/125256545-72bfc480-e2f4-11eb-8540-1747e0463406.png">

If there is no actual search term, it should say "Results for all packages" where ...

**Comment by Sherlouk** [comment]
100% agreed, and this is something I tried to capture in my original PR by "Update the search results page to show the filters separate to the search terms". This is very much needed but I didn't want to inflate what was already there.

I think the steps here would be to add something like this to the search results response object:

```
{
  query: {
    term: "dave is bored of reviewing james' code",
    filters: [
      { key: "updated", operator: "exact", value: "2020-01-01" }, // object style - OR -
      { key: "Last commit date", operator: "=", value: "2020-01-01" }, // object view model style - OR -
      "Last commit date on exactly 2020-01-01" // full view model style
    ]
  }
}
```

As to the displaying of this data, I prefer the second (rows) idea you have above.

**Comment by daveverwer** [comment]
> As to the displaying of this data, I prefer the second (rows) idea you have above.

Me too
