### ISSUE TITLE
Enhance search filter grammar

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1229]
https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/1226#discussion_r667631792

These are just ideas, and not instructions.

* Support for `>=` and `<=`
* Support for OR clauses `platform:ios|macos`
* Support for grouped clauses `((platform:ios stars:>5) OR (platform:macos stars:<5))`
* Support for strings `license:"MIT 2.0"`

**Comment by finestructure** [comment]
With the initial search filter extension in place now, I wonder if we should close this issue and make any further extension a discussion first before scheduling any concrete issues with what to add. Otherwise this'll stay open forever :)

**Comment by daveverwer** [comment]
Sven is in full-on "reduce the number of open issues" mode 😅 

Consolidated into https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/1403#discussioncomment-1728037
