### ISSUE TITLE
Community wide "good first issue" overview

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1266]
@fabianfett suggested the SPI might be a good place to aggregate and show "starter" issues, i.e. issues in projects that are typically tagged with "good first issue".

The idea is to make it easier for people interested in contributing to open source projects to get an overview of what projects have starter issues and more easily browse them.

**Comment by daveverwer** [comment]
This ties in well with some of what we've been discussing for the home page (which there isn't an issue for yet). I also want to tag #852 here as we start to bring some of this together.

Thanks @fabianfett!
