### ISSUE TITLE
ValueCodable failing macos-xcodebuild/5.5

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1267]
This isn't failing with macos-xcodebuild/5.4 and I don't think there's anything in it that would be a package build failure with 5.5. Might be a build system issue.

https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1638242989

```
xcodebuild: error: Building a Swift package requires that a destination is provided using the "-destination" option. The "-showdestinations" option can be used to list the available destinations.
```

<img width="737" alt="CleanShot 2021-09-30 at 17 04 17@2x" src="https://user-images.githubusercontent.com/65520/135481103-8daffd30-7132-40c1-b533-55a12485bd0e.png">

**Comment by finestructure** [comment]
After triggering a re-run, there's only one failure for 5.5: https://swiftpackageindex.com/builds/8085FC04-7A2F-4C63-B881-1E8B6DF881E5 and for watchOS where Swift < 5.3 (which might be expected).

<img width="735" alt="CleanShot 2021-11-17 at 07 54 00@2x" src="https://user-images.githubusercontent.com/65520/142149496-79439e96-c9e1-4ccb-8b20-694e06c26ba9.png">

[ValueCodable – Build Results – Swift Package Index.pdf](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/files/7552403/ValueCodable.Build.Results.Swift.Package.Index.pdf)

**Comment by daveverwer** [comment]
No changes to the build system between these? Do we have the logs from the original builds? Was it a reasonable failure?

**Comment by finestructure** [comment]
The log is linked above :)

My best guess it's the Xcode update from 13.0b5 to 13.1.

**Comment by finestructure** [comment]
The `macos-xcodebuild-arm` build fails on `spi-mb1-builder`, which is an Intel machine:

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:macos, arch:arm64 }
```

This is the exact same problem I observed in #1282 and fixed by tagging the builder. The tag went in:

<img width="384" alt="CleanShot 2021-11-19 at 15 33 46@2x" src="https://user-images.githubusercontent.com/65520/142639771-a7ba35bf-5df8-4d14-99a8-a5ad92c9373a.png">

but it's gone for some reason. Must have been rolled back accidentally or something.

**Comment by finestructure** [comment]
Ah no, it's not gone. I was on an older revision locally.

Somehow this build got scheduled on an Intel builder despite the arm tag.

**Comment by finestructure** [comment]
Right, I only added the `- arm` tag to the test matrix gitlab CI file, not the actual build trigger file 🤦

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/84

**Comment by finestructure** [comment]
There are 7.2 failed Swift 5.5/macos-xcodebuild-arm builds. Some/a lot/most of these might have been affected by this bug. I'll start deleting them in batches for reprocessing after this change has been deployed.

```sql
select *
from builds
where platform = 'macos-xcodebuild-arm'
and status = 'failed'
and swift_version->'major' = '5'
and swift_version->'minor' = '5'
```

**Comment by finestructure** [comment]
I'll hold off scheduling these for rebuild until we've sorted out our arm runner issue. Don't want to add more builds when our single arm runner keeps going offline.

**Comment by finestructure** [comment]
For some reason the re-build isn't triggered:

<img width="751" alt="CleanShot 2021-11-22 at 08 51 07@2x" src="https://user-images.githubusercontent.com/65520/142823201-ba9722f8-60d7-4efd-b257-034e90f12eb6.png">

This build has been marked "pending" in the UI since yesterday. There's no "build stub", i.e.

```sql
select * from builds
where version_id = 'd71bce49-a419-44f6-805a-cccf9edb672f'  -- version 0.1.0 of ValueCodable
and swift_version->'major' = '5'
and swift_version->'minor' = '5'
and platform = 'macos-xcodebuild-arm'
```

is empty. Which means it's probably not being triggered, i.e. it's likely not that it's being triggered but stuck in the build pipeline somewhere.

There is a small chance that it's being triggered, gets stuck, and is being garbage collected and I just happen to only look in the table when it's not in `triggered` state. That window should be pretty small though.

Checking this locally now.

**Comment by finestructure** [comment]
Ok, mystery solved. The way triggering builds works is that it fetches all builds for a given version and checks it against the currently supported versions. Any builds not in `Set(BuildPair.all).subtracting(Set(existing))` get triggered.

Now we don't want to do this blindly for all versions on every loop of the build trigger invocation (every 2 mins or so). So in order to find _packages_ whose versions to check, we do:

```sql
            SELECT package_id, min(created_at) FROM (
                SELECT v.package_id, v.latest, MIN(v.created_at) created_at
                FROM versions v
                LEFT JOIN builds b ON b.version_id = v.id
                WHERE v.latest IS NOT NULL
                GROUP BY v.package_id, v.latest
                HAVING COUNT(*) < \(bind: expectedBuildCount)
            ) AS t
            GROUP BY package_id
            ORDER BY MIN(created_at)
```

in `fetchBuildCandidates`. That's the preselect for `findMissingBuilds`. `expectedBuildCount` is currently 36.

However, we've recently dropped 5.0 from the supported builds – but we didn't delete existing 5.0 builds. So what's happening is that despite the missing 5.5 build there are still a couple of 5.0 builds hanging around what keep the total count above the package candidate selection and we never even get to the `findMissingBuilds` stage.

I'll delete all 5.0 builds from the db and [update our docs](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Infrastructure/blob/main/Add%20support%20for%20a%20new%20Swift%20version%20(analysis%20%2B%20build%20system).md) to include a note that we need to remove old builds.

**Comment by finestructure** [comment]
And fixed:

<img width="746" alt="CleanShot 2021-11-22 at 11 46 38@2x" src="https://user-images.githubusercontent.com/65520/142848053-c317bc6b-7849-46ac-92c2-3eb42e178e7d.png">

**Comment by finestructure** [comment]
I went ahead and deleted all failed 5.5/macos-xcodebuild-arm builds via

```sql
delete from builds where id in (
	select id
	from builds
	where platform = 'macos-xcodebuild-arm'
	and status = 'failed'
	and swift_version->'major' = '5'
	and swift_version->'minor' = '5'
)
```

We're actually triggering with a package limit of 2 per minute, i.e. even though we're creating a big backlog of unprocessed arm builds we won't be swarming the arm builder with them.

```
2021-11-22 14:24:41	
[ INFO ] Triggering builds (limit: 2) ... [component: trigger-builds]
2021-11-22 14:23:38	
[ INFO ] Triggering 1 builds for package name: MapboxCommon, ref: v20.1.0 [component: trigger-builds]
2021-11-22 14:23:38	
[ INFO ] Triggering 1 builds for package name: SemVer, ref: 3.0.0-Beta.5 [component: trigger-builds]
```

I'll add some more builds by manually triggering them but that's just to speed up the backlog processing. It'll catch up in its own time regardless.
