### ISSUE TITLE
Don't report timed out builds as "pending"

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1272]
https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/307#issuecomment-934086157

We seem to be showing timed out builds as "pending":

![CleanShot 2021-10-05 at 07 45 14@2x](https://user-images.githubusercontent.com/65520/135967175-e2b64868-b682-4084-acd5-5fb523ed8b05.png)

<img width="716" alt="CleanShot 2021-10-05 at 07 44 04@2x" src="https://user-images.githubusercontent.com/65520/135967025-f76f3d53-92f4-4345-a57e-28c86b232d20.png">

**Comment by finestructure** [comment]
Ok, this was actually as intended - and it's confusing. I've updated our snapshot test with all status:

```swift
.init(id: Self.id, swiftVersion: .v5_5, platform: .ios,                status: .ok),
.init(id: Self.id, swiftVersion: .v5_5, platform: .macosSpm,           status: .failed),
.init(id: Self.id, swiftVersion: .v5_5, platform: .macosXcodebuild,    status: .pending),
.init(id: Self.id, swiftVersion: .v5_5, platform: .macosSpmArm,        status: .timeout),
.init(id: Self.id, swiftVersion: .v5_5, platform: .macosXcodebuildArm, status: .infrastructureError),
```

And here's the resulting build view:

<img width="300" alt="CleanShot 2021-10-05 at 08 16 29@2x" src="https://user-images.githubusercontent.com/65520/135970489-e3384280-8a04-4bdb-a5bf-eba893ab2225.png">

The idea was to reduce the statuses on the user facing side to:

- ok
- failed
- imminent
- later

Where "imminent" are `.pending` builds that'll presumably be picked up by the build queue next and "later" are builds that were picked up but didn't report back for whatever reason and will be retried in a few hours.

I don't think our names reflect that well (calling it pending with different meanings is very confusing 😅) and is actually wrong in case of timeouts: we don't retry timeouts.

**Comment by daveverwer** [comment]
Yes, this is confusing. Do we cover the case in this test where a build has not yet been scheduled? That's the *true* pending case.

We should show Queued for the `pending` state as that's true. We should also show Pending for any state where we will automatically retry, or where the build has never been attempted. We should show what happened (eg. "Build Timed Out") if we are not going to retry.
