### ISSUE TITLE
Unexpected build failures in pointfreeco/swift-identified-collections

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1282]
Stephen reported this via DM. My understanding is the package should support all platforms (Swift 5.3+ probably).

https://swiftpackageindex.com/pointfreeco/swift-identified-collections/builds

![3C011BC6-2766-4754-9EC0-CE628391BFDB](https://user-images.githubusercontent.com/65520/136616415-ee79b949-cb77-44d7-9a77-8f4e2deb5afd.jpeg)

cc @stephencelis

**Comment by stephencelis** [comment]
My assumption is we may need to configure an spi.yml file or something. There's an [internal target](https://github.com/pointfreeco/swift-identified-collections/blob/f76e7d3fe4265ee09216044ec3780d74f546ca82/Package.swift#L34-L40) that should only build on macOS/Linux, but the public `IdentifiedCollections` product builds fine on all platforms.
