### ISSUE TITLE
test benchmark errors on 8th iteration

### ISSUE THREAD

**Issue by trozware** [SwiftPackageIndex/SwiftPackageIndex-Server#1332]
I tried twice, trashing the Docker container and re-running the make commands each time.

[error.txt](https://github.com/SwiftPackageIndex/spi-benchmark/files/7489514/error.txt)

**Comment by daveverwer** [comment]
For me it was always the 10th or 11th iteration 😱 but I did not see anyone from the results that I added to the benchmark manage to run the tests 20 times successfully on *any* machines.

**Comment by finestructure** [comment]
After 60 runs I'm finally getting this error again. This is going to be hard to verify 😅
