### ISSUE TITLE
Clicking on "Copy Package CollectionURL" button triggers collection generation

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1340]
I just discovered this while looking into instrumentation. Clicking this button:

<img width="874" alt="CleanShot 2021-11-10 at 16 27 25@2x" src="https://user-images.githubusercontent.com/65520/141141820-586f2b63-b00f-4926-9b6c-9049ddd968a4.png">

calls into `PackageCollectionController.generate`. I don't _think_ this should be happening - we should just be putting the string that's already on the page in the text field onto the clipboard, right?

I'm running this locally with a breakpoint in the method and it's hit as soon as I click the button.

**Comment by daveverwer** [comment]
Yea, that shouldn't be calling out to the server at all. I'll investigate and fix

**Comment by finestructure** [comment]
Ah great. I was poking around a bit but you'll find this much faster.

**Comment by finestructure** [comment]
I wonder if this is a Safari (or Safari Tech Preview) thing: I've just _pasted_ the collection url into the browser bar - without hitting return - and the breakpoint's being hit. It seems to be aggressively pre-fetching urls?

**Comment by finestructure** [comment]
I've looked at the requests for a "pre-fetch" and an "actual" GET and it's turned up something interesting:

Safari Tech Preview prefetch:
```
(lldb) po req
GET /apple/collection.json HTTP/1.1
Host: localhost:8080
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0
Accept-Language: en-GB,en;q=0.9
Accept-Encoding: gzip, deflate
Connection: keep-alive
```

Safari Tech Preview actual:
```
(lldb) po req
GET /apple/collection.json HTTP/1.1
Host: localhost:8080
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Accept-Language: en-GB,en;q=0.9
Accept-Encoding: gzip, deflate
Connection: keep-alive
```

The `User-Agent` of the pre-fetch has an additional value `facebookexternalhit/1.1 Facebot`. I'm wondering if it's some sort of extension at work?

Although I'm getting the same when using a Fluid created SSB, and I'm not sure that'd use extension.

**Comment by finestructure** [comment]
I'm also quite creeped out that something with `facebook` in the user agent seems to be hitting urls when I'm clicking on a button or pasting a url.

Are you seeing the same thing?

**Comment by finestructure** [comment]
Perhaps related, I've noticed the following in the console when I click the button:

```
[ INFO ] GET /apple-touch-icon-precomposed.png [component: server, request-id: 8DAF6277-773D-42EB-B58C-105E352D05D6]
[ ERROR ] ErrorPage.View 404: Abort.404: Not Found [component: server]
[ ERROR ] ErrorPage.View 404: Abort.404: Not Found [component: server]
[ ERROR ] ErrorPage.View 404: Abort.404: Not Found [component: server]
[ INFO ] GET /apple-touch-icon-precomposed.png [component: server, request-id: 40F1268D-6A24-4CF5-B823-4FC950F3DA28]
[ INFO ] GET /apple-touch-icon.png [component: server, request-id: C1F129C4-409E-4830-AF95-86AA5362587C]
[ INFO ] GET /favicon.ico [component: server, request-id: 4C8E7068-D8ED-47A0-87FE-8D8977A39642]
[ INFO ] GET /tapsandswipes/collection.json [component: server, request-id: 43F5A3F9-DB96-4E41-8150-50A507C586B0]
```

The last request (`.../collection.json`) is the GET for the copied url. The three 404s I'm pretty sure correspond to the three `apple-touch-ison` requests coming in. I wonder if those are related to the GET for the collection.

**Comment by finestructure** [comment]
These seem to be related to web clips: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by finestructure** [comment]
Yes:

```
[ NOTICE ] Server starting on http://127.0.0.1:8080 [component: server]
[ INFO ] GET /favicon.ico [component: server, request-id: DF52BB13-C382-4A4F-A203-46AACF7BEEEB]
[ INFO ] GET /apple-touch-icon.png [component: server, request-id: A9C86689-FABE-4585-B902-B81C44C2C3DB]
[ INFO ] GET /tapsandswipes/collection.json [component: server, request-id: 92771C50-0BF4-4EAD-8E7E-DE99001CE085]
[ INFO ] GET /apple-touch-icon-precomposed.png [component: server, request-id: BFF747CC-570C-412B-8591-CA69FEAAF199]
⚠️ GET request received
[ ERROR ] ErrorPage.View 404: Abort.404: Not Found [component: server]
ℹ️ 404: /favicon.ico
[ ERROR ] ErrorPage.View 404: Abort.404: Not Found [component: server]
ℹ️ 404: /apple-touch-icon.png
[ ERROR ] ErrorPage.View 404: Abort.404: Not Found [component: server]
ℹ️ 404: /apple-touch-icon-precomposed.png
```

**Comment by finestructure** [comment]
The same behaviour (prefetch on button click) is happening with Google Chrome. So it's not something Safari specific.

**Comment by finestructure** [comment]
This is _not_ happening when running the server in a fresh account on my machine. So it must be some app or service that does the url tickling.

**Comment by finestructure** [comment]
It's Paste.app, my clipboard manager. It tickles the urls when they're added to the pasteboard.

I'm not sure yet if I'm happy with that but at least I know what's happening and it has nothing to do with our site!

**Comment by finestructure** [comment]
Actually, nothing nefarious. It's simply "Enable link previews", which I had enabled:

![CleanShot 2021-11-25 at 12 29 11@2x](https://user-images.githubusercontent.com/65520/143433864-de39e621-e4d9-42e1-8744-5cb43661cb70.png)
