### ISSUE TITLE
Incorrect build tools used for build

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1373]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/drmohundro/SWXMLHash

**Please explain what data is incorrect and what you expected to see**

The site is claiming that this package supports Swift 5.1 and 5.3 but not 5.2. While technically possible, it feels fairly unlikely.
On a deeper dive though, it looks like the builds themselves failed due to an SPI issue - not the project itself.

https://swiftpackageindex.com/builds/157BC3B2-8C1D-49A9-B0EC-88D100CD34DE

**Screenshots**

![Captured 2021-11-14 at 11 34 34](https://user-images.githubusercontent.com/15193942/141679109-9b1c3174-c620-4a34-9d2c-0a58e1dbc605.png)
![Captured 2021-11-14 at 11 34 49](https://user-images.githubusercontent.com/15193942/141679114-413eca16-1ae0-41e1-9913-98796a6
![Captured 2021-11-14 at 11 34 57](https://user-images.githubusercontent.com/15193942/141679119-78ccacad-9d49-43ff-a28f-afe033f0d7de.png)
75cc1.png)

**Additional context**

Other libraries (Alamofire) are successfully passing on Swift 5.2 so 🤷  Might be a one off and nothing to worry about?

**Comment by finestructure** [comment]
Thanks for the report, James!

This seems to be correct: The `Package.swift` file has `// swift-tools-version:5.3` in the preamble, which makes it fail for any swift version < 5.3. The surprising thing is that it _passes_ with Swift 5.1 despite that. But if you look in the repo, you'll notice there's a `[Package@swift-5.1.swift](Package@swift-5.1.swift)`, which pulls it back for that Swift version.

This actually exposes that the authors should add a Swift 5.2 package manifest!

**Comment by Sherlouk** [comment]
Absolute great spot, had completely missed that. Thanks Sven!
