### ISSUE TITLE
Bug when running `git log` commands

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#139]
After the logging in #136 it's a little clearer that there's an error with the code to gather the history  metadata from git. When running against some repositories, there are errors like this:

```
[ ERROR ] analysis error: Shell command failed:
command: "git log -n1 --format=format:"%H-%ct" 0.1.0"
path:    "/Users/dave/Development/SwiftPackageIndex/Checkouts/github.com-fabianfett-vapor-lambda-runtime"
message: "ShellOut encountered an error
Status code: 128
Message: "fatal: ambiguous argument '0.1.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
Output: """
```

Running `git tag` on that repository shows the error clearly:

```
v0.1.0
v0.2.0
v0.3.0
```

The `v` is being omitted from the tag, probably as it's being stripped as it's not technically a valid version. We'll need to keep the original tag name around as well as the parsed semantic version.

Running the exact same command with the correct tag name works well:

```
git log -n1 --format=format:"%H-%ct" v0.1.0
```

Outputs:

```
8ecc257775d0567cf404287d2c7a40cee7d033d4-1579047775
```

**Comment by finestructure** [comment]
Oh, right! I'll have to think about to best fix this, that might be tricky.

**Comment by daveverwer** [comment]
I think the only way is to add another field in the database that stores the tag name as a string. 

It’s not duplicate data. The version is derived from the tag name, but that can’t be reversed.

**Comment by finestructure** [comment]
Just noticed while working on the fix that this is also an issue for our version links to `.../releases/<tagName>`, which are broken.
