### ISSUE TITLE
Set up issues redirects from the PackageList repository to here

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1439]
- [x] Respond to https://github.com/SwiftPackageIndex/PackageList/issues/1177 and close it
- [x] Add a placeholder issue explaining that that repository is specifically for package list issues.
- [x] Add a `.github` issue template so when people hit "New Issue" it redirects to this repository for software issues and allows issues only for removing packages or other package list issues.

**Comment by finestructure** [comment]
Should we switch off issues on PackageList entirely?

**Comment by daveverwer** [comment]
No. I think we should keep them on as people do reach for them when they have a problem. This issue is important, though. I'll get this implemented today.

**Comment by daveverwer** [comment]
This is now done. The only option in the issue template which opens an issue on PackageList is to remove a package. Everything else redirects to here.

<img width="861" alt="Screenshot 2022-02-15 at 17 51 24@2x" src="https://user-images.githubusercontent.com/5180/154120047-018a6a05-5543-4830-8a3f-f8c6826bbc08.png">
