### ISSUE TITLE
Squash schema

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#145]

**Comment by finestructure** [comment]
We shouldn't do this too late, because if we wipe the data, the recent packages query will be weird until updates straighten them out. We should also consider this for a potential move to MacStadium.

One way to correct that is to manually fiddle with package creation dates in the db - but that's a bit ugly...

**Comment by daveverwer** [comment]
This is a good point. I'll think about chasing that email tomorrow to see where we stand.

**Comment by daveverwer** [comment]
As we do this, let's change the materialised view to have a limit of 100 so that #64 can include more than 10 packages in the feed.
