### ISSUE TITLE
Swift 5.5.2 or Xcode 13.2 required for Concurrency backward compatibility

### ISSUE THREAD

**Issue by chris-araman** [SwiftPackageIndex/SwiftPackageIndex-Server#1465]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/chris-araman/AsyncCloudKit

**Please explain what data is incorrect and what you expected to see**

Swift's `async`/`await` concurrency keywords were introduced in Swift 5.5 (Xcode 13), but required the 2021 OS releases (macOS 12, iOS 15, etc.). Apple later released Swift 5.5.2 and Xcode 13.2 which brought backward compatibility to the 2019 OS releases (macOS 10.15, iOS 13, etc.).

[AsyncCloudKit](https://github.com/chris-araman/AsyncCloudKit) provides async extension methods for CloudKit. Its `Package.swift` declares support for macOS 10.15, iOS 13, etc. However, it requires Swift 5.5.2 (or Xcode 13.2) or later in order to build for those minimum targets. With Swift 5.5 (or Xcode 13), it can be compiled only for macOS 12, iOS 15, or later.

SwiftPackageIndex doesn't yet seem to build using Swift 5.5.2 or Xcode 13.2, so the [compatibility report](https://swiftpackageindex.com/chris-araman/AsyncCloudKit/builds) for AsyncCloudKit is empty.

I suspect the maintainers haven't yet found time to update to Xcode 13.2(.1), but I wanted to call out this issue specifically as it would affect any packages using Concurrency with platforms older than 2021.

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

The problem applies to all builds on Apple platforms. Linux is not supported by AsyncCloudKit because CloudKit is not generally available on Linux.

**Comment by finestructure** [comment]
> I suspect the maintainers haven't yet found time to update to Xcode 13.2(.1), but I wanted to call out this issue specifically as it would affect any packages using Concurrency with platforms older than 2021.

Yes, indeed. The build system is currently using Xcode 13.1 and the `swift:5.5` docker label to build packages.

Thanks for flagging this. The concurrency back port has created a bit of urgency for us to bump the Swift version once again.

**Comment by finestructure** [comment]
Builder PR: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/87

**Comment by chris-araman** [comment]
Thanks!
