### ISSUE TITLE
Change Score.compute to take defaultBranch version and release count

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1470]
It currently takes all versions but only uses the release count and some default version info. We can make the call into `Score.compute` in `updatePackages` (`Common.swift`) cheaper by not loading all versions.

**Comment by daveverwer** [comment]
Closing this. As part of #1793 we need to bring the latest stable release into the score calculation.

**Comment by finestructure** [comment]
This fix is showing weird performance behaviour. We've deployed this in two parts on `dev`:

- d6216bfe86cbab893a5a68495b4f37b0a6b42826 was just the preparatory changes, mostly ELF → a/a
- cadc77d9e5e36d7f0aafbbc9ea78b2f86af95244 was the change to skip loading versions in ingestion and passing the already computed versions into `updatePackages` in analysis

Here's what's happening on `dev`:

![CleanShot 2022-10-27 at 10 29 46@2x](https://user-images.githubusercontent.com/65520/198233132-9103628d-0bd1-4ebf-98b1-5da12a3cc1cf.png)

I've also seen weird performance after deploying the second part (cadc77d9e5e36d7f0aafbbc9ea78b2f86af95244) yesterday afternoon, so it doesn't seem to be a fluke.

Both times I've seen elevated CPU of the analysis job, which seems to hover around 20-25%.

![CleanShot 2022-10-27 at 10 23 49@2x](https://user-images.githubusercontent.com/65520/198234882-2ed78fde-7d27-449e-a4fa-04183adbae1c.png)

Also, analysis doesn't seem to progress:

![CleanShot 2022-10-27 at 10 24 06@2x](https://user-images.githubusercontent.com/65520/198234980-6b329a3f-0bdd-4cb4-b89e-8e480fd7552b.png)

The time of the screenshot was 10:24 and the last analysis log was 10:01. Normally, this should update at least every 20s or so.

**Comment by finestructure** [comment]
What's odd is that the second part of the fix should be the less problematic one 🤷‍♂️

I'll back out of this change now so that we can continue deploying generally and then I'll try and break down this change further and deploy it piece by piece.

I'll also delete the 2.78.16 tag so we don't accidentally deploy it or roll back to it. No 2.78.16 images have been produced yet, so there's no risk of a collision when we re-tag:

```
 docker-user@bastion  d1  ~  docker pull registry.gitlab.com/finestructure/swiftpackageindex:2.78.16                           371ms
Error response from daemon: manifest for registry.gitlab.com/finestructure/swiftpackageindex:2.78.16 not found: manifest unknown: manifest unknown
```

**Comment by finestructure** [comment]
Next tag should be 2.78.17, let's not re-tag since there are clones of the repo out there.

**Comment by finestructure** [comment]
We had another weird issue last night, on revision 7bfe274aaf828870162dcd47efeefec060aa8aa0 (which is basically e4513d8ebfae839a4746acaad75715a342a74ecf plus debug logging: ingestion just got stuck (no more logs), like analysis did the day before.

<img width="1329" alt="CleanShot 2022-10-28 at 12 21 12@2x" src="https://user-images.githubusercontent.com/65520/198565241-e19d99a2-f2b1-41e3-af40-44b0b7d773cd.png">

This didn't seem to be related to any deployment. It happened more than 2h after 7bfe274aaf828870162dcd47efeefec060aa8aa0 was deployed 🤷‍♂️

**Comment by finestructure** [comment]
I'm going to let 10bde735b475f66c2ea49dccd05ebcb9958df614 (which is `issue-1470-part-4` ad-hoc deployed) run for 24h to see if this is recurring.

**Comment by finestructure** [comment]
It happened again, this time on `analyze`:

<img width="1151" alt="CleanShot 2022-10-31 at 09 26 47@2x" src="https://user-images.githubusercontent.com/65520/198964484-0e20c699-5872-4bfd-b26c-706900b87ace.png">

We know that the following revisions are bad:

- 10bde735b475f66c2ea49dccd05ebcb9958df614
- 7bfe274aaf828870162dcd47efeefec060aa8aa0 → and therefore current `main` e4513d8ebfae839a4746acaad75715a342a74ecf

I'll back us out of the complete change now. We need to clear up to be able to push changes through.
