### ISSUE TITLE
Vapor compatibility matrix is gone after #1072

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1471]
![15914E14-0AEB-4D76-83E1-F20CA414E2CE](https://user-images.githubusercontent.com/65520/147749537-f32b00ed-dabb-445d-a1d9-fe58853f7d34.png)

**Comment by daveverwer** [comment]
That's curious, it's showing for me.

<img width="880" alt="Screenshot 2021-12-30 at 11 53 43@2x" src="https://user-images.githubusercontent.com/5180/147749695-511e50fc-5ea9-4cf6-abc8-6d38d01e52ae.png">

**Comment by finestructure** [comment]
Weird. That's from an iPad mini. Do we have a display issue in some cases? I've reloaded but I'll double check again.

**Comment by finestructure** [comment]
Same on my phone:

![image](https://user-images.githubusercontent.com/65520/147750141-5037f6ec-aadd-4210-b7c2-42bb6f276335.png)

**Comment by finestructure** [comment]
Actually, I think the compatibility matrix is gone for all packages on mobile it seems.

**Comment by daveverwer** [comment]
My bad, I was checking prod not staging. 😅 

The compatibility matrix has gone for all packages on all browsers:

<img width="890" alt="Screenshot 2021-12-30 at 12 02 50@2x" src="https://user-images.githubusercontent.com/5180/147750325-e56f8291-d5c3-4e0c-bb0c-54b318f28e89.png">

**Comment by daveverwer** [comment]
It's curious why the snapshots didn't pick this up.

**Comment by finestructure** [comment]
Pretty sure it's because they don't have builds. It's there for https://swiftpackageindex.com/SwiftPackageIndex/SemanticVersion for instance.

**Comment by finestructure** [comment]
> It's curious why the snapshots didn't pick this up.

I'm pretty sure it's because we don't have one without builds.

**Comment by finestructure** [comment]
This is not a super-straightforward fix. The way I've restructured the queries, we're now running an inner join between `versions` and `builds`, which collapses when there are no builds. I could change this to a `left join` in principle but it'll require quite a bit of re-jiggering because the query is shared between build related views and it's complicated due to the resulting optionals.

I can't easily special case the "no build" scenario, because I don't have the required version info (the reference name) if there are no records in the build join. I.e. it _needs_ to happen at the query level.

This is only a problem when there are no builds at all for a package. I.e. we could alternatively just hide the whole "Compatibility" section if that's the case. It would appear as soon as the first build has reported back.

**Comment by daveverwer** [comment]
So, if we had even one queued build, the whole matrix would still display? I think that's fine and should be extremely rare (except on staging).

In the instance where there are no builds at all, let's keep the Compatibility section so it doesn't break page layout, but add a line of text saying that there's no build data and a link to raise an issue if it persists for more than a few minutes.

**Comment by finestructure** [comment]
Yes, a single build brings up the matrix. I've replicated this by deleting all builds except for one for Arena on staging:

<img width="534" alt="CleanShot 2021-12-30 at 15 11 37@2x" src="https://user-images.githubusercontent.com/65520/147759555-98c6d34b-acbd-4700-8ab8-0cf8c26a75fa.png">

Another problem is that the build details page also collapses due to the inner join. This is with just the one build that's left:

<img width="790" alt="CleanShot 2021-12-30 at 15 11 25@2x" src="https://user-images.githubusercontent.com/65520/147759597-314c61b1-b503-4656-b693-45dadad51afe.png">

And this is when I delete that one as well:

<img width="762" alt="CleanShot 2021-12-30 at 15 12 25@2x" src="https://user-images.githubusercontent.com/65520/147759644-d70333ce-0efa-47fb-a02d-d7645c9e7b24.png">

I'll have to check if that case is easier to handle that the matrix but to be honest, I don't think it's really worth creating a lot of complexity here, either: as soon as builds are triggered all the columns will appear as expected.

The only thing we may want to consider is making the empty state a bit more appealing but I don't think it's terrible as it is.

> keep the Compatibility section so it doesn't break page layout, but add a line of text saying that there's no build data and a link to raise an issue if it persists for more than a few minutes.

Yes, that's what I was thinking, too.

**Comment by finestructure** [comment]
Notice isn't showing for some reason:

<img width="773" alt="CleanShot 2021-12-31 at 14 33 19@2x" src="https://user-images.githubusercontent.com/65520/147825918-ba7d150d-b5f9-4d77-89d5-b4014de7dcc2.png">

The package does _not_ have any versions, so the new condition `hasBuildInfo` should be false.
