### ISSUE TITLE
Report back build runner name

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1482]
We want to be able to tell at a glance if all runners are reporting back.

- [x] extend server to accept runner name
- [x] report runner name as build metrics label
- [x] extend builder to send runner name

**Comment by finestructure** [comment]
We have three options as to which id/name we report back from the runner. Here's what the different variables resolve to:

```
CI_RUNNER_DESCRIPTION: spi-prod-builder
CI_RUNNER_ID: 2648462
CI_RUNNER_SHORT_TOKEN: pMpxem39
```

Some properties to bear in mind:

- `CI_RUNNER_DESCRIPTION` is configurable at any time by updating the runner's description in the CI/CD settings
- `CI_RUNNER_ID` is probably Gitlab's internal id for a runner. It's probably stable unless we delete the runner and set it up again.
- `CI_RUNNER_SHORT_TOKEN` is always 8 characters long and is the 8 char prefix of the runner token that's generated during setup. This is stable unless a runner is deleted and set up again.

`CI_RUNNER_DESCRIPTION` is perhaps the obvious choice but it's easy to publish names that I'd consider internal. For instance, we had a `spi-dtk-builder` at some point... It's easy to forget that these would show up on a build page (once we add one).

`CI_RUNNER_ID` I'd avoid but `CI_RUNNER_SHORT_TOKEN` is a decent choice if we want a stable id. If we really needed to we could always map it to some better name.

**Comment by daveverwer** [comment]
> `CI_RUNNER_SHORT_TOKEN` is a decent choice if we want a stable id. If we really needed to we could always map it to some better name.

I agree this is the only one that makes sense, but let's definitely map it to a more readable name. Even if it's just for us, I don't want to have to map it to a machine manually.
