### ISSUE TITLE
`pg_dump` causes certain page/queries to timeout/block

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1489]
This is a continuation of the [discussion over in a repository that initially tried to reproduce the problem](https://github.com/finestructure/vapor-lockup-repro/issues/1).

The problem is the following:

If a slow running `pg_dump` is executed against the staging database, certain pages will time out with a 500 error code. Slow running here means the `pg_dump` is run over a slower network such that it takes several minutes. The errors don't appear immediately, only after the dump has been running for a minute or two.

One affected page is the home page.

Running queries that drive the home page uncovered that

```sql
-- blocks
SELECT * FROM recent_packages ORDER BY created_at DESC LIMIT 7;
```

will block, while

```sql
-- ok
SELECT * FROM recent_releases ORDER BY released_at DESC LIMIT 7;
```

does not. Both entities are materialised views and constructed almost identically. It's unclear why one would block and the other not.

Another odd result is the following: the page https://staging.swiftpackageindex.com/apple is driven by a single SQL query. Accessing this page during a `pg_dump` will, when the dump's been underway for a while, start throwing up 500s. _However_, the underlying SQL query can still be executed successfully via db client the whole time.

So there is certainly still something weird going on where a page we're building off an SQL query times out even though there's no evidence of the actual SQL query timing out or taking too long.

**Comment by finestructure** [comment]
Johannes recommended running the author page query ("apple" query) within a transaction scope to see if that's perhaps causing the blocking:

```sql
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT ... # your normal query here
;
COMMIT;
```

This makes no difference: the query completes fine with or without the transaction while the db is "locked up". Whatever is blocking the author page from loading, it doesn't seem to be the author SQL query.

**Comment by weissi** [comment]
@finestructure Wait, are you saying that this query

```sql
SELECT "packages"."id" AS "packages_id", "packages"."created_at" AS "packages_created_at", "packages"."updated_at" AS "packages_updated_at", "packages"."platform_compatibility" AS "packages_platform_compatibility", "packages"."processing_stage" AS "packages_processing_stage", "packages"."score" AS "packages_score", "packages"."status" AS "packages_status", "packages"."url" AS "packages_url", "repositories"."id" AS "repositories_id", "repositories"."created_at" AS "repositories_created_at", "repositories"."updated_at" AS "repositories_updated_at", "repositories"."forked_from_id" AS "repositories_forked_from_id", "repositories"."package_id" AS "repositories_package_id", "repositories"."authors" AS "repositories_authors", "repositories"."commit_count" AS "repositories_commit_count", "repositories"."default_branch" AS "repositories_default_branch", "repositories"."first_commit_date" AS "repositories_first_commit_date", "repositories"."forks" AS "repositories_forks", "repositories"."is_archived" AS "repositories_is_archived", "repositories"."is_in_organization" AS "repositories_is_in_organization", "repositories"."keywords" AS "repositories_keywords", "repositories"."last_activity_at" AS "repositories_last_activity_at", "repositories"."last_commit_date" AS "repositories_last_commit_date", "repositories"."last_issue_closed_at" AS "repositories_last_issue_closed_at", "repositories"."last_pull_request_closed_at" AS "repositories_last_pull_request_closed_at", "repositories"."license" AS "repositories_license", "repositories"."license_url" AS "repositories_license_url", "repositories"."name" AS "repositories_name", "repositories"."open_issues" AS "repositories_open_issues", "repositories"."open_pull_requests" AS "repositories_open_pull_requests", "repositories"."owner" AS "repositories_owner", "repositories"."owner_name" AS "repositories_owner_name", "repositories"."owner_avatar_url" AS "repositories_owner_avatar_url", "repositories"."readme_url" AS "repositories_readme_url", "repositories"."readme_html_url" AS "repositories_readme_html_url", "repositories"."releases" AS "repositories_releases", "repositories"."stars" AS "repositories_stars", "repositories"."summary" AS "repositories_summary", "versions"."id" AS "versions_id", "versions"."created_at" AS "versions_created_at", "versions"."updated_at" AS "versions_updated_at", "versions"."package_id" AS "versions_package_id", "versions"."commit" AS "versions_commit", "versions"."commit_date" AS "versions_commit_date", "versions"."latest" AS "versions_latest", "versions"."package_name" AS "versions_package_name", "versions"."published_at" AS "versions_published_at", "versions"."reference" AS "versions_reference", "versions"."release_notes" AS "versions_release_notes", "versions"."release_notes_html" AS "versions_release_notes_html", "versions"."resolved_dependencies" AS "versions_resolved_dependencies", "versions"."supported_platforms" AS "versions_supported_platforms", "versions"."swift_versions" AS "versions_swift_versions", "versions"."tools_version" AS "versions_tools_version", "versions"."url" AS "versions_url" FROM "packages" INNER JOIN "repositories" ON "packages"."id" = "repositories"."package_id" INNER JOIN "versions" ON "packages"."id" = "versions"."package_id" WHERE "versions"."latest" = $1 AND "repositories"."owner" ilike $2 ORDER BY "versions"."package_name" ASC [Optional(default_branch), Optional("apple")]
```

takes 2.5 _seconds_ to run in normal operation? And 6 seconds whilst `pg_dump` is running?

That seems like a very very long time, right? But anyway, is the issue you're seeing that when running through the Vapor app, the query runs for more than 6 seconds, namely more than your 10 seconds request timeout limit?

**Comment by finestructure** [comment]
> takes 2.5 _seconds_ to run in normal operation? And 6 seconds whilst `pg_dump` is running?

Yes, that's how bad my connection is :D Seriously, I get results almost immediately (my SQL client streams them) but it takes that long to complete. There's quite a bit of data being loaded in that query.

That's why I ran the query on our bastion host as well where we have excellent bandwidth and almost no latency - it all runs in <500ms. It's really just my network :/

**Comment by finestructure** [comment]
Starting to see the following errors when running our test suite locally on a fast machine (M1) in docker:

```
    ✖ test_triggerBuilds_trimming, XCTAssertEqual threw error "connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000))" - 
```

Happens for different tests. I suspect we're only starting to see it now, because

- we develop on macOS (where this doesn't seem to be happening) and typically only run the full suite on Linux in CI, which has slower machines
- now with better VS Code remote container integration and arm64 docker images have we started to run the tests more frequently on M1s
- it takes a couple of runs of the full suite to trigger the issue even on an M1, so it's easy to dismiss at first

I wonder if this test failure could be related to the `pg_dump` issue. If so, this might actually be a viable repro, because it's fairly easy to trigger once everything's set up.

**Comment by finestructure** [comment]
I'm going to go ahead and close this. I don't think we'll be putting more time into this anytime soon.

We've worked around the issue with our db dumps and the test error doesn't seem to be happening anymore. I don't remember what all has changed since that last push to understand the issue but it seems time has cured all wounds 😅
