### ISSUE TITLE
Build failure for swift-url on iOS; are full build logs available?

### ISSUE THREAD

**Issue by karwa** [SwiftPackageIndex/SwiftPackageIndex-Server#1499]
https://swiftpackageindex.com/karwa/swift-url/builds

The build results here are a little puzzling - version 0.2 of the package is failing on iOS on Swift 5.4 and Swift 5.5, but works on 5.3. The main branch is apparently failing on all Swift versions (but again, only for iOS). Also, watchOS appears flaky.

I've tested it using the provided build command on my local copy of Xcode 13.2.1, and the iOS and watchOS builds work. So no idea what's going on here.

Unfortunately, the logs don't appear to be complete, so I'm not able to diagnose the issue further. Is there a way to obtain the full build log?

Thanks!

**Comment by finestructure** [comment]
Hi Karl, that seems off indeed. We do have the full build logs but trim them on the build page. Let me dig them out for you. 

One thing to note: we switched to Xcode 13.2.1 yesterday but your builds still ran with 13.1. Although the pattern of failures (iOS only) doesn’t indicate that having anything to do with it.

Thanks for the report!

**Comment by finestructure** [comment]
So, swift-url 0.2.0 on iOS/5.5 shows an error code 65 but it's not clear to me why the compile failed. Here are the full logs:

[swift-url-0.2.0-ios-5.5.txt.zip](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/files/7906685/swift-url-0.2.0-ios-5.5.txt.zip)

Looking at one other, [swift 0.2.0 on iOS/5.4](https://swiftpackageindex.com/builds/67E5294F-870C-479A-95BB-3C859FF72871) shows that it's different issues at play apparently. That one failed during dependency resolution:

```
Message: "xcodebuild: error: Could not resolve package dependencies:
  https://github.com/karwa/swift-checkit.git has no Package.swift manifest for version 0.0.2
  https://github.com/karwa/swift-checkit.git has no Package.swift manifest for version 0.0.2
"
```

Looks like the `swift-checkit.git` dependency isn't recognised as a package at the revision. I see it does have a Package.swift with tools-version 5.1 right now. So this doesn't look like it should have been a problem. Is it possible that the tag moved after the build?

Let me know if you want me to re-try any/all of the failed builds.

**Comment by karwa** [comment]
@finestructure If you could try the iOS/5.5 build again (with Xcode 13.2.1), that would be great, thanks. And thanks for the logs.

There is an issue with System.framework (the toolchain/OS version of swift-system), where the toolchain is just broken:

```
${cwd}/Sources/WebURLSystemExtras/WebURL+FilePaths+System.swift:94:58: error: failed to build module 'System'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.29.207 clang-1300.0.28.1)', while this compiler is 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)'). Please select a toolchain which matches the SDK.
#if (os(macOS) || os(iOS) || os(tvOS) || os(watchOS)) && canImport(System)
                                                         ^
```

But I believe I worked around that a while ago, and testing it locally on Xcode 13.2.1 (with the command given on the SPI website) succeeds. The logs you provided seem to indicate that it was built with Xcode 13.1, so maybe something has changed with 13.2.1?

**Comment by finestructure** [comment]
Ok, that looks a bit better - main/iOS/5.5 passed now with 13.2.1. However, 0.2.0/iOS/5.5 still fails and it looks like it's the same error:

[swift-url-0.2.0-ios-5.5.txt.zip](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/files/7907075/swift-url-0.2.0-ios-5.5.txt.zip)

**Comment by karwa** [comment]
Yeah 0.2.0 doesn't have the workaround. I'm planning to release a new version this evening/tomorrow which includes it.

Thanks for the help! I think this can be closed now.

**Comment by finestructure** [comment]
Ah, I see. Great to know it's working as intended now and thanks again for the report!
