### ISSUE TITLE
Use a checkmark icon instead of the envelope icon on the Package page

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#150]
I forget where you suggested this @finestructure, but I liked the suggestion!

**Comment by daveverwer** [comment]
I've just been working on this and while I agreed with your suggestion at first, now I come to implement it, I don't 😂

So a checkmark on its doesn't fit with the weight of the rest of the icon, it's too sparse:

<img width="351" alt="Screenshot 2020-06-10 at 11 02 18@2x" src="https://user-images.githubusercontent.com/5180/84254976-df70fa00-ab09-11ea-8b9f-2bd9de30f393.png">

Which one is the odd one out? 😬

So the natural solution to that would be to stick it in a circle, or a square to make the weight of the icon match. But then I think that's too similar to the "stable" icon we have.

What do you think?

**Comment by finestructure** [comment]
How about just reusing the stable one? Might be ok because it's black/dark grey?

**Comment by daveverwer** [comment]
I think using the same icon for two things is a little troublesome, logically.

**Comment by daveverwer** [comment]
Hold on, I have an idea.

**Comment by finestructure** [comment]
True. Maybe just an outline circle?

Also I just noticed that the hour hands seem to be off centre. I think the tip is in the center, not the centre line.

**Comment by daveverwer** [comment]
The weighting might not look right with this, but it's different enough to be distinct from the stable icon. I'll give it a try in-place.


<img width="517" alt="Screenshot 2020-06-10 at 11 10 43@2x" src="https://user-images.githubusercontent.com/5180/84255837-11369080-ab0b-11ea-8097-bf098be2ce00.png">

**Comment by daveverwer** [comment]
> Also I just noticed that the hour hands seem to be off centre. I think the tip is in the center, not the centre line.

Fixed 

<img width="776" alt="Screenshot 2020-06-10 at 11 15 46@2x" src="https://user-images.githubusercontent.com/5180/84256436-cb2dfc80-ab0b-11ea-96d9-5e1665c16c8c.png">

**Comment by daveverwer** [comment]
I don't like the checkbox icon, it's just nowhere near "heavy" enough to match the rest.

![Screenshot 2020-06-10 at 11 40 29](https://user-images.githubusercontent.com/5180/84258657-37f6c600-ab0f-11ea-85f3-60923bf9a655.gif)

**Comment by daveverwer** [comment]
This isn't bad, maybe without the check mark?

<img width="128" alt="Screenshot 2020-06-10 at 12 01 35@2x" src="https://user-images.githubusercontent.com/5180/84260560-27941a80-ab12-11ea-9327-bf6c5374c4e4.png">

**Comment by daveverwer** [comment]
ChefsKiss.gif

<img width="217" alt="Screenshot 2020-06-10 at 12 10 42@2x" src="https://user-images.githubusercontent.com/5180/84261282-6e364480-ab13-11ea-80f6-81608f9c29d2.png">

**Comment by finestructure** [comment]
That looks nice!
