### ISSUE TITLE
Compatibility matrix is empty

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [SwiftPackageIndex/SwiftPackageIndex-Server#1505]
What makes the compatibility matrix empty like here https://swiftpackageindex.com/ably/ably-asset-tracking-swift?
[Package.swift](https://github.com/ably/ably-asset-tracking-swift/blob/main/Package.swift) contains either Swift version comment header and the platform[version] property.

**Comment by lukasz-szyszkowski** [comment]
That's a shame :( unfortunately, this can be a problem because this is the `mapbox` [requirement](https://docs.mapbox.com/ios/maps/guides/install/), but there is another problem with `mapbox` that I've raised [here](https://github.com/mapbox/mapbox-maps-ios/issues/966), in short: there is no way to compile their package using `x86_64` architecture.

**Comment by finestructure** [comment]
Well, the `x86_64` is an additional problem but you can see the binary dependency issue also with the arm build:

```
env DEVELOPER_DIR="/Applications/Xcode_13.2.1.app" xcrun swift build --arch arm64
```

https://swiftpackageindex.com/builds/2A5CCE48-5BB5-4F9C-9F84-21988E01751E

**Comment by lukasz-szyszkowski** [comment]
> Well, the `x86_64` is an additional problem then but you can see the binary dependency issue also with the arm build:
> 
> ```
> env DEVELOPER_DIR="/Applications/Xcode_13.2.1.app" xcrun swift build --arch arm64
> ```
> 
> https://swiftpackageindex.com/builds/2A5CCE48-5BB5-4F9C-9F84-21988E01751E

yes, I know we can use `arm64` instead of `x86_64` but it won't work too. We have 2 issues here:
1. `.netrc` configuration with `mapbox` credentials
2. swift package manager build

Ad 2.
Even if we can get rid of the Ad 1. problem we can't manage the problem with the SwiftPM build. As I mentioned above, this `Mapbox` versions inconsistency issue.
I tried to run `xcrun swift build --arch arm64` on my mac, and here is the result
```
error: the library 'MapboxNavigationNativeWrapper' requires macos 10.10, but depends on the product 'MapboxCommon' which requires macos 10.15; consider changing the library 'MapboxNavigationNativeWrapper' to require macos 10.15 or later, or the product 'MapboxCommon' to require macos 10.10 or earlier.
error: the library 'AblyAssetTrackingSubscriber' requires macos 10.10, but depends on the product 'Ably' which requires macos 10.11; consider changing the library 'AblyAssetTrackingSubscriber' to require macos 10.11 or later, or the product 'Ably' to require macos 10.10 or earlier.
error: the library 'AblyAssetTrackingInternal' requires macos 10.10, but depends on the product 'Ably' which requires macos 10.11; consider changing the library 'AblyAssetTrackingInternal' to require macos 10.11 or later, or the product 'Ably' to require macos 10.10 or earlier.
error: the library 'AblyAssetTrackingPublisher' requires macos 10.10, but depends on the product 'Ably' which requires macos 10.11; consider changing the library 'AblyAssetTrackingPublisher' to require macos 10.11 or later, or the product 'Ably' to require macos 10.10 or earlier.
error: the library 'MapboxNavigation' requires macos 10.10, but depends on the product 'MapboxDirections' which requires macos 10.12; consider changing the library 'MapboxNavigation' to require macos 10.12 or later, or the product 'MapboxDirections' to require macos 10.10 or earlier.
error: the library 'MapboxCoreNavigation' requires macos 10.10, but depends on the product 'MapboxDirections' which requires macos 10.12; consider changing the library 'MapboxCoreNavigation' to require macos 10.12 or later, or the product 'MapboxDirections' to require macos 10.10 or earlier.
error: the library 'MapboxMaps' requires macos 10.10, but depends on the product 'MapboxCoreMaps' which requires macos 10.15; consider changing the library 'MapboxMaps' to require macos 10.15 or later, or the product 'MapboxCoreMaps' to require macos 10.10 or earlier.
error: the library 'MapboxMaps' requires macos 10.10, but depends on the product 'Turf' which requires macos 10.12; consider changing the library 'MapboxMaps' to require macos 10.12 or later, or the product 'Turf' to require macos 10.10 or earlier.
error: the library 'MapboxMaps' requires macos 10.10, but depends on the product 'MapboxCommon' which requires macos 10.15; consider changing the library 'MapboxMaps' to require macos 10.15 or later, or the product 'MapboxCommon' to require macos 10.10 or earlier.```

summarize: this problem is unsolvable from our side 🤷‍♂️

Thanks for your help @finestructure !

**Comment by finestructure** [comment]
Yeah, sounds like you're out of luck :( Sorry about that!

**Comment by daveverwer** [comment]
I started a [discussion about this](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/1507) as I think it brings up an interesting topic.

I'll close this for now since I think this specific issue is done, but please do contribute to the discussion or re-open it if you think there's more we can do on our side to fix this specific issue.
