### ISSUE TITLE
Drop incorrect "supportsLatestSwiftVersion"

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1508]
We're reading from the swift versions as declared in the `platforms` key of the manifest, which is often empty.

**Comment by daveverwer** [comment]
As and when we get to this, we also need to change how this score calculation works. It's no longer valid to give points for supporting v5 and above (which is what we did here when v5 was new).

We should give points for the *true* latest Swift version as defined by our build system (which should track reality reasonably closely).

**Comment by finestructure** [comment]
This is going to be a rather complicated change, because we'd need to change the underlying query to pass through build information. Give that practically everything is Swift 5 right now, perhaps we should disable that +10 bonus for the time being so we don't skew results.

The reason I noticed was that The Composable Architecture wasn't ranking #1 even though it should have a higher score by all metrics I could think of.

**Comment by finestructure** [comment]
There's also an odd situation here in that TCA's score differ by 5 points between staging and prod.

**Comment by finestructure** [comment]
> There's also an odd situation here in that TCA's score differ by 5 points between staging and prod.

Ok, that at least is explainable: staging has no dependency information because they builds are downscaled, which adds 5 points (we reward 0..<3 dependency count with 5 points).

**Comment by finestructure** [comment]
As discussed, dropping the incorrect value for now.
