### ISSUE TITLE
SPI build tripping over example projects with `xcodebuild` based builds

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1532]
### Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/1531

<div type='discussions-op-text'>

<sup>Originally posted by **tgrapperon** February  4, 2022</sup>
Hello!

I have a package at https://swiftpackageindex.com/tgrapperon/composable-effect-identifier

It has a main `package.swift` manifest at the root of the repository, and another one in some Example folder. This example `LonelyTimer` package depends on the repository's package.

When SPI tries to build the repository, it fails to build the `LonelyTimer` package, having trouble resolving the dependency. 
I initially depended on the local version with `.dependency(path: "../../")` and I've now switched to see if `.dependency(url:"the repo url like you would do regularly"` would help. If fails in both cases, with different errors (it finds none or two versions of the dependency!)

I'm using a package in the sample to demonstrate how modularity is preserved when using my project. It works fine when opened directly with Xcode, or using the workspace provided.

As a result, badges for the package are not representative.
 I would like to instruct SPI to only build the first, root-level `package.swift`, but I'm not finding the documentation for this file. Is this possible?.

Thanks a lot!
</div>

**Comment by finestructure** [comment]
Hi Thomas, thanks for the report!

I think you're referring to the builds that are run via Xcode, [like the iOS one here](https://swiftpackageindex.com/builds/2EFB4D75-D5DB-4D55-90AC-A0F98A71D950), right?

The reason these are failing (when the SPM-based ones aren't) is that we're running `xcodebuild -resolvePackageDependencies` in order to be able to find the schemes for the build. We do have a mechanism in place for package authors to specify schemes manually, via an `.spi.yml` file in the repository but I've just realised that we run the `-resolvePackageDependencies` step first. I think we should be able to switch around the order here to make this work.

I'll post the required `.spi.yml` file once I'm sure that we handle it this way.

Thanks again for reporting this!

**Comment by tgrapperon** [comment]
Thanks Sven!
Yes, these are the failures I was talking about. It should work on the same platforms as TCA (albeit Swift 5.4+ for the local property wrappers).
Thanks a lot for looking into it!

**Comment by finestructure** [comment]
Ok, unfortunately, that won't help by itself (although it is required because of another issue I've discovered), because `xcodebuild build` later on effectively tries to run the same thing in order to build and fails. You can see this by running our effective build command in the repository:

```
env DEVELOPER_DIR="/Applications/Xcode_13.2.1.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" build -scheme "ComposableEffectIdentifier" -destination "generic/platform=ios"
```

I've found a way to make it work though - by moving the `Examples` folder into another folder. I'm not sure that's a great solution in your case - to nest just for that purpose.

I think what I'll do is add an option to `.spi.yml` to tell us to ignore certain paths within the repository, like so:

```yml
version: 1
builder:
  configs:
  - platform: ios
    scheme: ComposableEffectIdentifier
  ignore_paths:
  - Examples
```

**Comment by tgrapperon** [comment]
Thanks a lot for the thorough investigation!
I've tried the command and it builds fine on my machine, even after deleting all visible or hidden caches. But I reverted to a local dependency a few hours ago, so maybe it helps. It shows `LonelyTimer` in the "Resolved source packages".

I'll try the `.spi.yml` route then, as the Example arborescence is already quite intricate to move it somewhere deeper. I'm puzzled about the reason why this helps. Maybe the empty `Package.swift` that I'm using to make this folder disappear from Xcode UI is creating a bridge between the root and `LonelyTimer` that Xcode crawls. As I'm unable to make builds fail on my side, I can't check. If Xcode somehow limits its depth when looking for packages, I can probably find a name to nest `LonelyTimer` one folder deeper if needed though.

The `ignore_paths` would be optimal indeed, but this is not the end of the world if it's not implemented, and I'll think about a way to rearrange things in any case.

Is there an option in `.spi.yml` to specify one or more branches to watch and try to build, instead of the default branch?
Thanks again!

**Comment by daveverwer** [comment]
> I think what I'll do is add an option to `.spi.yml` to tell us to ignore certain paths within the repository, like so:
> 
> ```yaml
> version: 1
> builder:
>   configs:
>   - platform: ios
>     scheme: ComposableEffectIdentifier
>   ignore_paths:
>   - Examples
> ```

This is a great idea.

My only suggestion would be to expand a little on in what way these paths are being ignored. It's when we try to discover an Xcode project right? So maybe `ignore_path` should be nested under a `project_file_discovery` key or something similar?

**Comment by finestructure** [comment]
Meh, I've just found out something terrible. The reason it works for you but not for me and our build system is the following:

You are probably checking out as follows:

```
git clone https://github.com/tgrapperon/composable-effect-identifier.git
```

whereas our build system does

```
git clone https://github.com/tgrapperon/composable-effect-identifier.git checkout
```

If you checkout into a differently named directory, the Xcode build fails 🤪

I'm guessing it does some sort of scheme discovery based on the directory name.

The reason we're checking out into a named directory is to have an easier time cd'ing into the directory for the build. We should be able to work around that by introducing an extra level of nesting.

**Comment by tgrapperon** [comment]
That's some top-notch spelunking! I never cloned this repo, but my directory is indeed named as the repo. I can confirm it fails if I'm renaming this directory. I thought Xcode was taking the local package name from the `Package.swift`, but it seems it uses the directory's name instead (and we can see this in the file's list in the left sidebar: the package name matches the directory's name, regardless of what `Package.swift` says). Xcode is probably using this kind of trick to allow local copies to overrides published versions. SPM doesn't have to do that and works as expected (only a guess).

I'm sorry for the difficulties it causes.

**Comment by tgrapperon** [comment]
Hey Sven!
It occurred to me that we can specify a "name" argument to the local package dependency since 5.2:
```swift
.package(name: "composable-effect-identifier", path: "../../"),
```
It seems to solve the problem on my side.
I'll report back with SPI's build results. If it fixes the issue, you can probably clause this, as this is more a problem with the repository's code than SPI. Users should be able to clone the repo in arbitrary folders.

Sorry for the bothering, and congrats on finding the source of the issue. This is very impressive! I don't know why it worked with one additional nesting level though!

**Comment by tgrapperon** [comment]
@finestructure All Green! 
https://swiftpackageindex.com/tgrapperon/composable-effect-identifier/builds

If authors are using local dependencies in their packages, they should explicitly name them.

Thanks again for your very kind (and super effective) support.

**Comment by finestructure** [comment]
Thanks for the follow-up and great to see there's a work-around for the Xcode issue!

We'll definitely want to address that via additional nesting on our end and your raising the issue was a great help in finding out about it. Thanks!

It also made me spot another bug that we need to fix and it shows up in your newly "greened" builds. It's what I was referring to above when I said "that won't help by itself (although it is required because of another issue I've discovered)".

You see, when we run builds with `xcodebuild` we need to figure out which scheme to run and Xcode auto-creates lots of schemes for packages. In all our testing so far there's only ever been one scheme with a `-Package` suffix. You see where this is going 😆 We're picking the first one and so your package is marked green, because `swift-case-paths` sorts higher than your package 😬 

```
RegisterExecutionPolicyException ${cwd}/.derivedData/Build/Products/Debug-iphoneos/CasePaths.o (in target 'CasePaths' from project 'swift-case-paths')
    cd ${cwd}/.dependencies/checkouts/swift-case-paths
    builtin-RegisterExecutionPolicyException ${cwd}/.derivedData/Build/Products/Debug-iphoneos/CasePaths.o

** BUILD SUCCEEDED **

✅  build complete
```

I'll push a fix for this shortly, although the fix will have to be to fail if we find multiple `-Package` schemes, or perhaps try and match with the package name at least.

If you want to be sure we pick the right scheme, adding an `.spi.yml` with

```
version: 1
builder:
  configs:
  - platform: ios
    scheme: ComposableEffectIdentifier
  - platform: macos-xcodebuild
    scheme: ComposableEffectIdentifier
  - platform: macos-xcodebuild-arm
    scheme: ComposableEffectIdentifier
  - platform: tvos
    scheme: ComposableEffectIdentifier
  - platform: watchos
    scheme: ComposableEffectIdentifier
```

would be safest.

**Comment by tgrapperon** [comment]
Thanks Sven.
I was thinking about adding the `.spi.yml` anyway, as I'm getting "false" failures in 5.4 when it trips on the example which is 5.5. 
I will do it right now!

**Comment by finestructure** [comment]
Ok, PR for this one is up now: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/90

I'll re-run the 0.0.1 builds once this has been merged and deployed.

**Comment by tgrapperon** [comment]
Thanks a lot!
I can't access the PR, but I'm hopping it's a <20 lines change!

**Comment by finestructure** [comment]
Sort of 😆 

<img width="118" alt="CleanShot 2022-02-09 at 15 00 53@2x" src="https://user-images.githubusercontent.com/65520/153216359-f2640532-8cd8-4da3-94ab-23169899310f.png">

But it was a bug that needed fixing, so thanks for finding it!

**Comment by finestructure** [comment]
Ok, this is now deployed. You'll note that the 0.1.0 builds are still failing but this is because we didn't end up adding folder nesting since you discovered that you can fix it by using `.package(name: "composable-effect-identifier", path: "../../")`.

That keeps our implementation much simpler and we'll update our build FAQs with this info in case others are running into this issue.

I'll be closing this now, let me know if you're still seeing issues!
