### ISSUE TITLE
Invalid Package URL

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1563]
**Please describe the bug**

Okay so basically I spent like 25 minutes debugging why Xcode was being stupid until I realised that the URL I copied from SPI was actually invalid 😂 

**Explain the steps needed to reproduce the bug**

1. Navigate to a package
2. Click on 'Use this package' button
3. See that URLs for versions (not the default branch) are missing one slash on the scheme of the URL (aka its https:/github.com instead of https://github.com thus making it an invalid URL)

**What was the expected behaviour?**

**Screenshots**

![Captured 2022-02-15 at 9 59 27](https://user-images.githubusercontent.com/15193942/154156631-f72285a4-1028-4b05-9ca4-5bb4f5265edf.png)

**What web browser were you using? (if relevant)**

Chrome

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop
- Browser: Chrome

**Additional context**

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/5004b010f2e1428f02fd1f2d0d15d348e2f02554/Tests/AppTests/__Snapshots__/WebpageSnapshotTests/test_PackageShowView_few_keywords.1.txt#L90

You can see this issue in the snapshot tests here.

**Comment by finestructure** [comment]
Aw, sorry about that James! Unsurprisingly, my hack didn't take long to cause trouble 😆
