### ISSUE TITLE
Visual search bar glitch on iPad

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1572]
Might be a duplicate, I feel like I‘ve seen this before but I wanted to record it quickly just so we don‘t miss it.

![BC179006-A411-4B88-8724-74C32FEF2C90](https://user-images.githubusercontent.com/65520/154859231-73d8d9c1-7761-4e84-a0d9-b634991cb03d.jpeg)

**Comment by daveverwer** [comment]
That's a strange one. I don't see it at all:

<img width="361" alt="Screenshot 2022-02-20 at 19 42 15@2x" src="https://user-images.githubusercontent.com/5180/154861133-db373278-4515-497c-8e9f-9bf0ae5625b0.png">

**Comment by finestructure** [comment]
I wonder if I have stale CSS or something. I haven‘t used the 13“ for web browsing in quite a while, that might explain why I feel like I‘ve seen this before in the past. I‘ll check if I can reset the cache.

**Comment by Sherlouk** [comment]
This reminds me to check an annoying styling bug I have with code snippets too... without going on too much of a tangent it only happens on my work laptop and not my personal laptop.

It's the same spec, same browser, same version of the browser, same extensions, like by all accounts it's the same - and yet only one of the two devices has this weird styling bug.

I too will try to reset the cache and will raise a separate issue if I can't figure it out

**Comment by finestructure** [comment]
Mmmm, seems like it's real. I've "cleared history and website data" in Settings, I've made sure to reload without content blockers - but that rounded rect persists. Only on my 12.9" iPad, not on my mini.

I've got a software update on the 12.9", which I'll install later and then I'll retry. Weird!

**Comment by finestructure** [comment]
Nope, still there after SW update. Bizarre 🤷 

Maybe 12.9" screen size specific? (Happens in both portrait and landscape.)
