### ISSUE TITLE
Package signing: one-off false negative (successful signing with revoked key)

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1583]
```
✖ test_sign_collection_revoked_key, failed - signing with a revoked certificate must fail
[2488](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/5297380578?check_suite_focus=true#step:5:2488)
```

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/5297380578?check_suite_focus=true

**Comment by finestructure** [comment]
Oh wait, this is _not_ failing when signing with a _revoked_ key. We're successfully signing with a revoked key when it should fail. Running this test locally passes - rerunning.

**Comment by finestructure** [comment]
This [last passed](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/5291531815?check_suite_focus=true#step:5:2462) on

```
Tue, 22 Feb 2022 16:48:11 GMT
    ✔ test_sign_collection_revoked_key (0.427 seconds)
```

and [first failed](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/5297380578?check_suite_focus=true) on

```
Wed, 23 Feb 2022 01:35:26 GMT
    ✖ test_sign_collection_revoked_key, failed - signing with a revoked certificate must fail
```

There were no package updates on our end in between and we run tests with `--disable-automatic-resolution`, i.e. we shouldn't be pulling in any upstream changes even if there were any.

The test in its entirety is

```swift
    func test_sign_collection_revoked_key() throws {
        // setup
        let collection: PackageCollection = .mock
        // get cert and key and make sure the inputs are valid (apart from being revoked)
        // so we don't fail for that reason
        let revokedUrl = fixtureUrl(for: "revoked.cer")
        XCTAssertTrue(Foundation.FileManager.default.fileExists(atPath: revokedUrl.path))
        let revokedKey = try XCTUnwrap(fixtureData(for: "revoked.pem"))

        Current.collectionSigningCertificateChain = {
            [
                revokedUrl,
                SignedCollection.certsDir
                    .appendingPathComponent("AppleWWDRCAG3.cer"),
                SignedCollection.certsDir
                    .appendingPathComponent("AppleIncRootCertificate.cer")
            ]
        }
        Current.collectionSigningPrivateKey = { revokedKey }

        // MUT
        do {
            _ = try SignedCollection.sign(eventLoop: app.eventLoopGroup.next(),
                                          collection: collection).wait()
            XCTFail("signing with a revoked certificate must fail")
        } catch PackageCollectionSigningError.invalidCertChain {
            // ok
        } catch {
            XCTFail("unexpected signing error: \(error)")
        }
    }
```

It's unclear to me how that could start failing by suddenly signing a collection successfully.

**Comment by finestructure** [comment]
Passed on a re-run: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/1884903815

That's still very bizarre. How could this _not_ throw? First time we've seen this to my knowledge.

Note that we're not validating the signature in the test. I assume the result would still be a badly signed collection. It's just that were this to happen frequently, as an implementor you wouldn't realise you're creating bad signatures.

FYI @yim-lee @tomerd

**Comment by finestructure** [comment]
For reference, `SignedCollection.sign` is

```swift
    static func sign(eventLoop: EventLoop, collection: PackageCollection) -> EventLoopFuture<SignedCollection> {
        guard let privateKey = Current.collectionSigningPrivateKey() else {
            return eventLoop.makeFailedFuture(AppError.envVariableNotSet("COLLECTION_SIGNING_PRIVATE_KEY"))
        }

        let signedCollection = eventLoop.makePromise(of: SignedCollection.self)
        signer.sign(collection: collection,
                    certChainPaths: Current.collectionSigningCertificateChain(),
                    privateKeyPEM: privateKey) { result in
            switch result {
                case .success(let signed):
                    signedCollection.succeed(signed)
                case .failure(let error):
                    signedCollection.fail(error)
            }
        }
        return signedCollection.futureResult
    }
```

with `signer`

```swift
    static let signer = PackageCollectionSigning(
        trustedRootCertsDir: certsDir,
        additionalTrustedRootCerts: nil,
        observabilityScope: .ignored,
        callbackQueue: DispatchQueue.global()
    )
```

**Comment by yim-lee** [comment]
IIUC, the problem you saw was that signing with a revoked cert didn't fail? 

The code gets a cert's status from the OCSP responder. It's possible the OCSP request failed (e.g., network error, responder blip, etc.), and by default we assume the cert to be OK (rather than revoked).

**Comment by finestructure** [comment]
Yes, exactly. We're asserting on getting thrown a `invalidCertChain` exception when signing with a revoked cert.

Thanks a lot for clarifying this is conceivable in case of connectivity issues! I'll close this then.

**Comment by finestructure** [comment]
We're seeing this [happening again this morning](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/runs/5535049350?check_suite_focus=true#step:5:2155) and following @yim-lee 's advice I've updated the test to accept a signature success and validate the signature instead:

```swift
        do {
            let signedCollection = try SignedCollection.sign(eventLoop: app.eventLoopGroup.next(),
                                                             collection: collection).wait()
            // NB: signing _can_ succeed in case of reachability issues to verify the cert
            // in this case we need to check the signature
            // https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1583#issuecomment-1048408400
            let validated = try SignedCollection.validate(eventLoop: app.eventLoopGroup.next(),
                                                          signedCollection: signedCollection).wait()
            XCTAssertFalse(validated)
        } catch PackageCollectionSigningError.invalidCertChain {
            // ok
        } catch {
            XCTFail("unexpected signing error: \(error)")
        }
```

What's happening is that `XCTAssertFalse(validated)` is failing, i.e. the signature with the revoked key validates unexpectedly.

It feels like this _is_ a real problem that would also apply to the collection signing tool, wouldn't it?

`SignedCollection.validate` is a very thin wrapper around `PackageCollectionSigning.validate`: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/updatePackageDepedencies/Sources/App/Core/PackageCollection%2Bsigning.swift#L65

**Comment by finestructure** [comment]
This looks like a platform issue. If I run our revoked key test on macOS it passes but when run on Linux it fails.

**Comment by yim-lee** [comment]
> If I run our revoked key test on macOS it passes

In this case `sign` fails with `PackageCollectionSigningError.invalidCertChain` (i.e., the test never gets to `validate` and `XCTAssertFalse(validated)`), which is expected and is what we want since the cert is revoked.

> when run on Linux it fails

I can reproduce this locally. Looks like we are getting status 403 from the OCSP responder. I am looking into this.

**Comment by finestructure** [comment]
> I can reproduce this locally. Looks like we are getting status 403 from the OCSP responder. I am looking into this.

Ah great, thanks for confirming! Just for reference, this status 403 would be rather new. I can dig up when it last worked exactly, but it certainly would have been Friday. It's part of our normal test suite. I wonder if it's DST related? If I'm not mistaken you changed clocks this past weekend.

**Comment by yim-lee** [comment]
Thanks @finestructure. I know the cause but all we can do now is wait.

**Comment by yim-lee** [comment]
@finestructure We should be OK now. Please try running the test again.

I don't think the changes described in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1583#issuecomment-1066592057 are necessary. If everything works as expected, `sign` should fail and we would never get to `validate`. In case of faulty OCSP check and `sign` doesn't throw error, there is no guarantee that `validate` would fail because both `sign` and `validate` go through the same cert verification process (i.e., `validate` might run into the same problem as `sign`).

**Comment by finestructure** [comment]
Thanks, @yim-lee , the test is now passing again on Linux as well!

I didn't see any related changes in SPM so I'm guessing this fixed an upstream service's behaviour in not returning a 403 anymore, right?

You say

> there is no guarantee that validate would fail because both sign and validate go through the same cert verification process

Isn't that a problem though? Wouldn't this mean that should the OCSP check (which I'm not actually sure what it is exactly but my understanding is it's some HTTP request) for some reason, a badly signed collection would show a valid signature? Shouldn't at least `validate` fail if OCSP is unreachable?

**Comment by yim-lee** [comment]
> I didn't see any related changes in SPM so I'm guessing this fixed an upstream service's behaviour to not return a 403 anymore, right?

Right, there was an issue with the upstream service. 

> Wouldn't this mean that should the OCSP check (which I'm not actually sure what it is exactly but my understanding is it's some HTTP request) fail for some reason, a badly signed collection would show a valid signature?

One can find out if a cert has been revoked through OCSP. It's basically making an HTTP request to the URL listed in the cert. And yes, it would mean a collection signed with a revoked cert would show a valid signature. 

> Shouldn't at least validate fail if OCSP is unreachable?

But no, we don't want a cert to be considered invalid (subsequently causing `validate` to fail) simply because we cannot get an OCSP response. Think about what would happen on this occasion if we had thrown error instead--*all* certs would be considered invalid, and it would make *all* signed collections unusable. 

The recommendation we got is to fail open, so if OCSP malfunctions, we continue as if we are not doing OCSP check at all.

**Comment by finestructure** [comment]
> But no, we don't want a cert to be considered invalid (subsequently causing validate to fail) simply because we cannot get an OCSP response.

I think what stumps me a little is that the _signature_ is then considered _valid_. I see how you wouldn't want to consider the _cert_ invalid if you can't verify it. It's just that I'd have expected `validate` to return something other than "valid" if "invalid" is (understandably) too harsh. Something like

```swift
enum SignatureCheck {
  case valid
  case invalid
  case unverified
}
```

and then clients decide how to deal with `unverified` - erroring or messaging etc. In our test case we could assert on _not_ receiving _valid_ back for instance, which what we're essentially trying to do.

(The purpose of this test is to ensure we're not vending collections from a revoked cert that appear to have a valid signature.)

> The recommendation we got is to fail open, so if OCSP malfunctions, we continue as if we are not doing OCSP check at all, which is what the code does.

I see, thanks a lot for taking the time to explain!

I can imagine introducing a tri-state like I mentioned above is probably too disruptive a change at this point but I thought I'd mention it to see if you think it might make sense :)

**Comment by finestructure** [comment]
I'll close this for now, I don't think there's anything actionable for us at this time. Thanks again for taking the time, Yim!
