### ISSUE TITLE
Visual Bug with Code Snippets

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1584]
**Please describe the bug**

I'm finding that on one of my machines there's a bit of a weird visual bug with code snippets (see screenshot below).

![Screenshot 2022-02-23 at 3 12 22 pm](https://user-images.githubusercontent.com/15193942/155347759-6574ed31-ab21-4e5b-aaac-88b8543c5bb4.png)

This happens to all code snippets, both in our static pages (Add a Package) and dynamic pages like READMEs.

Relates slightly to this comment: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1572#issuecomment-1046311481

**Explain the steps needed to reproduce the bug**

1. Navigate to a page which contains a code snippet, example: https://swiftpackageindex.com/add-a-package
2. Depending on your device, you might see the weird visual issue on the code snippet.

**What was the expected behaviour?**

If I turn off `overflow: scroll` for the `<pre>` tag via "Inspect Element" then it goes back to what I would call the expected behaviour.

![Screenshot 2022-02-23 at 3 14 20 pm](https://user-images.githubusercontent.com/15193942/155348102-10a8f27b-f7a8-4051-aea8-bbcc2cf81e27.png)

**What web browser were you using? (if relevant)**

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop
- Browser: Chrome (Version 92.0.4515.107)

**Other information**

On affected machines, it happens 100% of the time. However, the number of devices it impacts appears to be low.
Of all my machines, only one is showing it - and given how Chrome syncs across devices essentially everything is the same on these two machines which is confusing me.

**Comment by daveverwer** [comment]
I can't reproduce this on my machine but I just checked with a hosted BrowserStack browser and it's reproducible there:

<img width="1002" alt="Screenshot 2022-02-23 at 16 35 28@2x" src="https://user-images.githubusercontent.com/5180/155364252-7f2339a4-b8af-4b35-922f-6b017bc2350f.png">

It's clearer in that picture that the white edges you are seeing are the scroll bars. 

I'm not sure I like what I've just prepared in #1586 but it'd be worth testing locally.

**Comment by Sherlouk** [comment]
Been testing this a bit more and it's happening on a single machine on both Safari and Chrome so doesn't seem to be browser specific, but is specific to the computer... very strange indeed.

Also happened on BrowserStack? so something related?

**Comment by tgrapperon** [comment]
<img width="886" alt="Capture d’écran 2022-02-28 à 15 17 05" src="https://user-images.githubusercontent.com/35562418/156036344-9d446c77-54df-4239-b560-2acfdb4ada71.png">
I'm seeing this on Safari 15.3 (17612.4.9.1.5) on Monterey 12.2
Is this the issue? I have a few extensions running, but it doesn't seem that disabling them helps.

**Comment by jnouwen** [comment]
Happens on my machine (macOS 11.6.4, Safari 15.3 and Chrome 98.0.4758.109).

I see this somewhat regularly and it's almost always caused by the scrollbars setting in System Preferences > General. If it's set to Always or Automatically _and_ the user is using a mouse (as opposed to a trackpad), the empty scroll gutters will appear.

<img width="421" alt="Screen Shot 2022-02-28 at 11 18 48 AM" src="https://user-images.githubusercontent.com/1261516/156036648-ec75e88e-d497-4510-98bc-62f10ed8824b.png">

<img width="853" alt="Screen Shot 2022-02-28 at 11 19 37 AM" src="https://user-images.githubusercontent.com/1261516/156036762-de38d100-d643-4486-94f7-122253877fab.png">

<img width="853" alt="Screen Shot 2022-02-28 at 11 19 54 AM" src="https://user-images.githubusercontent.com/1261516/156036834-860c75be-5365-4afc-99e7-6f25af91f250.png">

**Comment by tgrapperon** [comment]
@jnouwen, @daveverwer: I can confirm: Setting it to "when scrolling" immediately fixes the issue. I'm using a mouse.

**Comment by Sherlouk** [comment]
Can confirm, I do use a mouse on that computer... 👀

**Comment by robb** [comment]
FWIW, if you use a non-Apple mouse, you might not be to scroll horizontally otherwise.

**Comment by jnouwen** [comment]
> FWIW, if you use a non-Apple mouse, you might not be to scroll horizontally without visible scroll bars.

If you hold down shift and use the scroll wheel on a non-Apple mouse, it'll scroll horizontally.

**Comment by mattmassicotte** [comment]
Everyone's beaten me to suggesting the scrolling behavior setting. But, just in case, I can also reproduce this on macOS 12.0 with Safari.

**Comment by daveverwer** [comment]
Thank you all for your quick help!

So I use an Apple mouse and I have my settings set like this:

<img width="493" alt="Screenshot 2022-02-28 at 18 30 43@2x" src="https://user-images.githubusercontent.com/5180/156038287-296bcd23-d21e-45b3-888c-52aba52283c0.png">

Are you saying that with non-Apple mice, that setting causes this issue?

**Comment by jnouwen** [comment]
Correct. I use Logitech mice on my computers and basically anything with a physical scrollwheel (or more likely any non-Apple mice in general) causes scrollbars to be visible all the time with either of those settings toggled.

**Comment by tgrapperon** [comment]
@daveverwer Set like that and with a Logitech mouse, I have the issue.
The Apple mouse maybe declares itself as some kind of trackpad.

**Comment by daveverwer** [comment]
That is mind-blowing behaviour 😅

At least we have a fix. I'll close #1586.
