### ISSUE TITLE
Package submission can fail with rate limit error

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1607]
We've received a package submission while the nightly job is running and it got caught in the rate limiting we're under while the nightly is running its checks:

https://github.com/SwiftPackageIndex/PackageList/actions/runs/1940235873

We should maybe switch the nightly to use the 12k/hour dev GH token and/or spread it out a bit. Ideally, the nightly would have its own 12k token.

**Comment by daveverwer** [comment]
I'm not 100% familiar with what the nightly script does with the token, but I'm surprised it's running out on a 5k/hour token.

Without looking at the code, I can see it doing two things switch the token:

1. Asking "does this repository still exist?" to check for deleted repositories.
2. Asking "has this repository moved?" which is probably the same API call as 1.
3. Checking dependencies of each package (which I don't think needs an API call) and then asking GitHub for details.

So with this very naive view of what it's doing, and a package list size of ~4,400 packages. I'm surprised it's not able to run with a standard 5k token. It also doesn't all complete in one hour either, it takes > 5 hours to run. It may be that all of the API calls are being done upfront in the first hour, but even if that's the case then I'm surprised it's hitting the limit.

Of course, I'm probably not aware of what else it's doing which takes it over the limit.

**Comment by finestructure** [comment]
Fixed by https://github.com/SwiftPackageIndex/PackageList-Validator/pull/16

https://github.com/SwiftPackageIndex/PackageList/runs/5508651155?check_suite_focus=true
