### ISSUE TITLE
Bug with keyboard navigation in Firefox

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#166]
Works great in Safari/Chrome, but not so much in Firefox!

![Screenshot 2020-05-26 at 19 20 27](https://user-images.githubusercontent.com/5180/82936150-0fef5a80-9f86-11ea-8ef6-57f1227c7d4c.gif)

**Comment by finestructure** [comment]
Write once, run anywhere, they said! 😂

**Comment by daveverwer** [comment]
It wasn't true for Java, and it's not true for JavaScript. 😂
