### ISSUE TITLE
build system cannot handle submodules (host key verification failed)

### ISSUE THREAD

**Issue by kelvin13** [SwiftPackageIndex/SwiftPackageIndex-Server#1668]
the build system is apparently not able to clone a `git` submodule over SSH:

```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:swift-biome/swift-biome-index.git' into submodule path '/host/spi-builder-workspace/.biome' failed
Failed to clone '.biome'. Retry scheduled
Host key verification failed.
fatal: Could not read from remote repository.
```

this is causing all of `swift-json`’s `master` builds to [fail](https://swiftpackageindex.com/kelvin13/swift-json/builds) right now.

**Comment by daveverwer** [comment]
Thanks for the bug report, Kelvin! 

@finestructure I checked the config on mb5, where [this build](https://swiftpackageindex.com/builds/00724EEC-788C-4099-B7B7-7CF496B15E25) happened and it does have the `StrictHostKeyChecking no` set for the `builder` account.

I just checked that there's a github.com entry in the `known_hosts` too.

**Comment by daveverwer** [comment]
Investigated this a little more and I did make a mistake with this setting on one of the build machines. `mb4` had no `StrictHostKeyChecking no` set in the SSH config.

I've added it, but we'll need to investigate the impact of this further. Thanks again for the report Kelvin, leave it with us.

**Comment by daveverwer** [comment]
OK, so I've investigated this and there are a couple of things going on!

First, we've now added a new configuration option to all our builder machines (yes, all of them this time! 😬) that will rewrite `git@github.com:` URLs to be `https://github.com/`. This will help generally with this kind of problem, but the *true* issue was being masked and is unrelated to this.

`https://github.com/kelvin13/swift-json.git` has a submodule of `git@github.com:swift-biome/swift-biome-index.git` (which we now rewrite to be `https://github.com/swift-biome/swift-biome-index.git`) which has a submodule of `git@github.com:swift-biome/swift-biome-resources.git` (which we now also rewrite). However, all the rewriting in the world doesn't cope with the fact that `https://github.com/swift-biome/swift-biome-resources.git` gives a 404.

My guess is that https://github.com/swift-biome/swift-biome-resources.git is a private repository. Is it?

**Comment by kelvin13** [comment]
wow, that was exactly it! i just assumed github orgs were public by default…

thanks!!
