### ISSUE TITLE
Add the Build ID as a comment on the Build Report pages

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1669]
Currently, we have a comment that shows the `version_id` for the build, but it'd be useful to also have the `builds`.`id` available.

**Comment by finestructure** [comment]
Are you referring to the individual build pages? If so the reason they don’t have it is because it’s in the URL :)

**Comment by daveverwer** [comment]
That's an extremely good point 😂
