### ISSUE TITLE
Improve search results for exact package names

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#167]
First package I’ve come across where what I’m looking for isn’t above the fold:

![IMG_0075](https://user-images.githubusercontent.com/65520/82944804-256f7f00-9f9c-11ea-9ed9-1d943ac6fb97.png)

**Comment by finestructure** [comment]
Possible remedy: give exact package name hits extra weight

**Comment by finestructure** [comment]
Actually, this is bananas but: `https://github.com/vapor/vapor.git`isn't in the package list at all. Was this never submitted?!

**Comment by daveverwer** [comment]
If we could give packages a boost for a couple of reasons, it'd be perfect:

* Exact package name
* Package name starts with...

**Comment by daveverwer** [comment]
1 seems good, it just wins with an exact match, no matter what.

> In order to avoid this getting too gnarly with multiple search terms, I'd simple concatenate them together for this part of the search, perhaps with a space in between? Or we drop it entirely in this case, given that package names can't have whitespace (right?).

Unfortunately it looks like Package.swift *does* support spaces in Package name:

<img width="223" alt="Screenshot 2020-06-04 at 23 00 58@2x" src="https://user-images.githubusercontent.com/5180/83815010-4a0fd900-a6b7-11ea-9277-f0dfabe09f6f.png">

But, I think #1 actually gets rid of this problem, doesn't it? The != would match including spaces, and then score after that. Maybe I'm missing the problem

**Comment by finestructure** [comment]
Hah, nice one.

But yes, that'd be covered by re-concatenating with spaces in between. (With the slight caveat that we're splitting on whitespace and then re-concatenating with spaces.)

I'll go with 1) and also add some testing around packages with whitespace.

**Comment by daveverwer** [comment]
> But yes, that'd be covered by re-concatenating with spaces in between. (With the slight caveat that we're splitting on whitespace and then re-concatenating with spaces.)

Yes, this should work well
