### ISSUE TITLE
Flickering snapshot test

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1681]
I first noticed this yesterday and thought this commit 483f888874a50e1dc2bdcdc5ed3c3d464c6ce42d might fix the issue but it appears this is not due to the number of tags.

It's the test `test_PackageShowView_few_keywords` that's sometimes failing. Out of 10 runs of that test by itself (by clicking on the test diamond in Xcode) it failed 4 times for me just now. It obviously won't happen in CI because we don't run the image snapshot tests there.

![CleanShot 2022-04-07 at 10 09 43@2x](https://user-images.githubusercontent.com/65520/162152070-b4920457-8041-484d-bc16-11c8351d3977.png)

It must be something in the Javascript as the HTML snapshot is unaffected.

**Comment by daveverwer** [comment]
Yea I hadn't logged this but it's been happening for a little while. I'll look into it properly.
