### ISSUE TITLE
Missing docs for `.spi.yml` and how builds are actually done

### ISSUE THREAD

**Issue by thomasvl** [SwiftPackageIndex/SwiftPackageIndex-Server#1683]
1. Go to any _Information for [PACKAGE] Maintainers_ page (https://swiftpackageindex.com/apple/swift-protobuf/information-for-package-maintainers).
2. Under _Build Compatibility_, see the note for details about how to control the build system (`.spi.yml` reference), follow that link.
3. End up on https://swiftpackageindex.com/docs/builds, there doesn't appear to be any mention of of the `.spi.yml` and/or how to control the build.

Likewise, there aren't really any docs about things doing `swift build`/`swift test` vs. `xcodebuild`, etc. to help understand how things are done and what could be issues.

**Comment by daveverwer** [comment]
Thanks for this Thomas. We're very aware that the documentation is lacking. It's possible there was some information about `_spi.yml` in that FAQ at some point, as I can't imagine writing that with there not being!

We're tracking the documentation problem in #864.

There is some documentation contained in that issue. There's also some information in [this blog post](https://blog.swiftpackageindex.com/posts/the-swift-package-index-metadata-file-first-steps/). In fact, between the two that's everything the file does. Of course, no one can find that and so your complaint is valid. I point you to it only to help with what you were looking for.

We do now have a system set up to accept documentation, we just need to move all that information across into it and link it from the main site. If only there were more hours in the day! 😬

> Likewise, there aren't really any docs about things doing swift build/swift test vs. xcodebuild, etc. to help understand how things are done and what could be issues.

While we'll write a little bit about this, the main information in any documentation for this would be to redirect people to the build pages. The build command is at the top of each build log (where we got as far as generating a build command, at least) and that should be where you start when trying to reproduce any issues. That contains the full `xcodebuild` or `swift build` command that we executed.

I'll close this issue as we're tracking this in #864
