### ISSUE TITLE
Consider materialized view also for search

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#169]
Now that we've got materialised views in place we might as well make search faster as well.

It should be a simple adaptation of the existing machinery but also check performance figures before doing it.

**Comment by finestructure** [comment]
I'm having a quick look at this, because I'd like to get it in before the schema squash.

**Comment by finestructure** [comment]
Our current search query has an execution time for the search term of "foo" (single hit) of ~60ms and about 6-8ms with a materialised view.

For "swift" (~1500 hits), this goes up to ~75ms in our current search and around 10-15ms with the materialised view.

It's a nice speed bump and I think I'd like to bring that in.

**Comment by daveverwer** [comment]
Sounds good to me.
