### ISSUE TITLE
Documentation: Language and platform support

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#170]
Documentation around how package authors can get the Swift and platform information shown in their package pages. Include a screenshot of a well-configured package.

**Comment by finestructure** [comment]
This is about the landing page for the link from #171 when L&P info is missing, right?

Maybe instead of wiring up a full page, intially we link to a Wiki page here in the project?

**Comment by daveverwer** [comment]
Yep, I'm absolutely planning to use a page on the project's GitHub Wiki for this, at least initially 👍

**Comment by finestructure** [comment]
As part of #182 I've created a stub page here, which is now linked from the package page: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/wiki/Fixing-missing-Language-and-Platform-information

**Comment by daveverwer** [comment]
For review:

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/wiki/FAQ
