### ISSUE TITLE
`test_SearchShow` snapshot test sometimes fails due to selection

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1703]
I'm not sure if this is fixable 🤔 

![CleanShot 2022-04-20 at 06 43 01@2x](https://user-images.githubusercontent.com/65520/164152114-56417c41-b4e3-4357-b66a-8de9f5e19c45.png)

**Comment by daveverwer** [comment]
Yes, I've tried to fix this in the past and it's just unreliable when the snapshot gets taken. One of the things I hope Percy will fix. 🤞 

I'll close this but we can re-open if the problem comes back with Percy.
