### ISSUE TITLE
Package homepage buttons are showing for packages without a homepage set

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1716]
For example, on: https://swiftpackageindex.com/mxcl/PromiseKit

<img width="857" alt="Screenshot 2022-04-26 at 16 39 03@2x" src="https://user-images.githubusercontent.com/5180/165338817-b9e88e8f-7ad1-4867-b93d-6d4d353761ac.png">

I think this is a `NULL`/`EMPTY` string issue. For example, looking at Max's packages:

<img width="486" alt="Screenshot 2022-04-26 at 16 41 14@2x" src="https://user-images.githubusercontent.com/5180/165339230-6f3754a5-8e9e-45d9-aca0-5c90b3dc565f.png">

PromiseKit and [AppUpdater](https://swiftpackageindex.com/mxcl/AppUpdater) have the button, but [StreamReader](https://swiftpackageindex.com/mxcl/StreamReader) doesn't.

**Comment by finestructure** [comment]
AppUpdater doesn't show the button for me, I think you wanted to reference one of the other `EMPTY` ones (AppUpdater is `NULL`).

**Comment by finestructure** [comment]
Yeah, definitely. Looks like something where we're using an `unwrap` to show the element and would need to also guard against `isEmpty`. Or perhaps just convert empty to `NULL` during ingestion.

**Comment by Sherlouk** [comment]
Of course GitHub would give it back as an empty string... why wouldn't they be clever 😂  My bad!
