### ISSUE TITLE
Update versions based on S3 doc archive content

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1770]
```
500 - Internal Server Error - http://spi-prod-docs.s3-website.us-east-2.amazonaws.com/parse-community/Parse-Swift/main/documentation/parseswift (ios) is an invalid URL
```

<img width="761" alt="CleanShot 2022-05-31 at 09 43 16@2x" src="https://user-images.githubusercontent.com/65520/171119731-94b8c842-b4cd-4abe-b633-f18ac782e2a4.png">

**Comment by finestructure** [comment]
It looks like DocC is trimming off the ` (ios)` from the target name:

```
❯ curl -Is http://spi-prod-docs.s3-website.us-east-2.amazonaws.com/parse-community/Parse-Swift/main/documentation/parseswift/
HTTP/1.1 200 OK
x-amz-id-2: rmK7gS2ZqUse8aYAEDTMskUwq7taJC4992f2u6zW+7wGbUG5WvvY+NROgdJC2MM/U8BO0VNBRkA=
x-amz-request-id: SRM7YZZ0AAZG2CWP
Date: Tue, 31 May 2022 07:52:58 GMT
Content-Encoding:
Last-Modified: Mon, 30 May 2022 19:00:22 GMT
ETag: "53680e20cd5edd81bcb614c894cb61a7"
Content-Type: application/octet-stream
Server: AmazonS3
Content-Length: 5368
```

That means we need to change how we derive the target URL from the target name to not just `lowercase` it but also apply some trimming. We should try and find the logic in DocC so we don't have to go about guessing the transformations.

**Comment by finestructure** [comment]
> We should try and find the logic in DocC so we don't have to go about guessing the transformations.

Hope you don't mind if I ping you directly, @franklinsch, but you probably know exactly where to look for that :)

**Comment by franklinsch** [comment]
I would expect `(ios)` to be percent-encoded rather than dropped. Can you please file an [issue](https://github.com/apple/swift-docc/issues) with a sample project?

**Comment by finestructure** [comment]
Thanks, Franklin! After some investigation I suspect the behaviour is as expected (see the linked issue) but it means we need to change how we generate/discover doc urls from the generated output.

I'm pretty sure I know how to get this to work reliably without having to replicate any URL transformations and such.

Specifically, we should extend our ingestion step with a check for doc sets in a package's associated S3 docs bucket and record any findings in the versions table. This would also eliminated any issues around showing "Documentation" links when processing isn't actually complete yet.

The builder is also agnostic to any output naming transformations because it uploads any folders within the output directory. If we make the server side equally agnostic by simply enumerating the directory names it finds in the bucket, the target names in the SPI manifest become purely processing pointers without any impact on how we discover the actual artefacts.

**Comment by finestructure** [comment]
Some more details about our options to address this:

- we should just check the S3 directories for output, this would eliminate tracking target names entirely
- the builder has already eliminated that by uploading what's in the output dir - it is agnostic to what the resulting path is actually called
- checking S3 from the analyzer/ingestor might incur costs
	- if we stick it in the ingestor (where it would fit best), it would run across 100 packages every 5 mins → 288 runs of 100 package / day → 28.8k runs/day → 864k runs/month
	- we can probably ignore a few packages where we'd have to make several requests due to listing targets per revision - let's say 1M LISTS/month to cover that
	- 1M LISTS → $5
	- but this is only if we _blindly check every package every time_ (more on that below)
- we could also look at the filesystem in the builder to see what paths it generated
	- we'd have to add a reporting mechanism of doc build results to the server
	- this should be separate and in addition to the build reports so there's no dependency and chance of interference
	- the problem with such a mechanism is that reporting failures aren't autocorrecting if they don't get delivered, for instance in cases where the request is dropped due to a server update
	- in case of builds, this isn't a problem, because the lack of reporting back will get noticed and the build will be redone
	- the only cost here is that a build is made twice
	- doc builds wouldn't have that feature unless we also re-ran builds that lack docs
		- but the problem is identifying these builds
		- we're currently triggering on

```sql
            SELECT package_id, min(created_at) FROM (
                SELECT v.package_id, v.latest, MIN(v.created_at) created_at
                FROM versions v
                LEFT JOIN builds b ON b.version_id = v.id
                WHERE v.latest IS NOT NULL
                GROUP BY v.package_id, v.latest
                HAVING COUNT(*) < \(bind: expectedBuildCount)
            ) AS t
            GROUP BY package_id
            ORDER BY MIN(created_at)
```

- cont
    -  cont
		- there's no way to extend this to look at lack of docs as well that isn't going to turn this into a massively complex affair
		- we'd need to load `versions.spi_manifest` and look at `SPIManifest.documentationTargets` and if that's not empty check if there's a `NULL` in some `versions.documentation_targets` reporting field
		- the big problem here is that the `SPIManifest.documentationTargets` would have to happen Swift-side, meaning this would be a multi-step process that somehow needs to be merged with results from the existing SQL query
- $5/month beats that level complexity any time
	- it's the simple solution requiring _no_ cross-communication between subsystems
	- automatically auto-corrects _any_ changes to the S3 storage, be it target name mangling logic changes or doc set deletions
	- we can optimise the costs by checking only for repositories that have a SPI manifest with documentation targets
		- if we wanted to allow certain overrides to take effect, we could simply add a list of repositories that we run additional checks for (think swift-docc, swift-markdown)
	- we can then also feed this info into Grafana from the ingestor (packages that have a manifest but no S3 files) for better docc reporting
