### ISSUE TITLE
docc process-archive transform-for-static-hosting needs single input parameter

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1773]
Generating docs for https://swiftpackageindex.com/GetStream/stream-chat-swiftui/ for iOS creates four doc archives:

```
❯ find ".derivedData" -type d -name "*.doccarchive"
.derivedData/Build/Products/Debug-iphoneos/Nuke.doccarchive
.derivedData/Build/Products/Debug-iphoneos/Gifu.doccarchive
.derivedData/Build/Products/Debug-iphoneos/NukeUI.doccarchive
.derivedData/Build/Products/Debug-iphoneos/StreamChatSwiftUI.doccarchive
.derivedData/Build/Products/Debug-iphoneos/StreamChat.doccarchive
```

We pass this into

```swift
        docc process-archive transform-for-static-hosting \
        $(find "$PWD/.derivedData" -type d -name "*.doccarchive") \
        --output-path "\(outputPath)" \
        --hosting-base-path "\(hostingBasePath)"
```

but `docc process-archive transform-for-static-hosting` doesn't take a list:

```
Error: 4 unexpected arguments: '.derivedData/Build/Products/Debug-iphoneos/Gifu.doccarchive', '.derivedData/Build/Products/Debug-iphoneos/NukeUI.doccarchive', '.derivedData/Build/Products/Debug-iphoneos/StreamChatSwiftUI.doccarchive', '.derivedData/Build/Products/Debug-iphoneos/StreamChat.doccarchive'
```

We also don't really want to upload the unrelated archives `Gifu`, `NukeUI`, and `StreamChat`.

It'll have to come down to heuristics again if there's more than one archive.

**Comment by finestructure** [comment]
Also, running `checkout` followed directly by `generate-docs` raises the following error:

```
note: Build preparation complete
note: Building targets in dependency order
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "EHV7XZLAHA" with a private key was found. (in target 'StreamChatSwiftUI' from project 'StreamChatSwiftUI')"
```

This does not happen if we build in between:

- checkout
- build
- generate-docs

This is actually the sequence of operations on the builder, which saves us here. This might be a `xcodebuild docbuild` bug that we're dodging but it'll mean we need to make sure our regression tests work around that.

**Comment by finestructure** [comment]
This has been deployed but neither of the two package potentially benefiting from this change pass their iOS/5.6 builds at the moment:

- https://swiftpackageindex.com/GetStream/stream-chat-swiftui
  - https://swiftpackageindex.com/builds/23AC5393-6DB0-4579-9579-DF034A911BDC
- https://swiftpackageindex.com/builds/BBE45E9A-3A8F-4FEA-8550-A78026D778BF
  - https://swiftpackageindex.com/builds/BBE45E9A-3A8F-4FEA-8550-A78026D778BF

Not sure exactly why yet but I believe this is new - previously we got to the doc building stage at least. Now it's bailing out even earlier.

cc @jeroenleenarts

**Comment by jeroenleenarts** [comment]
Checked locally with this command. `xcodebuild -derivedDataPath "$PWD/.derivedData" docbuild -scheme "StreamChatUI" -destination 'generic/platform=ios'`. That seems to work.

Also the Target in the .spi.yml file looks good to me.

Wondering what could cause it not finding any schemes.

**Comment by finestructure** [comment]
The build is breaking, because no `scheme` is set and we fail to "guess" it. The `.spi.yml` needs to look like this:

```
version: 1
builder:
  configs:
  - platform: ios
    documentation_targets: [StreamChat, StreamChatUI]
    scheme: StreamChat
```

The `documentation_targets` key tells us which targets to generate docs for but for iOS we also need to know which Xcode scheme to build (and the build needs to pass in order to generate the docs). I'm guessing `StreamChat` is the intended scheme here and not `StreamChatUI`?

The same would apply to https://swiftpackageindex.com/GetStream/stream-chat-swiftui I think.

Does that make sense?

**Comment by finestructure** [comment]
I believe this has been fixed, please re-open if you are still seeing issues!
