### ISSUE TITLE
Verify doc links after lowercase url update

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1776]
- [x] AndrewBarba/swift-compute-runtime
- [x] apple/swift-docc
- [x] apple/swift-markdown
- [x] GetStream/effects-library
- [x] kharrison/ScaledFont
- [x] loopwerk/Saga
- [x] parse-community/Parse-Swift
- [x] pointfreeco/swift-composable-architecture
- [x] RevenueCat/purchases-ios/
- [x] simonbs/Runestone
- [x] skedgo/TGCardViewController
- [x] sherlouk/spangrid
- [x] stackotter/swift-bundler
- [x] swift-server-community/mqtt-nio
- [x] SwiftPackageIndex/SemanticVersion

**Comment by daveverwer** [comment]
All verified and correct!
