### ISSUE TITLE
Integrate Google Analytics

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#178]

**Comment by finestructure** [comment]
Quick note: in case we wanted to avoid GA, we could run an `nginx` cotainer and run the logs through Loki and Grafana now, as shown here: https://grafana.com/blog/2020/11/04/video-top-three-features-of-the-new-loki-2.0/

**Comment by finestructure** [comment]
![](https://grafana.com/static/assets/img/blog/loki2.0_video1.jpg)

**Comment by daveverwer** [comment]
This is very pretty! I think something like this potentially complements JavaScript-based analytics. The advantage of GA is that we can slice and dice the data a bit, and also record JavaScript events for feature usage, as we do for outbound links right now.

I think this will be great for spotting issues with error rates and the like though.
