### ISSUE TITLE
Running `re-analyze-versions` should pull repositories

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1783]
I've figured out why `re-analyze-versions` has been acting up while we've been testing DocC. It doesn't seem to pull/clone the repository before reanalyzing.

Running `analyze` and *then* `re-analyze-versions` works relaibly.

**Comment by finestructure** [comment]
Yep, that's actually a known issue :)

#1261

But now it all makes sense. Originally, re-analyze versions was for updating version when we've made logic changes. Now we're using it to re-analyze when there are _repo_ changes. Hence why it's now imperative to actually run `analyze` for the side-effect of fetching!

**Comment by daveverwer** [comment]
It would also be fine if we added a `--force` or something to `analyze` to stop it throttling so we could just use `analyze` for this.

But potentially better to just get `re-analyze-versions` to fetch
