### ISSUE TITLE
Highlight packages with documentation in search results

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1792]

**Comment by jeroenleenarts** [comment]
@daveverwer Starting on this one.

**Comment by daveverwer** [comment]
I hadn't thought much about how this might work, yet.

The most obvious place for it would be here:

![Screenshot 2022-07-01 at 15 48 13@2x](https://user-images.githubusercontent.com/5180/176917598-852c182f-7d7b-4e52-89a4-a81c9dc96869.png)
 
I am a little nervous to overload people with information in that area. It could be as simple as an icon, I guess. 

Did you have any thoughts on how to display it?

**Comment by jeroenleenarts** [comment]
I'll make a badge first and we can go from there.
Indicate docs in a corner could work too.
