### ISSUE TITLE
Bump package score if a package has documentation

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1793]

**Comment by Sherlouk** [comment]
Is this based purely on the existence of the configuration, or a value of how well it's documented? (A crude example being % of public interface documented)

**Comment by daveverwer** [comment]
My plan was to base it on neither of those things initially. Obviously, documentation coverage would be better than the existence of the configuration but we don't have that and I don't think we should delay boosting the score until (or if) we solve that problem.

#1784 adds a new field `versions.doc_archives` which is updated when the configuration is there *and* docs get successfully generated. I plan to use that to gate these points initially.

**Comment by kelvin13** [comment]
what if a package has documentation hosted elsewhere?

**Comment by heckj** [comment]
@kelvin13 I suspect that as long as it has the means to generate documentation w/ DocC, even if it's already hosted elsewhere, the flag would get triggered by the SPI build system. I don't think (or see) anything that manually turns it on - if it's there, it gets built, and if it gets built, that flag gets set.

**Comment by finestructure** [comment]
We have plans to allow authors to configure an external doc url via the `.spi.yml` file. I imagine we'll treat the presence of that url the same way as SPI hosted docs, allowing authors to easily opt-in via that path as well.

**Comment by daveverwer** [comment]
We've had "plans" for a while now but they've not been written down anywhere. Now they are! https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1894

One step closer! 😅
