### ISSUE TITLE
Swap around branches

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#18]
As discussed yesterday with @daveverwer , the plan is to move `master` to `vapor-3` and then `vapor-4` to be the new `master` branch.

Happy to do that, just let me know what you prefer.

**Comment by daveverwer** [comment]
Yep! This is great, please go ahead and swap the old master branch to be a `vapor-3` branch and make the `vapor-4` branch the new `master`, and default branch.

Fantastic work so far Sven, I'm so happy to be working with you on this!

**Comment by finestructure** [comment]
Thanks Dave, very happy to be chipping away at this! :)

I don't see the settings tab so I can't swap around the default branches, I'm afraid. I've just pushed current `master` as `vapor-3` but you'd need to do the swapping or allow me access.

**Comment by daveverwer** [comment]
All done!
