### ISSUE TITLE
iOS build failing on package index but not local

### ISSUE THREAD

**Issue by kylebrowning** [SwiftPackageIndex/SwiftPackageIndex-Server#1813]
**Please describe the bug**

On my package, [APNSwift](https://swiftpackageindex.com/swift-server-community/APNSwift/builds) builds are failing for iOS. However I can locally successfully, build my project. 

**Explain the steps needed to reproduce the bug**

1. Build and run APNSwift Locally inside an iOS Project
2. See build works.

**What was the expected behaviour?**
Build is built correctly on Package Index Server

**Additional context**
[here's an example project - Fern.zip](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/files/8911063/Fern.zip)

**Comment by finestructure** [comment]
Hi Kyle, thanks for reporting this!

We're guessing the wrong scheme, which unfortunately can happen with iOS builds. I've opened a PR which should fix the issue, given our build system the hint it needs.

**Comment by kylebrowning** [comment]
Thanks @finestructure I see your commit but no PR!  

I'll update spi later today if I don't see a pr from ya. Thanks a bunch!

**Comment by kylebrowning** [comment]
@finestructure this doesn't seem to be resolved, or am I mistaken?

**Comment by finestructure** [comment]
Looks like this is now resolved!
