### ISSUE TITLE
Report doc related 500s as 404s

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1825]
Example: https://rollbar.com/finestructure/SPI-server/items/74

**Comment by finestructure** [comment]
Ok, so the 500 was

<img width="461" alt="CleanShot 2022-06-20 at 07 46 33@2x" src="https://user-images.githubusercontent.com/65520/174533301-a747ab5d-729b-4da1-91eb-75410e731911.png">

which seems like an odd url to fail on.

But what Kingfisher is doing, is linking from our badge to the docs:

![CleanShot 2022-06-20 at 07 47 52@2x](https://user-images.githubusercontent.com/65520/174534057-5810e308-de6d-4d5a-a672-23b2f9a583c8.png)

I'm guessing that this url got messed up while testing it and that's how we ended up receiving it.

I'll keep this open as a reminder to check if a 500 is what we want to raise here. I suspect we just want a 404 instead.

**Comment by daveverwer** [comment]
Just an extra bit of context, they tagged me the other day to ask about the included plugin. https://github.com/onevcat/Kingfisher/discussions/1952

It's still our problem as I'd not expect it to raise a 500 either, but I thought I'd mention the conversation.

**Comment by finestructure** [comment]
These are probably also attempts to access doc target links that have been configured specifically:

<img width="900" alt="174616471-0d923816-3714-49c2-8d0d-5f6427362d9b" src="https://user-images.githubusercontent.com/65520/174754398-e5f7ae2d-1df6-4881-952a-f30e9008dad0.png">

I've [raised a PR](https://github.com/parse-community/Parse-Swift/pull/374#issuecomment-1161427767) to correct the config but we should still make those 404s so users can tell that they're accessing wrong urls.

**Comment by finestructure** [comment]
I believe this is fixed now by recent doccy-proxy changes.
