### ISSUE TITLE
Tweak analyzer's frequency/delay

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#184]
The Linode box currently runs quite hot at around 85% cpu, probably mainly due to the Analyzer.

- [ ] confirm if this is true
- [ ] check what our current refresh rate is
- [ ] dial it back a notch if it's more frequent than an hour (or so) for the full set
- [ ] estimate how big an effect version churn has and if we should change it

**Comment by daveverwer** [comment]
While it's obviously good to refresh packages quickly, don't forget this is only really benefiting us when new versions are released. New packages are always indexed within a couple of minutes of being added. New packages are super important to index quickly. New versions, while important, are much less so in terms of how quickly we index. 

Package releases move very slowly and if a package is showing one beta release out of date for a few hours, it's not even going to be an issue.

From a quick calculation, the SwiftPM Library completes a full cycle around everything in about 4 hours at the moment. That means the *worst case* is that there's a 4-hour delay from a release being pushed to GitHub and it appearing in the index. That seems more than good enough to me.
