### ISSUE TITLE
Analysis fails for "StreamChat"

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1840]
This is a follow-up from a discussion on our Discord: https://discord.com/channels/844491846452379649/844491846914539554/989433930774106172

The issue is as follows:

- an old tag isn't clearing in production
- running analysis locally on a production clone with that old tag clears it correctly
- copying the checkout directory from production also make the local analysis run keep the old tag

→ Something in that checkout either makes the analysis job fail, thereby not clearing the old tag, or the old tag somehow survives our attempts to pull/refresh the checkout.

Since this is now locally reproducible, I'll manually fix production so the correct tag is displayed.

**Comment by finestructure** [comment]
So the problem is that our fetch command isn't correctly pruning tags. We've accidentally picked up 10.0.9 and because we only do `git fetch --tags` we're not getting rid of it anymore. I suspect we don't often see this issue because it old versions don't show up anywhere except in our database. 10.0.9 is different, because it because the latest release version due to its high major release number.

What worked to get rid of the stale tags is:

```
❯ git fetch --tags --prune-tags --prune
From https://github.com/GetStream/stream-chat-swift
 - [deleted]             (none)     -> 1.5.3.1
 - [deleted]             (none)     -> 10.0.9
 - [deleted]             (none)     -> 2.0
 - [deleted]             (none)     -> 3.0
 - [deleted]             (none)     -> 3.0-alpha
 - [deleted]             (none)     -> 3.0-alpha.1
 - [deleted]             (none)     -> 3.0-beta.1
 - [deleted]             (none)     -> 3.0-beta.2
 - [deleted]             (none)     -> 3.0-rc.1
 - [deleted]             (none)     -> 3.0-rc.2
 - [deleted]             (none)     -> 3.0-rc.3
 - [deleted]             (none)     -> 3.2-beta
 - [deleted]             (none)     -> 3.2.1.6
 - [deleted]             (none)     -> 4.0-beta.1
 - [deleted]             (none)     -> list
 - [deleted]             (none)     -> ui-3.0-beta.1
 - [deleted]             (none)     -> ui-3.0-beta.2
 - [deleted]             (none)     -> ui-3.0-beta.3
 - [deleted]             (none)     -> ui-3.0-beta.4
```

I'm not sure if that's the canonical version of that git command (feels a bit redundant) but it certainly works.

**Comment by jeroenleenarts** [comment]
Looks good now on main page.
