### ISSUE TITLE
Builds timed out for Soto 6.0 release

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1845]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/soto-project/soto

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

Some of the soto builds timed out:
  https://swiftpackageindex.com/soto-project/soto/builds

**Comment by finestructure** [comment]
We may be able to lift this now, I don't think build time is as bad as it used to for Soto.

**Comment by finestructure** [comment]
It's still taking close to the 10min processing limit, so we wouldn't want to lift the downscaling. That's the best way to protect us getting bogged down by Soto dropping a release. The builds that can make it in time will do so eventually, and perhaps faster hardware or faster Swift versions might help.
