### ISSUE TITLE
Build failure: "spi-builder-workspace' is using Swift tools version 5.6.0 but the installed version is 5.5.0"

### ISSUE THREAD

**Issue by calimarkus** [SwiftPackageIndex/SwiftPackageIndex-Server#1847]
All builds other than Swift 5.6 are failing for my [`JDStatusBarNotification`](https://swiftpackageindex.com/calimarkus/JDStatusBarNotification) package (which is actually pure Obj-C, shouldn't it work across all swift versions?). See all [build results](https://swiftpackageindex.com/calimarkus/JDStatusBarNotification/builds).

Full error from [build results](https://swiftpackageindex.com/builds/68F0C57A-266C-4A51-B1BE-E7000A32FE6F):

```
Could not resolve package dependencies:
  package at '/Users/builder/builds/ogLoW6xX/0/finestructure/swiftpackageindex-builder/spi-builder-workspace' is using Swift tools version 5.6.0 but the installed version is 5.5.0
```

**What was the expected behaviour?**

Expected all swift versions to be ok?

**Screenshots**

<img width="602" alt="Screen Shot 2022-06-26 at 5 49 17 PM" src="https://user-images.githubusercontent.com/807039/175806773-72a35f97-523f-4ac9-9a94-ec9d4c37b50a.png">

**Comment by calimarkus** [comment]
My Package.swift defines a swift-tools-version of 5.6 - that's probably the culprit here, right?

**Comment by finestructure** [comment]
Yes, that'll prevent it from building with Swift < 5.6!

**Comment by calimarkus** [comment]
I set it to 5.3, but it hasn't triggered new builds so far. I'll wait a bit. I'll close this - thanks.

**Comment by calimarkus** [comment]
Just to follow up here.. updating the package file resolved it:

[![Builds results](https://user-images.githubusercontent.com/807039/176083435-9e896be0-300f-43db-a20b-a8b900639bb8.png)
](https://swiftpackageindex.com/calimarkus/JDStatusBarNotification/builds)
