### ISSUE TITLE
Packages with many documentation targets/archives break the DocC header

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1865]
[GatheredKit](https://swiftpackageindex.com/JosephDuffy/GatheredKit/main/documentation/gatheredkit)

<img width="1008" alt="Screenshot 2022-07-01 at 17 21 14@2x" src="https://user-images.githubusercontent.com/5180/176933139-a47714ff-0a7f-4954-b7fc-b0ddb0f7d44b.png">

[Epoxy](https://swiftpackageindex.com/airbnb/epoxy-ios/master/documentation/epoxybars)

<img width="1016" alt="Screenshot 2022-07-01 at 17 21 45@2x" src="https://user-images.githubusercontent.com/5180/176933201-960aa592-cb67-4977-a455-c2f7d4ed4574.png">

**Comment by finestructure** [comment]
It's loading for me, local caching issue?

**Comment by finestructure** [comment]
<img width="730" alt="CleanShot 2022-07-01 at 18 25 21@2x" src="https://user-images.githubusercontent.com/65520/176933691-121d7cf7-eca2-4d08-b57a-d83ee0bd492d.png">

**Comment by daveverwer** [comment]
No, no. Sorry. I mean the header where it lists the archive switcher is broken as it's now wrapping "Documentation for:" and the targets go off the right-hand side of the screen.

Purely a visual bug, nothing wrong with the docs themselves.

**Comment by finestructure** [comment]
Oh, I completely missed the issue title 🤦‍♂️
