### ISSUE TITLE
S3 lookup race condition

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1868]
There is still a race condition in our doc archive discovery. What's happening is that we're looking for doc archives in S3 when a new version is picked up from the repository. However, _new_ versions have not triggered any builds at that point, which means there's no doc archive uploaded yet.

In case of default branch builds, this means that currently when a package adds documentation, the first new version with that documentation will _not_ pick up the documentation. Subsequent runs will, however, because in case of default branches, we update the existing folder in S3 with newer docs in place.

In other words:

new `main` with docs picked up by analysis
→ no docs in S3 yet
→ `version.docArchives = []`
→ no documentation url shown, because versions.docArchives is `[]`
→ build triggered
→ doc archives uploaded

another change to `main` pushed
→ previous doc archive found
→ `version.docArchives = [...]`
→ doc url shown
→ build triggered
→ doc archives updated

It's quite obvious in hindsight but the fact that the second run straightens things out is what obscured this in testing.

In case of versioned docs (which we're not currently exposing), the mechanism is entirely broken, because we're never updating docs in place unless we rebuild for a given release:

new release with docs picked up by analysis
→ no docs in S3 for that release
→ `version.docArchives = []`
→ no documentation url shown, because versions.docArchives is `[]`
→ build triggered
→ doc archives uploaded

Since there is no subsequent build for the same release, in this case the error doesn't correct itself (but can be easily fixed via `re-analyze-versions`).

There is no reliable way to discover the docs unless we do it repeatedly on analysis passes. That's no really possible in case of release versions that only appear once, and that's not really a mechanism we want to change at this point.

The best way to fix this is to pick up the doc archive results from the build itself. Dave, you'll be happy to hear this :)

The reason I wanted to avoid this initially was because I didn't want to deal with the complexity of adding an additional ping back from the builder. Also, there was no way a doc build would be re-run if the additional ping back was lost, for instance due to a deployment being in progress when the ping happened.

For builds this isn't a problem, because they get retried when the build doesn't report back.

I also didn't want to simply move the single build report until after the doc are processed initially, because I wanted to make sure doc builds cannot interfere with the build process by design.

I think at this point we've seen that the doc builds aren't problematic and I'd be ok with making this change.

I'd certainly rather have a single build report with additional doc archive info in it than try to report back twice (for the reasons given above). This way, we'd get the info and we'd also be certain that any builds that don't report back are automatically retried, just like before.

Side note: I'm a bit worried that we don't have a decent test setup for all this in staging. Running the full build system in dev is prohibitive and we'd then also double our S3 costs. I think the best solution would be to designate a handful of packages for which we disable build downscaling on staging. This way we'd have some packages that get indexed exactly the same way as prod without paying the full price for it.

**Comment by daveverwer** [comment]
> The best way to fix this is to pick up the doc archive results from the build itself. Dave, you'll be happy to hear this :)

Yea. I know we covered it previously but with the amount of manual checking for people we are doing at the moment I think this is becoming more urgent. I'm happy to have another reason we'll need to do it!

> I think the best solution would be to designate a handful of packages for which we disable build downscaling on staging. This way we'd have some packages that get indexed exactly the same way as prod without paying the full price for it.

Good idea.

**Comment by finestructure** [comment]
The builder side reporting is ready: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/130

**Comment by finestructure** [comment]
The builder changes are live and seem to be working.

The remainder of the roll-out is as follows:

- Merge #1889 , which removes all the S3 lookup business and resets the `versions.doc_archives` field to `NULL`. We don't need a schema change even though we're changing the structure of `DocArchive` in Swift, because the backing store is `JSONB[]` - i.e. it can handle any array of `Codable`s, which this still is. We just need to nil the field out to avoid decoding errors from reading an older version of the struct with the newer definition.
- Merge #1891 , which then allows the server to handle the incoming build reports with doc archives and saves them to `versions.doc_archives`
- Run a query to delete all builds that produce docs, in order to start a reprocessing and reporting of doc archives.
- Update the doc url again to use `doc_archives` (Revert 2.72.1)

The query is the following:

```sql
-- delete 5.6+(ios|macos-spm) builds for versions that should have docs
delete from builds where id in (
  select b.id
  from versions v
  join builds b on b.version_id = v.id
  where spi_manifest::text like '%documentation_targets%'
  and (doc_archives is null or doc_archives = '{}')
  and b.platform in ('ios', 'macos-spm')
  and b.swift_version->>'major' = '5' and b.swift_version->>'minor' = '6'
)
;
```

This is slightly too broad, because it deletes both the `ios` as well as `macos-spm` builds for all versions with `documentation_target` manifests. However, there are just 294 builds in total, so while we could make the selection perfect it's not really worth fiddling with if for saving to run 150 builds.

**Comment by finestructure** [comment]
All builds are reset. First versions have been reported back, just need to wait for all of them to catch up:

```
31cd615a-65c7-4c8d-9af1-296153d64a33 | {"{\"name\": \"tgcardviewcontroller\", \"title\": \"TGCardViewController\"}"}
d4b9b078-91bd-468e-9036-638bc01771c8 | {"{\"name\": \"saga\", \"title\": \"Saga\"}"}
0176e51e-0d17-491e-9b57-9aa48cc77e64 | {"{\"name\": \"scaledfont\", \"title\": \"ScaledFont\"}"}
768b29c9-fbdf-4462-aca3-cbd59f852fbe | {"{\"name\": \"mqttnio\", \"title\": \"MQTTNIO\"}"}
34cb78a1-f12a-4877-bbf9-9f4e57431b0d | {"{\"name\": \"semanticversion\", \"title\": \"SemanticVersion\"}"}
9a937e68-4360-4cb0-b369-95c1be2c2d18 | {"{\"name\": \"swiftbundler\", \"title\": \"SwiftBundler\"}"}
61a205e3-555c-41d6-b68d-a85e23411d16 | {"{\"name\": \"scaledfont\", \"title\": \"ScaledFont\"}"}
a332e75e-1981-45bd-a3eb-6584749c2bf1 | {"{\"name\": \"semanticversion\", \"title\": \"SemanticVersion\"}"}
```
