### ISSUE TITLE
Order tags in search results by keyword weight

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1870]
Now that we have keyword counts on the package page (thanks @jeroenleenarts!) there’s one more obvious place that we can make use of this data. Tag search results.

<img width="248" alt="Screenshot 2022-07-04 at 13 05 18@2x" src="https://user-images.githubusercontent.com/5180/177151324-2f0d9d07-0dd1-476c-badd-0807367a413a.png">

We should change these in two ways:

- [x] Order by the weighted count, highest to lowest.
- [x] Display the count as a tag, as we do on the package page.

**Comment by jeroenleenarts** [comment]
I'll get to this one in the next few days.

**Comment by jeroenleenarts** [comment]
```SELECT *
from search s
join unnest(keywords) as singlekeyword on true
join weighted_keywords wk on wk.keyword = singlekeyword```

**Comment by jeroenleenarts** [comment]
@finestructure I need to represent the above in SQLKit... Any idea how to get that into `keywordMatchQueryBuilder`?
