### ISSUE TITLE
Duplicate version

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#190]
For some reason the `max(version)` isn't kicking in to filter out multiple releases:

![IMG_0076](https://user-images.githubusercontent.com/65520/83102684-5d1e1a00-a0b5-11ea-88f2-09ef532f135b.png)

**Comment by finestructure** [comment]
Actually, these are two different packages:

- https://github.com/orta/packageconfig.git
  http://173.255.229.82:8080/packages/1535505A-32EC-459F-AD60-413D0AA732D9
- https://github.com/shibapm/packageconfig.git
  http://173.255.229.82:8080/packages/7AA89197-1D68-493E-BC7A-0EB73BA2E8E9

**Comment by daveverwer** [comment]
Weeeird... neither is a fork of the other, but they're clearly the same thing.

I guess we just leave them? 🤷‍♂️

**Comment by finestructure** [comment]
Oh, interesting - https://github.com/orta/packageconfig.git redirects to the other one. This must be a name change

**Comment by daveverwer** [comment]
Ahh yes, let me remove the old one from the master list.

**Comment by daveverwer** [comment]
Done.
