### ISSUE TITLE
Add a note about how to log database queries to the LOCAL_DEVELOPMENT.md

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1903]
Instructions are in #1896

**Comment by heckj** [comment]
setting to `.info` was an eye opener, and unexpected!

The docs referenced from Logger.level indicate the levels are ordered in terms of criticality, but then have descriptions that make me think they're not entirely in an expected order in the DocC generated content, which is immensely confusing. Instead, I think they're just dropped in alphabetically by DocC. I'll make a mention of this upstream in Logger, as that was the most surprising to me. I misread things and thought `.debug` was more messages and less focused than `.info`, but it's (apparently) the other way around.

**Comment by heckj** [comment]
Logged the fact that it's grossly unordered in DocC upstream: https://github.com/apple/swift-log/issues/224

**Comment by samdeane** [comment]
I had the same confusion @heckj. I read the instructions, and thought “right, must be a typo, I probably need to set it to debug to get the extra info”, then looked at the code and went “huh?”.
