### ISSUE TITLE
Versioned documentation go-live

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1909]
- [x] Regenerate all documentation using 5.7 so we have consistent documentation across branches and versions
- [x] Remove breadcrumb feature gate at DocumentationPageProcessor.swift:104
- [x] Remove latest-stable feature gate at DocumentationPageProcessor.swift:148

**Comment by finestructure** [comment]
Via https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/134#note_1032316154

> The problem with this change is that we require packages to build with 5.7 in order to have docs. The added difficulty is that we're not showing 5.7 builds on the package page, so authors can't even check on the results if there are failures.
> 
> 5.7 should work in most cases but I've already seen a test failure with our regression suite building ref `ff90e2e52b586e63dfa7876106e8773ab2733aa9` of https://github.com/GetStream/stream-chat-swiftui.git. Switching to a newer ref `195c996ec0c48f96b7813b12a2aefcda374ca282` doesn't fix the issue.
> 
> This is an iOS build. I can't tell if they're all broken or if it's just this one. Either way, I don't think we can ship this unless we at least also show 5.7 builds on the package page. Even then it might be premature to switch to 5.7 wholesale. I.e. there are likely a number of packages that would lose docs (or have them grow stale rather) if we did that.
> 
> We may need to make 5.7 docs opt-in via `.spi.yml` initially, or delay it until we're futher along in the beta cycle or even until after release.

**Comment by daveverwer** [comment]
> We may need to make 5.7 docs opt-in via .spi.yml initially, or delay it until we're futher along in the beta cycle or even until after release.

I don't think this is a terrible idea. Launching with 5.6 docs and re-generating and upgrading at 5.7 stable would be a "feature", too! 😅

I think we were thinking along similar lines this morning, I [just posted this](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/1911).

**Comment by finestructure** [comment]
I think we need to

- add 5.7 to the package pages
- review the builds status of package with docs and 5.7 to assess how many cases there are where 5.7 fails vs 5.6
- based on that decide if we default to 5.7 or make it opt-in 

For instance, if we see that lots of packages fail on 5.7 we should stay on 5.6 for the doc builds and advertise the option of opting into 5.7 doc builds for packages that support 5.7.

If there are very few packages where 5.7 breaks when 5.6 didn't, we could default to 5.7 and submit PRs to those package to fall back to 5.6 doc builds.
