### ISSUE TITLE
Look at `.swift-version` for swift version info

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#191]

**Comment by finestructure** [comment]
My memory is terrible - I think we concluded not to prioritise this until we have some indication whether this would move the needle?

Preference would be for people to adopt our metadata file but if we see that a lot of packages don't have a version but do have a `.swift-version` file then we could easily ingest this data.

**Comment by daveverwer** [comment]
Yep, we were going to leave the investigation of this until after launch, and start it by seeing how many repos actually implement it by running a check on the checked out repositories.

**Comment by finestructure** [comment]
I don’t think we want to do this anymore. I’ll close it.
