### ISSUE TITLE
Package list “add” is failing

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1918]
Seems to affecting a number of packages - there are a number of open issues to add new packages.

![D7822966-7AFD-459B-8640-2920424C1EAA](https://user-images.githubusercontent.com/65520/180703552-2244e1aa-b4c1-4e6d-adda-87c5e8326b8e.png)

**Comment by daveverwer** [comment]
I keep a close eye on those issues and that's an odd failure that I've not seen before. The script usually only fails for valid reasons.

The current status of those open Issues is:

* #2325 has been open for a while and needs 5.7
* #2549/#2560 in discussion with package author about reducing from 5.7 to 5.6 as it doesn't *actually* need 5.7
* #2474 needs 5.7
* #2469 did require 5.7 but the author made it 5.6 last night

I think we can close this.

One thing. I think you disabled notifications for issues and kept pull requests on? I think it might be better to switch it around and get issues and not PRs. I have issues on to catch when this fails but it'd be better if we were both aware.
