### ISSUE TITLE
Explore using PackageConfig mechanism to embed spi metadata in Package.swift

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#192]
https://github.com/shibapm/PackageConfig

We should be able to define our own type and extract it server side. Downside is that it'll require a compile and run step on the sever (i.e. slower, prone to version mismatch).

A proper yaml file is easier but it might still be worth at least exploring the option.

**Comment by daveverwer** [comment]
I saw this package and had the same thought. 

One downside is that some formats are just better suited for metadata, especially text metadata like longer descriptions, and the like... I'm not sure Swift is the perfect format for it. It's certainly something to keep in mind though.

**Comment by finestructure** [comment]
Actually, re-reading the package description just now I don’t think this would be terribly useful. Adopting packages would need to include `PackageConfig` in the `Package.swift`.

I think we can close this, no?
