### ISSUE TITLE
Code Syntax Highlighting not working within Docc documentation

### ISSUE THREAD

**Issue by aure** [SwiftPackageIndex/SwiftPackageIndex-Server#1928]
When the code is marked with three ticks and the word Swift, it should be highlighted properly, and it does work on README.md files for repos so it should work in docc too. Here's an example of it not highlighted properly:

https://swiftpackageindex.com/AudioKit/PianoRoll/main/documentation/pianoroll

**Comment by daveverwer** [comment]
Hi Aurelius, and while you're here thanks so much for all your valuable work on AudioKit!

I've not looked into this yet, but my first thought would be to check whether this highlights correctly running DocC locally/outside of the SPI wrappers. I don't suppose you've done that, have you? If it works there, it's definitely our problem!

**Comment by daveverwer** [comment]
> does work on README.md files for repos

On this point, we highlight README files in a different way from DocC, which relies entirely on the DocC tool itself.

**Comment by finestructure** [comment]
I believe the problem is that you've used `Swift` as the marker after the triple tick, not `swift` (lowercase). It seems to work for Runestone for instance:

https://swiftpackageindex.com/simonbs/runestone/main/documentation/runestone/gettingstarted

**Comment by aure** [comment]
@finestructure I made that change, waiting for things to update to see if it worked.

**Comment by aure** [comment]
That was indeed it, thank you!
