### ISSUE TITLE
Approve docker image for building swift-cross-ui

### ISSUE THREAD

**Issue by stackotter** [SwiftPackageIndex/SwiftPackageIndex-Server#1988]
SwiftCrossUI fails to build unless the gtk system dependency is present on the build machine, and hence I was told that the best option was to create a custom docker image and add it to the spi.yml configuration file so that at least the ci works for Linux.

A contributor to the project (@NinjaCheetah) has created [such a docker image](https://hub.docker.com/layers/swift-cross-ui/ninjacheetah/swift-cross-ui/1.0.1/images/sha256-a128de5625adefef27c43972bc12cc45209a2d2dce2173f4fef7425320756670?context=explore) and it successfully builds the package when run with the command in the blog post about spi manifests.

I think the next step is getting it approved?

**Comment by finestructure** [comment]
> I think the next step is getting it approved?

Yes, we need to allow-list it in our build system.

One thing that's missing is variants for the various swift versions we builds.

But rather than you provide those, I wonder if there's an easier mechanism here and I want to try something to support it. Do you have a link to the Dockerfile that's been used to create this image?

**Comment by NinjaCheetah** [comment]
Here's the Dockerfile that I used:
[https://github.com/NinjaCheetah/swift-cross-ui/blob/main/Dockerfile](https://github.com/NinjaCheetah/swift-cross-ui/blob/main/Dockerfile)

**Comment by finestructure** [comment]
#1994 also needs a base image.

I'll set something up to host them both - or even a combined image, which is probably the easiest and most efficient way to go. Builders will have it cached even if it's a bit larger and the only reason for us to manage different images would be incompatible dependencies or dependency versions.

**Comment by finestructure** [comment]
I've opened a PR here that should address this: https://github.com/stackotter/swift-cross-ui/compare/main...finestructure:swift-cross-ui:patch-1

**Comment by stackotter** [comment]
Sadly it doesn’t seem to have worked afaict. It looks like the builder didn’t use the new docker image?

**Comment by finestructure** [comment]
Yes, same for SPI-Sever, which I've been testing with 🤔 I'll keep you posted here!

**Comment by finestructure** [comment]
Ok, I've found the issue. I'll re-run your builds once it's been deployed.

**Comment by finestructure** [comment]
This is now succeeding for SPI-Server: https://swiftpackageindex.com/builds/DB4B7E5C-797E-4542-817F-870948B99F9A

but still failing for swift-cross-ui: https://swiftpackageindex.com/builds/9F53D249-E980-4851-9F58-B9AE9BAB63AB

The chosen image is ok now so it seems like the dependencies are not correct?

Command:

```
docker run --rm -v "checkouts-4609320-1":/host -w "/host/spi-builder-workspace" registry.gitlab.com/finestructure/spi-images:basic-5.6-latest swift build 2>&1
```

Error:

```
[1/29] Compiling SwiftGtk Orientation.swift
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "header.h"
         ^
/host/spi-builder-workspace/.build/checkouts/SwiftGtk/Sources/CGtk/Linux/header.h:1:10: error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^
/host/spi-builder-workspace/.build/checkouts/SwiftGtk/Sources/SwiftGtk/Application.swift:5:8: error: could not build C module 'CGtk'
import CGtk
       ^
```

Base image [Dockerfile](https://gitlab.com/finestructure/spi-images/-/blob/main/Dockerfile):

```
ARG SWIFT_VERSION
FROM swift:${SWIFT_VERSION}-focal

RUN apt-get update && apt-get install -y \
    sqlite3 libsqlite3-dev  # SPI-Server \
    libgtk-3-dev clang # swift-cross-ui
```

**Comment by finestructure** [comment]
Meh, I see what happened:

```
RUN apt-get update && apt-get install -y     sqlite3 libsqlite3-dev  # SPI-Server     libgtk-3-dev clang # swift-cross-ui
```

that was clever...

**Comment by finestructure** [comment]
Ok, here we go now 😅

https://swiftpackageindex.com/stackotter/swift-cross-ui/builds

<img width="739" alt="CleanShot 2022-08-30 at 12 54 24@2x" src="https://user-images.githubusercontent.com/65520/187419060-81ae30b6-8f42-4b26-aa62-866937368bd6.png">

**Comment by stackotter** [comment]
> Meh, I see what happened:

Hahah, that was sneaky.

Thanks for getting Linux builds working!
