### ISSUE TITLE
Carthage shows "Unknown License"

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#199]
Could just be that they've not picked the license from a template perhaps?

<img width="1219" alt="Screenshot 2020-05-29 at 07 41 28" src="https://user-images.githubusercontent.com/65520/83225324-cff3c780-a17f-11ea-8f18-f8a1f467767a.png">

<img width="1219" alt="Screenshot 2020-05-29 at 07 41 35" src="https://user-images.githubusercontent.com/65520/83225330-d3874e80-a17f-11ea-9682-dfbcdd33d26e.png">

**Comment by finestructure** [comment]
I wonder if it'd be useful to add a "Report issue" button to the package page to autocreates an issue (with a label that we can filter on) to make quality issues simple to report. I guess it could create at lot of noise but we could always disable it or filter out the issues?

**Comment by daveverwer** [comment]
Yea for some reason GitHub is failing to detect that license type for some reason. They use [licensee](https://github.com/licensee/licensee) under the hood for this. You can also see it's not recognised on their GitHub page:

<img width="267" alt="Screenshot 2020-05-29 at 09 54 55@2x" src="https://user-images.githubusercontent.com/5180/83241257-78ab2280-a192-11ea-8f28-fe9d06a9e2c5.png">

Whereas a package with a recognised license shows up in GitHub like this:

<img width="250" alt="Screenshot 2020-05-29 at 09 57 58@2x" src="https://user-images.githubusercontent.com/5180/83241585-f1aa7a00-a192-11ea-84bf-90a03c9d9188.png">

I don't think we have a report issue button, but Unknown License button itself could be a link to a FAQ page on how to fix this. (Filed as #203)

**Comment by daveverwer** [comment]
Closing in favour of #203 and #204.
