### ISSUE TITLE
Broken URL on SPI Blog

### ISSUE THREAD

**Issue by ahmdyasser** [SwiftPackageIndex/SwiftPackageIndex-Server#1993]
**The build system** URL is broken in [this](https://blog.swiftpackageindex.com/posts/the-swift-package-index-metadata-file-first-steps/) article. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42544598/186779403-953e4d59-880a-4a4c-9e86-f09f2f038152.png)

![image](https://user-images.githubusercontent.com/42544598/186779360-268148e6-dc49-42d4-9a4c-a83067a1f72f.png)

**Comment by daveverwer** [comment]
Thank you for reporting this, Ahmad! Fixed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Blog/pull/81
