### ISSUE TITLE
apple/swift-docc renders blank page

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1998]
https://swiftpackageindex.com/apple/swift-docc/main/documentation/docc renders a blank page:

<img width="1405" alt="CleanShot 2022-08-30 at 09 39 06@2x" src="https://user-images.githubusercontent.com/65520/187378527-37c65512-7b7e-4447-82e2-cb42725c4ffa.png">

**Comment by daveverwer** [comment]
Yea, something is odd with [this package](https://swiftpackageindex.com/sivx76/Swift-Table) that added documentation yesterday, too:

<img width="1367" alt="Screenshot 2022-08-30 at 08 42 16@2x" src="https://user-images.githubusercontent.com/5180/187379196-365ac5e6-243c-41d3-bcac-f48218c73809.png">

**Comment by daveverwer** [comment]
I just went back to the window, and it eventually loaded this:

<img width="1367" alt="Screenshot 2022-08-30 at 08 44 00@2x" src="https://user-images.githubusercontent.com/5180/187379626-ddd7b040-1ce0-4911-ac56-caf0172ba33c.png">

**Comment by daveverwer** [comment]
... and now it loads fine ...

Maybe an S3 blip?

<img width="1367" alt="Screenshot 2022-08-30 at 08 44 42@2x" src="https://user-images.githubusercontent.com/5180/187379795-08cef78d-dfa0-40ff-8720-44a476a80e1a.png">

**Comment by daveverwer** [comment]
Or could be Azure, as I just got this:

<img width="1101" alt="Screenshot 2022-08-30 at 08 45 40@2x" src="https://user-images.githubusercontent.com/5180/187379983-6cd493bd-3587-4ab3-b615-bbab57d03a10.png">

**Comment by finestructure** [comment]
Getting this now after a browser cache reset:

<img width="1405" alt="CleanShot 2022-08-30 at 10 01 31@2x" src="https://user-images.githubusercontent.com/65520/187383376-405e11f2-4837-4cb7-bf9d-c6220891779f.png">

**Comment by finestructure** [comment]
I've restarted `p1` and `p3` as well now (I'd restarted `p2` earlier when we got an analysis alert). When I cycled `p3` became unstuck for me. Looks like an internal network glitch, possibly inside docker swarm.

Leaving this open for a while as we monitor.

**Comment by finestructure** [comment]
TBH, Azure's own dashboard seems to be having internal timeouts.

<img width="391" alt="CleanShot 2022-08-30 at 12 19 16@2x" src="https://user-images.githubusercontent.com/65520/187412850-8379ca8f-cf0b-4b32-9cdf-dec4748ec19c.png">

**Comment by finestructure** [comment]
Might be related, I think that's our base image.

https://status.azure.com/en-gb/status

<img width="852" alt="CleanShot 2022-08-30 at 12 37 13@2x" src="https://user-images.githubusercontent.com/65520/187415968-ac606e3e-9729-4ac8-b27b-b666dd847f6f.png">

**Comment by finestructure** [comment]
Seems to have settled down:

<img width="387" alt="CleanShot 2022-08-30 at 14 17 59@2x" src="https://user-images.githubusercontent.com/65520/187434643-f04012fb-ac1e-4265-bb3a-966bb8dd7753.png">
