### ISSUE TITLE
Bad URLs in the master package list are currently ignored

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2]
In `ReconcilePackageListCommand` the `fetchMasterPackageList` method currently throws away bad URLs from the fetched JSON.

There should never be bad URLs in that file, but if there are, the reconciliation process should report on them.

**Comment by 0xTim** [comment]
Should this just print out bad URLs or do you have something else in mind?

**Comment by daveverwer** [comment]
Not sure yet 😬 the reason I added it as an issue rather than just implementing it now is that I'm not sure how these tasks are going to execute when this is hosted and what kind of feedback I can get from them.

This situation will be rare enough that it might be as simple as making the `Command` fail in this situation and output the bad URLs. Maybe if the `Command` fails in production it can be configured to email the output to me? Not sure yet.

The alternative is to have a table of strings for bad URLs, but that seems like overkill and would need checking manually.

**Comment by daveverwer** [comment]
The current implementation uses [Rollbar](https://rollbar.com/) for this which takes care of all sorts of things like multiple occurences of the same error over and over, and various other niceties.

Rollbar supports iOS projects, but implementing it for Vapor would probably be something that would need to be done via their API which is going to be a ton of work.

**Comment by 0xTim** [comment]
Eh the API doesn't look too difficult. I'll do a PR for the first bit, then look at Rollbar if you want

**Comment by daveverwer** [comment]
Wonderful work, thank you Tim!
