### ISSUE TITLE
Timeout aborted Linux builds not reporting back

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2001]
There are more env variables that need to be set:

```
⚠️  Signal to terminate received.
⚠️  Some environment variables unset, cannot report back timeout.
```

https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/2959304694

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/149

**Comment by finestructure** [comment]
One problem we're having right now is that all of these we're running through the same two linux builders:

- builds (currently back-logged > 100)
- builder updates (docker image build + CI matrix)
- spi-server update builds

We'll need to set something up to at least funnel the latter two through a different builder so we can get them past a build backlog.

**Comment by finestructure** [comment]
I've manually killed all the linux jobs ahead of the builder update now. That should allow this to deploy next and then hopefully slowly clear up the backlog.

**Comment by daveverwer** [comment]
I know it's more work, but there's always the possibility of splitting those tasks out onto separate machines rather than having a combined pool.

**Comment by finestructure** [comment]
Well, we don’t have any machines to split it out to at the moment, that’s the problem :)

**Comment by daveverwer** [comment]
No, that's what I was suggesting. We have Azure budget we could use.

**Comment by finestructure** [comment]
Deployed
