### ISSUE TITLE
Add support for Swift 5.7

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2008]
- [x] Open validation for 5.7-only packages
  - [x] https://github.com/SwiftPackageIndex/PackageList/pull/2717 → update nightly to official release and update validation as well (this requires an official release version)
- [x] Use 5.7 for package dump (update server base image to 5.7) #2009 
- [x] Add support for 5.7 in builder ([PR](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/150))
- [x] Install 5.7 on Mac builders
- [x] Update matrix in server (#2013)
- [x] Deploy updated builder
- [x] Deploy updated server

**Comment by finestructure** [comment]
Of these 5.7 packages that I've just added:

- https://swiftpackageindex.com/tevelee/SwiftUI-Flow.git
- https://swiftpackageindex.com/rnapier/RNAJSON.git
- https://swiftpackageindex.com/akardas16/SideMenu.git
- https://swiftpackageindex.com/orchetect/OSCKit.git
- https://swiftpackageindex.com/NeilsUltimateLab/AutolayoutExtension.git
- https://swiftpackageindex.com/apple/swift-nio-imap.git
- https://swiftpackageindex.com/icanzilb/MarkCodable.git

only 

- https://swiftpackageindex.com/orchetect/OSCKit.git

is showing up in the index. Since we're using 5.6 to dump the package I would have expected none of them to pass analysis. Not sure yet how that one is different - it definitely has `// swift-tools-version:5.7` in its `Package.swift`.

**Comment by finestructure** [comment]
Failing as expected

```
~/D/OSCKit on  main
❯ env DEVELOPER_DIR="/Applications/Xcode-13.4.1.app" xcrun swift package dump-package
'osckit': error: package 'osckit' is using Swift tools version 5.7.0 but the installed version is 5.6.0
error: invalid manifests at [<AbsolutePath:"/Users/sas/Downloads/OSCKit">]
~/D/MarkCodable on  main
❯ env DEVELOPER_DIR="/Applications/Xcode-13.4.1.app" xcrun swift package dump-package
'markcodable': error: package 'markcodable' is using Swift tools version 5.7.0 but the installed version is 5.6.0
error: invalid manifests at [<AbsolutePath:"/Users/sas/Downloads/MarkCodable">]
```

**Comment by heckj** [comment]
Did it start as a 5.6 project and evolve to 5.7?

**Comment by finestructure** [comment]
Mmm, that shouldn’t make a difference - plus when it was first seen after adding it earlier it _was_ 5.7 🤔

**Comment by finestructure** [comment]
Not sure what exactly happened - but they're all there now. Just as I'd run the analysis locally and found no problem 😅

**Comment by finestructure** [comment]
Ok, the package-dump failure mentioned above does _not_ prevent the package from showing up in the index anymore. We're not getting all the info (like the proper package name) but we _are_ saving versions etc. It's still not quite clear to me how for instance `MarkCodable` showed up in search but wasn't available yet (indicating analysis hadn't run) or why none of the package above other than `OSCKit` showed up in the "Recently Added" (still not, even now that they're available).

Not going to dwell on that though for the moment.

**Comment by finestructure** [comment]
This is done
