### ISSUE TITLE
Colour the license lozenges differen colours for Unknown License and licenses that are incompatible with the App Store.

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#204]
<img width="290" alt="Screenshot 2020-05-29 at 10 03 16@2x" src="https://user-images.githubusercontent.com/5180/83242024-a2187e00-a193-11ea-8921-dfdc4da8fad8.png">

**Comment by daveverwer** [comment]
Also, remove the OSI logo for "Unknown License" (but not incompatible licenses).

**Comment by mattt** [comment]
Glad to see this change. Thanks for responding to my feedback, @daveverwer.

I think that red may not be the best treatment for "unknown", as it indicates an error. Most design systems treat unknown would associate gray or yellow for this state.

Also, I didn't realize that the color corresponded to App Store compatibility. If you aren't doing this already, you might consider calling this out in a "title" attribute or some other kind of onhover disclosure.

**Comment by daveverwer** [comment]
👍

I was planning to use red even for unknown licenses as I think it's as bad as an incompatible license. Unlicensed/unknown code is more urgent and important than the absence of something generally is and shouldn't be ignored. I think red is warranted in that situation.

Also, clicking a "red" license will take the viewer to the FAQ too (#203).

**Comment by mattt** [comment]
Based on that description, I'd say yellow would be more appropriate. For me, it's:

- <span style="color: green;">Green</span>: OK, good to go
- <span style="color: yellow;">Yellow</span>: Warning, proceed with caution
- <span style="color: red;">Red</span>: Error, this is a problem
- <span style="color: gray;">Gray</span>: Not sure, invalid, N/A, or to be determined

I suspect that we'll see more variation in open source licenses in the coming years, as folks experiment with new commercial and ethical standards. I worry that red unnecessarily conflates "different" with "harmful".
