### ISSUE TITLE
Tutorial links load, but 404 on reload

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#2044]
Here's an interesting one.

Navigate to ChimeKit's docs:

https://swiftpackageindex.com/ChimeHQ/ChimeKit/main/documentation/chimeextensioninterface

Select the tutorial from the side bar, or from the main page content. Takes you here:

https://swiftpackageindex.com/ChimeHQ/ChimeKit/main/tutorials/create-an-extension

That page **loads**. But, it cannot be reloaded and cannot be linked to externally. Both produce a 404.

Safari Version 16.1

From what I can tell, this only affects tutorials. URLs to articles and API docs all work as expected.

**Comment by finestructure** [comment]
Oh, that's weird! Thanks for the report, Matt. I'll take a look asap.

**Comment by finestructure** [comment]
This doesn't seem to have anything to do with my multi-target hack. https://swiftpackageindex.com/GetStream/effects-library/main/documentation/effectslibrary is affected the same way and it is documenting only one target.
