### ISSUE TITLE
The "Has Documentation" icon possibly looks wrong

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#2047]
I noticed the icon displayed for packages with documentation looks a little funny.

<img width="128" alt="Screenshot 2022-09-27 at 9 35 36 AM" src="https://user-images.githubusercontent.com/85322/192541837-367fc1c1-d46b-437f-bcd4-eded22ce3c97.png">

Note the little line to the right of the icon.

Safari 16.1

**Comment by daveverwer** [comment]
Not a Safari bug. I see the same when testing it in Chrome too

<img width="210" alt="Screenshot 2022-09-27 at 14 40 11@2x" src="https://user-images.githubusercontent.com/5180/192542391-9a0341c6-d4ab-4c5e-a96b-299159132e96.png">
