### ISSUE TITLE
Move logic to redirect to default documentation into a route handler

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2053]
- [ ] Make a generic link that encodes the logic we use for the "Documentation" link from package pages. So, visiting https://swiftpackageindex.com/vapor/postgres-nio/documentation would redirect to https://swiftpackageindex.com/vapor/postgres-nio/1.11.1/documentation/postgresnio or https://swiftpackageindex.com/vapor/postgres-nio/main/documentation/postgresnio if there was no stable release.
- [ ] Remove that logic from the package page so that right-clicking the "Documentation" page lets people copy a stable link that will always work.

Thanks to @fabianfett for the suggestion!

**Comment by fabianfett** [comment]
That's awesome! Thanks so much!

**Comment by finestructure** [comment]
We should also pass along any catchall after the `.../documentation` to support deeper links. I.e.

```
https://swiftpackageindex.com/vapor/postgres-nio/documentation/foo
```

would ideally resolve to

```
https://swiftpackageindex.com/vapor/postgres-nio/1.11.1/documentation/postgresnio/foo
```

as per the rules above.
