### ISSUE TITLE
Double doc query inefficiency

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2056]
There's one inefficiency in our doc url handling. When we hit the default URL, we do the following:

* call `defaultDocumentation(req:)` via /simonbs/Runestone/documentation
* run `PackageResult.query(...)`
* redirect to /simonbs/Runestone/0.2.5/documentation/runestone
* call `documentation(req:fragment:)` via that /simonbs/Runestone/0.2.5/documentation/runestone redirect
* run `Joined3.query(...)`
* proxy to http://spi-prod-docs.s3-website.us-east-2.amazonaws.com/simonbs/runestone/0.2.5/documentation/runestone

I.e. we run a query that gets us the doc parameters and then we redirect to a url - which runs essentially the same query again to then proxy to AWS.

I think that's fixable. (I've got a change locally but it's currently failing some tests.)

This isn't a new problem actually - we're already doing the same for the redirect when we get an underspecified doc request like

http://localhost:8080/simonbs/Runestone/0.2.5/documentation

This goes to `documentation(req: Request)`, which runs a `Joined3.query(...)` to find the archive and then redirects to 

http://localhost:8080/simonbs/Runestone/0.2.5/documentation/runestone

and this will run another `Joined3.query(...)`.

We should have all the information to avoid that redirect and second query.

_Originally posted by @finestructure in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/2054#discussion_r987594616_

**Comment by daveverwer** [comment]
I'm not feeling great today, so haven't looked at this in-depth but just to say that the redirect was intentional. I think it's important to have a link on the package page that does a redirect so that people can right-click and copy it, but we don't want that URL to be their final destination.

So, the URL on the page should be `/owner/package/documentation` and it should redirect to `owner/package/ref/documentation/archive`

It needs to be two requests, otherwise we'd be serving the documentation from `/owner/package/documentation` which is an ambiguous URL

**Comment by finestructure** [comment]
Ok, I think the blocker is going to be that the URL isn't actually canonically resolved by `/{owner}/{package}/{ref}/documentation/{archive}`. Since we're injecting the header with _all_ `{ref}`s that have docs, we'd need to either somehow pass along the `refs` found in the first query in the redirect (meh) or query again.

**Comment by finestructure** [comment]
As mentioned above, this isn't actually fixable unless we pass information from the first request through the redirect.

There are two ways of doing this:

- get request parameters
- headers

Request parameters are ugly but headers might work. It's not great but it's there as an option in case we're seeing performance issues.

Closing this for now.
