### ISSUE TITLE
Search ranking issues

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2072]
Searching for "composable" returns the following results:

1. https://swiftpackageindex.com/FluidGroup/Brightroom
1. https://swiftpackageindex.com/tgrapperon/swift-composable-environment
1. https://swiftpackageindex.com/tgrapperon/composable-effect-identifier
1. https://swiftpackageindex.com/darrarski/swift-composable-presentation
1. https://swiftpackageindex.com/pointfreeco/composable-core-location
1. https://swiftpackageindex.com/thread/Composed
1. https://swiftpackageindex.com/pointfreeco/composable-core-motion
1. https://swiftpackageindex.com/binaryscraping/swift-composable-keychain
1. https://swiftpackageindex.com/alexito4/RelayStore
1. https://swiftpackageindex.com/pointfreeco/swift-composable-architecture

Searching for "composable architecture" returns:

1. https://swiftpackageindex.com/tgrapperon/swift-composable-environment
1. https://swiftpackageindex.com/tgrapperon/composable-effect-identifier
1. https://swiftpackageindex.com/alexito4/RelayStore
1. https://swiftpackageindex.com/darrarski/swift-composable-presentation
1. https://swiftpackageindex.com/pointfreeco/composable-core-location
1. https://swiftpackageindex.com/pointfreeco/composable-core-motion
1. https://swiftpackageindex.com/binaryscraping/swift-composable-keychain
1. https://swiftpackageindex.com/pointfreeco/swift-composable-architecture

TCA's position of 10 and 8 seems way too low.

It has more stars than any of the other results, it has the "has docs" flag, it has an App Store compatible license. I'm puzzled why we're not ranking it first.

Need to drill into what the actual score is.

**Comment by finestructure** [comment]
Ok, score wise it should be ranking it first, tied with "Brightroom". Something's off with our ordering. It's neither sorted by `score` nor `tsrankvalue`.

![CleanShot 2022-10-13 at 11 08 59@2x](https://user-images.githubusercontent.com/65520/195554774-63b1ba18-deeb-4262-b95f-8360a4f8175d.png)

**Comment by finestructure** [comment]
The problem is that we use `LOWER("package_name") = 'composable'` to put exact package name matches first. However, "Brightroom"'s package name is `NULL` and SQL being weird that leads to `LOWER("package_name") = 'composable'` being `NULL` and sorting first.

The rest _is_ actually sorted correctly. We sort by

```sql
ORDER BY 
  LOWER("package_name") = 'composable' DESC, 
  "tsrankvalue" DESC, 
  "score" DESC, 
  "package_name" ASC 
```

I think we should change this to

```sql
ORDER BY 
  LOWER("package_name") = 'composable' DESC, 
  "score" DESC, 
  "tsrankvalue" DESC, 
  "stars" DESC,
  "package_name" ASC 
```

After fixing the `NULL` package name issue, this would sort TCA, Brightroom and then the rest as listed.

**Comment by finestructure** [comment]
I'm inserting `stars` as a new tie breaker, because Brightroom and TCA tie on both `score` and `tsrankvalue` and I think overall stars are a good tie breaker here.

**Comment by daveverwer** [comment]
> I'm inserting `stars` as a new tie breaker, because Brightroom and TCA tie on both `score` and `tsrankvalue` and I think overall stars are a good tie breaker here.

Yea this seems like a good fallback 👍

**Comment by daveverwer** [comment]
Let's chat about this when I'm back at a desk, but doesn't moving the `tsrankvalue` down take us back to the situation we were in before @heckj did all that work to improve searches for things like "ftp" and "ping"?

**Comment by finestructure** [comment]
That's a good point. The problem is that if we sort by `tsrankvalue` first, we're effectively ignoring everything that's part of `score` - stars, docs, license - unless it's a tie. Which is rare, given that `tsrankvalue` is a double.

We'd have to merge `tsrankvalue` into `score` to preserve both aspects.

**Comment by finestructure** [comment]
Here's the same search with `tsrankvalue` before `score`:

<img width="1277" alt="CleanShot 2022-10-13 at 13 28 57@2x" src="https://user-images.githubusercontent.com/65520/195584775-bb130642-42b7-47d9-ad39-7b380b0e670e.png">

**Comment by daveverwer** [comment]
Yea, I knew that we de-emphasised search in search when we merged the `tsrankvalue ` changes, but it seemed like a reasonable trade off that better matching on words was worth it. 

It's hard to know what to do, I agree TCA being at rank 9 for this term isn't good, but those examples with "ftp" and "ping" were also really valid examples.

I've not put I wonder if we could do something with banding `tsrankvalue ` results into some round numbers and then add them to score would work better? It may be that the banding might not even be needed, just some normalisation?

**Comment by finestructure** [comment]
I think I've got a solution for this, will push an update to try it later.

**Comment by finestructure** [comment]
Ok, so I think the way this can work is as follows (which is essentially what you're suggesting, too).

What the `tsrank` in the `ping` and `ftp` searches does is lift their word matches above partial matches. Here's the rank value for the SQL

```sql
SELECT "package_name", ts_rank("tsvector", "tsquery") AS "tsrankvalue", ts_rank("tsvector", "tsquery") > 0.05 AS "rank" 
FROM "search", plainto_tsquery('ping') AS "tsquery" 
WHERE 
  CONCAT_WS(' ', "package_name", COALESCE("summary", ''), "repo_name", "repo_owner", ARRAY_TO_STRING("keywords", ' ')) ~* 'ping'
  AND "repo_owner" IS NOT NULL 
  AND "repo_name" IS NOT NULL 
ORDER BY LOWER(COALESCE("package_name", '')) = 'ping' DESC, "rank" DESC, "score" DESC, "package_name" ASC 
```

<img width="385" alt="CleanShot 2022-10-13 at 15 07 56@2x" src="https://user-images.githubusercontent.com/65520/195604817-1a2c294a-268e-467e-8856-58a37d124c1c.png">

It's the same for `ftp`: effectively, all results that _don't_ have `ping` or `ftp` as a _word_ have `tsrankvalue` zero. So by setting a threshold like I did in the sample SQL of, say, `ts_rank("tsvector", "tsquery") > 0.05`, we can still sort by that first and then by score to bring word matches to the front while preserving `score` order otherwise.

**Comment by finestructure** [comment]
```sql
SELECT "package_name", ts_rank("tsvector", "tsquery") AS "tsrankvalue", ts_rank("tsvector", "tsquery") > 0.05 AS "rank" 
FROM "search", plainto_tsquery('composable') AS "tsquery" 
WHERE 
  CONCAT_WS(' ', "package_name", COALESCE("summary", ''), "repo_name", "repo_owner", ARRAY_TO_STRING("keywords", ' ')) ~* 'composable'
  AND "repo_owner" IS NOT NULL 
  AND "repo_name" IS NOT NULL 
ORDER BY LOWER(COALESCE("package_name", '')) = 'composable' DESC, "rank" DESC, "score" DESC, "package_name" ASC 
```

<img width="406" alt="CleanShot 2022-10-13 at 15 10 33@2x" src="https://user-images.githubusercontent.com/65520/195605429-9b124eb9-587a-44b9-8812-981e5d909798.png">

**Comment by finestructure** [comment]
This is still ok (or at least no worse) if we search for a partial like `comp` (adding `score` and `stars` to the select for clarity):

```sql
SELECT "package_name", ts_rank("tsvector", "tsquery") AS "tsrankvalue", ts_rank("tsvector", "tsquery") > 0.05 AS "rank", "score", "stars"
FROM "search", plainto_tsquery('comp') AS "tsquery" 
WHERE 
  CONCAT_WS(' ', "package_name", COALESCE("summary", ''), "repo_name", "repo_owner", ARRAY_TO_STRING("keywords", ' ')) ~* 'comp'
  AND "repo_owner" IS NOT NULL 
  AND "repo_name" IS NOT NULL 
ORDER BY LOWER(COALESCE("package_name", '')) = 'comp' DESC, "rank" DESC, "score" DESC, "package_name" ASC 
LIMIT 21 OFFSET 0
```

These are all solid, popular matches and the `stars` in the `ORDER BY` looks like a good improvement:

<img width="551" alt="CleanShot 2022-10-13 at 15 16 24@2x" src="https://user-images.githubusercontent.com/65520/195606882-aeba00ec-1c5f-4663-9478-27f33371cc3d.png">
