### ISSUE TITLE
Broken package MockingJ

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#211]
http://173.255.229.82:8080/packages/8010F85D-D099-43AA-876E-BE05FB69BD45

```
{"error":true,"reason":"Something went wrong."}
```

**Comment by finestructure** [comment]
And http://173.255.229.82:8080/packages/E8DB6B7D-5127-4509-8C7B-CD09B87A0143 and probably more

**Comment by finestructure** [comment]
Ok, can repro with my local prod copy

**Comment by finestructure** [comment]
Oh, right, these are packages that don't have the new version format. They're still saved as

```
{"tag": {"build": "", "major": 0, "minor": 2, "patch": 0, "preRelease": ""}}
```

instead of

```
{"tag": {"semVer": {"build": "", "major": 3, "minor": 1, "patch": 1, "preRelease": ""}, "tagName": "3.1.1"}}
```

Not great to fail like that but also not sure if we want to try and recover. We _could_ create `tagName` from `semVer` but that will break in subtle ways further down the line if the actual name was `v0.2.0`.

This will all shake itself out once we reset the schema and also once all records are reprocessed. I think the issue here was that the package is in the state `metadata_request_failed` and didn't get an update.

I found this package via a search and I'm wondering if we should filter on `status = ok` in search (would need an update for the search view and query for that).

**Comment by finestructure** [comment]
Actually, I don't think we want that filter. If for some reason, like for instance due to a rate limit generating errors, we log a lot of packages in a temp error state we'd pull them all from search.

**Comment by daveverwer** [comment]
> Not great to fail like that but also not sure if we want to try and recover. We _could_ create `tagName` from `semVer` but that will break in subtle ways further down the line if the actual name was `v0.2.0`.

Yea I think this is fine for now since the database is going to get a full reset. 

> This will all shake itself out once we reset the schema and also once all records are reprocessed. I think the issue here was that the package is in the state `metadata_request_failed` and didn't get an update.

I think this is the bug! Is there a reason why packages in the `metadata_request_failed` state are not getting updates?

**Comment by daveverwer** [comment]
But it's certainly been longer than the ingest time interval since that change went live? I think the interval is an hour and that change was days ago, wasn't it?

**Comment by finestructure** [comment]
Yes, but we've been hitting the rate limit towards the tail end of every hour. I'll need to adjust more processing settings.

I'll verify these links again later tonight or tomorrow and also look further into the processing settings. I'll hold of squashing the schema for now.

**Comment by finestructure** [comment]
Ok, these are still broken and we're not hitting rate limits anymore. Checking now!

**Comment by finestructure** [comment]
Ok, MockingJ is a 404: https://github.com/JuanjoArreola/MockingJ

**Comment by finestructure** [comment]
The second one, https://github.com/tadija/AECli, exposes an interesting bug:

- when trying to update the package status at the end of ingestion, the update statement fails, because the join with `versions` fails due to the incompatible field
- this leads to the package not being moved out of `metadata_request_failed` state to `ok`
- which keeps it eternally failing due to bad data

A couple of things to fix:

- make `updatePackage` fail safe against bad data
- I was expecting the error from the failed write to be logged but for some reason it doesn't bubble up correctly

**Comment by finestructure** [comment]
Just to follow up: after schema squashing both packages are correctly excluded from search
