### ISSUE TITLE
Airbnb swift style reports compatibility with linux but it is actually not compatible.

### ISSUE THREAD

**Issue by doozMen** [SwiftPackageIndex/SwiftPackageIndex-Server#2116]
**Please describe the bug**

As you can see in the readme it displays linux https://github.com/airbnb/swift#readme but it is not running on linux. As detailed here https://github.com/airbnb/swift/discussions/197

**Explain the steps needed to reproduce the bug**

1. run `swift package format` on ci
2. then it reports binary not available for linux
3. that the bug

**What was the expected behaviour?**

I would expect swift package index to only show macos and not linux if a binary is not available for the linux platform

**Screenshots**
<img width="690" alt="Screenshot 2022-11-04 at 10 17 18" src="https://user-images.githubusercontent.com/686038/199936944-43b7a35b-6e2b-4e50-a50a-f0224720de57.png">

**Additional context**

https://github.com/airbnb/swift/discussions/197

**Comment by finestructure** [comment]
Thanks for the report, @doozMen !

This is a tricky one. Our build system uses something like `swift build` on a package to determine its compatibility and for the AirbnbSwift plugin this actually works on Linux.

I'm not sure how to best deal with platform and Swift version compatibility for plugins. Clearly, a plain "build" process like we have is problematic.

Until we come up with something, one way to fix this false positive would be to intentionally break the Linux build of the plugin by adding:

```swift
#if os(Linux)
#error("Linux is currently not supported")
#endif
```

somewhere in the source or even the `Package.swift` manifest.

I'll raise the question over in the original issue if that's a feasible approach until we have a better solution. I can't really think of a better way to deal with this for now.

**Comment by finestructure** [comment]
One approach I considered is to create a dummy package and reference a package (plugin) as a dependency from there. This is as simple as placing a `Package.swift` with the following content in an empty directory:

```swift
// swift-tools-version:5.7

import PackageDescription

let package = Package(
    name: "dependency-check",
    dependencies: [
        .package(url: "https://github.com/airbnb/swift.git", from: "1.0.0")
    ]
)
```

That succeeds as well though:

```
⋊> ~/dep-test uname -a                                                                                                 12:14:12
Linux lb1 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
⋊> ~/dep-test swift build                                                                                              12:14:19
Fetching https://github.com/airbnb/swift.git from cache
Fetched https://github.com/airbnb/swift.git (0.22s)
Computing version for https://github.com/airbnb/swift.git
Computed https://github.com/airbnb/swift.git at 1.0.2 (0.01s)
Fetching https://github.com/apple/swift-argument-parser from cache
Fetched https://github.com/apple/swift-argument-parser (0.16s)
Computing version for https://github.com/apple/swift-argument-parser
Computed https://github.com/apple/swift-argument-parser at 1.1.4 (0.02s)
Creating working copy for https://github.com/airbnb/swift.git
Working copy of https://github.com/airbnb/swift.git resolved at 1.0.2
Creating working copy for https://github.com/apple/swift-argument-parser
Working copy of https://github.com/apple/swift-argument-parser resolved at 1.1.4
Downloading binary artifact https://github.com/calda/SwiftFormat/releases/download/0.51-beta-2/SwiftFormat.artifactbundle.zip
Downloading binary artifact https://github.com/realm/SwiftLint/releases/download/0.48.0/SwiftLintBinary-macos.artifactbundle.zip
Downloaded https://github.com/calda/SwiftFormat/releases/download/0.51-beta-2/SwiftFormat.artifactbundle.zip (0.53s)
Downloaded https://github.com/realm/SwiftLint/releases/download/0.48.0/SwiftLintBinary-macos.artifactbundle.zip (2.17s)
Compiling plugin FormatSwift...
Compiling plugin GenerateManualPlugin...
/home/docker-user/dep-test/.build/checkouts/swift/Plugins/FormatSwift/Plugin.swift:53:13: warning: 'launchPath' is deprecated: renamed to 'executableURL'
    process.launchPath = launchPath
            ^
/home/docker-user/dep-test/.build/checkouts/swift/Plugins/FormatSwift/Plugin.swift:53:13: note: use 'executableURL' instead
    process.launchPath = launchPath
            ^~~~~~~~~~
            executableURL
Building for debugging...
Build complete! (4.12s)
⋊> ~/dep-test echo $status                                                                                             12:14:33
0
```

If we wanted to generalise this we'd need to

a) create a package with an honest package dependency for library targets
b) somehow execute plugin commands for plugin targets

For a) that's probably somewhat feasible and could replace our current builds. (This is not directly related to this issue but I believe _if_ we change how we determined build compatibility we'll want to do it in similar ways for both plugins _and_ libraries.)

The main problem here is which library target(s) to pick. All of them? Heuristics like we have for schemes? That's not a great prospect given the problems we often see with `xcodebuild`.

For b) I don't know how we'd discover the commands to run nor how to determine if the problem was due to the platform or some other issue with its execution in a dummy package. Perhaps just running it with `--help` could be an indicator.

For example, this seems to be a way to trigger an error on Linux (using the above-mentioned minimal package manifest):

```
⋊> ~/dep-test swift package plugin --allow-writing-to-package-directory format --help                                  12:23:52
Building for debugging...
Build complete! (0.21s)
error: Plugin does not have access to a tool named ‘swiftformat’
⋊> ~/dep-test echo $status                                                                                             12:23:54
1
```

Running the same on macOS yields:

```
❯ swift package plugin --allow-writing-to-package-directory format --help
Fetching https://github.com/airbnb/swift.git
Fetched https://github.com/airbnb/swift.git (68.47s)
Computing version for https://github.com/airbnb/swift.git
Computed https://github.com/airbnb/swift.git at 1.0.2 (0.87s)
Fetching https://github.com/apple/swift-argument-parser from cache
Fetched https://github.com/apple/swift-argument-parser (1.83s)
Computing version for https://github.com/apple/swift-argument-parser
Computed https://github.com/apple/swift-argument-parser at 1.1.4 (0.62s)
Creating working copy for https://github.com/airbnb/swift.git
Working copy of https://github.com/airbnb/swift.git resolved at 1.0.2
Creating working copy for https://github.com/apple/swift-argument-parser
Working copy of https://github.com/apple/swift-argument-parser resolved at 1.1.4
Downloading binary artifact https://github.com/calda/SwiftFormat/releases/download/0.51-beta-2/SwiftFormat.artifactbundle.zip
Downloading binary artifact https://github.com/realm/SwiftLint/releases/download/0.48.0/SwiftLintBinary-macos.artifactbundle.zip
Downloaded https://github.com/calda/SwiftFormat/releases/download/0.51-beta-2/SwiftFormat.artifactbundle.zip (5.76s)
Downloaded https://github.com/realm/SwiftLint/releases/download/0.48.0/SwiftLintBinary-macos.artifactbundle.zip (49.83s)
Building for debugging...
[48/48] Linking AirbnbSwiftFormatTool
Build complete! (3.87s)
USAGE: airbnb-swift-format-tool [<directories> ...] --swift-format-path <swift-format-path> [--swift-format-cache-path <swift-format-cache-path>] --swift-lint-path <swift-lint-path> [--swift-lint-cache-path <swift-lint-cache-path>] [--lint] [--log] [--swift-format-config <swift-format-config>] [--swift-lint-config <swift-lint-config>] [--swift-version <swift-version>]

ARGUMENTS:
  <directories>           The directories to format

OPTIONS:
  --swift-format-path <swift-format-path>
                          The absolute path to a SwiftFormat binary
  --swift-format-cache-path <swift-format-cache-path>
                          The absolute path to use for SwiftFormat's cache
  --swift-lint-path <swift-lint-path>
                          The absolute path to a SwiftLint binary
  --swift-lint-cache-path <swift-lint-cache-path>
                          The absolute path to use for SwiftLint's cache
  --lint                  When true, source files are not reformatted
  --log                   When true, logs the commands that are executed
  --swift-format-config <swift-format-config>
                          The absolute path to the SwiftFormat config file
                          (default:
                          /Users/sas/Downloads/dep-test/.build/arm64-apple-macosx/debug/AirbnbSwift_AirbnbSwiftFormatTool.bundle/airbnb.swiftformat)
  --swift-lint-config <swift-lint-config>
                          The absolute path to the SwiftLint config file
                          (default:
                          /Users/sas/Downloads/dep-test/.build/arm64-apple-macosx/debug/AirbnbSwift_AirbnbSwiftFormatTool.bundle/swiftlint.yml)
  --swift-version <swift-version>
                          The project's minimum Swift version
  -h, --help              Show help information.

~/Downloads/dep-test took 2m15s 
❯ echo $status
0
```

So maybe we do this for package that vend only a plugin as a product (or several and per plugin but not a mix of plugins and libraries) and keep the regular build process as is?

**Comment by finestructure** [comment]
As to how we'd get the verb to run the plugin, I can see two approaches:

a) we could run `swift package describe --type json` in the plugin package directory and then get it from the target's `plugin_capabilitiy.intent.verb` attribute.

<img width="608" alt="CleanShot 2022-11-04 at 13 35 23@2x" src="https://user-images.githubusercontent.com/65520/199974253-0ee7fa3c-3ace-4498-b026-bbeb51ed9d68.png">

b) run `swift package plugin --list` and parse the output:

```
❯ swift package plugin --list
‘format’ (plugin ‘FormatSwift’ in package ‘AirbnbSwift’)
‘generate-manual’ (plugin ‘GenerateManualPlugin’ in package ‘swift-argument-parser’)
```

The slight problem here is (as we can see in the example) that this list is going to be "polluted" by plugins from other dependencies. And of course we'd be relying on output format stability.

Option a) is cleaner and more stable. We probably wouldn't need to worry about trying to find the correct target - we could just take any `verb`s we find in `plugin_capability.intent`s. All of them should be declared plugins of the package we're inspecting.

One thing to check is if the `describe` format is stable for all the Swift tools versions that support plugins.

**Comment by calda** [comment]
One other idea is that you could check the platforms supported by the binary dependencies. For example our `Package.swift` has:

```swift
    .binaryTarget(
      name: "SwiftFormat",
      url: "https://github.com/calda/SwiftFormat/releases/download/0.51-beta-3/SwiftFormat.artifactbundle.zip",
      checksum: "4b0516d911258b55c3960949f4a516a246f35a1dc7647a6440c66e1f1fe1a32e"),
```

The `artifactbundle` file has an `info.json` manifest:

```json
{
  "schemaVersion": "1.0",
  "artifacts": {
    "swiftformat": {
      "version": "0.51-beta-3",
      "source": "https://github.com/calda/SwiftFormat/releases/tag/0.51-beta-3",
      "type": "executable",
      "variants": [
        {
          "path": "swiftformat",
          "supportedTriples": ["x86_64-apple-macosx", "arm64-apple-macosx"]
        }
      ]
    }
  }
}
```

Since the `supportedTriples` only includes macOS targets, this dependency can't be used on Linux.

**Comment by doozMen** [comment]
I think we discovered a caveat in the system an maybe should consider filing a bug on swift package manager. It should not build for packages on platforms it does not support. 

Although I find the found workarounds profoundly clever they seam too complex. The spm build system should manage that. 

Where do you post bugs on spm build? Should I?

**Comment by finestructure** [comment]
> It should not build for packages on platforms it does not support.

I'm not sure what you mean by this - to my knowledge there's no way to tell SPM that a platform isn't supported. We actually have to try and build on all of them to find out.

**Comment by doozMen** [comment]
@finestructure What I mean is that I do not think your tooling should change because a build on a platform does work but the binary used for that platform is not available on that platform. It seams logical to me that the build should fail. But it does not. So I consider that  bug in spm.

I would however not wait for that and if possible read the target triples from the info.json files so that the build of plugins that use binaries would fail. But that would also require to download the artifact bundle and go peek in there ...

**Comment by finestructure** [comment]
> I would however not wait for that and if possible read the target triples from the info.json files so that the build of plugins that use binaries would fail. But that would also require to download the artifact bundle and go peek in there ...

That just feels like a too fiddly and implementation detail a thing for us to do, to be honest (plus some other reasons I can go into but the upshot is that it'd be quite the departure to how we're currently testing compatibility, requiring quite a bit of effort). We have to try and stick to higher level ways of determining compatibility so our system isn't too brittle in the face of SPM changes. (We've seen this a couple of times already.)

I believe if invalidating the build via an `#if` isn't viable, the next best thing would be for us to extend our `.spi.yml` file with a way for package authors to declare incompatibility (and _only_ incompatibility) for a certain platform.

However, I think even regular package users would probably benefit from the clear compile time messaging via `#error` - if SPM doesn't provide that messaging.

As to reporting it, I believe the best place would be https://github.com/apple/swift-package-manager/issues. I'll definitely be seen and triaged by the SPM folks there!

**Comment by finestructure** [comment]
Looks like this is fixed now, please re-open if you're still seeing issues!
