### ISSUE TITLE
airbnb/swift repo no longer appears on Swift Package Index

### ISSUE THREAD

**Issue by calda** [SwiftPackageIndex/SwiftPackageIndex-Server#2117]
After https://github.com/airbnb/swift/pull/206, which implemented a suggestion @finestructure made in https://github.com/airbnb/swift/discussions/197#discussioncomment-4055303, the airbnb/swift repo no longer displays correctly on Swift Package Index: https://swiftpackageindex.com/airbnb/swift

<img width="898" alt="image" src="https://user-images.githubusercontent.com/1811727/200094148-75d13f57-9f1a-4d28-ae3c-a828c07e1d71.png">

This repo is still listed in [`packages.json`](https://github.com/SwiftPackageIndex/PackageList/blob/main/packages.json#L136), and displayed correctly before https://github.com/airbnb/swift/pull/206.

The package itself still builds and runs correctly on macOS. Is this something that can be fixed on the Swift Package Index side, or should we revert the change to our `Package.swift`?

**Comment by finestructure** [comment]
Thanks for the report, @calda !

I see the package is showing as expected with the `#if os(Linux)` still present on `master` and it all looks ok now:

<img width="536" alt="CleanShot 2022-11-05 at 08 57 36@2x" src="https://user-images.githubusercontent.com/65520/200109965-3c630359-f124-446a-8633-284fda8f2173.png">

I can't quite explain how you've gotten the "Package not found" error unless you perhaps mistyped the URL. Is that possible?

**Comment by calda** [comment]
Weird! Appears to be fixed now
