### ISSUE TITLE
Collections URL broken

### ISSUE THREAD

**Issue by aure** [SwiftPackageIndex/SwiftPackageIndex-Server#2118]
**Please describe the bug**

This is giving an error message: https://swiftpackageindex.com/AudioKit/collection.json

**Explain the steps needed to reproduce the bug**

Go to https://swiftpackageindex.com/AudioKit/collection.json
See bug.

**What was the expected behaviour?**

JSON for AudioKit Packages

**Comment by finestructure** [comment]
Thanks a lot for the report, @aure ! This seems to affect collections generally 😣

**Comment by finestructure** [comment]
According to a local bisect it looks like #2060 broke this. However, it's unclear to me how a) that PR would have anything to do with collections and b) why the collection tests wouldn't catch this.

**Comment by finestructure** [comment]
Specifically, the error is an unexpected force-unwrap in `PacakageCollection+VersionResult.swift`:

<img width="724" alt="CleanShot 2022-11-06 at 10 16 16@2x" src="https://user-images.githubusercontent.com/65520/200163020-fe20d6d5-e382-4022-bb5e-b627e9ea9314.png">

which in this case I triggered via

```
curl -s "http://localhost:8080/AudioKit/collection.json"
```

**Comment by finestructure** [comment]
Deleted that previous analysis. After re-testing a third time it's _not_ reproducible on #2060. I reset the db and re-applied migrations. Might have had something to do with the fact that I jumped over the migration when bisecting without applying the db changes for the revision correctly.

**Comment by finestructure** [comment]
I suspect this is config level breakage. I'm getting this error locally which I thought was as issue with my local setup:

```
❯ curl -s "http://localhost:8080/AudioKit/collection.json"
{"error":true,"reason":"invalidCertChain"}⏎
```

But I suspect something's changed with respect to the cert chain/the certs. That would perhaps explain why no tests fired, because I'm not sure to what extent we have coverage with the full live setup in CI.

If that's the issue, we need to add a collection url to our smoke tests.

**Comment by finestructure** [comment]
FWIW, I see no such error in the prod logs, which might mean it's not the actual error or a logging gap.

**Comment by aure** [comment]
Seems to be more of a puzzle than usual, didn't think I'd stump y'all. :)

**Comment by finestructure** [comment]
Ah, _now_ it's failing - we hadn't triggered CI runs in the last couple of days:

![image](https://user-images.githubusercontent.com/65520/200254766-2aa4e3d4-f299-4ed8-afc8-cbe20eb36e40.jpeg)

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3408252222/jobs/5668668270

I suspect this is certificate related.

@daveverwer I recall we renewed our dev account recently so this might mean our certificate needs to be renewed.

**Comment by daveverwer** [comment]
It's almost certainly that. I'll renew it. Thanks so much for the bug report @aure! I'll also put a reminder in to do it in advance next year.

**Comment by daveverwer** [comment]
Tested in production and all is now fixed 👍
