### ISSUE TITLE
Preview DocC feature on staging

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2129]
We'll want to help preview/test upcoming DocC features. The plan is to use our staging environment for this and build documentation for a selection of packages.

See this post on the forums for details of the first feature that would benefit from this: https://forums.swift.org/t/support-for-docc-experimental-features/61276

**Comment by finestructure** [comment]
Brief update on the progress. The builder side changes are [done](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/158). The remaining todos are:

- [ ] source list of packages to allow-list for building on `dev`
- [ ] implement allow-list trigger downscaling override in the server
- [ ] deploy builder changes
- [ ] deploy server changes
- [ ] end-to-end test process with SemanticVersion package

**Comment by finestructure** [comment]
Re: toolchain install, that's [Swift Development Snapshot 2022-11-03 (a)](https://download.swift.org/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2022-11-03-a/swift-DEVELOPMENT-SNAPSHOT-2022-11-03-a-osx.pkg).

After installing, use the following command to validate the installation:

```
xcrun --toolchain org.swift.57202211031a swift --version
```

This should print

```
Apple Swift version 5.8-dev (LLVM 1299cdab04e4506, Swift 56665d5ce9f6420)
Target: arm64-apple-macosx13.0
```

**Comment by finestructure** [comment]
Here's a script to list installed toolchains:

```swift
#!/usr/bin/env swift

import Foundation

let toolchainsDir = URL(fileURLWithPath: "/Library/Developer/Toolchains")

struct ToolchainInfoPlist: Codable {
    var bundleIdentifier: String
    var createdDate: Date
    var displayName: String

    enum CodingKeys: String, CodingKey {
        case bundleIdentifier = "CFBundleIdentifier"
        case createdDate = "CreatedDate"
        case displayName = "DisplayName"
    }
}

func readPlist(url: URL) throws -> ToolchainInfoPlist {
    let data = try Data(contentsOf: url)
    return try PropertyListDecoder().decode(ToolchainInfoPlist.self, from: data)
}

func getToolchainInfo(toolchainsDir: URL) throws -> [ToolchainInfoPlist] {
    try FileManager.default.contentsOfDirectory(atPath: toolchainsDir.path)
        .map { toolchainsDir.appendingPathComponent($0) }
        .filter(\.hasDirectoryPath)
        .map { $0.appendingPathComponent("Info.plist")}
        .map(readPlist(url:))
}

print("Installed toolchains:")
try getToolchainInfo(toolchainsDir: toolchainsDir)
    .map(\.bundleIdentifier)
    .forEach {
        print("xcrun --toolchain \($0) swift --version")
}
```

**Comment by finestructure** [comment]
Initial allow list:

- SemanticVersion
- SPIManifest
- ArgumentParser

```json
[
  "38D534BF-4BE1-498E-B973-E7E885FC3A4E",
  "B16EF7C1-A039-4D41-AFBE-FCAB873713CE",
  "112BDD86-7BBB-490F-9484-BD4020ED5A50",
]
```

**Comment by finestructure** [comment]
Crosspost from https://forums.swift.org/t/support-for-docc-experimental-features/61276/6

------------------

We're almost done implementing this but have hit a weird last minute error. When generating the docs on our build machine, we're getting a `"Bad CPU type in executable"` error with the Nov 3 nightly toolchain. This works fine with the regular 5.7 toolchain.

Our build machine is an M1 Mac mini which doesn't have Rosetta installed. That might explain why in my testing this same command works fine on my M1 MBP which has Rosetta.

Is there anything new in the 5.8 doc generation workflow that might be calling our to an x86 only binary? We can install Rosetta on the build machines if need be but if we can avoid it that'd be even better.

Here's the whole command sequence that replicates our process and works on my machine but fails on our builder with the above mentioned error:

```
git clone --depth=1 --branch 0.3.5 "https://github.com/SwiftPackageIndex/SemanticVersion.git"

cd SemanticVersion

mkdir -p .docs/swiftpackageindex/semanticversion

cat <<EOF >> Package.swift

package.dependencies.append(
    .package(url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0")
)
EOF

xcrun --toolchain "org.swift.57202211031a" env DOCC_JSON_PRETTYPRINT="YES" swift package --allow-writing-to-directory ".docs/swiftpackageindex/semanticversion/0.3.5" generate-documentation --disable-indexing --transform-for-static-hosting --output-path ".docs/swiftpackageindex/semanticversion/0.3.5" --hosting-base-path "swiftpackageindex/semanticversion/0.3.5" --target "SemanticVersion"
```

**Comment by finestructure** [comment]
Crosspost from https://forums.swift.org/t/support-for-docc-experimental-features/61276/7

-------

Oh, it's actually the `docc` binary in that toolchain itself that's x86 only:

```
❯ file /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-11-03-a.xctoolchain/usr/bin/docc
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-11-03-a.xctoolchain/usr/bin/docc: Mach-O 64-bit executable x86_64
```

vs

```
❯ file /Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc
/Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by finestructure** [comment]
The problem with the nightly toolchain was fixed but the fix broke the toolchain build and had to be rolled back: https://github.com/apple/swift-docc/issues/433

However, in the process of addressing this, Apple have created a toolchain build that I've validated works and which we can install on mb5 for now:

https://ci.swift.org/job/swift-PR-toolchain-macos/418/artifact/branch-main/swift-PR-62306-418-osx.tar.gz

This would need to go into `/Library/Developer/Toolchains` and it should be listed when running the lookup command from above:

```
❯ list-toolchains.swift
Installed toolchains:
xcrun --toolchain org.swift.57202211031a swift --version
xcrun --toolchain org.swift.pr.62306.418 swift --version
```

- [ ] update builder with new toolchain version

**Comment by daveverwer** [comment]
I removed the 20221103 version and installed this the 62306 version. Here is the output of `list-toolchains.swift` from mb5:

```shell
mb5:~ $ ./list-toolchains.swift 
Installed toolchains:
xcrun --toolchain org.swift.pr.62306.418 swift --version
```

Running `xcrun --toolchain org.swift.pr.62306.418 swift --version` opened up the "Untrusted developer" window on macOS, and the process was killed. I manually ran the `swift` command from within the installed toolchain and confirmed it was safe, and now `xcrun --toolchain org.swift.pr.62306.418 swift --version` reports:

```shell
mb5:~ $ xcrun --toolchain org.swift.pr.62306.418 swift --version
Apple Swift version 5.8-dev (LLVM f21cfd5346ab53b, Swift f6429bee5531fbd)
Target: arm64-apple-macosx13.0
```

I only did that for the `swift` binary, so if we need more than that then let me know which ones we need.

**Comment by finestructure** [comment]
Interesting, I didn't get any such alert when I tested the toolchain locally. I wonder what that's about 🤔

Anyway, I've run my test script from above and it worked fine. So we should have all binaries available.

```
mb5:SemanticVersion (0.3.5*) $ xcrun --toolchain "org.swift.pr.62306.418" env DOCC_JSON_PRETTYPRINT="YES" swift package --allow-writing-to-directory ".docs/swiftpackageindex/semanticversion/0.3.5" generate-documentation --disable-indexing --transform-for-static-hosting --output-path ".docs/swiftpackageindex/semanticversion/0.3.5" --hosting-base-path "swiftpackageindex/semanticversion/0.3.5" --target "SemanticVersion"

Fetching https://github.com/apple/swift-docc-plugin from cache
Fetched https://github.com/apple/swift-docc-plugin (0.58s)
Computing version for https://github.com/apple/swift-docc-plugin
Computed https://github.com/apple/swift-docc-plugin at 1.0.0 (0.50s)
Creating working copy for https://github.com/apple/swift-docc-plugin
Working copy of https://github.com/apple/swift-docc-plugin resolved at 1.0.0
Generating documentation for 'SemanticVersion'...
Building for debugging...
[5/5] Compiling SemanticVersion resource_bundle_accessor.swift
Build complete! (13.83s)
Converting documentation...
Conversion complete! (0.06s)
Generated DocC archive at '/Users/builder/Downloads/SemanticVersion/.docs/swiftpackageindex/semanticversion/0.3.5'
```

Also our builder CI now passing so we should be good to go:

https://gitlab.com/finestructure/swiftpackageindex-builder/-/pipelines/712400478

**Comment by finestructure** [comment]
Failed in end-to-end testing. For some reason the deciding env variable [isn't picked up in process](https://staging.swiftpackageindex.com/builds/B4D6A081-D72D-4569-BD5C-06DC236D7CCE):

```
WARNING: environment variable API_BASE_URL is not set
```

Perma-link to job logs: https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/3418633688

This means we're falling back to release-5.7 and building with the old docs.

I think the problem is that while `API_BASE_URL` is set where we run the builder, this isn't re-exported into its env.

**Comment by finestructure** [comment]
Well, the variable is actually named `API_BASEURL` 🤪

**Comment by finestructure** [comment]
Ok, this is working now:

<img width="1188" alt="CleanShot 2022-12-03 at 19 00 13@2x" src="https://user-images.githubusercontent.com/65520/205455163-fd7c44f5-946b-4349-bc46-cf6eb458f447.png">

https://staging.swiftpackageindex.com/SwiftPackageIndex/SemanticVersion/0.3.5/documentation/semanticversion

**Comment by finestructure** [comment]
I've rebuilt the docs for all three packages in our current allow-list:

- [SemanticVersion](https://staging.swiftpackageindex.com/SwiftPackageIndex/SemanticVersion/documentation)
- [SPIManifest](https://staging.swiftpackageindex.com/SwiftPackageIndex/SPIManifest/documentation)
- [swift-argument-parser](https://staging.swiftpackageindex.com/apple/swift-argument-parser/documentation)

**Comment by finestructure** [comment]
If anyone's watching, please let us know (here or via email/Discord) if there are other packages you'd like us to allow-list for processing on dev!
