### ISSUE TITLE
Docs not showing up

### ISSUE THREAD

**Issue by sindresorhus** [SwiftPackageIndex/SwiftPackageIndex-Server#2141]
I added the `.spi.yml` file (https://github.com/sindresorhus/Defaults/blob/main/.spi.yml) two days ago, but the docs have still not appeared: https://swiftpackageindex.com/sindresorhus/Defaults

Is there any way I can debug this?

**Comment by daveverwer** [comment]
Hi @sindresorhus, and sorry that we're having a problem with these docs! I just checked and it's entirely our fault.

We're still working on the feature to highlight which build is responsible for your documentation generation in the [build matrix](https://swiftpackageindex.com/sindresorhus/Defaults/builds), but I can see that it's this one:

https://swiftpackageindex.com/builds/13ECD366-EAD1-48A6-9085-79BF025038B5

As you'll see from the log, the sync docs stage failed. We're having some serious issues with network stability on our Ventura-based build machine, and it looks like your build was affected by these problems.

I'm going to queue up new builds for you now and monitor them while they process. Apologies again for the problems here. We're working to try and solve them.
