### ISSUE TITLE
Move SPI Mastodon accounts to mastodon.social

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2167]
I've noticed a few times now that https://mas.to is having capacity problems:

<img width="1134" alt="CleanShot 2022-12-03 at 12 14 38@2x" src="https://user-images.githubusercontent.com/65520/205438167-cba6c43d-1dd5-4730-8ec9-7b97520ad068.png">

https://mastodon.social is coping fine at the same time, so I think it's time to move the accounts.

I'd originally picked mas.to, because mastodon.social had closed its signups. However, I later discovered that existing users can create invite links and so I'd created our two accounts subsequently on mastodon.social, just in case.

I think it's time to activate them now.

- [ ] set up link verification for https://mastodon.social/@SwiftPackageIndex
- [ ] set up link verification for https://mastodon.social/@SwiftPackageUpdates
- [ ] create app for posting on https://mastodon.social/@SwiftPackageUpdates
- [ ] update api url and access token for update posts
- [ ] [move accounts](https://blog.joinmastodon.org/2019/06/how-to-migrate-from-one-server-to-another/)

Moving accounts in Mastodon is possible without losing followers, however posts do not come across.

**Comment by finestructure** [comment]
Looks like this was a DoS attack: https://mastodon.world/@ruud/109449235553044156

Still might make sense to move as m.s seems to have weathered that ok as opposed to mas.to.

**Comment by Sherlouk** [comment]
what would the cost be of self hosting all the SPI accounts? 👀

(he says this inevitably knowing this has already been a convo and there's a valid reason not to)

**Comment by finestructure** [comment]
I briefly ran my own instance via masto.host for $6/month, so it's not a huge cost and given there are only two fairly inactive accounts (in terms of following content that would need federating in), the cheapest plan should suffice.

However, I don't think even moving to mastodon.social is necessarily required at this time unless issues with availability persist.

I think hosting our own instance would mostly be attractive if we wanted to have more official looking addresses, like

@packages@swiftpackageindex.com
@updates@swiftpackageindex.com

It's early days with Mastodon and while I'm personally enjoying it immensely and am convinced it's here to stay, I don't think we need to rush into anything with SPI as long as we're covering the basics.

People can find us there and we can move around as needed when we need it.

**Comment by finestructure** [comment]
I haven't seen any more issues with mas.to. I think rather than moving to mastodon.social moving to a hosted instance purely for SPI would be best eventually. Something to ponder/discuss but I'll close this issue in the meantime.
