### ISSUE TITLE
Broken images in GRDB docs

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2172]
I just noticed some image 404s in the logs:

```
[ ERROR ] Abort.404: Not Found: /groue/grdb.swift/v6.3.1/images/DatabasePoolConcurrentRead~dark@3x.png [component: server]
```

and indeed when browsing the GRDB docs I can see the broken image icon:

https://swiftpackageindex.com/groue/grdb.swift/v6.4.0/documentation/grdb/concurrency

<img width="787" alt="CleanShot 2022-12-05 at 09 31 29@2x" src="https://user-images.githubusercontent.com/65520/205590206-31625fe7-d3e4-454b-99dd-771e72c7bf1e.png">

(The versions of the docs differ but that shouldn't be relevant here, these links are broken for both doc versions by the looks of it.)

FYI @groue

**Comment by finestructure** [comment]
Images are there, so it's likely a proxy path issue:

<img width="1000" alt="CleanShot 2022-12-05 at 09 49 24@2x" src="https://user-images.githubusercontent.com/65520/205593977-4b6f940b-f402-4085-88bf-956fe618d5ce.png">

**Comment by groue** [comment]
Thank you @finestructure :-)
