### ISSUE TITLE
SwiftSyntax docs 404

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2179]
https://swiftpackageindex.com/apple/swift-syntax/main/documentation/swiftsyntax returns a 404

**Comment by finestructure** [comment]
Ok, the problem is this:

```
Syncing directory: spi-builder-workspace/.docs/apple/swift-syntax/main
1030	spi-builder-workspace/.docs/apple/swift-syntax/main
Directory size must not exceed 500.0 MB (was: 1030.0 MB)
```

https://swiftpackageindex.com/builds/DB1FC253-1F7A-4C96-9566-7F20A6FC8E5E

I'll lift the limit for swift-syntax and issue a rebuild.

cc @yim-lee

**Comment by finestructure** [comment]
Now we're timing out when uploading the docs:

```
S3 URL: s3://spi-prod-docs/apple/swift-syntax/main
Sync docs (attempt 1)
Syncing... [10%]
⚠️  Signal to terminate received.
⚠️  Signal to terminate received.
⚠️  Reporting timeout result for 3D99F53D-6E30-4CEA-8EAC-5C34F93D9A62 / 5.7 / macosSpm...
⚠️  Reporting timeout result for 3D99F53D-6E30-4CEA-8EAC-5C34F93D9A62 / 5.7 / macosSpm...
⚠️  Done.
```

We seem to be having weird bandwidth/connection issues from our builders to S3 at times.

For instance the first attempt failed as follows:

```
S3 URL: s3://spi-prod-docs/apple/swift-syntax/main
Sync docs (attempt 1)
Error: The operation couldn’t be completed. (SotoCore.AWSResponseError error 1.)
Retrying in 5 seconds ...
Sync docs (attempt 2)
⚠️  Signal to terminate received.
⚠️  Reporting timeout result for 3D99F53D-6E30-4CEA-8EAC-5C34F93D9A62 / 5.7 / macosSpm...
⚠️  Done.
```

I'll increase the timeout.

**Comment by finestructure** [comment]
We have abysmal network performance between MacStadium and AWS S3 at the moment.

The current run (with a timeout increased to 15m) is set to fail, because we're not managing to upload 1 GB from `mb5` to S3 _within 10 minutes_.

In fact it sits at just 10% after 5 minutes:

```
Syncing directory: spi-builder-workspace/.docs/apple/swift-syntax/main
1030	spi-builder-workspace/.docs/apple/swift-syntax/main
Doc size: 1030.0MB
S3 URL: s3://spi-prod-docs/apple/swift-syntax/main
Sync docs (attempt 1)
Syncing... [10%]
```

There's no timeout setting that would make that work.

We need to take this up with MacStadium, that can't be right.

Before we do we should run a network test on the machine directly, to S3.

**Comment by finestructure** [comment]
FWIW, the build itself finishes in 1.5m, i.e. we're essentially failing to upload 1GB within the remainder of the time of 13.5m.

**Comment by finestructure** [comment]
[Now we're getting an error again](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/3449784545):

```
Syncing directory: spi-builder-workspace/.docs/apple/swift-syntax/main
1030	spi-builder-workspace/.docs/apple/swift-syntax/main
Doc size: 1030.0MB
S3 URL: s3://spi-prod-docs/apple/swift-syntax/main
Sync docs (attempt 1)
Error: The operation couldn’t be completed. (SotoCore.AWSResponseError error 1.)
```

This is as of 9:45 UTC. I'll retry this again later this afternoon and in the meantime I'll see if we can get more detail to raise with MacStadium via https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-slow-downloads-uploads/

**Comment by finestructure** [comment]
Ok, this is going to be a problem. In order to test if this is machine specific, I copied the docs over to another builder. This took almost 6 minutes (!) via scp on the internal network:

```
scp -r swift-syntax-docs 63.135.169.77:~/Downloads/  28.60s user 62.63s system 26% cpu 5:50.04 total
```

The problem is that this directory contains 80k files:

```
mb5:Downloads $ find swift-syntax-docs -type f | wc -l
   81472
```

That's what's killing the upload speed. We're trying to issue 80k requests uploading tiny files.

**Comment by finestructure** [comment]
One way I can see us deal with this is to upload zip files to some service that expands them into S3 asynchronously.

Perhaps that's something a lambda could do?

**Comment by finestructure** [comment]
```
Error: The operation couldn’t be completed. (SotoCore.AWSResponseError error 1.)
```

might actually be an AWS rate limiting error. We should log more details here.

**Comment by finestructure** [comment]
Finally got this manually uploaded:

```
========================================
SyncDocs
========================================
Syncing directory: swift-syntax-checkout/.docs/apple/swift-syntax/main
1030    swift-syntax-checkout/.docs/apple/swift-syntax/main
Doc size: 1030.0MB
S3 URL: s3://spi-prod-docs/apple/swift-syntax/main
Sync docs (attempt 1)
Syncing... [10%]
Syncing... [20%]
Error: The operation couldn’t be completed. (SotoCore.AWSResponseError error 1.)
Retrying in 5 seconds ...
Sync docs (attempt 2)
Syncing... [10%]
Syncing... [20%]
Syncing... [30%]
Syncing... [40%]
Syncing... [50%]
Syncing... [60%]
Syncing... [70%]
Syncing... [80%]
Syncing... [90%]
Error: The operation couldn’t be completed. (SotoCore.AWSResponseError error 1.)
Retrying in 10 seconds ...
Sync docs (attempt 3)
Syncing... [10%]
Syncing... [20%]
Syncing... [30%]
Syncing... [40%]
Syncing... [50%]
Syncing... [60%]
Syncing... [70%]
Syncing... [80%]
Syncing... [90%]
Syncing... [100%]
env DOCS_MAX_SIZE_MB_DEFAULT=1500 ./builder sync-docs --aws-access-key-id      1647.18s user 33.10s system 83% cpu 33:35.54 total
```

and the link is now working:

<img width="1202" alt="CleanShot 2022-12-09 at 13 45 58@2x" src="https://user-images.githubusercontent.com/65520/206705537-bee05aa4-0130-4835-8826-1784492c4ac7.png">

Obviously this isn't a permanent solution as updates will fail but at least there's something in place for the moment that won't 404.

**Comment by yim-lee** [comment]
Thanks @finestructure!

**Comment by finestructure** [comment]
I don't think there's anything we can do here for the moment. I've created a follow-up issue to dry and deal with the upload of large doc sets in #2181 .
