### ISSUE TITLE
Unable to dismiss results dropdown

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#218]
I was searching and then I wanted to clear the drop down to see the recent feeds and noticed that there's no way other than page reload to get rid of the results drop down:

<img width="1219" alt="Screenshot 2020-05-30 at 11 40 49" src="https://user-images.githubusercontent.com/65520/83325167-9ea3f600-a26a-11ea-9ba2-22f72898bad7.png">

**Comment by daveverwer** [comment]
Interesting. Does deleting all of the text in the field not dismiss it? It does for me.

**Comment by finestructure** [comment]
Mmm, no - neither on the Mac nor the iPad. "Escape" doesn't dismiss it either. This is Safari on both.

**Comment by finestructure** [comment]
What works is typing a space - to get no results - and then backspace.

**Comment by finestructure** [comment]
Ah - the difference seems to be how fast I backspace. If I do it quickly, the results stay up.

**Comment by daveverwer** [comment]
With escape, would you expect it to clear the search text, or just dismiss the results?

If it just dismissed, how would you expect to get them back? Typing another character would do it, but it's not super intuitive. Maybe another escape to bring them back? Not sure that's super intuitive either.

**Comment by daveverwer** [comment]
Looking at what Google does is probably a good guide here:

![Screenshot 2020-05-30 at 10 57 11](https://user-images.githubusercontent.com/5180/83325478-5f72a680-a264-11ea-80ea-3229dc9a4ee6.gif)

Escape dismisses the results, and they don't come back until you type another character.

The only difference here is that with Google, hitting <Enter> has an effect, which it doesn't here. So if you have dismissed the search results with Google, you still have somewhere to go. With the SPI in its current design, you don't.

I'm not sure the solution to how to implement this is super obvious.

**Comment by finestructure** [comment]
Yes, I think that's a good match for expectations and I'd agree with Enter as well. So:

- hitting escape dismisses the result but doesn't clear the search
- hitting enter brings back the results (re-run or run the search)
- leaning towards leaving the search term up when hitting esc (i.e. non-descructuve)

**Comment by finestructure** [comment]
I think what we have is perfectly fine for launch btw

**Comment by daveverwer** [comment]
Yep, absolutely. I might fix the debounce issue, but I think the enhancement is for later.

**Comment by mthormann-dhi** [comment]
I think clicking anywhere else outside the dropdown should also dismiss the dropdown.

**Comment by daveverwer** [comment]
Yep also mentioned by @manmal in #392:

> Just in case there's interest in a possible solution:
> Personally, I'm used to the way Google's seach box works. If the textfield loses focus, the autocomplete list is hidden. Google only shows the autocomplete list again if the user enters another character, but that always annoyed me - I think the list should be shown as soon as the textfield regains focus.

Added to the "post-launch" project.

**Comment by daveverwer** [comment]
So I just had a go at fixing this and revealed a tricky problem with the concept. It's fixable, but the fix in my head is a little ugly so I want to run it by some people.

The changes I have made:

* When focus is received, if there is a search query perform a search and show the results.
* When focus is lost, always hide the results.

That all works as expected. The problem comes when trying to click one of the results... What happens is:

* The query field contains a query, and results are displayed.
* The user clicks a result in the list.
* As the user's mouse clicks, the text field loses focus and the results are hidden.
* The user's click falls through to whatever is behind the results. 💥

The obvious fix is to `setTimeout` the hiding of the results div, but as with `performSelector:afterDelay:` using `setTimeout` is *never* the correct fix 😂

**Comment by manmal** [comment]
@daveverwer I agree, timeout seems like a hack :)
Maybe this strategy could work? https://stackoverflow.com/a/43356000

**Comment by daveverwer** [comment]
You should see the code on my screen right now... it's exactly where we are right now...

```
    document.addEventListener('mousedown', () => {
      console.log('click');

      const queryFieldElement = document.getElementById('query')
      if (!queryFieldElement) { return }

      // if (event.target)

      // queryFieldElement.blur()
    })
```

😂

It's not trivial though as we need to get information passed through to the `blur` to know whether to prevent default on it.

**Comment by manmal** [comment]
I can imagine.. makes me appreciate UIKit more 😂

**Comment by daveverwer** [comment]
I feel only very slightly less ill when I think about [this solution](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/commit/892205885a58a0dc3eaca705e1bdf914bce01396), which does work, but 50+ lines of JS just to fix this (and that's before even starting to tackle keyboard dismissal of it).

Ugh

**Comment by finestructure** [comment]
/e leans back and rocks his chair over in the backend 😉

**Comment by daveverwer** [comment]
Yea, this is uglyyyyyyy

I think however the version I just pushed to `fix-218` is the best fix for this. It doesn't yet do keyboard dismissal of the results, which should be part of this PR, but that's for tomorrow. I'm done for tonight.

**Comment by daveverwer** [comment]
#402 if you want to look at the diff so far.

**Comment by manmal** [comment]
Looks sound to me!
