### ISSUE TITLE
swift-collections docs show no landing page

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2180]
https://swiftpackageindex.com/apple/swift-collections/1.0.4/documentation/collections

<img width="1070" alt="CleanShot 2022-12-09 at 09 43 46@2x" src="https://user-images.githubusercontent.com/65520/206661330-073ee99d-9f7a-4529-81cb-eb860b724c4a.png">

**Comment by finestructure** [comment]
The problem appears to be that `data/documentation/collections.json` doesn't include data for the `abstract`:

```json
"doc://Collections/documentation/Collections": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/Collections\/documentation\/Collections",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "Collections",
  "type" : "topic",
  "url" : "\/documentation\/collections"
}
```

I notice that the package manifest for 5.7 (i.e. just `Package.swift`) excludes `Collections.docc`:

```swift
    .target(
      name: "Collections",
      dependencies: [
        "DequeModule",
        "OrderedCollections",
      ],
      path: "Sources/Collections",
      exclude: ["CMakeLists.txt", "Collections.docc"],
      swiftSettings: settings),
```

In my [testing in PR 252](https://github.com/apple/swift-collections/pull/252/files#r1041898065) this lead to the abstract being stripped out.

However, when I re-tested this locally a moment ago the resulting `collections.json` _did_ contain the full abstract and the preview displayed it.

**Comment by finestructure** [comment]
Ah, hold on. I was looking at `Package.swift`, thinking it'd be the one used with 5.7 whereas it's actually `Package@swift-5.5.swift` that is.

And that one is correctly only excluding the `CMakeLists.txt` file:

```swift
    .target(
      name: "Collections",
      dependencies: [
        "DequeModule",
        "OrderedCollections",
      ],
      path: "Sources/Collections",
      exclude: ["CMakeLists.txt"],
      swiftSettings: settings),
```

**Comment by finestructure** [comment]
OK, I've reproduced this locally. The problem is that we're bumping the `tools-version` of `Package.swift` when we build the docs. What that does is elevate `Package.swift` to 5.7 which apparently makes it then override `Package@swift-5.5.swift` again - which brings back the problem discovered in [PR 252](https://github.com/apple/swift-collections/pull/252/files#r1041898065) 🤦‍♂️

We've been advised to bump the tools version to the latest because that can help with getting the latest feature support when building docs. However, we must be careful which file we bump. I.e. if there are versioned package manifests we need to make sure we bump the latest one (or perhaps refrain from messing with the tools-version entirely, in case that's problematic).

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/160

Will deploy and rebuild shortly.

**Comment by lorentey** [comment]
Oh interesting! Thank you very much for looking into this.

I did not realize I was going against the grain when versioning the manifests; SPM didn't care, but now I see that other packages usually go the other way. 🤔

**Comment by lorentey** [comment]
I wonder if implicitly bumping to the latest toolchain version would cause issues if DocC starts using the manifest version to gradually phase in potentially source breaking changes -- such as updates to the doc comment or markdown syntax conventions (link formatting etc). The Swift compiler / stdlib / package manager does this sometimes to mitigate source breaks.

**Comment by finestructure** [comment]
> I wonder if implicitly bumping manifests to the latest toolchain version would cause issues if DocC starts using the manifest version to gradually phase in potentially source breaking changes -- such as updates to the doc comment or markdown syntax conventions (link formatting etc). The Swift compiler / stdlib / package manager does this sometimes to mitigate source breaks.

Yeah, I've now removed this entirely. The more we mess with people's manifests in our build system the harder it gets to reason about things when they go pear shaped 😅

However, in principle we should be ok, because we're only generating docs on the latest Swift version and bump to that same version. So the two should always be in sync.

**Comment by finestructure** [comment]
Ok, this took way longer than expected to deploy due to some unrelated technical issues but it's now deployed and the abstract is up again:

<img width="1270" alt="CleanShot 2022-12-09 at 22 01 27@2x" src="https://user-images.githubusercontent.com/65520/206795537-afaad68a-c58a-4283-8aa5-47fa741b7975.png">

**Comment by yim-lee** [comment]
Thanks @finestructure! 🙏
