### ISSUE TITLE
Offload DocC uploads to upload service

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2181]
We've seen via #2179 that uploading large doc sets is problematic. The 1GB/80k files doc set takes 6mins to transfer via scp between MacStadium machines.

Even if there was a network issue on the day, we'll be hard pressed to upload doc sets of that size within the 10min timeout we impose on builds (and that includes the build and doc generation).

We should probably consider sending the zipped doc set to an intermediary which then deals with the upload asynchronously and with a more generous timeout and additional retries than we afford the current upload.

Not sure what the file size limits are for lambda but I could see that being a decent solution: send a zip to a lambda and let it deal with the S3 population.

**Comment by finestructure** [comment]
Looking through AWS Lambda examples with Swift I'm not particularly excited by the prospect... that's a lot of legwork and would probably be particularly awkward to get going from an M1 Mac.

Maybe https://swiftpackageindex.com/swift-cloud/Compute is the better option?

**Comment by finestructure** [comment]
I had an app running in under 10 mins in Swift Cloud:

<img width="1024" alt="CleanShot 2022-12-10 at 11 12 58@2x" src="https://user-images.githubusercontent.com/65520/206849485-ae0075a7-f42d-49cf-91fd-0f23214be33b.png">

The problem is that it's in beta, so it's unclear what pricing and availability will be like.

What we could do though is only send certain problematic doc sets to a service powered by this. Right now we're not succeeding to upload them so worst case we're no worse off than before.

If we choose doc sets that exceed 500MB, we zip them up and send them there and try our luck. Until we encountered #2179 we didn't even attempt to upload doc sets >500MB so either way this is an improvement.

**Comment by finestructure** [comment]
Ok, so this isn't going to be straightforward on Swift Cloud either, because `SotoS3FileTransfer` (or rather the dependencies it pulls in) don't compile with SwiftWasm:

```
12:17:02.578 | [build] swift build: /build_6debxa7ol4n2/.build/checkouts/async-http-client/Sources/CAsyncHTTPClient/CAsyncHTTPClient.c:35:38: warning: implicit declaration of function 'strptime_l' is invalid in C99 [-Wimplicit-function-declaration]     const char * firstNonProcessed = strptime_l(string, format, result, (locale_t)locale);                                      ^ /build_6debxa7ol4n2/.build/checkouts/async-http-client/Sources/CAsyncHTTPClient/CAsyncHTTPClient.c:35:18: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]     const char * firstNonProcessed = strptime_l(string, format, result, (locale_t)locale);                  ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 2 warnings generated.
-- | --
12:17:02.835 | [build] swift build: [1/461] Compiling _NIODataStructures Heap.swift /build_6debxa7ol4n2/.build/checkouts/swift-nio/Sources/_NIODataStructures/Heap.swift:199:28: error: cannot find 'log2' in scope                 return Int(log2(Double(index + 1)))                            ^~~~ [1/461] Compiling _AtomicsShims.c
```

**Comment by daveverwer** [comment]
I'm still in London so can't look in any detail, but I met Andrew yesterday and he gave a great talk on exactly this subject. He's in our discord, too, so we have a friendly face to ask some of these questions of.

**Comment by finestructure** [comment]
We could perhaps achieve similar sync times with our current setup if we didn't do exponential back-off and allowed for retries per file. Right now we retry the whole sync on error, that's probably what's making our sync so slow.

**Comment by finestructure** [comment]
Just spotted another package (via 404s in our logs) that's failing doc upload and therefore showing a documentation link:

<img width="755" alt="CleanShot 2022-12-19 at 11 00 29@2x" src="https://user-images.githubusercontent.com/65520/208399536-628657b1-e2fd-4a5c-88fd-04579f79ae6a.png">

I've manually triggered a rebuild but I suspect this might be a rather frequent occurrence that we don't have good visibility into.

This doc upload service is probably important to fix not just for large doc set uploads (this package has 162MB of docs and is failing).

**Comment by daveverwer** [comment]
It might even be worth deleting builds for the ~200 packages with documentation when we have a fix in place.

**Comment by finestructure** [comment]
![Doc Uploader](https://user-images.githubusercontent.com/65520/210773047-9c1f7cba-252c-4da9-a0f5-2ab8d1ed123d.png)

Link to implementation notes: https://noteplan.co/n/21830411-C2AB-4EFF-932C-1A04DBBCB16C

**Comment by finestructure** [comment]
Quick update. The lambda and builder changes are live and activated for swift-syntax.

There are however performance problems even when copying from the Lambda to S3. With a bit of effort it can be done in 14m30s, which is _just_ under the 15m hard Lambda runtime budget. That's too close to ship it like that.

Also, we'd be paying 15m of compute per version when all we're doing is copying (which takes ~13m30s), at a rate of $15 per mille.

We know that the doc set can be copied to S3 in under 6mins, so before shipping this I'm looking into ways to make this faster.

The problem likely is due to the fact that the Lambda is single threaded and we're not uploading in parallel.

**Comment by finestructure** [comment]
Thanks to @adam-fowler's help we're down to ~9.5m for the copy, with the total run time (arm64) being just over 10m.

**Comment by finestructure** [comment]
This is now live. The doc set limit is currently still 500MB for all packages except swift-syntax, for which it is 1GB.

That means currently only swift-syntax will opt-into the new doc uploader, because we only start using the doc uploader for doc sets > 500MB but actually reject all doc sets > 500MB except swift-syntax.

We'll lower the threshold over the coming days to onboard more packages into the new process.
