### ISSUE TITLE
Documentation fallback links should include beta releases where no default branch documentation is available

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2191]
The fallback order should be:

* Latest stable release (Highest priority)
* Latest pre-release tagged version
* Default branch (Lowest priority)

I believe it currently only does:

* Latest stable release (Highest priority)
* Default branch (Lowest priority)

**Comment by finestructure** [comment]
I’ve had a look around before sending that email and I _think_ we’re already doing that:

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/02fd647990ed012227a84b1a4a4899bd71ebc36a/Sources/App/Controllers/PackageController%2BPackageResult.swift#L87

It would be odd (or rather a bug I think) if `hasDocumentation` took pre-releases into account but we then filtered them out in the drop-down.

Worth confirming properly though!

**Comment by finestructure** [comment]
<img width="296" alt="CleanShot 2022-12-14 at 21 02 58@2x" src="https://user-images.githubusercontent.com/65520/207702597-3bb2d246-1f61-432c-b0a7-3eaa84762045.png">

https://swiftpackageindex.com/putridparrot/SwiftUnits

**Comment by daveverwer** [comment]
Thanks for checking. I think this does need a tweak. Even though the beta docs do appear, which I didn't doubt they would, the fallback there is back to main.

I think we need to make the fallback go from release, to pre-release, to default branch.

**Comment by finestructure** [comment]
The problem in this case is that there is no main

**Comment by daveverwer** [comment]
That's my point, we'd want to fall back to the pre-release before going to the default branch. I think what we currently have would potentially fail in the case where there was a beta tag that had documentation and a main branch that didn't.
