### ISSUE TITLE
swift-hash showing 3 contributors, but it only has 1?

### ISSUE THREAD

**Issue by kelvin13** [SwiftPackageIndex/SwiftPackageIndex-Server#2193]
**Which package(s) are showing incorrect data?**

- [swift-hash](https://swiftpackageindex.com/kelvin13/swift-hash)

**Please explain what data is incorrect and what you expected to see**

the page for swift-hash shows “Written by kelvin13 and 2 other contributors”, but (unfortunately) i don’t remember anyone besides me [contributing to it](https://github.com/kelvin13/swift-hash/graphs/contributors)?

**Comment by daveverwer** [comment]
The default display is based on unique committer names in git history. It's likely there's a couple more in there that you were not aware of. You can run `git shortlog` to see them. 

You can also customise this string completely.

More details here: https://blog.swiftpackageindex.com/posts/recognising-package-authors

**Comment by Sherlouk** [comment]
Just checked and this is the output of the shortlog on the repo:

```
    30  kelvin13 <kelvin13ma@gmail.com>
    15  taylorswift <kelvin13ma@gmail.com>
     1  kelvin <kelvin13ma@gmail.com>
```

It would appear that the same email is being used, but the git username changed at some point (perhaps using different machines, or different GUIs with different configurations).

@daveverwer Is there any desire (one way or another) to dedupe/group based on email?

**Comment by kelvin13** [comment]
ah that makes sense, thanks dave!

**Comment by daveverwer** [comment]
> @daveverwer Is there any desire (one way or another) to dedupe/group based on email?

We could, but then we'd need to make a decision about what name to use, and that's all just more steps down potentially getting it wrong.

We have a mechanism for correcting the automated detection. Unless it becomes a bigger issue, I think we're good for now. 👍
