### ISSUE TITLE
Improve the "Use this Package" snippets

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2197]
We're currently showing the following info:

<img width="624" alt="CleanShot 2022-12-20 at 12 54 06@2x" src="https://user-images.githubusercontent.com/65520/208661107-9e7819b4-f315-4ab1-a6f8-b4e8058c477f.png">

However,

```swift
.package(url: "https://github.com/soto-project/soto-s3-file-transfer.git", from: "1.1.0")
```

is only part of what's needed for the package manifest.

In your target, you also need to specify

```swift
.product(name: "SotoS3FileTransfer", package: "soto-s3-file-transfer"),
```

to use the dependency.

We actually have all the information to provide these bits as well, per product. I.e. we could generate a `.product(name: "\(product)", package: "\(package)")` line per product (typically just one).

We can cap this at some number to avoid an overflow for packages with lots of products.

We would _not_ need to do this per significant version, it could be a common section below. (Yes, theoretically the default branch could have different products defined than the stable release but I don't think we need to take that sort of nuance into account.)

**Comment by finestructure** [comment]
We could also perhaps save a bit of space on that popover if we folded the `.package(...)` clauses into a single line with a drop-down selector which version to pick. I think it's safe to say the vast majority of times you'll want the stable release, so that should be the default.

**Comment by daveverwer** [comment]
As discussed:

![Untitled - 22 December 2022 17 18 25](https://user-images.githubusercontent.com/5180/209191579-a1304e8e-c673-4ede-81bc-331859d11024.jpg)

* Xcode section is unchanged.
* SPM section is split into two drop-downs with copy buttons next to each other:
  * First one allows the branch/release to for the `.package` line
  * Second one has a list of all products and copies the `.product` line

Neither of the drop-downs show lines of code any more, but a more readable representation of what will be copied.

**Comment by finestructure** [comment]
I've [just learned](https://swift-open-source.slack.com/archives/C5GMX4LP9/p1681265675548359?thread_ts=1681203004.747199&cid=C5GMX4LP9) that Xcode has an `xcode://showPackage?url=` url scheme that brings up the following dialog when clicked:

```
xcode://showPackage?url=https://github.com/apple/swift-nio
```

<img width="768" alt="CleanShot 2023-04-12 at 11 46 33@2x" src="https://user-images.githubusercontent.com/65520/231421525-369f22f1-1611-43df-b96c-65d025778da7.png">

This panel allows you to configure your "package clause" at the top and then copy it (when in an SPM package) or presumably add it directly if in an Xcode project. It puts the following on the clipboard for example:

```
.package(url: "https://github.com/apple/swift-nio.git", .upToNextMajor(from: "2.0.0")),
```

This could augment/replace our "per branch" package clauses (pro: less clutter, more configurable, con: extra click, Xcode only/required).

We'd still want something to allow you to create the "product" clause you also need to add to the targets using the dependency in your manifest.

**Comment by finestructure** [comment]
Note that full package loading via `xcode://showPackage` doesn't work reliably for arbitrary packages anymore as of Xcode 15. It seems like there's an allow list that's limited to certain orgs:

![CleanShot 2023-07-25 at 12 04 41@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/ea5e96e6-9fc2-435c-9d5e-c93fcd356758)

(Layout seems to be messed up in Xcode 15b4)

This used to work in Xcode 14:

![CleanShot 2023-07-25 at 12 06 57@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/d23a542a-5c79-4e1e-9f68-c535ff5995dc)

**Comment by finestructure** [comment]
I accidentally deleted a comment which I thought to be a duplicate. The gist was that as of Xcode 15 there's an allow list for packages which load the readme via the above callback. Others show a message `For security reasons, we do not load the Read Me through xcode:// URLs.`
