### ISSUE TITLE
Remove twitter spaces announcement

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2198]
We should really remove the Twitter Spaces announcement from the home page, it's quite outdated :)

<img width="486" alt="CleanShot 2022-12-21 at 10 21 09@2x" src="https://user-images.githubusercontent.com/65520/208870220-3c1624b7-7752-4642-bc79-ca7999be9129.png">

**Comment by daveverwer** [comment]
Closing in favour of #2137
