### ISSUE TITLE
Report server errors up to Rollbar

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#221]
5xx for sure, perhaps 4xx as well

**Comment by daveverwer** [comment]
We could do 4xx errors for now, and see how noisy they are.

5xx for sure.

**Comment by daveverwer** [comment]
> We could do 4xx errors for now, and see how noisy they are.

I predict they'll be wayyyyyyyy too noisy. "Stuff" hits sites all the time looking for vulnerabilities and every one of those will be a 4xx.
