### ISSUE TITLE
Configure Cloudflare and SSL

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#223]

**Comment by finestructure** [comment]
Is there a port mapping facility so we can route a subdomain, for instance `mon.swiftpackageindex.com` at Grafana on port 3000?

**Comment by daveverwer** [comment]
I'd normally just have the webserver(s) run on 80 and have them respond to the host. However, with [this Cloudflare app](https://www.cloudflare.com/apps/portzilla) it appears it can be done.

I'd say that's worth a try, if it's hard to get them to respond to host/subhost names.

**Comment by finestructure** [comment]
Fixed as of earlier today 🎉
