### ISSUE TITLE
Incorrect link to `TecoSigner` documentation

### ISSUE THREAD

**Issue by stevapple** [SwiftPackageIndex/SwiftPackageIndex-Server#2249]
**Please describe the bug**

After changing title from `TecoSigner` to `Teco Signer` on the main branch of [teco-core](https://github.com/teco-project/teco-core), some links to the documentation are broken.

**Explain the steps needed to reproduce the bug**

1. Navigate to https://swiftpackageindex.com/teco-project/teco-core
2. Click on "Documentation"
3. From the top bar, choose "Documentation for **main**" and "Teco Signer".
4. 404 Not found at https://swiftpackageindex.com/teco-project/teco-core/main/documentation/teco%20signer

**What was the expected behaviour?**

The link should point to https://swiftpackageindex.com/teco-project/teco-core/main/documentation/tecosigner

**Screenshots**

![C07A9847-9AE2-4DD9-B736-BD6F08ED6C75](https://user-images.githubusercontent.com/26525394/216635889-df11849f-18dc-4cfc-b2cf-ed05f4b5fdb7.png)

**Additional context**

The title is changed by a DocC directive called [`Metadata.DisplayName`](https://developer.apple.com/documentation/docc/displayname). The display name of a module is not necessarily identical to its name, which may be assumed by the infrastructure.

There’re some other display issues including missing module picker at https://swiftpackageindex.com/teco-project/teco-core/main/documentation/tecosigner, but that’s less pain.

**Comment by finestructure** [comment]
Hi @stevapple , thanks for the report!

I think I know where this might be going wrong, I just hope we've got the correct data to resolve this at that point 😧

**Comment by finestructure** [comment]
Sorry for the long delay, @stevapple! I'm taking a closer look at this now so you can hopefully revert that workaround at some point.

**Comment by finestructure** [comment]
@stevapple – the fix is now live. You should be able to revert your workaround and use the proper title in your docs.
