### ISSUE TITLE
Build Error - Does Not Contain Scheme that is Available Using the `--list` Option

### ISSUE THREAD

**Issue by PSchmiedmayer** [SwiftPackageIndex/SwiftPackageIndex-Server#2261]
**Please describe the bug**

Dear Swift Package Index team,

First of all: Thank you for building the Swift Package Index and maintaining the project!

We are currently encountering an error for our [CardinalKit](https://swiftpackageindex.com/StanfordBDHG/CardinalKit) project: https://swiftpackageindex.com/builds/501AD011-0145-48C2-8D83-A286EF4D4683. The build error indicates that the `CardinalKit-Package` scheme is not present.

Running the "-list" option locally indicates that the `CardinalKit-Package` scheme is present.
We can also reproduce that building the Swift Package build works successfully using our GitHub action: https://github.com/StanfordBDHG/CardinalKit/actions/runs/4172050105/jobs/7222685888. This also applies to the last pushes on the main branch as well as the `0.3.0` release and previous releases.

We observed that some builds on the main branch had been successul, and we could access the documentation at some point in the past, which looked awesome! An amazing feature that the Swift Package Index offers; thank you for that!

Nevertheless, it looks like the latest changes on the main branch did fail and resulted in a time-out: https://swiftpackageindex.com/StanfordBDHG/CardinalKit/builds

Please let me know if there is anything that I could do to further help you reproduce the error and get the documentation hosting up and running on the Swift Package Index. I am happy to further help reproduce the issue and help you there!

**Comment by finestructure** [comment]
Hi @PSchmiedmayer , thanks for raising this issue!

The error message here is misleading or probably outright wrong. I believe it's exactly the the existing `CardinalKit-Package` that is the problem. I've opened a PR against your `.spi.yml` to specify an explicit scheme that should fix this.

I suspect there was perhaps a change in your xcodeproj file that brought in the `-Package` scheme was started tripping us up. We're applying a number of heuristics to figure out which scheme to build and this can go wrong for larger projects.

The error message you're seeing is from the last stage in our attempts to fix it by deleting the project file and build via the auto-generated one. This then seems to fail in your case, presumably because autogeneration doesn't produce the `-Package` scheme.

Hope that helps!

I'll keep this issue open until we seen the `main` build flip back to green.

**Comment by heckj** [comment]
For what it's worth, I've had this happen to myself when you go from a simple Swift package library with a single target to a library that has multiple targets - for example, it bit me when I added an executable target that provided benchmarks for my library.

**Comment by finestructure** [comment]
Ah yes, that'll do it I guess!

**Comment by PSchmiedmayer** [comment]
@finestructure Thank you a lot for your input! Thanks for providing some more detail about the inner workings of the build system!
Greatly appreciate the time and effort you put into maintaining this project!

The CardinalKit Swift Package exposes several targets that are exposed as products. Using the `CardinalKit` scheme would only build a single package and not the complete set of targets/products that are exposed and should probably be validated by the SPI build job.
I have not found any reference if it is possible to pass more than one scheme in the arguments (e.g., a yml list)?
Is there some more detail about the structure of the `.spi.yml` file [beyond this article](https://blog.swiftpackageindex.com/posts/the-swift-package-index-metadata-file-first-steps/)? Or is it completely fine if we just define the single scheme as this is our main product and the other targets/products are not build using the SPI build verification?

As far as I understood, the documentation building is independent of the selected scheme, so it should still expose all the other targets in the documentation?

**Comment by finestructure** [comment]
@PSchmiedmayer We only support a single scheme. Think of it as choosing a scheme that's representative for a package's overall compatibility (typically the main product to be used by clients), not as an exhaustive CI-like check of a package. We're more like a probe rather than a CI system :)

Your documentation will still be built across all the targets listed, regardless of the scheme.

**Comment by PSchmiedmayer** [comment]
Thank you for the clarification @finestructure!

That sounds great, I will adjust the list of document targets that we want to build documentation for and will merge the proposed changes in our main branch. Thank you for your help! 🚀

**Comment by PSchmiedmayer** [comment]
@finestructure I have merged the suggested changes into the main branch but, unfortunately still observe a build error for the main branch as well as for the latest release: https://swiftpackageindex.com/StanfordBDHG/CardinalKit/builds
I am actively working on moving a few things out of the repo into other repos to make the build times more manageable + separate a few dependencies into separate projects, so there is no need to resolve all dependencies if you want to use the framework. That might help with the timeout issue. Nevertheless, the build error still persists for the main branch: https://swiftpackageindex.com/builds/4B8887A2-409E-4F45-8689-E81827960FD7

Is there anything that I can do to help with that issue? Is there a way to help reproduce the issue locally?

**Comment by finestructure** [comment]
Thanks for following up, @PSchmiedmayer . There's something interesting going on: When I tested this with my patch it worked but the reason it worked was that I ran the build after changing the `.spi.yml` file on the same directory. It turns out that the build succeeds _if run a second time_ after this error appears 🤪

```
< ... snip ... >
Resolve Package Graph
Resolve Package Graph
ResearchKit - https://github.com/StanfordBDHG/ResearchKit @ 2.2.8
❌ xcodebuild: error: The workspace named "checkout" does not contain a scheme named "CardinalKit". The "-list" option can be used to find the names of the schemes in the workspace.
Error: Build failed
command: BuildCommand(command: "env DEVELOPER_DIR=\"/Applications/Xcode-14.1.0.app\" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride=\"$PWD/.dependencies\" -derivedDataPath \"$PWD/.derivedData\" build -scheme \"CardinalKit\" -destination \"generic/platform=ios\"")
message: Resolve Package Graph
Resolved source packages:
  abseil: https://github.com/firebase/abseil-cpp-SwiftPM.git @ 0.20220203.2
  leveldb: https://github.com/firebase/leveldb.git @ 1.22.2
  SwiftProtobuf: https://github.com/apple/swift-protobuf.git @ 1.20.3
  GTMSessionFetcher: https://github.com/google/gtm-session-fetcher.git @ 3.1.0
  Firebase: https://github.com/firebase/firebase-ios-sdk @ 10.4.0
  Promises: https://github.com/google/promises.git @ 2.1.1
  GoogleAppMeasurement: https://github.com/google/GoogleAppMeasurement.git @ 10.4.0
  CardinalKit: /Users/sas/Projects/SPI/spi-builder/checkout
  ResearchKit: https://github.com/StanfordBDHG/ResearchKit @ 2.2.8
  HealthKitOnFHIR: https://github.com/StanfordBDHG/HealthKitOnFHIR @ 0.2.2
  BoringSSL-GRPC: https://github.com/firebase/boringssl-SwiftPM.git @ 0.9.1
  GoogleDataTransport: https://github.com/google/GoogleDataTransport.git @ 9.2.0
  gRPC: https://github.com/grpc/grpc-ios.git @ 1.44.3-grpc
  GoogleUtilities: https://github.com/google/GoogleUtilities.git @ 7.11.0
  FHIRModels: https://github.com/apple/FHIRModels @ 0.4.0
  nanopb: https://github.com/firebase/nanopb.git @ 2.30909.0
  ResearchKitOnFHIR: https://github.com/StanfordBDHG/ResearchKitOnFHIR @ 0.1.5
"
~/P/S/spi-builder on doc-uploader-post-release-cleanup took 1m35s
❯ ./builder build -p ios -s 5.7
< ... snip ... >
Resolve Package Graph
nanopb - https://github.com/firebase/nanopb.git @ 2.30909.0
[XCTRuntimeAssertions] Compiling XCTFail.swift
[CardinalKit] Compiling Configuration.swift
[CardinalKit] Compiling TypedCollection.swift
[CardinalKit] Compiling DynamicDependenciesPropertyWrapper.swift
[CardinalKit] Compiling CardinalKit+LifecycleHandlers.swift
[CardinalKit] Compiling LifecycleHandler.swift
[CardinalKit] Compiling EncodableAdapter.swift
[CardinalKit] Compiling Standard+DataStorageProviders.swift
[CardinalKit] Compiling Component+Dependencies.swift
[CardinalKit] Compiling ComponentDependency.swift
[CardinalKit] Compiling TypedAsyncSequence.swift
[CardinalKit] Compiling CardinalKit+DataStorageProvider.swift
[CardinalKit] Compiling DataStorageProvider.swift
[CardinalKit] Compiling DataStorageProvidersPropertyWrapper.swift
[CardinalKit] Compiling CardinalKit+ObservableObjects.swift
[CardinalKit] Compiling ObservableObjectComponent.swift
[CardinalKit] Compiling Module.swift
Resolve Package Graph
Build Succeeded
Build complete.
```

I need to take a closer look into what's going on here.

**Comment by finestructure** [comment]
I believe this is due to the project not having an `xcodeproj` file check in in combination with the way we're listing the schemes.

If you run

```
git clone https://github.com/finestructure/CardinalKit.git
cd CardinalKit
xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.derivedData" -list
```

you'll notice that the first time you call `-list` here it returns

```
There are no schemes in workspace "CardinalKit".
```

If you run it again, it finds the schemes.

If instead you run

```
git clone https://github.com/finestructure/CardinalKit.git
cd CardinalKit
xcodebuild -list
```

it finds the schemes the first time around.

We need to use `-IDEClonedSourcePackagesDirPathOverride="$PWD/.derivedData"` so we don't clog up the build machines and have builds interfere with each other. I'm not sure why/how it screws up scheme listing but it obviously does.

We should be able to run `-list` a second time if we find no schemes.

**Comment by PSchmiedmayer** [comment]
@finestructure Thank you for the explanation!

> We should be able to run -list a second time if we find no schemes.

That sounds like a good workaround, even though this might all originate from some bug or unexpected behavior in `xcodebuild`. It might make sense to file a radar for that, or do you have some other connections/ideas on how to fix the issue in the long run?

How can I help to get the workaround in the codebase for the Swift Package Index? Where are the build steps documented or implemented? Happy to make a contribution or support you in making these changes.

**Comment by finestructure** [comment]
Turns out the `-list` command has no effect on the build but running the build a second time does work.

I've prepared a fix to add a build retry to our setup, although I wonder if adding an xcode project file would be the cleaner option here 🤔

**Comment by finestructure** [comment]
Fixed by https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/180

**Comment by finestructure** [comment]
Ok, this is working better but I can already tell watching the build that it'll time out. We've got a 10min build time budget and the initial build only takes a minute or so. However, there are so many documentation targets defined (which all get built) that the overall process hits the limit.

I'd recommend perhaps starting with a small set of documentation targets initially, ones that are most relevant to the users.

PS: it did in fact time out while I was typing this:

```
Successfully merged into spi-builder-workspace/.docs-staging/stanfordbdhg/cardinalkit/0.3.1/index/index.json
Target:                   Scheduler
Resolve Package Graph
⚠️  Signal to terminate received.
⚠️  Reporting timeout result for 37AA2736-2752-424F-AEC2-CBA6D71B1D11 / 5.7 / ios...
⚠️  Done.
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit status 1
```

**Comment by finestructure** [comment]
FYI @PSchmiedmayer ☝️ 

I don't think there's more we can do here on our end, sadly.

**Comment by PSchmiedmayer** [comment]
@finestructure Thank you for merging the fix! Greatly appreciate the time and effort that goes into this project!

We are currently splitting the framework into smaller projects that are independent of each other, which should reduce the build time of the main repo by a lot. I will update you once this is further along, and I suspect the build times will decrease in that process.

**Comment by finestructure** [comment]
👍  I'll go ahead and close this issue then in the meantime, ok? Feel free to re-open or add a new one if there are further issues!

**Comment by PSchmiedmayer** [comment]
Sounds good, thank you for your help @finestructure! 🚀
