### ISSUE TITLE
Search for "syntax" yields unexpected results

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2263]
https://swiftpackageindex.com/search?query=syntax&page=1

<img width="759" alt="CleanShot 2023-02-16 at 10 44 02@2x" src="https://user-images.githubusercontent.com/65520/219328634-3d6f79ce-8163-42a9-ac9d-a937f756fbc0.png">

This is from the middle of the _second_ page:

<img width="731" alt="CleanShot 2023-02-16 at 10 44 40@2x" src="https://user-images.githubusercontent.com/65520/219328868-fa9e8bd8-fd84-4338-bc57-405318ae4492.png">

- https://swiftpackageindex.com/nerdsupremacist/Syntax should be the top package as it's an exact package name hit
- https://swiftpackageindex.com/apple/swift-syntax should definitely rank higher given its score of 115, which is very high

**Comment by finestructure** [comment]
Ok, the high level reasons for the bad rankings are the following

- https://swiftpackageindex.com/nerdsupremacist/Syntax has no `package_name` on the default branch. Not yet clear why that is but it prevents the package from being ranked first.
- https://swiftpackageindex.com/apple/swift-syntax has `has_exact_word_matches = FALSE`, which ranks it first _after_ all the packages that do (which is 35). Not yet clear why that is but we should definitely ensure this gets an exact word match, because the repo name clear does and the pascal cased package name `SwiftSyntax` arguably also does. We may need to investigate if word stemming can take camel/pascal case into account.

**Comment by finestructure** [comment]
- https://swiftpackageindex.com/nerdsupremacist/Syntax is fixed by running
```
./Run re-analyze-versions --id 9898984d-dfed-4771-92e2-a408e0bc6ebb -r
```
  Not sure how exactly it happened (both in dev and prod) but both apparently failed to parse the manifest when they first ingested it. The default branch was last updated on July 3 last year and the package has a tools version 5.7. My guess is we didn't support 5.7 at the time and that's what made this fail. (I don't think it's feasible for us to detect this and reprocess such versions. We're going to have to rely on package authors moving their default branches forward so we can re-index newer versions.)

I've corrected both dev and prod by re-analysing the versions and the package now ranks first.

**Comment by finestructure** [comment]
Ok, this was interesting. apple/swift-syntax doesn't actually mention `syntax` as a word _anywhere_ we searched! It's always `SwiftSyntax`, which our word-stemming apparently doesn't break down. The only place where we have a chance to "see" `syntax` is in the repo name `swift-syntax`, which we didn't have in our word-stemming source field.

It makes sense to add it though, and this does in fact fix the ranking issue.

<img width="781" alt="CleanShot 2023-02-22 at 13 01 16@2x" src="https://user-images.githubusercontent.com/65520/220614322-fa6b440f-afe8-4fd7-b8be-b03cc0168c84.png">

**Comment by finestructure** [comment]
This fix works but it would revert to the bad behaviour if the repo name was changed to `SwiftSyntax`, in which case again we wouldn't "see" the word `syntax` amongst the search fields.

While this is of course unlikely, it would be better if we could somehow either make the word stemmer "see" camel/pascal case word boundaries (seems unlikely after a quick web search) or make it blind to some common terms like "swift".

Even if the latter could be made to work (I have my doubts), it'd not ideal to have to identify such common terms. Plus they might be load-bearing in other cases. We wouldn't want to interfere with ranking of "swiftly" by blinding out "swift" in that case.

That approach is likely a dead-end and the current approach the best we can reasonably achieve unless camel/pascal case word boundaries can be made to work.

**Comment by heckj** [comment]
FYI - stemming in the Postgres side doesn't care about casing - except for something like snake case or whatever you call the one with hyphens tossed throughout the words. It doesn't handle the removal of those characters, so it doesn't treat those as separate words, and it mucks up the stemming algorithm, assumes they're all individual and complete words

**Comment by finestructure** [comment]
Thanks @heckj ! I also asked around on Mastodon and it seems the only way to do it is via a custom TS (Text Search) parser. Looks like that needs to be an extension and even in the unlikely case we'd want to invest that kind of effort we probably wouldn't be able to install and load it in our hosted Postgres db.

One thing we could to is run our own "word chunker" on select fields as part of our processing and save the result. For example, analysis could chunk up package, repo name, and summary into new, search related fields that we use for ranking.

But I don't think any of this is needed at this time.
