### ISSUE TITLE
New default branch versions make default branch docs unavailable until new doc build completes

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2279]
I've manually re-triggered the docs but there are clearly two issues here:

- Linux doc builds get to the `pending` reporting stage when they clearly shouldn't, blocking then the actual doc builds
- tying the doc link to the `doc_uploads` record is bad, because it goes away on new versions - I'm pretty sure we didn't have that problem previously although it's late and I can't quite figure out how we avoided it

_Originally posted by @finestructure in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2278#issuecomment-1448837685_

**Comment by finestructure** [comment]
Here's another idea: we _could_ copy the `doc_archives` field content over to a new default branch version in analysis. That way we'd keep the doc link up optimistically. Well, even realistically - the docs will always remain there in S3. However, they will _not_ yet reflect the actual new version until it is reprocessed successfully.

A downside of this is that is easy to mask a problem where default branch docs go stale due to doc build errors but you never notice until there's an obvious divergence in content.

Re-opening this for a discussion whether this is worth exploring. I feel like it's probably better _not_ to do this at this time.

**Comment by daveverwer** [comment]
I agree we shouldn't copy `doc_archives` across as that's confusing data (as you say).

I wonder if we need to track the state of `doc_archives` somewhere. So (for example), if we have some sort of pending state, it knows to use the `doc_archives` from a previous release.

That wouldn't solve the issue of us not noticing stale documentation, but it'd make it easier to debug when it does happen. We could also put some kind of alert on records that keep a pending state for > a few hours.

I'm just running out of the door, but I wanted to get the idea out before I did.

**Comment by finestructure** [comment]
> That wouldn't solve the issue of us not noticing stale documentation, but it'd make it easier to debug when it does happen. We could also put some kind of alert on records that keep a pending state for > a few hours.

The problem would be the detection though, not the debugging. Once we know a doc build is bad, it's quite easy to get to all the logs and re-run.

A pending marker would help with detection but I worry about the number of false negatives, simply by judging from other places where we use them (build reports, doc reports). I frequently spend time investigating them and they often turn out to be false negatives. And that's only some internally visible pending records that I happen to check. Exposing that to users (via the docs page for example) would just create too much maintenance work.

On the other hand if we don't expose them to users (by placing the marker on the build details page, which hardly anyone looks at), it depends on us spotting it. But if it's for us to spot, there's a much easier way to do that: I have an SQL query to check on doc reports which reports across all doc builds not just a single one. That's our most effective way for a doc build system health check.

I believe we have two options here:

1. paint over the gap by copying the `doc_archives` and defer detection to some general doc build system health check
2. accept the gap and ensure the doc link doesn't disappear by making pre-release build keep it up (#2191)

Both really come down to doc builds on the default branch being best effort. Builds sometimes break on `main` and that'll naturally impact docs. The solution is to have (pre-)release docs in place - they're actually the ones that matter most. Default branch docs shouldn't be load-bearing for package documentation.

We also have to bear in mind that we've only seen this being problematic for one or two packages, so by all accounts this is not a huge issue we're dealing with here.

I think we should go with 2) for now and see if this develops into a bigger issue. Option 1) is still available to us then.

**Comment by finestructure** [comment]
Ok, looks like we agree and now that we've got #2191 live I'll go ahead and close this for now. Can revisit this should we see more requests from packages that have neither a release nor a pre-release.
