### ISSUE TITLE
Doc build fails for `SelectionKit` reference `feature/2.0.0`

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2287]
Umbrella issue to track the full fix

- [x] doc uploader: https://github.com/SwiftPackageIndex/DocUploader/pull/11
- [x] builder: [MR 186](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/186)
- [x] re-trigger doc build
- [x] server url

**Comment by finestructure** [comment]
Ok, we have the docs uploaded to S3 but we need to adjust the server side url to find them:

<img width="198" alt="CleanShot 2023-03-09 at 11 01 40@2x" src="https://user-images.githubusercontent.com/65520/223987960-783c36f9-920a-4428-a0c9-e7a962dc22f9.png">

It's looking for https://staging.swiftpackageindex.com/linhay/SectionKit/feature/2.0.0/documentation/sectionui but this needs to be https://staging.swiftpackageindex.com/linhay/SectionKit/feature.2.0.0/documentation/sectionui

<img width="818" alt="CleanShot 2023-03-09 at 11 03 14@2x" src="https://user-images.githubusercontent.com/65520/223988243-e8447543-b347-4566-b3aa-ba2ae15c8912.png">

**Comment by daveverwer** [comment]
Is there any way we could shield this change from reflecting in the URL? That URL is nicely understandable right now, but `feature.2.0.0` is less clear than `feature/2.0.0` to end users.

**Comment by finestructure** [comment]
I'm not sure. This would probably be tricky because it introduces an additional path segment which might affect routing.

It's actually quite tricky to get this to work even with the current "encoding" :/

**Comment by daveverwer** [comment]
Can we try? I'm in the middle of editing the podcast right now, but maybe we can get together later and try and figure it out. It would be a shame to have this change.

**Comment by finestructure** [comment]
I'm out this afternoon and this isn't actually working at all yet. I think we need to get this to serve up the default branch docs at all first!

**Comment by finestructure** [comment]
Ok, I've got a fix for the doc archive lookup but I don't think the `/` in the path can be preserved.

We have the doc routes structured as follows:

```swift
            app.get(":owner", ":repository", ":reference", "documentation") {
                try await PackageController.documentation(req: $0)
            }
```

and in order to parse out a multi-segmented reference, we'd need something like this:

```swift
            app.get(":owner", ":repository", "**", "documentation") {
                try await PackageController.documentation(req: $0)
            }
```

However, the `**` catch all cannot be in the middle of a route:

```
RoutingKit/TrieRouter.swift:47: Precondition failed: Catchall ('**') must be the last component in a path.
```

We could use a character other than `.` to do the path escaping - maybe `-` would read nicer - but we can't use `/` as far as I can see.

**Comment by finestructure** [comment]
It's possible that the more powerful routing via Pointfree.co's library would allow us to express this route but unfortunately we can't use that for other reasons.

**Comment by daveverwer** [comment]
Yes, it’s a shame we can’t use the Pointfree router, and not just because of this!

I think the `-` works better than `.`. Certainly for branches like this where it would be `feature-2.0.0` but I think something like `feature-my-feature` would look better than `feature.my-feature` for a branch named `feature/my-feature`.

The good news is that this only affects (currently) five packages in our database:

<img width="348" alt="Screenshot 2023-03-10 at 09 40 09@2x" src="https://user-images.githubusercontent.com/5180/224283640-434636dd-b3ae-43ea-bdb4-d8df425e6cc4.png">

One of those is this one, one is archived, one hasn’t been updated for 3 years, leaving only two other packages with this situation that are being actively maintained. The other two don’t host docs yet, but they could.

Thanks for looking into it. I think my vote would go for `-`.

**Comment by finestructure** [comment]
- [ ] re-trigger doc build on dev
- [ ] add tests to url change
- [ ] ad-hoc deploy branch with server-side change to dev

**Comment by finestructure** [comment]
Updated upload is working:

<img width="218" alt="CleanShot 2023-03-10 at 12 23 39@2x" src="https://user-images.githubusercontent.com/65520/224303921-7d4f8961-00b2-456c-a9da-de6cb55b286f.png">

**Comment by finestructure** [comment]
We have a new problem. When querying for the `DocumentationTarget`s for such a version, we fail to find any because of this query:

```swift
        let archive = try await Joined3<Version, Package, Repository>
            .query(on: database,
                   join: \Version.$package.$id == \Package.$id, method: .inner,
                   join: \Package.$id == \Repository.$package.$id, method: .inner)
            .filter(Repository.self, \.$owner, .custom("ilike"), owner)
            .filter(Repository.self, \.$name, .custom("ilike"), repository)
            .filter(\Version.$reference == reference)
            .filter(\Version.$docArchives != nil)
            .field(Version.self, \.$docArchives)
            .first()
            .flatMap { $0.model.docArchives?.first?.name }
```

The `reference`s here are `Reference`s and even with an overloaded `Equatable` that applies `pathEncoded` on both sides this won't match (because under the hoods that's a `JSONB` match in Postgres).

This does not affect the documentation picker but it would affect documentation links displaying in case it's the only doc set.

That's why it doesn't affect SectionKit at the moment - the release version docs take care of the doc link showing up and then the picker populates simply via the reference names.

This is probably not fixable in a reasonable manner.

**Comment by finestructure** [comment]
Oh wait, `/owner/package/documentation` does not hit `DocumentationTarget.query`, so that might work after all.
