### ISSUE TITLE
Xcode version doesn't match one being used

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#2304]
I was looking through logs, and I noticed that the UI specifically calls out "Xcode 14.0", but Xcode 14.1 was actually being used.

<img width="882" alt="Screenshot 2023-03-21 at 12 09 07 PM" src="https://user-images.githubusercontent.com/85322/226670180-ba77ecbc-6340-4fec-99d8-e24d29c2b356.png">

This is minor, but I thought I'd report it just in case.

**Comment by finestructure** [comment]
Thanks Matt, I noticed that as well just yesterday :) Will address this when switching to Xcode 14.2, which is overdue as well.
