### ISSUE TITLE
Add Xcode 14.3 / Swift 5.8

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2306]
# Add a new Swift version (major or minor)

This guide assumes that an older Swift version is removed when adding a new one. This makes the process less cumbersome, because updating the test expectations in the Server package (of which there are a number) is easier if one just shuffles Swift version numbers around without having to add and remove versions separately.

## Update SPIManifest

Preconditions: None.

This can be done at any time. It only takes effect once the adopting packages (Server and Builder) update to this version.

- [x] Update [SPIManifest](https://github.com/SwiftPackageIndex/SPIManifest)
- [x] Tag new release

Example change: https://github.com/SwiftPackageIndex/SPIManifest/pull/28/files

## Update setup-swift GH action

Preconditions: Swift 5.8 available (Xcode and Ubuntu release)

- [x] Update setup-swift GH action
- [x] Rebase to latest upstream changes
- [x] Upstream the change https://github.com/swift-actions/setup-swift/pull/549

Example change: https://github.com/SwiftPackageIndex/setup-swift/pull/1/files

## Update PackageList

Preconditions:
- new Swift docker image available (alternatively, use a nightly toolchain)
- step `Update setup-swift GH action`

- [x] Update [PackageList](https://github.com/SwiftPackageIndex/PackageList)
- [x] Merge https://github.com/SwiftPackageIndex/PackageList/pull/3797

Example change: https://github.com/SwiftPackageIndex/PackageList/pull/3797/files

## Update PackageList-Validator

Preconditions:
- new Swift docker image available (automatically ensured by package CI)
- setp `Update setup-swift GH action`

This ensures via the CI build that the `validator` binary which is built in the `PackageList` repository can be built successfully with the latest Swift version.

- [x] Update [PackageList-Validator](https://github.com/SwiftPackageIndex/PackageList-Validator)
- [x] Merge https://github.com/SwiftPackageIndex/PackageList-Validator/pull/41

Example change: https://github.com/SwiftPackageIndex/PackageList-Validator/pull/41/files

## Update spi-images

Preconditions: new Swift docker image available (automatically ensured by package CI)

The images don't need to be tagged, as they are automatically picked up via their `.../spi-images:basic-5.8-latest` tag.

- [x] Update the Swift versions in the image build matrix of [spi-images](https://gitlab.com/finestructure/spi-images)
- [x] Merge https://gitlab.com/finestructure/spi-images/-/merge_requests/3

Example change: https://gitlab.com/finestructure/spi-images/-/merge_requests/3/diffs

## Update builder machines

Preconditions: new Xcode version available

- [x] Install the Xcode version on all macOS builders
- [x] Set a runner tag for the new version `swift-x.y` in [builder CI/DC](https://gitlab.com/finestructure/swiftpackageindex-builder/-/settings/ci_cd)

## Update Builder

Preconditions:
- step `Update builder machines`
- step `Update spi-images`

- [x] Update to new SPIManifest version and address all issues arising from non-exhaustive `switch` statements.
- [x] Update `Makefile` to build and test with new Xcode version
- [x] Update `.gitlab-ci-builder.yml`: add/remove `build <platform> <swift-version>` blocks.
- [x] Update `.gitlab-ci-testmatrix.yml`: add/remove new `test <platform> <swift-version>` jobs
- [x] Merge https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/196

Example change: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/196/diffs

## Update spi-base

Preconditions: new Swift docker image available (automatically ensured by package CI)

- [x] Update spi-base
- [x] Merge https://gitlab.com/finestructure/spi-base/-/merge_requests/12
- [x] Tag new version (as `0.10.0`)

Example change: https://gitlab.com/finestructure/spi-base/-/merge_requests/12/diffs

## Update Server

Preconditions:
- step `Update Builder`
- step `Update spi-base`

- [x] Update `SPIManifest` dependency
- [x] Update spi-base to newly tagged version
- [x] Update `SwiftVersion+Build.swift` and adjust to changes
- [x] Update `PackageShow.Model.SwiftVersionResults` and adjust to changes
- [x] Ensure any new [`SupportedPlatform`](https://github.com/apple/swift-package-manager/blob/main/Sources/PackageDescription/SupportedPlatforms.swift) keys are added to our matching `Manifest.Platform.Name` enum so we don’t fail to decode package manifests that use them. (See [issue 1441](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1441) for details.)
- [x] Merge https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/2313
- [x] set `BUILD_TRIGGER_LATEST_SWIFT_VERSION_DOWNSCALING` to 0.2
- [x] Deploy

Example change: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/2313/files

## Delete old Swift version builds

Preconditions: New server (one that doesn't trigger the Swift version to be deleted) has been deployed

Nothing needs to be done with respect to database content when adding a new version.

When removing Swift versions, it's important to remove its builds from the `builds` table, because the total count of builds per version is used as a trigger signal. (See https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1267#issuecomment-975379966 for details.)

- [x] Delete outdated builds
  - [x] dev
  - [x] prod

Example SQL:

```sql
delete
from builds
where
swift_version->'major' = '5'
and swift_version->'minor' = '4'
```

This should be run once the new Server has been deployed. Running it too early will lead to the deleted versions being triggered again. It's harmless but wastes build resources.

Deleting the records too long after deployment will inhibit triggering of the new Swift versions, because the presence of the old records will make the build result set appear to be complete. This is also harmless, as these will then be triggered once the deletion has happened.

## Post deployment

Preconditions: all the above steps have been completed, not time critical

- [x] Remove obsolete runner tag `swift-x.y` in [builder CI/DC](https://gitlab.com/finestructure/swiftpackageindex-builder/-/settings/ci_cd)
- [ ] Change back to `swift-actions/setup-swift` after Swift version change has been upstreamed
  - [ ] PackageList
  - [ ] PackageList-Validator

**Comment by daveverwer** [comment]
Either as part of this or as a separate stage afterwards, we can remove Swift 5.4, which would free up mb3 to become a Ventura build machine and mean we only have to maintain two different macOS versions rather than three.

**Comment by finestructure** [comment]
We should do this while adding 5.8. It makes adjusting all the test expectations easier when we're just shuffling them around. Otherwise we'll have to do considerable structural changes twice.

**Comment by ahmdyasser** [comment]
@finestructure Can I work on that?

**Comment by finestructure** [comment]
Thanks for your offer to help out with this one, @ahmdyasser!

This is probably one of the fiddliest things we do twice a year and it has to be me who does it, I'm afraid 😅

However, we do still have a couple of [good first issues](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that might be a great way to contribute. Would one of those interest you?

**Comment by finestructure** [comment]
Swift 5.8 processing is under way. Remaining todos tracked here: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2323
