### ISSUE TITLE
500+ packages not ingested

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#232]
As of this morning more than 500 packages have not been ingested, i.e.

```
select * from packages where status is null;
```

returns 536 records. They have a weird set of timestamps: All packages except one have been created and updated between

2020-05-30 13:07:00.9508+00
and
2020-05-30 13:07:01.033275+00

The outlier has been created/updated on
2020-05-30 21:34:12.399723+00

**Comment by finestructure** [comment]
- The ingestor is running and processing records
- I've copied the prod db and ingested one of the affected packages locally without issues (via `--id` flag)

Current best guess is that the candidate selection doesn't pick them up for some reason.

**Comment by daveverwer** [comment]
Well spotted! Hope it's an easy fix. 🤞

**Comment by finestructure** [comment]
Can reproduce locally. The issue is that the selection clause

```
ORDER BY status!='ok', updated_at asc
```

leads to packages with `status = null` to be last in the list. This may have been a problem before but I suspect it only surfaced because we dialled back the processing turnaround. We may now get packages up for reprocessing before we get through the queue. This is def something I want to add stats for - to see that every package gets visited.

The fix is likely as simple as

```
ORDER BY status!='ok' desc, updated_at asc
```

Before testing that I want to move prod to its own `GITHUB_TOKEN` though.

**Comment by finestructure** [comment]
Actually, there was a reason for sorting `status!='ok'` like that: make sure failed packages don't clog up the candidate pipeline. This might be taken care of the update time though. In any case, the candidate selection should meet these criteria:

- generally process in order of least recently updated first
- make sure new packages go to the front
- make sure continuously failing packages can't clog up the front of the queue, such that we end up churning on the same set of packages without moving through the queue

**Comment by finestructure** [comment]
Found this test

```
    func test_fetchCandidates_ingestion_prefer_ok() throws {
        // make sure records with status != .ok go to the end (to avoid blocking good
        // records)
        // (reonciliation does not currently actually report back any status != ok but
        // we'll account for it doing so at no harm potentially in the future.)
```

That didn't age well 🤣

**Comment by finestructure** [comment]
Regarding those three criteria: In my upcoming PR I've changed the query to fulfill the first two: `status IS NULL` come first, then FIFO. The third one I'm not so sure we want/need it anymore.

Since packages should be updated they won't be able to clog up the queue, because they'll be moved to the back after processing, even if they keep failing.

One issue I see with new packages currently (and previously): They will only be preferred by the ingestion stage. After ingestion, they won't have `status IS NULL` anymore and therefore end at the back of the analysis queue. It'll get picked up eventually but I think it'd be nicer if it came to the front.

I think we should introduce a status `new` that we assign and handle instead of "abusing" `NULL` (but in a sepatate issue, not this bug fix).

What do you think?

**Comment by daveverwer** [comment]
Yep, we discussed this on the call. We'll pay attention to bad packages in produdction, and if new statuses are needed we can add them at that point.
