### ISSUE TITLE
Pluralisation for number of stars on Package pages

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2326]
Support proper pluralisation for the number of stars on the package page:

<img width="210" alt="Screenshot 2023-04-03 at 14 41 02@2x" src="https://user-images.githubusercontent.com/5180/229527386-508fd587-842b-41df-bbdc-f4982e8aa42b.png">

I'm *sure* we did this 😬

**Comment by finestructure** [comment]
Just give it a star, Dave
