### ISSUE TITLE
Google favicon?

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2327]
I just noticed that we don't show our favicon on Google. Perhaps a format issue?

<img width="1302" alt="CleanShot 2023-04-04 at 08 52 03@2x" src="https://user-images.githubusercontent.com/65520/229712383-ea8268f5-e086-48c4-ac1c-4e359e4750a9.png">

**Comment by daveverwer** [comment]
Might have been a temporary glitch. Are you still seeing the problem @finestructure? I see this:

<img width="686" alt="Screenshot 2023-07-27 at 09 58 41@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/54dc43d8-9696-4581-aec6-541c77fe820f">
