### ISSUE TITLE
Add `SPI_BUILD` and `SPI_GENERATE_DOCS` env variables to builder

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2336]
Motivated by #2307 and #2330

**Comment by hassila** [comment]
Thanks! Will give it a spin!

**Comment by hassila** [comment]
Ok, I have played with this bit now but it doesn't seem to work for me:

https://swiftpackageindex.com/builds/C48613DD-906C-40AF-A2F0-CA2418103621

I've tested it locally by setting SPI_BUILD and will print a warning if it is disabled in an SPI build:

```bash
hassila@max ~/G/package-benchmark (fix-spi)> SPI_BUILD=1 swift build
warning: 'package-benchmark': Building for SPI@macOS, disabling Jemalloc
Building for debugging...
[54/54] Linking BenchmarkTool
Build complete! (10.49s)
hassila@max ~/G/package-benchmark (fix-spi)> SPI_BUILD=0 swift build
Building for debugging...
[58/58] Linking BenchmarkTool
Build complete! (10.17s)
hassila@max ~/G/package-benchmark (fix-spi)> 
```

**Comment by hassila** [comment]
Ping @finestructure

**Comment by hassila** [comment]
https://github.com/ordo-one/package-benchmark/blob/d98ed5a8a861367ea7959f5ff126865dc2bdf7ec/Package.swift#L122

**Comment by finestructure** [comment]
Well, that was hilariously silly. When I implemented this I was too lazy to set up a whole test package for an integration test, which of course meant I didn't notice that I'd added the env variables before our env allow list filter which didn't include them 🤦‍♂️

I've now used your repo as a test and it's passing!

Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/203 and deployed

**Comment by finestructure** [comment]
I've re-triggered your builds and they passed now:

<img width="275" alt="CleanShot 2023-04-18 at 20 20 16@2x" src="https://user-images.githubusercontent.com/65520/232868393-db637144-ef8b-4ddc-97b7-211e65e33dfc.png">

**Comment by hassila** [comment]
Super, thank you so much for adding this !
