### ISSUE TITLE
Remove Rollbar error reporting

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2346]
I haven't actually looked at the error reports there in years and they've shut us down god knows when:

<img width="1102" alt="CleanShot 2023-04-18 at 09 44 11@2x" src="https://user-images.githubusercontent.com/65520/232723168-449a4727-bed0-4f94-8228-d281dc8c7b7e.png">

The deployment email are still working so this is only about the error reports apparently.

Not sure if the emails add any value but this is just about removing the broken error reporting api calls for now.

**Comment by finestructure** [comment]
I should add that our internal logging covers most of this use case, so I'm not sure if it's worth trying to get a free account. I didn't use it even when we had it after I'd set up our logging.

**Comment by daveverwer** [comment]
and here I am thinking we just had an app that never ever crashed 😇

Fine by me to shut it down. I did still use the emails as notifications of deployments, but I can switch to the Discord channel instead 👍

**Comment by finestructure** [comment]
This actually highlighted a problem. There seem to be errors that are only reported to rollbar and not to the logs. When rollbar went away we silently lost access to those reports (which isn't that big a deal, because we never checked them).

However, our explicit tests to ensure errors are being reported rely on the rollbar reporting mechanism, giving us a false sense of security.

During my first stab at removing rollbar this became apparent when I tried to assert the errors in the logs.

It's going to be a bit of a bigger task to move this across.
