### ISSUE TITLE
swift-dependencies-additions docs are blank

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2353]
Not sure yet if it's a package issue (with its docs) or a generation issue.

https://swiftpackageindex.com/tgrapperon/swift-dependencies-additions/documentation

<img width="1309" alt="CleanShot 2023-04-24 at 09 54 56@2x" src="https://user-images.githubusercontent.com/65520/233934025-9395f820-a878-413e-9727-b970a95f237a.png">

**Comment by tgrapperon** [comment]
Hey Sven, thanks for spotting it. I'm aware of that. `DependenciesAddtions` is mostly an umbrella module, and it doesn't pick the doc that's mostly declared in the individual child modules. I'm not sure if we can do something about it, but my sentiment was that it would suffer the same issues as referencing external modules when writing the documentation. I think that Brandon and Stephen had the same issue with `Dependencies` when it was a sub-module of TCA.

**Comment by finestructure** [comment]
I think what'd be neat is to list out the available dependencies in a markdown docs file and make that the landing page.

There might also be a way to use the new extension doc support via a flag. I'm going to poke around a bit!

**Comment by tgrapperon** [comment]
Thanks! In any case, Xcode does a better job at it. I think it does it by itself using all the workspace's dependencies.
<img width="265" alt="Screenshot 2023-04-24 at 20 51 18" src="https://user-images.githubusercontent.com/35562418/233988414-a6849e72-b4dc-416f-9fbe-47eb979b7a1b.png">
Feel free to experiment with `swift-dependencies-additions`, I'll make any change required to make it work!
I also just spotted that I have a bunch of broken overload references. I'll fix them ASAP.

**Comment by finestructure** [comment]
Yes, that's what I meant by "the new extension doc support". This should be possible via the `--include-extended-types` opt-in parameter. We've recently added support for custom doc generation parameters but it doesn't seem to be working yet :(

**Comment by tgrapperon** [comment]
I got it partially working, in the sense that it generates the documentation for `LoggerDependency` where most of the doc lies in some `Logger` extension. Currently, Xcode doesn't generate anything for this module.

But it doesn't work for `DependenciesAdditions`, which consists in one file with a sequence of exported imports:
```swift
@_exported import AccessibilityDependency
@_exported import ApplicationDependency
@_exported import AssertionDependency
@_exported import BundleDependency
…
```
So I guess the flag is needed for a few dependencies here (maybe a new option for spi.yml?), but this is not the solution to the "dependencies of dependencies" problem which I think is not soluble in all generality (where to stop?).
That being said, the library is quite exotic in this area. I can probably define a list of modules in `spi.yml` (or a markdown file as you proposed) to automatically build them and generate a toc/frontmatter.

**Comment by finestructure** [comment]
> maybe a new option for spi.yml?

In theory that should be our new `custom_documentation_parameters:` key – but unfortunately it doesn't seem to be working correctly yet: https://swift-open-source.slack.com/archives/C04PCMXMBD0/p1682338242103749?thread_ts=1679643396.399739&cid=C04PCMXMBD0
