### ISSUE TITLE
It says Sentry dont support WatchOS

### ISSUE THREAD

**Issue by brustolin** [SwiftPackageIndex/SwiftPackageIndex-Server#2374]
**Which package(s) are showing incorrect data?**

https://swiftpackageindex.com/getsentry/sentry-cocoa

**Please explain what data is incorrect and what you expected to see**

It shows that watchOS is not supported for Sentry 8.6.0

I tried the build command at https://swiftpackageindex.com/builds/E1EF3DF3-12F5-481A-80CA-88A4B684AC8D
for the package, and at first it did not worked because the `-scheme` was `Sentry-Package` when it should only by `Sentry` (which does not seem to be a problem for SPI), but by changing the scheme everything works fine.

**Comment by finestructure** [comment]
Thanks for the report, @brustolin ! We'll need a hint to discover the correct scheme in this case. I've opened a PR to add the required setting here: https://github.com/finestructure/sentry-cocoa/pull/1

**Comment by finestructure** [comment]
Hold on, wrong PR. Will update in a sec.

**Comment by finestructure** [comment]
https://github.com/getsentry/sentry-cocoa/pull/3006
