### ISSUE TITLE
Incorrect Build Data for Builds in Package

### ISSUE THREAD

**Issue by matteofontana-app** [SwiftPackageIndex/SwiftPackageIndex-Server#2383]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/matteofontana-app/OneFingerRotation

**Please explain what data is incorrect and what you expected to see**

I noticed some errors in the compatibility section of the package, first of all I made some tests with it personally and the package works with Swift 5.6, 5.7 and 5.8 (Not 5.5, this is shown correctly), also, the package is compatible also with macOS and watchOS as of today with some fixed bugs, can you please update it or is is an automatic process?

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

I noticed some errors in the compatibility section of the package, first of all I made some tests with it personally and the package works with Swift 5.6, 5.7 and 5.8 (Not 5.5, this is shown correctly), also, the package is compatible also with macOS and watchOS as of today with some fixed bugs, can you please update it or is is an automatic process?

Please find the builds exhibiting the problem from the "Full Package Compatibility Report" menu item in the side menu and link the build reports here.

- https://swiftpackageindex.com/builds/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
- https://swiftpackageindex.com/builds/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY

Where possible, try and replicate the problem you have found by running the "Build Command" at the top of a build report. This command is what our build servers execute.

**Screenshots**

If they would be helpful, please add screenshots to help explain the problem.

**Additional context**

Is there anything else we might find useful?

**Comment by daveverwer** [comment]
Thanks for the report @matteofontana-app!

> can you please update it or is is an automatic process?

Yep, the index will poll your package for changes and build whatever the default branch is every 24 hours. We also build every tagged release, no matter what the schedule.

It looks like we picked up your changes from main around three hours ago and your package is now showing compatibility as expected.

I'll close this now but please feel free to let us know if you see anything unexpected!
