### ISSUE TITLE
Missing .mailmap support for merging contributors with slightly different names/emails into a single set.

### ISSUE THREAD

**Issue by heckj** [SwiftPackageIndex/SwiftPackageIndex-Server#2393]
**Please describe the bug**

In the realm of finding interesting corner cases, I noticed that in one repository I have commits from multiple devices, and I didn't keep a sanity configuration - so there's different names associated with the commits, even though they're all mine. This is showing up as my name as a contributor twice - because I'm the main person making noise in this repo. (example: https://swiftpackageindex.com/automerge/automerge-swifter)

In other OSS projects, when contributors have multiple email addresses that they want to be consider "a single contributor", there's support for a `.mailmap` file - a good example of this is in Swift-NIO at https://github.com/apple/swift-nio/blob/main/.mailmap. The gist is that this lets contributors normalize their commits to a single person, even though that configuration (emails, etc) may change over time.

I wouldn't expect this to be high on a priority list, but I wanted to raise the idea that `.mailmap` support would be a nice feature for the specific case that I'm hitting - when prominent contributors appear to be replicated.

**What was the expected behaviour?**

Ideally, the header in SPI would read:

> Written by Joseph Heck and 2 other contributors.

instead of 

> Written by Joseph Heck, Joe Heck, and 2 other contributors.

**Screenshots**

<img width="881" alt="Screenshot 2023-05-23 at 5 37 13 PM" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/43388/62ac8792-e8f5-4d31-a6bb-0f481fd7afca">

**What web browser were you using? (if relevant)**

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop/Tablet/Smartphone
- Browser [e.g. Chrome, Safari]
- Version [e.g. Version 15.1]

**Additional context**

Is there anything else we might find useful?

**Comment by finestructure** [comment]
Hi Joe, thanks for the issue report! We're using git commands under the hood to prepare the contributor list, so with a bit of luck this might Just Work™. If I'm not mistaken the repo you pointed to doesn't have a `. mailmap` file. Do you want to try to add one and we can see what happens?

**Comment by heckj** [comment]
Absolutely! I didn't think to just slap one in, but I should have! I'll give that a shot immediately (well, tomorrow) and report on the details after it's had a chance to flow through the pipes.

**Comment by daveverwer** [comment]
The `mailmap` is a smart idea, and I bet it will work.

But also, that field can be overridden to say whatever you'd like it to say in the manifest: https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.17.2/documentation/spimanifest/manifest/metadata-swift.struct/authors

What is lacking there is documentation. Once we know whether the `mailmap` works, I'll add documentation for both. Tracked in #2394

**Comment by heckj** [comment]
Yep, totally solved it. Thanks @finestructure
