### ISSUE TITLE
Timeout on linux

### ISSUE THREAD

**Issue by brennobemoura** [SwiftPackageIndex/SwiftPackageIndex-Server#2406]
**Please describe the bug**

The Linux build consistently encounters timeout issues. I noticed similar problems being discussed here recently, but currently, other packages are not experiencing this issue. It appears there might be a problem with the library, but I'm unable to identify it.

Fortunately, the library has a Github Actions workflow in place for compiling and testing on Linux (Ubuntu latest), which is functioning successfully.

**Explain the steps needed to reproduce the bug**

1. Navigate to RequestDL package
2. Click on Full Build Results
3. See the timeout message for Linux build

**What was the expected behaviour?**

Swift Package Index successfully build the package for linux.

**Screenshots**

If applicable, please add screenshots to help explain your problem.

**What web browser were you using? (if relevant)**

<img width="877" alt="Captura de Tela 2023-05-29 às 18 37 48" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/37243584/ed9cb3ec-d052-4a17-bd05-c9a9cec0c89f">

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop
- Browser Safari
- Version Version 16.5

**Additional context**

Is there anything else we might find useful?

I'm not sure what happened, as the build was functioning properly before I made some changes. If there are any issues in the code, the build timeout should provide us with the console output, which can be helpful for debugging.

**Comment by finestructure** [comment]
Thanks for the report, @brennobemoura . I've manually re-triggered the build to get a little more detail. I looks like the build is doing ok but our builder hangs after it's completed the build:

```
@preconcurrency 
[1153/1153] Compiling RequestDL Task.swift
/host/spi-builder-workspace/Sources/RequestDL/Tasks/Sources/Raw Task/Upload/Models/ResponseHead.swift:89:16: warning: stored property 'url' of 'Sendable'-conforming struct 'ResponseHead' has non-sendable type 'URL?'
    public let url: URL?
               ^
Foundation.URL:1:15: note: struct 'URL' does not conform to the 'Sendable' protocol
public struct URL : ReferenceConvertible, Equatable {
              ^
/host/spi-builder-workspace/Sources/RequestDL/Tasks/Sources/Raw Task/Upload/Models/ResponseHead.swift:5:1: remark: add '@preconcurrency' to suppress 'Sendable'-related warnings from module 'Foundation'
import Foundation
^
@preconcurrency 
Build complete! (77.17s)
```

It then sits there until it gets killed after 10m due to our build timeout.

Linux builds are pretty difficult to debug for the moment. It would help tremendously if you recalled which was the last version that went through ok. Perhaps the code diff could give us a hint as to what's going on here.

**Comment by brennobemoura** [comment]
I don't have the specific commit details, but I remember that this error started happening after I implemented the Sendable functionality across all objects in the library. 

I have just fixed the warnings that were being generated by Swift. I believe it may be related to the timeout. I will wait for the next build to see if the issue has been resolved. 🤞🏻

Thank you for bringing this to my attention! I had forgotten to check that.

**Comment by brennobemoura** [comment]
The problem was fixed 👏🏻

Thank you so much @finestructure

**Comment by finestructure** [comment]
Oh, that's great news, glad it's working now. Although I have to admit I'm puzzled why this was failing in the first place!

I managed to reproduce the problem locally yesterday and I could see the build container exiting after the build finished. However, the controlling container never resumed its work afterwards. It's unclear to me how/why that would happen, or how error messages would be the cause. Really bizarre.

I was at a loss at what else to try yesterday, so I'm quite relieved that it's been resolved :)
