### ISSUE TITLE
Set up a search and package smoke test

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#242]
- Query for some common terms and check results
- hit a few popular packages
- schedule a run after deployment and regularly

**Comment by finestructure** [comment]
I've just run a full test against all 2470 fully ingested packages in the index locally.

Interesting fact: we've got one package that takes 1.1s to load, and that's 

http://173.255.229.82:8080/swift-aws/aws-sdk-swift

I suspect it's because it has - get this - 224 libraries 🤪

<img width="706" alt="Screenshot 2020-06-03 at 15 59 41" src="https://user-images.githubusercontent.com/65520/83645984-61659e00-a5b3-11ea-826b-e5af7dcf251e.png">

Might be a nice one for our announcement stats.

**Comment by finestructure** [comment]
It could go something like this: Of course an Amazon swift package would have 224 libraries - one per service!

**Comment by daveverwer** [comment]
Ah yes, I was aware of this package! There's another one like it (not quite as big) if I remember right.

It also presents interesting limitations if/when we ever decide to list those products out on the package page. Hard to design a UI that is comfortable with 200+ items when 99% of other packages have 1 or 2.
