### ISSUE TITLE
Check if our doc icon moves if a package changes doc gen swift version

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2429]
I.e. what's going to happen here?

![CleanShot 2023-06-13 at 16 31 28@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/58655985-f230-4009-8703-fd260c221f10)

[brightdigit/NPMPublishPlugin/builds ](https://swiftpackageindex.com/brightdigit/NPMPublishPlugin/builds)

**Comment by daveverwer** [comment]
Did you delete the builds @finestructure? I just checked on this and it currently has zero builds:

<img width="638" alt="Screenshot 2023-06-13 at 19 59 43@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/e42f8f94-fe67-4a3a-9197-bc2e2d424d13">

<img width="905" alt="Screenshot 2023-06-13 at 20 00 28@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/15a14405-2390-4ce9-ba13-bdb6494f7ebf">

**Comment by finestructure** [comment]
No, just the one. That's the new default branch revision coming through, deleting them all.

**Comment by finestructure** [comment]
Docs are now on 5.9 for the package. Wasn't quite exactly the test I was looking for but it's good enough.
