### ISSUE TITLE
SectionKit sitemap is giving incorrect URLs

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2462]
https://swiftpackageindex.com/linhay/SectionKit/sitemap.xml shows:

<img width="811" alt="Screenshot 2023-06-22 at 17 01 59@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/0c5ed2d8-4a11-4b73-8de6-1c13b5046018">

Caused by the `/` in the branch name, which we serve as `-`. So:

```
https://swiftpackageindex.com/linhay/SectionKit/feature/2.0.0/documentation/sectionui/sectionarrayresultbuilder/buildexpression(_:)-1f9wx
```

should be:

```
https://swiftpackageindex.com/linhay/SectionKit/feature-2.0.0/documentation/sectionui/sectionarrayresultbuilder/buildexpression(_:)-1f9wx
```

**Comment by finestructure** [comment]
Is this still an issue? I can't see any reference to a branch name in `sitemap.xml`, nor find the string `feature` in what we're currently serving from https://swiftpackageindex.com/linhay/SectionKit/sitemap.xml

Was this fixed when we changed to canonical doc urls without the reference in them?

**Comment by daveverwer** [comment]
Interesting, they've done a release which removes the problem, but the issue is still valid.

The issue is still valid, though, it's related to the branch name. The `feature/2.0.0` should be `feature-2.0.0`. I know we have code somewhere that does that but I hadn't had a chance to look into it yet.
