### ISSUE TITLE
Improving the performance of documented package sitemaps

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2471]
A package’s `linkable-entities.json` can be large and needs parsing every time a sitemap for that package is requested. One [specific package](https://swiftpackageindex.com/GetStream/stream-chat-swiftui/4.33.0/documentation/streamchatswiftui) has a sitemap with over 48,000 URLs, and the sitemap takes almost a minute to generate from a `linkable-entities.json` of over 80Mb.

As discussed, we should pre-process and only upload the list of URLs rather than the full `linkable-entities.json` file.

### In the builder

After documentation generation, we should parse `linkable-entities.json` and extract every `path` from the top-level dictionary. That is all the data we need to build the sitemap. These URLs need no processing and can be stored as a JSON string array or a text file with one URL per line.

`linkable-entities.json` and other `--emit-digest` files can all be deleted before the documentation is uploaded to S3.

### In the server

Rather than fetching and parsing `linkable-entities.json`, we fetch the newly generated file and generate the sitemap from that.

### Other notes

In the final rendered sitemap, we should clip the maximum number of URLs to 49,000 (we need a couple of URLs for the package itself, and the maximum is 50,000. We can clip this either in the builder or as we serve the sitemap, but we need to be able to report on any packages that are going over this limit.

It might be useful to store a count of the total number of documentation pages in the database against the associated `version` record so we can query packages that have large amounts of documentation. This may even be useful as an indicator for package score.

If we don’t want to do that, some kind of reporting of this should be built into this mechanism so we can investigate very large documentation sets.

**Comment by heckj** [comment]
@daveverwer I don't think you're doing the same with linkable entities that I am (deriving symbols for curation), but a tidbit worth knowing is that the symbols in Swift 5.9 changed - what's in the linkable entity is no longer the identical format to the symbols. They're still the external URL link pieces, but the internal references now use the full suite of unicode characters (so `<=` used to be converted to `_=`, but with Swift 5.9+, the symbol in the docs is `<=`).

**Comment by daveverwer** [comment]
> @daveverwer I don't think you're doing the same with linkable entities that I am (deriving symbols for curation), but a tidbit worth knowing is that the symbols in Swift 5.9 changed - what's in the linkable entity is no longer the identical format to the symbols. They're still the external URL link pieces, but the internal references now use the full suite of unicode characters (so `<=` used to be converted to `_=`, but with Swift 5.9+, the symbol in the docs is `<=`).

That's really good to know, thanks for the heads up, Joe.

I think we should be fine as long as `linkable-entities.json` contains `path` entries that map to the same URLs as the documentation generated at the same time. We are using it to get a catalogue of the documentation paths to the documentation generated at the same time as `linkable-entities.json`. I *think* what you're implying is that there could be incompatible paths if we were trying to mix and match them from documentation generated with previous versions of Swift?

**Comment by heckj** [comment]
>  I think what you're implying is that there could be incompatible paths if we were trying to mix and match them from documentation generated with previous versions of Swift?

The URL links remain consistent - it's only the "internal symbols" that you use when creating the markdown that's undergoing this kind of transition. I just happened to have used the source - which was really meant more for how you're using - in a way that happened to work earlier, but doesn't so much going forward.

**Comment by finestructure** [comment]
> One [specific package](https://swiftpackageindex.com/GetStream/stream-chat-swiftui/4.33.0/documentation/streamchatswiftui) has a sitemap with over 48,000 URLs, and the sitemap takes almost a minute to generate from a `linkable-entities.json` of over 80Mb.

Just a note on the performance concerns we discussed around decoding this large JSON file.

I've tested decoding the same `[LinkableEntitiy].self` we've defined in the server:

```swift
struct LinkableEntity: Decodable {
    var path: String
}
```

from this file and the smaller one from swift-argument-parser in a docker container on `d1`, which is a 2 core `Standard B2ms` vs prod's `Standard B4ms` (probably the same cores, just two more) and the 80MB file only takes 2.5 to decode on that machine. It's in a docker container, just like our production process, and I ran it with optimisations.

So the JSON decoding isn't a bottleneck we need to worry about. However, stripping out the useless info is definitely helpful to reduce the overall file size that we store and then handle downstream.

```
argument-parser-linkable-entities.json size: 0.234195 MB
decode [LinkableEntity]: 0.009093046188354492s
count: 243
stream-chat-linkable-entities.json size: 82.773497 MB
decode [LinkableEntity]: 2.505120038986206s
count: 48312
```

So whatever takes a minute to generate the sitemap, it's not the decoding of the JSON file.

**Comment by finestructure** [comment]
For reference:

```swift
// Run as follows:
// docker run --rm -v $PWD:/host -w /host swift:5.8-focal swiftc -O -static-stdlib -static-executable test-linkable.swift && ./test-linkable
import Foundation

func timed<T>(_ label: String, _ block: () throws -> T) rethrows -> T {
    let start = Date()
    let res = try block()
    print("\(label): \(Date().timeIntervalSince(start))s")
    return res
}

struct LinkableEntity: Decodable {
    var path: String
}

for fname in ["argument-parser-linkable-entities.json", "stream-chat-linkable-entities.json"] {
    let data = try Data(contentsOf: .init(fileURLWithPath: fname))
    print(fname, "size:", Double(data.count) / 1_000_000.0, "MB")
    let entities = try timed("decode [LinkableEntity]") {
        return try JSONDecoder().decode([LinkableEntity].self, from: data)
    }
    print("count: \(entities.count)")
}
```

**Comment by finestructure** [comment]
This [builder MR](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/212) adds a new file `linkable-paths.json` to the doc archive which contains the linkable entities paths (`[String]`) for all targets and is truncated to 49k paths.

The original count is reported back via the doc reporting mechanism (but not yet saved in the db, that's to come).
