### ISSUE TITLE
Badge does not correctly reflect compatibility matrix

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2477]
Package: https://swiftpackageindex.com/allaboutapps/Fetch

![CleanShot 2023-07-03 at 12 04 29@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/1f8f3dde-08a5-483f-9872-9dbf88539a41)

I first spotted this a couple of days ago and it's still like this, well outside the badge caching interval.

**Comment by finestructure** [comment]
Swift versions are also off. Other packages look ok, this might be package specific.

**Comment by mbuchetics** [comment]
thanks for noticing!

**Comment by daveverwer** [comment]
Now showing fixed 🎉

![Screenshot 2023-07-04 at 09 29 11@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/5433be15-771e-4e9c-9860-ea88020b50d1)
