### ISSUE TITLE
Runestone doc build started failing

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2504]
Our doc smoke test started failing yesterday. [Runestone](https://swiftpackageindex.com/simonbs/Runestone) has lost its doc build link.

It's unclear what exactly is happening. The error during the doc build phase is

```
There are no schemes in workspace "Runestone".
```

which I can reproduce in the latest release 0.3.1. The last version we've managed to generate docs for was 0.3.0. It's unclear to me why we can't detect the scheme anymore.

Simon is actually referencing [his own generated docs](https://docs.runestone.app/) in his Readme, so perhaps the easiest solution is simply to remove our generation from the SPI manifest file and link to his external docs. I'll open a PR over there to discuss.

In the meantime I'll remove Runestone from the doc smoke test to silence the failures.

**Comment by finestructure** [comment]
For reference, the command we run to detect schemes is

```
env DEVELOPER_DIR="/Applications/Xcode-14.3.1.app" xcrun xcodebuild -list -destination "generic/platform=ios"
```

**Comment by heckj** [comment]
Out of random curiosity, I just did a walk through the recent tags to checkout what I found:

(using `xcodebuild -list`)
- `0.3.0` - couldn't find scheme due to complaint about a invalid local location for the library treesitter
- `0.3.1` - found Runestone
- `0.3.2` - found Runestone

Error in 0.3.0:
```
xcodebuild: error: Could not resolve package dependencies:
  invalid custom path 'tree-sitter/lib' for target 'TreeSitter'
```

**Comment by finestructure** [comment]
Thanks for taking a look, Joe! The error is an old friend and it's an odd one: this fails on first attempt and `docbuild` simply needs to be run again 🫠

We've had the same issue with (some) builds a while back.

```
❯ git clone https://github.com/simonbs/Runestone checkout && cd Runestone
❯ env DEVELOPER_DIR="/Applications/Xcode-15.0.0-Beta.4.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" docbuild OTHER_DOCC_FLAGS=--emit-digest -scheme Runestone -destination 'generic/platform=ios'
→ error complaining about a missing scheme
❯ env DEVELOPER_DIR="/Applications/Xcode-15.0.0-Beta.4.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" docbuild OTHER_DOCC_FLAGS=--emit-digest -scheme Runestone -destination 'generic/platform=ios'
→ success
```

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/216

Requires https://github.com/simonbs/Runestone/pull/307 to be merged

**Comment by finestructure** [comment]
Docs are back now.
