### ISSUE TITLE
Check performance and potential optimisations of products/targets queries

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2534]
Related to the new Package page query in #2531.

**Comment by finestructure** [comment]
We can't actually merge the two `Joined4` queries that collect the products and targets from their respective tables - or at least not in a way that would help. If we make it a `Joined5` we'd blow up the result set to N x M just to save a query.

For example, Soto has 348 products and 349 targets and therefore the `Joined5` has 121,452 rows. Of course, Soto is the extreme but it's also just simpler in terms of implementation. We're not gaining anything here.
