### ISSUE TITLE
Wrong package name in "Use this package" popover

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2541]
![CleanShot 2023-08-08 at 08 43 17@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/6d0b1145-4047-4c35-a6d8-342ac3da9e22)

Should be `automerge-swift`:

```
❯ swift package resolve
error: 'automerge-test': unknown package 'Automerge' in dependencies of target 'Automerge-test'; valid packages are: 'automerge-swift'
```

**Comment by daveverwer** [comment]
Is this something I did incorrectly with the data, or an underlying problem? I'm happy to fix if it's something I did.

**Comment by finestructure** [comment]
No, it's a misconception on what we take as the package name - or rather package id - in this context. It's actually unlikely that we can properly fix it, as far as I can tell at this moment.

**Comment by heckj** [comment]
Oy vey - that's my mess. Is there anything I can do (spi.yml?) to make this better for all?

**Comment by finestructure** [comment]
It's really not - it's our and SwiftPM's mess 🙂

**Comment by finestructure** [comment]
Ok, this is pretty unfortunate. [The docs](https://developer.apple.com/documentation/packagedescription/target/dependency/product(name:package:)-2nako) actually say `.product(...)` is referencing the package name:

```
Creates a target dependency on a product from a package dependency.

Parameters:
  name: The name of the product.
  package: The name of the package.
```

What it expects thought seems to be a package id as it exists in `Package.resolved`, for example:

```json
{
  "pins" : [
    {
      "identity" : "automerge-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/automerge/automerge-swift.git",
      "state" : {
        "revision" : "c50c4b66a9544dd9526f70c987c4fafd16e96886",
        "version" : "0.5.0-alpha3"
      }
    }
  ],
  "version" : 2
}
```

We could try and derive the id from the package url but the safer option would be to get it from SwiftPM.

**Comment by finestructure** [comment]
So SwiftPM constructs this in [`PackageIndentity.swift`](https://github.com/apple/swift-package-manager/blob/main/Sources/PackageModel/PackageIdentity.swift#L290):

```swift
    public static func computeDefaultName(fromLocation url: String) -> String {
        #if os(Windows)
        let isSeparator : (Character) -> Bool = { $0 == "/" || $0 == "\\" }
        #else
        let isSeparator : (Character) -> Bool = { $0 == "/" }
        #endif

        // Get the last path component of the URL.
        // Drop the last character in case it's a trailing slash.
        var endIndex = url.endIndex
        if let lastCharacter = url.last, isSeparator(lastCharacter) {
            endIndex = url.index(before: endIndex)
        }

        let separatorIndex = url[..<endIndex].lastIndex(where: isSeparator)
        let startIndex = separatorIndex.map { url.index(after: $0) } ?? url.startIndex
        var lastComponent = url[startIndex..<endIndex]

        // Strip `.git` suffix if present.
        if lastComponent.hasSuffix(".git") {
            lastComponent = lastComponent.dropLast(4)
        }

        return String(lastComponent)
    }
```

We should just use this directly, perhaps even via `PackageIndentity` itself (we're already depending on SwiftPM) rather than fiddle with importing it from some package description/resolved.

**Comment by finestructure** [comment]
This is also a fairly common problem. Running

```sql
select package_name, p.repo
from versions v
join (
	select id, url[array_upper(url, 1)] as repo 
    from (select id, string_to_array(url, '/') as url from packages) t
) p on v.package_id = p.id
where latest = 'default_branch'
and p.repo not ilike package_name || '.git'
```

shows 1186 packages where the package name is very likely different from this SwiftPM package identifier.
