### ISSUE TITLE
Keyword Count Incorrect

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#2549]
![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/15193942/1b43acd7-1fab-4949-88be-03e9e6359455)

Looks like keyword counts are currently broken (showing 0 instead of the real number).

https://swiftpackageindex.com/search?query=toast

Works on any search but above is example.

**Comment by finestructure** [comment]
Ah, well spotted, @Sherlouk ! I broke that recently and wanted to see how long it'd take you to notice 😎
