### ISSUE TITLE
kaascevich/Rapid package page not loading

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2577]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/kaascevich/Rapid

**Please explain what data is incorrect and what you expected to see**

![Screenshot 2023-08-22 at 19 20 22@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/c59a0f61-710e-4fe4-a609-9b48babde3b8)

I've run a `xcrun swift package dump-package` and the dump looks fine but haven't done any more investigation yet.

**Comment by daveverwer** [comment]
It's back. I bet this is related to the [versions issue](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2571) we've had today. This is a very rare (unprecedented, even!) issue and should not happen again.

**Comment by daveverwer** [comment]
I just checked in on this again and it's still not showing up. Our sincere apologies, this is an ongoing problem (still being discussed in #2571).

**Comment by finestructure** [comment]
The default branch version flickering should be addressed by #2594

**Comment by finestructure** [comment]
This has been deployed.
