### ISSUE TITLE
Package build results haven't updated (since initial submission?)

### ISSUE THREAD

**Issue by edonv** [SwiftPackageIndex/SwiftPackageIndex-Server#2583]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/edonv/SwiftUIPHPicker

**Please explain what data is incorrect and what you expected to see**

Give as much detail as possible.

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

Please find the builds exhibiting the problem from the "Full Package Compatibility Report" menu item in the side menu and link the build reports here.

- https://swiftpackageindex.com/edonv/SwiftUIPHPicker/builds (no builds)

**Screenshots**

N/A

**Additional context**

It says that there are 0 completed builds, and I haven't seen the badges say anything other than `pending` yet.

**Comment by daveverwer** [comment]
Hi @edonv, and apologies for the issue you're seeing. The good news is that it's nothing to do with your package specifically. The bad news is that we have an issue this week (#2571) that caused us to need a re-build a significant portion of our build compatibility results. Your builds are still in the queue, and our build machines are working through the backlog as quick as they can.

I'm sorry for the issue, it's unprecendented that we are in this situation and we hope not to be here again! 😬 I'll leave this issue open until your builds have been processed, but there's unfortunately nothing we can do to speed that up.

**Comment by finestructure** [comment]
This should be fixed now, sorry for the inconvenience!
