### ISSUE TITLE
Some targets within a package have incorrect target type

### ISSUE THREAD

**Issue by cyndichin** [SwiftPackageIndex/SwiftPackageIndex-Server#2589]
### Description
There are some targets that have a target type as NULL when it should have a test type.

In the screenshot below, we can see some packages (i.e. https://github.com/0xLeif/Chronicle.git) that have a NULL target type, but the target type for `ChronicleTests` should be test, which can be verified in the [Package.swift](https://github.com/0xLeif/Chronicle/blob/main/Package.swift) file. 

![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/6743397/5ce7d679-b595-41f2-a025-8c211e4f626e)

Query to generate results above:
```
select distinct v.id, v.package_id , v.package_name , v.latest,  p.id, p.url, t.type, t.name
from versions v
inner join targets t  on v.id = t.version_id 
inner join packages p on v.package_id = p.id 
where v.latest = 'default_branch'
order by p.url
```

### Test Steps

1. Run the above query in your DB client.
2. Verify that there exists target types that are NULL, but should be shown as tests

### Additional Context
This bug was discovered after investigating issue #317

**Comment by finestructure** [comment]
The problem is that we only started test target types from a certain point onwards and these versions are older than that. I just ran `re-analyze-versions` locally on this package and the test target is being picked up.

The good news is that we re-analysed almost half of our versions just last week! 😬

I'll kick off a process to re-analyse the other half.

**Comment by finestructure** [comment]
I've completed reprocessing of all affected versions. There are now only 8 targets `where v.latest = 'default_branch' and type is null` (down from over 10k), and these are likely packages that have general processing issues.

**Comment by finestructure** [comment]
For reference:

```
38752ed7-bacc-419d-8226-14848c2e6e4e | e6f418d6-6004-41d4-80df-1ee7162b74db | 2023-07-26 15:51:01.621945+00 | FilesProvider | default_branch | e6f418d6-6004-41d4-80df-1ee7162b74db | https://github.com/amosavian/FileProvider.git |   | FilesProvider
38752ed7-bacc-419d-8226-14848c2e6e4e | e6f418d6-6004-41d4-80df-1ee7162b74db | 2023-07-26 15:51:01.621945+00 | FilesProvider | default_branch | e6f418d6-6004-41d4-80df-1ee7162b74db | https://github.com/amosavian/FileProvider.git |   | FilesProviderTests
96dac2be-13fc-4c7d-81bc-f6b22b29e046 | cb0893f8-50b5-470c-94ef-daf226c8aca1 | 2023-09-18 05:43:54.300018+00 | Quack | default_branch | cb0893f8-50b5-470c-94ef-daf226c8aca1 | https://github.com/cpageler93/quack.git |   | Quack
96dac2be-13fc-4c7d-81bc-f6b22b29e046 | cb0893f8-50b5-470c-94ef-daf226c8aca1 | 2023-09-18 05:43:54.300018+00 | Quack | default_branch | cb0893f8-50b5-470c-94ef-daf226c8aca1 | https://github.com/cpageler93/quack.git |   | QuackUnitTests
60b863c3-b9dc-4dc2-9ce9-ffdf28d99c6a | 62ba6d3a-fde7-4215-b7e9-9c80800d618b | 2023-09-18 09:50:33.772722+00 | CancelForPromiseKit | default_branch | 62ba6d3a-fde7-4215-b7e9-9c80800d618b | https://github.com/dougzilla32/CancelForPromiseKit.git |   | CancelForPromiseKit
60b863c3-b9dc-4dc2-9ce9-ffdf28d99c6a | 62ba6d3a-fde7-4215-b7e9-9c80800d618b | 2023-09-18 09:50:33.772722+00 | CancelForPromiseKit | default_branch | 62ba6d3a-fde7-4215-b7e9-9c80800d618b | https://github.com/dougzilla32/CancelForPromiseKit.git |   | CPKCoreTests
a522967b-2a53-4e90-a79b-cfca322b9314 | d29ac622-5c1c-4b24-a4b1-ec84619f06f6 | 2023-09-18 10:07:20.139639+00 | StellarKit | default_branch | d29ac622-5c1c-4b24-a4b1-ec84619f06f6 | https://github.com/kinecosystem/StellarKit.git |   | StellarErrors
a522967b-2a53-4e90-a79b-cfca322b9314 | d29ac622-5c1c-4b24-a4b1-ec84619f06f6 | 2023-09-18 10:07:20.139639+00 | StellarKit | default_branch | d29ac622-5c1c-4b24-a4b1-ec84619f06f6 | https://github.com/kinecosystem/StellarKit.git |   | StellarKit
```

**Comment by daveverwer** [comment]
Thanks Sven!

I just checked over all of those packages and they are all either archived, or [worse](https://github.com/SwiftPackageIndex/PackageList/pull/5157). Certainly nothing to worry about!
