### ISSUE TITLE
SwiftDataKit missing all version records

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2605]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/fatbobman/SwiftDataKit

**Please explain what data is incorrect and what you expected to see**

I searched for this package on the index and thought it wasn't in the package list, but [it is](https://github.com/SwiftPackageIndex/PackageList/blob/60177a6d47cd78d156d94fff397346f3866fb8b3/packages.json#L1871C4-L1871C49)

<img width="472" alt="Screenshot 2023-09-07 at 13 03 30@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/7e800065-b901-4d3e-b062-36c83093c311">

Looking at the data, it's in `packages`, but the status is set to `no_valid_versions` and there are 0 version records associated with that package ID in `versions`.

<img width="690" alt="Screenshot 2023-09-07 at 13 07 45@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/cd35b2ac-0f3e-4a7b-a8f9-4070a496bd10">

I checked the package out locally and ran a `dump-package` and looked at the tags and git repository and everything looks fine. 

It'll probably recover with another analysis cycle, but it's very odd that it hasn't picked up the `0.1` tagged version since it was tagged 13 hours ago so I wanted to make sure we logged it somewhere, especially after our recent issues.

**Comment by daveverwer** [comment]
5 hours later (so should have been through an analysis cycle) and the status is the same:

<img width="803" alt="Screenshot 2023-09-07 at 18 50 00@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/73a3d7f3-39e6-4107-9b1c-7d6951038522">

The `updated_at` has been updated, but still `no_valid_versions` and still 0 records for it in `versions`.

**Comment by daveverwer** [comment]
I mistakenly tagged this as "Fixed" with #2607 which means this got closed before it's *actually* fixed. Re-openeing until we get it back in the index.

**Comment by finestructure** [comment]
This is now deployed and fixed.

**Comment by Sherlouk** [comment]
@finestructure - looks like all builds are failing or timing out. Is something still awry?
