### ISSUE TITLE
`owner/repo` url edge case with renamed repos

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#261]
There's an edge case regarding the owner/repo urls when a repo changes ownership or is renamed.

When this happens, we update its owner/repo automatically via ingestion, because the Github requests will give us the new owner/name even if we keep polling the old url. However, the package url itself won't change unless we find a way to update it.

This won't break any links but would lead to us using a new url while the package url we expose is still the original one.

It would also mean that any links to us via the old url will 404 after we see the name change.

An ad hoc fix is to delete and re-add the package with the new url. It would probably also work to simply change the package url and re-ingest (but safer to go via the master list).

A way to detect this could be to compare the package url that we get back from our Github metadata call (it is part of the JSON payload) with the current package url.

We should be able to then update `Package.url` or at least report the issue up to Rollbar.

If we really wanted to, we could at this point also populate a redirect table where we keep mappings of old owner/repo pairs to new ones.

**Comment by daveverwer** [comment]
I think the solution to this comes if/when we deprecate the master package list. It's a great point, but not one that we can easily do much about for now. Let's keep an eye on it as we move forward though.

**Comment by finestructure** [comment]
I think we've essentially fixed this via the nightly package list check - closing.
