### ISSUE TITLE
swift-nio documentation: No data available

### ISSUE THREAD

**Issue by tayloraswift** [SwiftPackageIndex/SwiftPackageIndex-Server#2624]
the DocC sidebar for `swift-nio` displays No data available.

https://swiftpackageindex.com/apple/swift-nio/2.58.0/documentation/nio

![Firefox_Screenshot_2023-09-17T22-17-12 473Z](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/2556986/b64e1c64-d7fd-4cdc-b549-c4d726428dd0)

in the firefox web inspector, only one request seems to be failing, `theme-settings.json`, which returns HTML with status code 404.

i first noticed this on ubuntu 22.04 desktop **firefox 117.0.1**, but also got the same behavior on iOS 16.6.1 safari while connected to a different network.

it only seems to affect the page for `NIO`, the other modules (e.g. NIOHTTP1) seem to work normally.

**Comment by finestructure** [comment]
Thanks for the report, @tayloraswift !

The 404 on the theme-settings.json is a red herring, this is just what the top level docs for NIO look like if you look at the NIO target.

You get the same when you run

```
swift package --disable-sandbox preview-documentation -p 8080 --target NIO
```

to view the docs locally:

![CleanShot 2023-09-18 at 09 21 47@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/79aae24e-2ddc-4f0c-b427-08dfb37af23d)

I've mentioned this to the DocC folks when I first noticed this and they confirmed it's an unfortunate result of the NIO target being an empty placeholder target for the documentation overview.

I'm not sure if they're tracking this to display a better empty state for the sidebar.

cc @ethan-kusters @franklinsch

**Comment by finestructure** [comment]
I believe we've done everything we can here. Please reopen if there's indeed something to be done here!
