### ISSUE TITLE
MSSPhoneNumber package page is not rendering

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2655]
https://swiftpackageindex.com/skaik-mo/MSSPhoneNumber package page is not rendering.

![Screenshot 2023-10-03 at 15 54 07@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/d6c2d05c-4106-460e-9d0c-d78b65b2b865)

I've not looked into it yet, just reporting it for now so I don't lose the link.

**Comment by finestructure** [comment]
It's not in the index anymore, it was removed last week: https://github.com/SwiftPackageIndex/PackageList/blob/e38bbdd0dc6633f4cecc50edb46e0428c60e2d98/denylist.json#L47

**Comment by daveverwer** [comment]
Ah yes, I think I even approved that one. It was (of course) still in the RSS feed cached by my feed reader.
