### ISSUE TITLE
Package doesn't show documentation (JDStatusBarNotification)

### ISSUE THREAD

**Issue by calimarkus** [SwiftPackageIndex/SwiftPackageIndex-Server#2681]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/calimarkus/JDStatusBarNotification

**Please explain what data is incorrect and what you expected to see**

- Missing docs.
    - I expected generated docs to be displayed. But there are none.
- Locally generating them from Xcode works.
- Using `xcodebuild docbuild` only works if I navigate into the folder that contains the `xcodeproj` first.
    - I don’t have the `xcodeproj` at the root of my repository, it's located at `/ExampleProject/JDStatusBarNotificationExample.xcodeproj`.
    - Note: It also has a different filename than the package name.
    - Maybe your implementation expects the project to be at the root level? Or at the same level as the Package file? Might that be it?
    - Is it possible to provide the project name / directory manually in the `.spi.yml` maybe?

_PS: I also have the docs hosted through GitHub here: http://calimarkus.github.io/JDStatusBarNotification/documentation/jdstatusbarnotification/_

**Comment by finestructure** [comment]
Thanks for the report and the additional info, @calimarkus !

The [build logs](https://swiftpackageindex.com/builds/18590A2E-394C-44CC-99CF-D7B309416201) indicate success in building the docs but then there's no doc archive found to be uploaded. I suspect that's due to the fact that your doc gen requires the Xcode project.

I'll take a look to see if there's something we can do or propose a change to the project to get the docs up.

**Comment by daveverwer** [comment]
> _PS: I also have the docs hosted through GitHub here: http://calimarkus.github.io/JDStatusBarNotification/documentation/jdstatusbarnotification/_

in the mean time, if you'd like your package to point at your self-hosted documentation, we support that, too.

https://swiftpackageindex.com/swiftpackageindex/spimanifest/documentation/spimanifest/commonusecases#Configure-a-documentation-URL-for-existing-documentation

**Comment by calimarkus** [comment]
Thank you! I merged your PR, so that plus my project file change should solve my current issues.

Some further thoughts:

- It'd be nice if you could specify a custom `xcodeproj` path in the `.spi` config file - to cover similar situations.
- I also wonder if docs generation could work without an Xcode project. As the package file already knows of all relevant sources. Minus the markdown pages to customize the generation. Not sure if there's anything planned on the swift package side of things to annotate it with the additional `.md` files.

**Comment by calimarkus** [comment]
Looks all good now on SPI! I also released a new version, which also is green and has docs. 👌🏼

**Comment by finestructure** [comment]
Great, closing this then, thanks for the follow-up!
