### ISSUE TITLE
Logo SVG is unoptimized

### ISSUE THREAD

**Issue by gwynne** [SwiftPackageIndex/SwiftPackageIndex-Server#2690]
Title kinda says it all. Here is a much smaller, visually identical version (note: this was hand-optimized; it was _not_ run through any automatic tools like `svgo` or what have you):
```svg
<svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><defs><filter id="a" height="110.6%" width="110.6%" x="-5.3%" y="-5.3%"><feOffset dy="3" in="SourceAlpha" result="o"/><feGaussianBlur result="b" stdDeviation="5"/><feColorMatrix result="m" values="0,0,0,0 0,0,0,0 0,0,0,0 0,0,0,0 0,0,.3,0"/><feMerge><feMergeNode in="m"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="b"><stop stop-color="#f88a36"/><stop stop-color="#fd2020" offset="1"/></linearGradient><linearGradient id="c" href="#b" x1="1" x2="0" y2="1"/><linearGradient id="d" href="#c" x1=".5" x2=".5"/><path id="e" d="m70.5,70.5h339v339h-339z"/></defs><g fill="#fdfafa" filter="url(#a)" stroke="url(#c)" stroke-width="11"><use href="#e" transform="matrix(.5.866-.866.5 343.846-71.846)"/><use href="#e" transform="matrix(.866.5-.5.866 168.154-71.846)"/><use href="#e" x="16" y="16"/></g><path d="m312.9,348.5c-61.4,35.55-154.9,2.73-199.9-69.44,26.83,22.4,96.8,52.38,151,18.64-46.27-38.32-92.45-85.2-125.7-135.7,34.22,31.3,88.52,70.82,107.9,82-40.9-43.24-77.36-96.92-75.88-95.43,38.96,40.35,83.1,74.95,129.8,105.8,11.13-28.52,12.75-76.75-24.1-127.4,74.3,45.05,93.9,121.2,79.8,167.1,29.26,36.15,22.86,78.98,18.37,69.98-14.65-26.1-36.4-25.37-61.24-15.56z" fill="url(#d)"/></svg>
```

**Comment by finestructure** [comment]
Very nice, thank you!

Is there perhaps a way to automate this "hand-optimised" process? I'm asking because we have a number of SVGs and we might change them or the logo in the future - so we'd have to be able to redo what you did somehow.

**Comment by daveverwer** [comment]
Thanks for this Gwynne, I'll add integrate it later today.

> Is there perhaps a way to automate this "hand-optimised" process? I'm asking because we have a number of SVGs and we might change them or the logo in the future - so we'd have to be able to redo what you did somehow.

Outside of this logo (and some variations on it) and the sponsor logos, our process for SVGs in the rest of the app is a little different than plain "files on disk", and I do optimise the SVGs as part of that process. I don't do it by hand, I use ImageOptim, but it works well.

I thought I had run the files on disk through optimisation, too, but I must not have.

I'd be curious what your process for hand-optimising is, too.

**Comment by gwynne** [comment]
> > Is there perhaps a way to automate this "hand-optimised" process? I'm asking because we have a number of SVGs and we might change them or the logo in the future - so we'd have to be able to redo what you did somehow.
> ...
> I'd be curious what your process for hand-optimising is, too.

Sorry for the late reply here-

Unfortunately, it's one of those things where "hand-optimized" (sorry, my autocorrect keeps insisting on the US spelling 😒) by definition excludes automation - I more or less literally sit there and stare at the raw XML making little corrections and simplifications as they occur to me. Then I pop it open in Inkscape, grab the node editing tool, and do the same thing - It's a little bizarre; for any given complex path, I usually end up deleting at least 33% - and often as much as 75% - of the individual nodes without any visual impact whatsoever. Then I start seeing how many significant digits I can trim before the rounding error changes the rendering in any way whatsoever, the answer is pretty much always "most of them". Neither the authoring tools nor the optimizer tools are good at finding truly minimal paths - which actually makes a lot of sense once you realize that finding a "truly minimal" path is literally another way of phrasing [the Traveling Salesman problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem). The transformations I perform are _not_ functionally or observably idempotent; the image is not the same one when I'm done, you just aren't seeing the difference because I take shameless advantage of several different inherent limitations of the systems involved:

- Floating-point values have limited precision and suffer unintuitive rounding behaviors
- Even with infinite precision a given display has only so much resolution
- Any given display's gamut can only represent a finite number of discrete colors, in terms of both the technological limitations of the display elements emitting the light in question _and_ of the quantization of the photons themselves (at this juncture, there's another three paragraphs worth of discussion on the quantum mechanics involved for those foolish enough to let me go on, but I'll spare poor Github that much 😆)
- In the same vein, there are both resolution and gamut limits to the differences the human eye can perceive (and then there's the difference between the ability to perceive individual discrete wavelengths (colors) and the ability to recognize any given change in wavelength, but that's a whole 'nother kettle of piranha).

It also helps a lot that there's so much wiggle room built into the syntaxes of XML and CSS, and that the SVG spec makes extremely useful choices of default values for so many things 😁

Last but not least, you probably would not _want_ to try to make my way of hand-optimizing a common practice; one of the major reasons I produce such striking results is I tend to not realize until after the fact that I've been sitting and staring at the same ten lines of XML for 3 or 4 hours... 🤦‍♀️.

**Comment by daveverwer** [comment]
😱

It's a shame it's so much work, but we'll take it until the file is next updated! Integrated with #2698. Thank you @gwynne!
