### ISSUE TITLE
Repos turned private trigger `git clone` password prompt

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#27]
It seems that https://github.com/SwiftyBeaver/AES256CBC.git went private and that messes with the analysis:

```
[ INFO ] cloning https://github.com/SwiftyBeaver/AES256CBC.git to /Users/sas/Projects/SPI-Server/SPI-checkouts/github.com-swiftybeaver-aes256cbc
Username for 'https://github.com': ^C⏎
```

I've tried various incantations of `git -c core.askPass="" clone ...` and `git clone -c credentials.helper= clone ...`, `GIT_ASKPASS` and `SSH_ASKPASS` where not yet, still always getting the prompt.

I thought this might be specific to me running the job on my Mac but it also tripped up the job in the docker container just now.

Need to try and disable the prompt in the docker container, should have more control over the env there.

**Comment by finestructure** [comment]
Another way of dealing with this is not even trying repos that failed the metadata fetch. Still, it might be good to figure this out so we're not caught out if a repo goes private at the wrong time.

**Comment by finestructure** [comment]
Actually, we should be able to simply run `git config ...` for the docker user to suppress. It’s just something I didn’t want to do on my machine.

**Comment by daveverwer** [comment]
Apologies for the slow response.

So if I understand correctly, a `git config` command will prevent this from prompting? Meaning that it'll just fail, and we can then manually remove the package? That seems like a perfect solution if that's how it'll work.
