### ISSUE TITLE
Fix Package Name, thanks.

### ISSUE THREAD

**Issue by William-Weng** [SwiftPackageIndex/SwiftPackageIndex-Server#2703]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/William-Weng/WWSignInWith3rd_Weibo

**Please explain what data is incorrect and what you expected to see**

This SPM name is WWSignInWith3rd+Weibo, thanks.
https://swiftpackageindex.com/William-Weng/WWSignInWith3rd_Weibo

**Screenshots**

![WWSignInWith3rd_Weibo](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/18256962/6681c63b-95cf-460a-b738-df3f92f6994e)

**Comment by daveverwer** [comment]
This will be fixed via https://github.com/William-Weng/WWSignInWith3rd_Weibo/pull/1

It will take a couple of hours to update after that PR is merged, but it will update automatically. Thanks for adding your packages!
