### ISSUE TITLE
Troubleshooting .spi.yml

### ISSUE THREAD

**Issue by DandyLyons** [SwiftPackageIndex/SwiftPackageIndex-Server#2706]
Hello, I'm a fan and user of SPI as well as https://github.com/tgrapperon/swift-dependencies-additions/

I noticed that it has documentation on SPI but it only has the [first page](https://swiftpackageindex.com/tgrapperon/swift-dependencies-additions/1.0.1/documentation/dependenciesadditions). Nothing else. So I raised an [issue](https://github.com/tgrapperon/swift-dependencies-additions/issues/84) on his repo. 

I also forked it and tried to fix his `.spi.yml` but everything looks right according to the SPI [documentation](https://swiftpackageindex.com/SwiftPackageIndex/SPIManifest/1.1.1/documentation/spimanifest). I see that there is an included validation executable, however the link appears to be broken on that documentation page. 

How can I find out more about how to use this validation executable?

**Comment by finestructure** [comment]
Thanks for reporting this, @DandyLyons .

The best way to verify documentation is via the [online checker](https://swiftpackageindex.com/validate-spi-manifest) and Thomas' `.spi.yml` validates ok.

This seems to be an build/doc gen issue. I can see a missing theme-settings.json file being reported in the console when viewing the docs:

<img width="1091" alt="Screenshot 2023-11-12 at 13 55 26" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/51d90240-fd03-4ca9-be24-9baa6cf03493">

I'll look into this, thanks again for the report!

**Comment by finestructure** [comment]
Looks like this is a red herring, `theme-settings.json` is also missing for SemanticVersion for example:

```
[Error] Failed to load resource: the server responded with a status of 404 () (theme-settings.json, line 0)
```

<img width="1011" alt="Screenshot 2023-11-12 at 17 57 24" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/d03bcbf4-174c-4abb-ab8b-b961ab9060d1">

This is new. 0.3.3 for example _has_ a `theme-settings.json` file in the bucket, as does 0.3.4. 0.3.5 is the first release without it. According to our GH releases page, 0.3.4 and 0.3.5 were tagged on the same day. So it's unlikely to be related to the move to 5.9 as the doc generator.

**Comment by finestructure** [comment]
I just wanted to generate the docs locally and I found the command for `DependenciesAdditions` in my shell history. Turns out this is a known issue: 2353. (The situation seems slightly improved but I believe it's still the same underlying issue.)

I'll close this issue then but re-open one regarding the `theme-settings.json` files.

**Comment by DandyLyons** [comment]
In case this is relevant to you: 

The documentation for swift-dependencies-additions does build on my machine. Not sure if there's a difference between that and DocC preview. 

Just mentioning because I think you said it wasn't building locally for you here: 

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2353#issuecomment-1519991683

**Comment by finestructure** [comment]
Thanks, @DandyLyons !

To clarify: the docs are building ok but the hosted docs look exactly the same as when I generate them locally. So it doesn't seem to be an issue with doc generation in our build system.

Hosted:
![CleanShot 2023-11-14 at 09 13 30@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/ad1ccc27-8e1f-44b9-b308-a1ed95fec541)

Local:
![CleanShot 2023-11-14 at 09 13 25@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/14b7a0a1-4aa0-49d3-be14-7a171c479109)

FWIW, the command I used to generate the docs locally is:

```
swift package --disable-sandbox preview-documentation -p 8080 --target DependenciesAdditions
```

This is essentially what we're doing in our build system.
