### ISSUE TITLE
`theme-settings.json` missing in newer doc archives

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2707]
`theme-settings.json` is also missing for SemanticVersion for example:

```
[Error] Failed to load resource: the server responded with a status of 404 () (theme-settings.json, line 0)
```

<img width="1011" alt="Screenshot 2023-11-12 at 17 57 24" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/d03bcbf4-174c-4abb-ab8b-b961ab9060d1">

This is new. 0.3.3 for example _has_ a `theme-settings.json` file in the bucket, as does 0.3.4. 0.3.5 is the first release without it. According to our GH releases page, 0.3.4 and 0.3.5 were tagged on the same day. So it's unlikely to be related to the move to 5.9 as the doc generator.

_Originally posted by @finestructure in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2706#issuecomment-1807185313_

**Comment by finestructure** [comment]
This doesn't appear to be unique to us. The same is true for SwiftGodot's docs hosted on GH pages:

![CleanShot 2023-11-18 at 11 53 35@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/0d3b584a-ef3d-4ae0-a829-4008d801edea)

and for Pointfree.co's TCA:

![CleanShot 2023-11-18 at 11 57 35@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/a3b0cc10-6512-4a16-83b7-dbd1a279bea1)

Perhaps this is new behaviour in Swift 5.9?

cc @franklinsch @ethan-kusters

**Comment by franklinsch** [comment]
If the original DocC catalog doesn't specify a theme-settings.json, I don't expect DocC to create one. Is this error expected @mportiz08?

**Comment by mportiz08** [comment]
I believe this is a known issue that we would love to eliminate. @franklinsch is correct that DocC doesn't create this file if it isn't provided, and it shouldn't create it if it won't be used. Unfortunately the renderer on its own isn't smart enough to know whether or not to request the theme-settings JSON file, so it attempts to request it even in cases where there isn't one, resulting in this 404.

We would likely need to fix this in DocC itself so that it only includes a request for this file in the HTML if one has been provided in the doc catalog. Unfortunately it's not something we can fix by just adding a build setting to the Vue app itself :(

**Comment by finestructure** [comment]
Thanks for following up, @mportiz08 !

This seems to be a new problem though, or is it just that perhaps in the past DocC created theme settings more liberally? I know that our own package, SemanticVersion, didn't do anything different with respect to dec generation over recent versions and it "lost" its theme settings.

Maybe as a workaround we should just inject an empty file when we build the doc archive?

The error in the console isn't a big deal by itself but I've seen a couple of instances now where people (myself included) wrongfully attribute problems to it.

**Comment by mportiz08** [comment]
> Thanks for following up, @mportiz08 !
> 
> This seems to be a new problem though, or is it just that perhaps in the past DocC created theme settings more liberally? I know that our own package, SemanticVersion, didn't do anything different with respect to dec generation over recent versions and it "lost" its theme settings.
> 
> Maybe as a workaround we should just inject an empty file when we build the doc archive?
> 
> The error in the console isn't a big deal by itself but I've seen a couple of instances now where people (myself included) wrongfully attribute problems to it.

Yep, the empty file should silence the 404 error. It's still not ideal since it will be doing a request for an unnecessary file, but we would need to fix the root issue to eliminate that entirely.

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/238

**Comment by finestructure** [comment]
This has been deployed

**Comment by finestructure** [comment]
Thanks again @franklinsch and @mportiz08 for your help!
