### ISSUE TITLE
Move to OpenAPI spec as API source of truth

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2752]
We've [uncovered some issues](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2746#issuecomment-1834104094) with generating the OpenAPI spec from VaporToOpenAPI annotations. We're also blocked from bumping this dependency to the next major release [due to a compile error](https://github.com/dankinsoid/SwiftOpenAPI/issues/5).

Finally, [Honza makes some great points](https://swift-open-source.slack.com/archives/C05AZ55J75K/p1701335812592429?thread_ts=1701294193.099139&cid=C05AZ55J75K) why starting from the OpenAPI spec as the source of truth is good best practise.

We should take a stab at switching to this approach.

**Comment by heckj** [comment]
I guess I shouldn't continue to babble away on a closed issue, huh? ;-)
