### ISSUE TITLE
error: Target 'DependenciesMacrosPlugin' must be enabled before it can be used.

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2761]
We're seeing build failures when macros are requiring permissions:

https://github.com/pointfreeco/swift-parsing/discussions/327#discussioncomment-7750853

Hopefully there's a way to grant this for automated builds.

**Comment by finestructure** [comment]
`-skipMacroValidation` (for `xcodebuild`) or

```
defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
```

should help.

- https://forums.swift.org/t/is-there-a-way-to-programmatically-allow-trust-the-compiler-plugin-to-run-from-the-command-line/65690
- https://stackoverflow.com/questions/77302264/use-skipmacrovalidation-for-xcodebuild-command-when-using-an-external-package

**Comment by finestructure** [comment]
For reference, the error is

```
/Users/builder/builds/TDmZkXJm/3/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies/checkouts/swift-dependencies/Package@swift-5.9.swift:PACKAGE-TARGET:DependenciesMacrosPlugin: error: Target 'DependenciesMacrosPlugin' must be enabled before it can be used.
```

and it can be observed in https://swiftpackageindex.com/pointfreeco/swift-composable-architecture/builds

NB: this is an issue only for Xcode builds, SwiftPM builds are fine.

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/239

I will re-run the TCA builds once it's deployed to confirm it's working as expected.

**Comment by heckj** [comment]
Really curious - what was the fix? (I can't see the gitlab PR link)

**Comment by finestructure** [comment]
This is now fixed:

![CleanShot 2023-12-13 at 09 59 34@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/be52a9ad-26a9-4ebf-9b02-93ae346908e7)

**Comment by finestructure** [comment]
> Really curious - what was the fix? (I can't see the gitlab PR link)

We're now running `xcodebuild` with the `-skipMacroValidation` flag!
