### ISSUE TITLE
False positive visionOS builds

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2777]
We need to be careful when building for visionOS to make sure we don't pick up an unexpected default destination when our setup it faulty.

For example, https://swiftpackageindex.com/apple/swift-openapi-generator/ is (currently) falsely showing a successful visionOS build:

![Screenshot 2023-12-13 at 12 11 37 PM](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/5fa5fc71-7a1c-4b79-8f30-cb1fdec2ca57)

It should be failing with

```
.../Yams/Sources/Yams/Representer.swift:19:8 No such module 'Glibc'
```

The problem seems to be that we're not finding the visionOS SDK (or its not compatible) and fall back to macOS:

```
** BUILD SUCCEEDED **
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0008793E26D2001E }
{ platform:macOS, arch:x86_64, id:00008103-0008793E26D2001E }
```

**Comment by finestructure** [comment]
A working combination that passed our visionOS positive/negative tests is Xcode 15.2b1 + visionOS 10.b7. I think we should deploy this version as 5.9 to the builders to fix visionOS builds. That version should work find for regular 5.9 builds while also supporting visionOS.

```
❯ env DEVELOPER_DIR=/Applications/Xcode-15.2.0-Beta.app xcrun swift --version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
```

**Comment by daveverwer** [comment]
I can put this on the 5.9 build machine first thing tomorrow. 👍

**Comment by finestructure** [comment]
This is now fixed:

![CleanShot 2023-12-18 at 10 49 19@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/876890f6-5bee-47cf-b361-fd10682539b2)
