### ISSUE TITLE
Error: Swift Package Manager plugin must be enabled before it can be used

### ISSUE THREAD

**Issue by jkrukowski** [SwiftPackageIndex/SwiftPackageIndex-Server#2792]
My [library](https://swiftpackageindex.com/jkrukowski/SwiftMistral) written in Swift is using a Swift Package Manager OpenAPIGenerator plugin. When SPI is trying to build it I get the [following error](https://swiftpackageindex.com/builds/3C90E108-31F5-474D-8C1C-4CDCB29C617C):

```
Validate plug-in “OpenAPIGenerator” in package “swift-openapi-generator”
error: “OpenAPIGenerator” must be enabled before it can be used
```

I noticed that in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2761 you've added support for `-skipMacroValidation` flag. Would it be possible to add support for `-skipPackagePluginValidation` flag as well? Adding it might fix the above issue. Thanks!

**Comment by finestructure** [comment]
Yes, we'll add that flag. Thanks for the report!

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/241

Will re-trigger builds after it's deployed.

**Comment by jkrukowski** [comment]
> Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/241
> 
> Will re-trigger builds after it's deployed.

Thanks a lot!

**Comment by finestructure** [comment]
This is fixed now with the latest builder:

![CleanShot 2023-12-19 at 12 37 57@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/a77f53d6-eaa9-4e8a-ab7b-7495f4ad6b71)

Thanks again for the report!

**Comment by finestructure** [comment]
(The watchOS build error is due to a failure building the test target. The fix would be to create an Xcode scheme that builds for watchOS without the tests and [reference that scheme in `.spi.yml`](https://swiftpackageindex.com/swiftpackageindex/spimanifest/1.1.1/documentation/spimanifest/commonusecases#Control-Targets-and-Schemes))
