### ISSUE TITLE
Add DocC's source link feature support

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2794]
### Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2793

<div type='discussions-op-text'>

<sup>Originally posted by **Kyle-Ye** December 17, 2023</sup>
IMO, we could have it by passing customDocumentationParameters eg. "--source-service-base-url https://github.com/Kyle/TestKit/blob/main" but it will lead to both main and release/1.0 branch doc to link to my main branch's source code unless we update the .spi file manully for each release.
I think we can abstract it on SPI side. So the downstream user can just opt-in this feature more easily.

If SPI only support GitHub, maybe a single bool key is enough. Otherwize, we may consider adding 2 parms
"source-service" - pass through to docc directly
"spi-source-service-base-url" (eg. ttps://github.com/<org>/<repo>) - we transform it to "source-service-base-url" to docc by appending "blob/main" or "blob/release/1.0"
(checkout-path is not needed to pass in in SPI, we just handle it internally and pass it to docc)

https://www.swift.org/documentation/docc/distributing-documentation-to-other-developers#Include-Links-to-your-Projects-Sources</div>

**Comment by daveverwer** [comment]
> If SPI only support GitHub, maybe a single bool key is enough. Otherwize, we may consider adding 2 parms "source-service" - pass through to docc directly "spi-source-service-base-url" (eg. ttps://github.com//) - we transform it to "source-service-base-url" to docc by appending "blob/main" or "blob/release/1.0" (checkout-path is not needed to pass in in SPI, we just handle it internally and pass it to docc)

If we do this, it would probably be best to use just one parameter as both an opt-in and a definition of which source service to use. As discussed in Discord, we do not support more than GitHub right now, but we do hope to in the future.

Given this is going to need arbitrary logic on our side to determine the URL structure, I don't think we need any additional manifest parameters. We support GitHub right now, and know the rules for how GitHub construct their source file URLs, so we could add this in to all current packages with documentation as they are, by definition, all on GitHub. If and when we add GitLab/other support, we'll need different logic, but that logic would be keyed off the source repository URL domain name, so we'll have everything we need.

This is a great feature request! Thanks for adding it @Kyle-Ye!

**Comment by finestructure** [comment]
Is there any reason _not_ to make this the default for all doc sets? The only reason I can think of is if you were to generate docs for a closed source package - something which can't really happen in our case by design *).

*) Perhaps in case of a binary framework package but I think in that case you wouldn't be able to ship reference docs, only Markdown article/tutorial docs that wouldn't have any source links, right?

**Comment by daveverwer** [comment]
Yes, I think it should be on by default. We could add an opt-out if we find examples of it not working well.

**Comment by Kyle-Ye** [comment]
I'm +1 for making it on by default in SPI. cc @franklinsch

Also an implementation reminder: "checkout-path" needs to be a absolute path not a relative one.

**Comment by finestructure** [comment]
This was pretty straightforward to add but is unfortunately breaking doc builds with `xcodebuild docbuild` (i.e. if you opt-in to build docs for iOS, default is macOS-SwiftPM). I've updated the implementation to only apply these parameters for the SwiftPM based doc generation.

What I don't understand is why this is failing the iOS doc builds. The error is

```
[x] Error: Unknown option '--emit-digest --source-service github --source-service-base-url https://github.com/kukushi/SideMenu/blob/2.0.9 --checkout-path /var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/FF37D94B-F54E-4423-B2AF-0393B8651792/checkout'
```

Yet when I run the exact same command manually in the same checked out directory (fresh run)

```
env DEVELOPER_DIR=/Applications/Xcode-15.2.0-Beta.app xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride=/private/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/4F9F4B91-E785-4B13-A3A1-6FCFBC3884A0/checkout/.dependencies -skipMacroValidation -skipPackagePluginValidation -derivedDataPath /private/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/4F9F4B91-E785-4B13-A3A1-6FCFBC3884A0/checkout/.derivedData docbuild OTHER_DOCC_FLAGS='--emit-digest --source-service github --source-service-base-url https://github.com/kukushi/SideMenu/blob/2.0.9 --checkout-path /private/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/4F9F4B91-E785-4B13-A3A1-6FCFBC3884A0/checkout' -scheme SideMenu -destination generic/platform=ios
```

it succeeds:

```
/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/4F9F4B91-E785-4B13-A3A1-6FCFBC3884A0/checkout/SideMenu.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'SideMenu' from project 'SideMenu')
warning: Run script build phase 'SwiftLint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'SideMenu' from project 'SideMenu')
** BUILD DOCUMENTATION SUCCEEDED ** [9.682 sec]
```

It must be something about the environment that we're not controlling but I can't yet figure out what it is.

**Comment by finestructure** [comment]
I propose we ship this for the default doc builds via SwiftPM for now and add support for iOS doc builds (which are very rare) later.

**Comment by Kyle-Ye** [comment]
I suppose it will be a opt-out feature eventually. Will it now be a manually opt-in feature or we just release it by default?

**Comment by finestructure** [comment]
I wasn't even planning to make it opt-out at this time because I don't see any downsides of it. It would be on by default but only for SwiftPM doc builds (macOS + Linux at this time).

It's quite a bit of effort to route the opt-out through in the implementation, so I'd only want to do it if we're seeing problems with it that can only be fixed by an opt-out.

**Comment by Kyle-Ye** [comment]
Got it. And the current appearance and customization ability for source link is not very flexible. If SPI receives any feedback/suggestion on it, feel free to add a Feature Request issue on swift-docc repo.

**Comment by Kyle-Ye** [comment]
> It's quite a bit of effort to route the opt-out through in the implementation, so I'd only want to do it if we're seeing problems with it that can only be fixed by an opt-out.

Because some repo is already passing such parameter to SPI using "custom_documentation_parameters".

eg. https://github.com/hylo-lang/hylo https://github.com/hylo-lang/Lotsawa

**Comment by finestructure** [comment]
The repos in our tests don't have any custom parameters themselves, so it's not any interference of that sort (plus it would be reflected in the actual command I'm taking from the processing step).

As to repos with existing `source-service` parameters: I don't think we need to account for those because they cannot succeed, because they cannot possibly set a correct `--checkout-path`. I.e. their current settings are without effect:

```
  --source-service, github,
  --source-service-base-url, https://github.com/val-lang/Lotsawa/blob/main,
  --checkout-path, .
```

We're the only ones in a position to make that work.

**Comment by finestructure** [comment]
This has been deployed: https://swiftpackageindex.com/swiftpackageindex/semanticversion/main/documentation/semanticversion/semanticversion

![CleanShot 2023-12-20 at 11 11 08@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/35e94f4d-8875-48ed-802e-9c1c14955314)

I'll keep the issue open for a moment longer to see if we can fix the issues for `xcodebuild docbuild` source service settings.

**Comment by finestructure** [comment]
Surprise, surprise, this is a shell quoting issue. Even a simple test that has nothing to do with source-service flags fails the doc build:

```
[x] Error: Unknown option '--emit-digest --include-extended-types'
```

I.e. currently our `custom_documentation_parameters` parameter is broken in general for iOS doc builds. This has nothing to do with the source-service flags.

It works ok for single items but since we already inject `--emit-digest` any additional parameters coming from `.spi.yml` will break doc generation on iOS.

**Comment by finestructure** [comment]
Will be fixed by https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/243

**Comment by finestructure** [comment]
This has been deployed.

**Comment by Kyle-Ye** [comment]
Noticed some line number mismatch issue here, and I suspect it should be a [upstream issue](https://github.com/apple/swift-docc/issues/781) instead of SPI. 

eg. https://swiftpackageindex.com/openswiftuiproject/opencombine/main/documentation/opencombine/connectablepublisher

Could you share SPI's build command for the package I mentation on the upstream issue so that we can reproduce it more easily? @finestructure

**Comment by Kyle-Ye** [comment]
I can conform the issue is on SPI side. See https://github.com/apple/swift-docc/issues/781#issuecomment-1871792054

Should I file a new issue or reopen this to track it.

**Comment by finestructure** [comment]
I'm don't quite see the problem, @Kyle-Ye  🤔 When I follow the link I land on the type, on line 99. What's the behaviour you expect instead here?

<img width="648" alt="Screenshot 2023-12-29 at 09 42 22" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/82ceeae6-c5f6-493a-9ed1-8035f28b6d58">

**Comment by finestructure** [comment]
Looking at the example in the upstream issue I also can't reproduce it. Here's what I see:

<img width="816" alt="Screenshot 2023-12-29 at 09 50 38" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/ed756346-aacd-4036-8ec0-4e788da4149b">

<img width="637" alt="Screenshot 2023-12-29 at 09 50 24" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/6e627a4b-55cb-4697-9c51-ec65e6e1d991">

**Comment by finestructure** [comment]
Was it perhaps a browser caching issue?

**Comment by Kyle-Ye** [comment]
That's strange, it was at the wrong path yesterday.

I probably know the issue here. I've deleted 2 lines recently.

Say
```
commit ID A -> commit ID B
					⬆️
			PR to delete 2 line
```

The original `protocol P` is on Line 106 on commit ID A and so the generated doc version for it will have a link to `P:L#106`.

Then we commit B and push it to main. (The P's location on commit B will be Line 104)

But the SPI workflow is not triggered currently(I remember it is a daily job job).

So if we browser the doc here, it will give a link to `P:L#106` which will be wrong.

<img width="841" alt="image" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/43724855/b1f02a0c-742d-46fb-8dd4-923ff5d5ddaa">

**Comment by Kyle-Ye** [comment]
Solution:
1. Ignore it, as it will be auto-fixed less than a day. Or
2. Update "source-service-base-url" logic to use "tree/$COMMIT_ID" instead of "blob/main" or "blob/release/1.0"

**Comment by finestructure** [comment]
Ah right, I see. This is a default branch issue and one that we can't really overcome. We collate builds on the default branch over a 24h period in order to avoid build churn. However, the doc links will naturally always point to the latest default branch source, so they can get out of sync until our build catches up.

I believe we do have the commit around to use it in the link instead of the branch name if we deem this a problem that needs fixing (I lean towards leaving it as is).

**Comment by Kyle-Ye** [comment]
+1 for leaving it as it in general. But I prefer we add some hint / badge label banner here to imply the fact that the current SPI documentation may be out of sync of the target branch/release.

It can be achieved by providing a custom header.html to swift-docc-render.

> swift-book have a great example on this. https://github.com/apple/swift-book/blob/main/TSPL.docc/header-staging.html

The implementation detail is when a new commit is push, we mark it as stale and the header.html will be updated/inserted. When 24h period pipeline is triggered and SPI successfully builds a new documentation we discard the stale mark for that package.

**Comment by finestructure** [comment]
Adding such a banner would be quite tricky. We can't embed it when we generate the docs, because we can't foresee future drift. Instead we'd had to check on each doc request if the upstream default branch revision has changed and embed the banner dynamically. That's not really something I'd want to be doing.

I think we should generally steer people to look at release docs (tagged versions), which have none of these problems, and we already do this by making the latest release docs the default.
