### ISSUE TITLE
Cant fetch Pendo SDK 

### ISSUE THREAD

**Issue by MikePendo** [SwiftPackageIndex/SwiftPackageIndex-Server#2800]
**Please describe the bug**

We are trying to fetch the latest 3.0.1 of Pendo SDK
[Pendo](https://github.com/pendo-io/pendo-mobile-sdk) and we fail.
On Xcode 14.3 endlessly loading on Xcode 15 there is an error with manifest 

**Explain the steps needed to reproduce the bug**

Explained in the bug 
**What was the expected behaviour?**
Fetching the SDK

**Comment by finestructure** [comment]
Thanks for the report, @MikePendo . It sounds like you're having an issue with using the Pendo SDK itself and not with its package page on the Swift Package Index (which this repository is about).

If this is about using the SDK in Xcode, you should probably raise and issue here: https://github.com/pendo-io/pendo-mobile-sdk/issues

**Comment by MikePendo** [comment]
Hi @finestructure 
We cant fetch the SDK, We are the one who develop it, maybe u can try to fetch it on your side to see what we did wrong

**Comment by MikePendo** [comment]
Is there any command line tool we could try to fetch the SDK. I am not sure how to get the error from the Xcode

**Comment by MikePendo** [comment]
Ok resolve packages leads to that error:
```
nvalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/db/zcgk7dmj2tz44zyqvsycsq9m0000gn/T/TemporaryDirectory.LIP1ch/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-target", "arm64-apple-macos13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk", "-package-description-version", "5.3.0", "-Xfrontend", "-serialize-diagnostics-path", "-Xfrontend", "/Users/mrt/Library/Caches/org.swift.swiftpm/manifests/ManifestLoading/pendo-mobile-sdk.dia", "/Package.swift", "-disallow-use-new-driver", "-o", "/var/folders/db/zcgk7dmj2tz44zyqvsycsq9m0000gn/T/TemporaryDirectory.n4T5cJ/pendo-mobile-sdk-manifest"])
<unknown>:0: warning: legacy driver is now deprecated; consider avoiding specifying '-disallow-use-new-driver'
/Package.swift:6:1: error: cannot find '' in scope
 in https://github.com/pendo-io/pendo-mobile-sdk
 ```

**Comment by finestructure** [comment]
I'm still not sure where on our end you see this error. Looking at the package page I see green ticks for iOS:

![CleanShot 2023-12-20 at 19 31 09@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/0d90f79b-8080-4757-a6ee-508bd5ed02fb)

Where are you seeing this error and what operation exactly triggers it?

**Comment by MikePendo** [comment]
ok so basically if I try to fetch in Xcode 15.1 it will fails but I have an option to add it any way 
<img width="778" alt="Screenshot 2023-12-20 at 13 38 01" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/56674958/791274ff-dac9-4740-911e-d7f27a712555">
as I dont see the error properly I am adding it anyway  and then try to resolve it like that:
`xcodebuild -resolvePackageDependencies -disablePackageRepositoryCache -skipPackagePluginValidation -project TeslaApp.xcodeproj` I tried different options and get that error which I am not sure what really means

If u will try to fetch the SDK I believe you will see the same error

**Comment by MikePendo** [comment]
@finestructure 
Any idea what can we try. I am not sure what the error about.

**Comment by finestructure** [comment]
Help me understand what you're trying to do. I'm assuming you started somewhere on this page:

https://swiftpackageindex.com/pendo-io/pendo-mobile-sdk

and found or ran into some kind of error. Which part of the page did you interact with?

**Comment by finestructure** [comment]
From looking at your screenshot you're having trouble using the Pendo SDK in an Xcode project. We're hosting pages showing details about Swift packages, I'm afraid help on how to use SDK is out of the scope of our project.

**Comment by MikePendo** [comment]
So I guess I should open the issue here [SPM](https://github.com/apple/swift-package-manager).
My issue was that I fail to fetch the SDK (we can fetch it with cocopods or manually). i.e it's not directly related to the SDK.
I am sorry if we have opened issue in a wrong repo, Maybe you have seen such error and can suggest something about it.
(So swiftpackgeindex is only a web that show info about packages it doesnt interact with the SPM logic )

**Comment by finestructure** [comment]
That's right, SPI is about showing info about packages. I don't think the Swift Package Manager repository is where you'll find help to be honest. I would try the Apple Developer Forums: https://developer.apple.com/forums/

Hope that helps!
