### ISSUE TITLE
NetworkKit

### ISSUE THREAD

**Issue by sabapathyk7** [SwiftPackageIndex/SwiftPackageIndex-Server#2806]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/sabapathyk7/NetworkKit/builds

**Please explain what data is incorrect and what you expected to see**

**Package version 1.0.1 was successfully installed across different platforms and Swift versions ranging from 5.9 to 5.6. However, when installing the package from the main branch, it only succeeded on Swift 5.9 while failing on other versions. I have confirmed that both source codes are identical. I would appreciate it if you could help me understand why the installation failed on the other versions.**

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

Please find the builds exhibiting the problem from the "Full Package Compatibility Report" menu item in the side menu and link the build reports here.

- https://swiftpackageindex.com/builds/E4AF80FB-1646-44B4-AD08-E98F92CFA4A3
- https://swiftpackageindex.com/builds/89F665B9-FD9F-4C79-B723-9A73ADB5A179

Where possible, try and replicate the problem you have found by running the "Build Command" at the top of a build report. This command is what our build servers execute.

**Screenshots**

If they would be helpful, please add screenshots to help explain the problem.

**Additional context**

Is there anything else we might find useful?

**Comment by finestructure** [comment]
This is likely because we build tags immediately but default branch changes only after up to 24h. This should align automatically by tomorrow.

**Comment by sabapathyk7** [comment]
Thanks for the information.
