### ISSUE TITLE
Redirect www.swiftpackageindex.com to swiftpackageindex.com

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#281]
If we can't do this easily in Vapor, I can do it with a Cloudflare rule. It'd be better in source control though.

**Comment by finestructure** [comment]
I think that would def be easier to do in Cloudflare. I think we'd need to set up a Middleware in Vapor for that so it can affect every request. Seems like the wrong place to do that sort of thing.

**Comment by daveverwer** [comment]
Done 

<img width="1050" alt="Screenshot 2020-06-06 at 10 16 50@2x" src="https://user-images.githubusercontent.com/5180/83940963-6ad34e00-a7df-11ea-95ac-4b1e69851a75.png">
