### ISSUE TITLE
ipp-nio builds fail

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2811]
all builds on SPM seem to fail because of this target with a custom path
```
        .executableTarget(
            name: "PrintPDF",
            dependencies: [
                .target(name: "IppClient"),
            ],
            path: "Examples/PrintPDF",
            exclude: ["hi_mom.pdf"]
        ),
```

error: 'spi-builder-workspace': invalid custom path 'Examples/PrintPDF' for target 'PrintPDF'

it works just fine locally - any tips?

_Originally posted by @sliemeobn in https://github.com/SwiftPackageIndex/PackageList/issues/6115#issuecomment-1879057462_

**Comment by finestructure** [comment]
I've just run the build locally and it works, so there must be something tripping up our build system.

**Comment by daveverwer** [comment]
I have just been looking into this, too, and I *do* get the error in every environment.

I tried it with our build environment tool, first and could reproduce the error, but I also get it from a simple checkout of the project and a `swift build`.

![Screenshot 2024-01-05 at 19 32 00@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/a935271f-e5ed-4c25-bc2c-34d94a38c4ae)

**Comment by daveverwer** [comment]
Ohh wait, that `*` is suspicious, and sure enough look what's happened.

![Screenshot 2024-01-05 at 19 32 59@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/3ebd99b2-da6d-4ccf-8991-bc6c162df2e2)

We must be deleting those two files with the build tool somehow, maybe as we're trying to clean up misleading xcodeproj files, which I know we do.

**Comment by daveverwer** [comment]
Thanks so much for the report, @sliemeobn. We'll need to figure this out and get it fixed.

**Comment by finestructure** [comment]
>  I mean what could possibly go wrong, right? 😆

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2798#issuecomment-1867900493

**Comment by sliemeobn** [comment]
haha, sometimes things don't work in mysterious way, but rather crudely ; )

thanks for jumping on this so quickly!
should I rename to folder for now, or is this something you are intent on fixing soon-ish?

PS: can't wait to hear about Sven joining the SSWG on the next podcast episode.

**Comment by finestructure** [comment]
Nothing to change on your end! It's a simple fix that I'll push out tomorrow, no worries :)

**Comment by finestructure** [comment]
Fixed here: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/246

Will re-trigger builds once deployed and close the issue once it's confirmed to work.

**Comment by finestructure** [comment]
Deployed and re-triggered:

![CleanShot 2024-01-06 at 12 35 15@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/623e24e7-bae3-4518-8de9-373607d2cd6f)

It's odd that the visionOS build succeeds while iOS fails but we've made some progress at least. I'll close this for now, please re-open if these still look wrong to you in some way.

You can find the complete build command properly shown also for failing builds when you click through on individual builds. That should help verify that everything is in order.

Thanks again for the report, @sliemeobn !
