### ISSUE TITLE
Incorrect dependency count

### ISSUE THREAD

**Issue by RemiBardon** [SwiftPackageIndex/SwiftPackageIndex-Server#2814]
**Please describe the bug**

I was looking at [PeriodDuration](https://swiftpackageindex.com/davdroman/PeriodDuration) and the page says "This package depends on 7 other packages.". I went to look at [`Package.swift`](https://github.com/davdroman/PeriodDuration/blob/146828748b61cb2eefe755916c4a806594e09d08/Package.swift) to see what it could be and I realized there are only 3 dependencies:

```swift
/* ... */

let package = Package(
    /* ... */
    targets: [
        .target(name: "PeriodDuration", dependencies: [
            .product(name: "Parsing", package: "swift-parsing"),
        ]),
        .testTarget(name: "PeriodDurationTests", dependencies: [
            .target(name: "PeriodDuration"),
            .product(name: "JSONTesting", package: "swift-json-testing"),
        ]),
        .executableTarget(name: "Benchmarks", dependencies: [
            .target(name: "PeriodDuration"),
            .product(name: "Benchmark", package: "swift-benchmark"),
        ]),
    ]
)

package.dependencies = [
    .package(url: "https://github.com/google/swift-benchmark", from: "0.1.2"),
    .package(url: "https://github.com/pointfreeco/swift-parsing", from: "0.13.0"),
    .package(url: "https://github.com/davdroman/swift-json-testing", from: "0.2.0"),
]
```

**Explain the steps needed to reproduce the bug**

Nothing really, everything is already explained above.

**What was the expected behaviour?**

I would have expected to see "This package depends on 3 other packages.".

**Comment by finestructure** [comment]
Hi @RemiBardon , thanks for the report! The number is actually "correct", because it counts the total dependencies, i.e. including the transient ones which we take from `Package.resolved`:

https://github.com/davdroman/PeriodDuration/blob/main/Package.resolved

We're planning to extend this to report both dependency counts (and more) in the future!

**Comment by RemiBardon** [comment]
Hi @finestructure, thanks for your prompt answer!

You're completely right, I should have thought about transitive dependencies…
The number 7 and 7 target dependencies mislead me 🙄

I'm closing this as it is not an issue 🫢
