### ISSUE TITLE
Go to top result when hitting return?

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#282]
I think we should go to the top result on return. Probably always but certainly when there's only one result.

**Comment by daveverwer** [comment]
I think that might feel a little weird. It wouldn't be hard to implement so it's worth testing.

**Comment by manmal** [comment]
I just wanted to open an issue for exactly this :)

**Comment by daveverwer** [comment]
Closing as this is now being tracked as part of #637 in the [intermediate search page project](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/projects/5).
