### ISSUE TITLE
Add crash and server restart alert

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2849]
We should add an alert for server restarts

```
[ NOTICE ] Server starting on http://0.0.0.0:80 [component: server]
```

We've seen crashes today that led to `swift-backtrace` locking up the nodes for a while:

![CleanShot_2024-01-18_at_17 55 452x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/5605667a-af49-46bf-b282-22aa6281ddb2)

We don't have good visibility when restarts happen - it's a testament really to how stable the processes have been, we've never really had issues with crashes in the server process.

**Comment by finestructure** [comment]
I don't think we want `swift-backtrace` running by default in prod with those performance characteristics. On staging, yes, but in prod I'd want to enable it explicitly as a last resort to track down issues. We ended up shooting down nodes left, right, and centre due to it taking so long to wrap up.

**Comment by finestructure** [comment]
We had another instance this morning where a node was completely locked up for hours, running swift-backtrace at 100% CPU:

![CleanShot 2024-01-20 at 10 49 25@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/d6c8b0fe-2e09-4ae7-937f-e63c1dcd1b5a)

**Comment by tayloraswift** [comment]
> We had another instance this morning where a node was completely locked up for hours, running swift-backtrace at 100% CPU:

i have seen something sporadically similar to this ever since upgrading to swift 5.9. did you see `swift-backtrace` in `top` while this was occurring? as far as i understand, `swift-backtrace` should not take more than a minute to complete.

**Comment by finestructure** [comment]
Yes, exactly - like in the screenshot at the very top. My understanding is that the hang was perhaps due a misconfiguration. We're statically linking but hadn't bundled up and reference the backtrace binary. But it's possible that this happens regardless, it's hard to tell at this point.
