### ISSUE TITLE
Funding link related crash

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2850]
We've seen repeated crashes of the server, forcing a roll-back to 2.97.16. There were warnings like

```
[ WARNING ] invalid field: 'funding_links', type: Array<FundingLink>, error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [SomeCodingKey(stringValue: "repositories_funding_links (10)", intValue: nil)], debugDescription: "Unable to interpret value of PSQL type JSONB[]: ByteBuffer { readerIndex: 0, writerIndex: 240, readableBytes: 240, capacity: 240, storageCapacity: 32768, slice: _ByteBufferSlice { 1616..<1856 }, storage: 0x00007f7ab43c04a0 (32768 bytes) }", underlyingError: nil)) [component: server]
```

near the crashes in the logs, which might be related or causing the issue.

**Comment by finestructure** [comment]
Dave has found four packages which cause a crash when running locally:

```
[ INFO ] GET /hexedbits/AboutThisApp [component: server, request-id: 760427FF-CAA9-4D5C-AB5D-047DD3C02F2E]
App/PackageController+PackageResult.swift:28: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

- AboutThisApp
- Nine41
- swift-outdated
- accept-language-parser

I can reproduce them crashing the server on staging, where 2.97.17 is still running. Behaviour looks like what we saw in prod. The fact that we didn't see the same warning is odd but can perhaps the warning doesn't make it into the logs.

**Comment by finestructure** [comment]
The logs on dev are full of the `invalid field: 'funding_links'` errors, and what's interesting is that they're at exactly 5min intervals:

![CleanShot 2024-01-19 at 08 40 36@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/06bb8c15-9b98-41f1-8ffb-6b6689c52bd3)

Note that this is the server process, not ingestion (which runs at a 5min interval). Not sure how they could be related.

**Comment by finestructure** [comment]
The DDL looks ok, and we've been using the same data type in the `releases` field for a long time:

```sql
    releases jsonb[] DEFAULT '{}'::jsonb[],
...
    funding_links jsonb[] DEFAULT '{}'::jsonb[]
)
```

and

```swift
    @Field(key: "funding_links")
    var fundingLinks: [FundingLink]
...
    @Field(key: "releases")
    var releases: [Release]
```

**Comment by finestructure** [comment]
OK, the problem is a data error, the field can't be parsed. The content in this case is

```
{"{\"url\": \"https://github.com/jessesquires\", \"platform\": \"gitHub\"}","{\"url\": \"https://liberapay.com/jsq\", \"platform\": \"liberaPay\"}","{\"url\": \"https://paypal.me/jessesquires\", \"platform\": \"customUrl\"}","{\"url\": \"https://cash.app/$jsq\", \"platform\": \"customUrl\"}","{\"url\": \"https://venmo.com/u/jsq1312\", \"platform\": \"customUrl\"}"}
```

Note the `liberaPay`, capital P. Our platform type is

```swift
        case liberapay
```

It's harsh that this decoding error leads to a crash in the query. This is going to make this approach quite fragile, because I don't think we have a chance to handle decoding error at this point. I.e. we can't ignore them when doing `try packageResult.model.joined(Repository.self)` and can't prevent it from making the whole repository record invalid.

We have to be really careful with our insert and also look into how we can make `joined` safer.

**Comment by finestructure** [comment]
OK, it's understood how this happened and while the crash is not ideal it's not an external data change that caused the problem. We changed our enum values without resetting the data.

**Comment by finestructure** [comment]
The 5-minute interval "invalid field" warnings are still a mystery to me. A few things to note:

- they seem to be coming in batches of 11, i.e. every 5 mins there are 11 warnings of this type
- there are no other notable consistent warnings or error happening in between, in fact there are few logs in between, the "invalid field" warnings dominate the logs
- the 5min interval points to ingestion but this is the server process and they don't talk to each other
- our only external trigger into the server are http requests, i.e. every 5mins there seem to be 11 requests triggering the warning - I wonder if it's Azure's uptime monitor. It could be for 11 regions or something.

**Comment by finestructure** [comment]
What we're testing is https://staging.swiftpackageindex.com though, and I can't reproduce the warning running locally hitting just the home page.

**Comment by daveverwer** [comment]
The other thing I can't explain is that if this only affected 4 package pages, which I believe is all it affected. How did it cause such a huge number of crashes?

The auditing tool hits every URL only once.

**Comment by finestructure** [comment]
Also notable: We're seeing this warning every 5mins on staging but in that case the server process is not crashing. Staging should be down constantly if those led to a crash.

**Comment by finestructure** [comment]
The data reset also fixed the recurring warnings:

![CleanShot 2024-01-19 at 15 55 17@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/6030a7f7-a7f6-436f-b745-dcd566962456)
