### ISSUE TITLE
`.spi.yml` exceeds size limit

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2868]
### Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2867

<div type='discussions-op-text'>

<sup>Originally posted by **Wei18** January 26, 2024</sup>
**Please describe the bug**

I modified [.spi.yml@af70860](https://github.com/Wei18/github-rest-api-swift-openapi/blob/main/.spi.yml) and verified on [validate-spi-manifest](https://swiftpackageindex.com/validate-spi-manifest), wait for days but not working.

The only first time added [.spi.yml@a97557c](https://github.com/Wei18/github-rest-api-swift-openapi/blob/a97557c42628b2621faf3f8e8c3fa8e1fcaa2b93/.spi.yml) worked.
(doc: https://swiftpackageindex.com/Wei18/github-rest-api-swift-openapi/main/documentation/githubrestapiissues)

Thanks

</div>

**Comment by finestructure** [comment]
- [ ] raise size limit slightly
- [ ] make sure our validator fails with a proper error message if the file is too large

**Comment by finestructure** [comment]
The job [times out](https://swiftpackageindex.com/Wei18/github-rest-api-swift-openapi/builds), with the build alone taking 6 minutes. It's just too many targets to try and generate docs for afterwards. We just manage two of them before it times out, and that's before uploading the docs.

@Wei18, I'm afraid there's nothing we can do here. You'll have to get the build time down to a couple of minutes to even have a chance generating docs for that many targets, I believe.

![CleanShot 2024-01-26 at 17 28 09@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/c712413c-ea04-480e-828c-3801ff069624)

**Comment by finestructure** [comment]
OK, I've re-run the build job and this time it went faster. The build only took 2m20s and we manage to generate docs for around 25 targets before it times out (at target `GitHubRestAPIPackages`).

It might work with 10 doc targets but I'd actually try and keep it below 5 or so to make the results more reliable.

**Comment by Wei18** [comment]
Okay, I will try other methods to reduce the number of targets.

Thanks.
