### ISSUE TITLE
Better page titles

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#287]
Package pages should include the package name, the FAQ page should have a title, etc...

**Comment by daveverwer** [comment]
We should use Ink's support for Markdown metadata.

**Comment by finestructure** [comment]
- [ ] package page
- [ ] faq
- [ ] privacy

**Comment by finestructure** [comment]
FYI the package name was already set as page title for the package pages - unless you meant package name without the `– Swift Package Index` suffix?
