### ISSUE TITLE
Alamofire Shows No Info For Dependencies

### ISSUE THREAD

**Issue by jshier** [SwiftPackageIndex/SwiftPackageIndex-Server#2873]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/Alamofire/Alamofire

**Please explain what data is incorrect and what you expected to see**

According to the Package Score section, there is info for dependencies. Alamofire has no dependencies, and there is nothing in the package.

**Screenshots**

<img width="275" alt="Screenshot 2024-01-27 at 4 36 59 PM" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/51020/fb67a481-76b9-4107-94fc-d2cd2fac2914">

**Additional context**

Discussed with Dave offline, suggested reporting a bug.

**Comment by finestructure** [comment]
Thanks for the report, @jshier . This seems to have corrected itself in the meantime:

![CleanShot 2024-01-28 at 09 16 56@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/271d41dc-0536-4006-952d-14d50533eb5d)

I believe what's happening is that this reverts to "no information" when we detect a change on the default branch until the compatibility build with new dependency information is complete. We should try and preserve the original data in this case.

**Comment by daveverwer** [comment]
I just checked this and it's back to showing correct dependency information.

![Screenshot 2024-01-28 at 08 17 10@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/8507e7f3-bb36-4ec5-aeb2-c843d0016854)

I notice there was a push to `master` about 90 minutes before you messaged me, so it's possible that we were still gathering the dependency information at that point.

**Comment by daveverwer** [comment]
hah, we must have both been replying at the same time 😂

**Comment by daveverwer** [comment]
> We should try and preserve the original data in this case.

This would be good, but I think there may be another good change to make here. We should calculate the score (and this score report) slightly differently. We currently base it on the default branch, but we should base it on the stable release, or if it does not have one, a pre-release, and only of both of those don't exist then the default branch. We have this logic encoded in lots of places in the app, so it shouldn't be a big change.

Tracked in #2874
