### ISSUE TITLE
Remove blog front-matter from posts

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#2908]
I am sure the front-matter isn't needed anymore, but blog posts in the `posts` directory still have it. I need to take a look and remove all the old front-matter in favour of taking it from `posts.yml`.

**Comment by finestructure** [comment]
Oops, that Sonar checkbox closes issues 😅

**Comment by daveverwer** [comment]
Yes, I thought it was a little too easy to do, too. I managed not to click it, but it's too tempting!
