### ISSUE TITLE
Swift Version CI badge sorting 5.10 last instead of first

### ISSUE THREAD

**Issue by bdrelling** [SwiftPackageIndex/SwiftPackageIndex-Server#2918]
**Please describe the bug**

Swift Version badge's descended sorting is sorting 5.10 last (alphabetically) instead of first (numerically).

**Explain the steps needed to reproduce the bug**

Navigate to a package that supports at least 5.10 and any other swift version. (Example: https://swiftpackageindex.com/swift-kipple/Core)

**What was the expected behaviour?**

Versions should sort descending numerically.

**Screenshots**

![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/3022693/18fc662e-72df-46ae-bd80-1d4a5f48c8d5)

**Love and Appreciation**

Swift Package Index is the best, please keep up the amazing work. ❤️

**Comment by finestructure** [comment]
Good catch, thanks for the report and the kind words, @bdrelling !

Fix will be deployed shortly but it'll take a while to take effect due to badge caching.
