### ISSUE TITLE
Update to Swift 5.10 release

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2927]
- [x] package list [PR](https://github.com/SwiftPackageIndex/PackageList/pull/6551)
- [x] validator [PR](https://github.com/SwiftPackageIndex/PackageList-Validator/pull/64)
- [x] install new Xcode version on builders
- [x] Update spi-images ([example Merge Request](https://gitlab.com/finestructure/spi-images/-/merge_requests/12/diffs)) [PR](https://gitlab.com/finestructure/spi-images/-/merge_requests/22)
- [x] update spi-base [PR](https://gitlab.com/finestructure/spi-base/-/merge_requests/26)
- [x] make sure SPIManifest SwiftVersion.latestRelease is pointing to the desired Swift version (for doc builds) ([example PR](https://github.com/SwiftPackageIndex/SPIManifest/pull/33/files)) [PR](https://github.com/SwiftPackageIndex/SPIManifest/pull/41)
- [x] update builder ([example Merge Request](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/221/diffs)) [PR](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/265)
  - [x] `SwiftVersion.xcodeVersion`
  - `SwiftVersion.dockerImage` doesn't need changing, this is done via `spi-images`
- [x] update server ([example Pull Request](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/2308/files)) [PR](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/2928)
  - [x] `SwiftVersion.xcodeVersion`
  - [x] update to latest SPIManifest
- [ ] remove old Xcode version from builders

**Comment by daveverwer** [comment]
All Mac Sonoma build machines have been updated.

**Comment by finestructure** [comment]
This has been deployed end-to-end.
