### ISSUE TITLE
contributor names should refresh periodically

### ISSUE THREAD

**Issue by tayloraswift** [SwiftPackageIndex/SwiftPackageIndex-Server#2943]
it would be good for the accuracy of the site if the GitHub profile names were crawled and refreshed on some interval, maybe weekly.

i noticed the names do not refresh since the package was first indexed when checking on 
https://swiftpackageindex.com/tayloraswift/swift-json

![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/2556986/a823197d-d7a3-4c3b-8585-6de8e67a501f)

**Comment by daveverwer** [comment]
Hi @tayloraswift, and I'm sorry if it's not showing what you want it to. We do refresh this list every day from git history. To get the data, we run `git shortlog -sn` and populate this field from there.

For this repository, I get this result:

```
$ git shortlog -sn

    79  kelvin13
    36  kelvin
    16  taylorswift
     1  Tobias
     1  taylorswift (dianna)
```

We then take the most significant names from that list and if there are more, it gets "and X other contributors" appended.

Obviously, it's not trivial to fix up the names in the git history so we also allow this field to be overridden with any text that you'd like it to have. We read an [`authors`](https://swiftpackageindex.com/swiftpackageindex/spimanifest/1.3.0/documentation/spimanifest/manifest/metadata-swift.struct/authors) property from the `.spi.yml` file in your repository.

As an example, the Vapor team have done this:

![Screenshot 2024-03-15 at 23 50 55@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/55382b02-912d-4778-83e0-566e62b2ecb9)

You can see this specified in their `.spi.yml` file here: https://github.com/vapor/vapor/blob/3a7da193a2937472b252b8db210897e7abf37b47/.spi.yml#L3

**Comment by finestructure** [comment]
Also, because we just use `git` to pull the info, you can use `git mailmap` to update existing entries in the git log: https://git-scm.com/docs/gitmailmap

This has the advantage that it won't interfere with future changes to the author list by overriding the stat computation.

Hope that helps!

**Comment by finestructure** [comment]
See also https://ntietz.com/blog/git-mailmap-for-name-changes/

**Comment by daveverwer** [comment]
I'll close this as I think it might be resolved, but please feel free to re-open it if there is anything still outstanding @tayloraswift!
