### ISSUE TITLE
Swift 6 preview run #2

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2975]
We'll be running our second Swift 6 preview test this week.

Toolchain will be https://download.swift.org/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2024-04-01-a/swift-DEVELOPMENT-SNAPSHOT-2024-04-01-a-osx.pkg

- [x] install toolchain
  - [x] mb-temp-5.9-a 
  - [x] mb-temp-5.9-b
  - [x] mb6
- [x] [update builder](https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/274)
- [x] trigger builds
- [ ] finish by taking db snapshot

**Comment by daveverwer** [comment]
All installed.

**Comment by finestructure** [comment]
I've kicked off the second run moments ago.

**Comment by finestructure** [comment]
Had to switch the M2 builder back to building 5.7 & 5.8 builds, because we're not keeping up with regular builds if we let those run 5.9 builds.

**Comment by finestructure** [comment]
Run is complete
