### ISSUE TITLE
Migrate Grafana legacy alert rules

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#2985]
https://grafana.com/docs/grafana/latest/alerting/set-up/migrating-alerts/

- SPI Stats
  - [ ] Build Jobs
  - [ ] Build Triggers
  - [ ] Build Reports
  - [ ] CRITICAL / ERROR levels in logs
  - [ ] Operational Alerts
- Host Metrics
  - [ ] Available Disk Space
  - [ ] CPU load

**Comment by armandgrillet** [comment]
Grafana 10.4 is the last version including legacy alerting (and the one use in `mon.yml` right now), the correct link now that Grafana 11 is out is https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts/. Migrating the legacy alerts should be done before upgrading to Grafana 11.

**Comment by daveverwer** [comment]
> Grafana 10.4 is the last version including legacy alerting (and the one use in `mon.yml` right now), the correct link now that Grafana 11 is out is https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts/. Migrating the legacy alerts should be done before upgrading to Grafana 11.

Just figuring out who you are and how you must have found this issue, I have to say that's unbelievable dedication to your project and thank you so much for doing what you do. ❤️

**Comment by finestructure** [comment]
Thanks so much for the heads-up, @armandgrillet. You've saved me a big headache there 🙂

**Comment by armandgrillet** [comment]
No worries, was looking for issues I could help with and this one rang a bell 😉. With Grafana 10.4, the migration preview should be the easiest way to do this: https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts/#upgrade-with-preview-recommended. The main thing is to not upgrade to Grafana 11 until you have migrated to Grafana Alerting.

**Comment by finestructure** [comment]
The docs mention that with 10.4 (we're on 10.4.3) there should be a preview option enabled by default. I can't see anything of the sorts in the Alerting settings:

<img width="1262" alt="CleanShot 2024-06-24 at 15 07 45@2x" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/fab81e7f-25ed-45c8-955f-d11280be80c3">

I'll ad hoc deploy Grafana 11 on dev to see what happens.

**Comment by finestructure** [comment]
Seems to have just worked™ 

![CleanShot 2024-06-24 at 16 02 52@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/a945a23a-9ef9-482a-9b2a-7578e7cc096e)
