### ISSUE TITLE
Supporting beta versions of Packages

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#30]
Looking through the differences between the existing dataset from swiftpm.co, and the new dataset from this project there are a few differences. One that's important is that swiftpm.co correctly parses semantic versions that have a `pre` part, more commonly known as beta versions 😂

For example, for one package on swiftpm.co:

<img width="193" alt="Screenshot 2020-05-06 at 11 14 33@2x" src="https://user-images.githubusercontent.com/5180/81165982-d630c280-8f8a-11ea-8b3d-c4e9bd5d2ba9.png">

and for the same package in this project:

<img width="87" alt="Screenshot 2020-05-06 at 11 14 49@2x" src="https://user-images.githubusercontent.com/5180/81166008-e0eb5780-8f8a-11ea-9b4e-882f3e7fd9d7.png">

**Comment by finestructure** [comment]
Is there a spec for what the pattern should look like? I.e. is there always a `-` and is anything after the `-` allowed?

**Comment by finestructure** [comment]
Right [this](https://semver.org) has got the details and there's a regex we can use:

https://regex101.com/r/Ly7O1x/3/

(and filter down)

**Comment by daveverwer** [comment]
As you might imagine, the spec is more complex than you might imagine 😬 https://semver.org

I used [this gem](https://github.com/jlindsey/semantic) originally and then explicitly only take the MAJOR/MINOR/PATCH and PRE parts.

There's another little gotcha that we'll need to cope with. SPM supports semantic versions that start with a `v` character even though anything starting with a `v` is *not* a semantic version. SO I manually cope with that too. I just trim any leading `v` characters before parsing the semantic version.

**Comment by daveverwer** [comment]
There's also this if a regex doesn't work out:

https://github.com/AlexanderNey/SemanticVersioning

Seems like it's well maintained, and it supports SPM.
