### ISSUE TITLE
Quikliy

### ISSUE THREAD

**Issue by tasnef** [SwiftPackageIndex/SwiftPackageIndex-Server#3008]
**Please describe the bug**

Please give a clear and concise description of what went wrong.

**Explain the steps needed to reproduce the bug**

1. Navigate to to '…'
2. Click on '…'
3. See an error…

**What was the expected behaviour?**

**Screenshots**

If applicable, please add screenshots to help explain your problem.

**What web browser were you using? (if relevant)**

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop/Tablet/Smartphone
- Browser [e.g. Chrome, Safari]
- Version [e.g. Version 15.1]

**Additional context**

Is there anything else we might find useful?

**Comment by tasnef** [comment]
The entire device is out of control. Sometimes, I write sentences in the translation, and they are snatched up, and he sends a Facebook 🤗, a clearer movement. And all my devices.. for GitHub. I know how to hack. Increases barcode protection. The barcode can be photographed. If I have my own picture, he will not be able to photograph the barcode. This barcode is widely penetrated. Before it scrolled quickly, now it makes long scrolls
~~~classificsion<~~>

**Comment by heckj** [comment]
I suspect you might need to block this one - looks like GPT bot antics

**Comment by finestructure** [comment]
Yeah I blocked them for a day, may need more!
