### ISSUE TITLE
Fix pluralisation in issue count

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#302]
![F7B31DAD-A3A6-4694-B0DE-D8F176728F4A](https://user-images.githubusercontent.com/65520/83953268-52931b80-a83f-11ea-8305-5029694bb88b.jpeg)

Raised in #300

**Comment by finestructure** [comment]
Wait - this is correct actually, isn't it? Initially I misread it as `issue` as the wrong plural form but I believe @mattt was referring to `There are`. However, that should be `are` as it's referring to the open issues and pull requests. Or does that read weirdly?

**Comment by daveverwer** [comment]
Yea that reads strangely. It should be:

There is 1 open issue and 5 open pull requests. 

Or

There are 5 open issues and 1 open pull request.
