### ISSUE TITLE
tvOS build fails for Swift 5.8 and 5.7

### ISSUE THREAD

**Issue by ganeshnj** [SwiftPackageIndex/SwiftPackageIndex-Server#3048]
**Please describe the bug**

tvOS build fails for Swift 5.8 and 5.7 because the system doesn't have tvOS installed.

**Explain the steps needed to reproduce the bug**

For Swift 5.10 and 5.9, the build works fine but fails for 5.8 and below
5.10: https://swiftpackageindex.com/builds/7E2EDB16-722F-4598-A7C8-459E93B369AB
5.9: https://swiftpackageindex.com/builds/55C3A300-1D62-4EEE-A6E2-8439292BFC95

5.8: https://swiftpackageindex.com/builds/CF9E97F2-A877-4693-8221-99A027BA7F90
```
Any tvOS Device, error:tvOS 16.4 is not installed. To use with Xcode, first download and install the platform
```

5.7: https://swiftpackageindex.com/builds/99FE3BF7-B497-4705-AFD9-BCEE84A5734E
```
The run destination Any tvOS Device is not valid for Running the scheme 'Datadog-Package'.
	tvOS 16.1 is not installed. To use with Xcode, first download and install the platform
BUILD FAILURE 5.7 tvOS
```

**What was the expected behaviour?**

Atleast one simulator must be installed to be able to correctly build for tvOS.

**Comment by daveverwer** [comment]
Thanks for reporting this! We did check the machines after the [Xprotect issue](https://eclecticlight.co/2024/05/03/did-xprotect-remediator-132-damage-your-xcode/) a few days ago and everything looked to be OK, but maybe it happened for these machines after we checked.

I'll check again now

**Comment by daveverwer** [comment]
Interesting. I remember more clearly now that we only checked the Sonoma build machines as they are the only ones with Xcode 15 on them and we thought this was a problem specific to Xcode 15. I just logged into the Ventura build machines where we have Xcodes 14 installed (for Swift 5.7 and 5.8) and they all had Xprotect prompts on screen and the platform installations for tvOS and watchOS were all gone.

It's now fixed across our whole build system. I'll re-trigger your compatibility builds later this afternoon and post here when they are fixed.

**Comment by daveverwer** [comment]
I just did a full re-build for your package and I can see tvOS is showing compatibility for tvOS.

![Screenshot 2024-05-08 at 16 44 37@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/b8b5ecb0-cc2d-46dd-84d6-a03618126730)

I'll close this now but if anything still seems off, please re-open it. Thanks for reporting the issue, too!

**Comment by ganeshnj** [comment]
Thanks @daveverwer
