### ISSUE TITLE
Heart icon SVG is broken in the GitHub funding panel

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#3063]
This does not affect any rendering in any real browser, but it's consistent in Percy. Logging here so I can move on with today's work.

![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/7286112f-993b-4a67-bdfb-045bdf6d5c12)

**Comment by 0xWDG** [comment]
FYI, this fails also on a iPad (Safari)
iPadOS 17.5 (21F79)

![IMG_1897](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/1290461/52619c5a-48fb-4822-ab9c-e2f882ca33ce)

**Comment by Sherlouk** [comment]
It's also bugged on iPhone 👀

![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/15193942/bbeb0ec2-3f5b-4987-b4f6-1ad894272cbd)

**Comment by daveverwer** [comment]
Oh and now when I test it in Safari it's broken for me too! Must have been a caching issue with Safari.

Actually. Now I test it again, it's broken on Safari, Chrome, *and* Firefox! How was I not able to reproduce this?!
