### ISSUE TITLE
ParticleEffects is not picking up changes

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#3068]
- https://swiftpackageindex.com/kudit/ParticleEffects
- still on 1.0.3 when 1.0.4 was tagged two days ago on May 15
- reporting wrong compatibility according to author

**Comment by finestructure** [comment]
The problem is that with version 1.0.4 `swift package dump-package` is failing:

```
~/P/S/s/S/github.com-kudit-particleeffects on HEAD (cdf8587)
❯ swift package dump-package
error: 'github.com-kudit-particleeffects': invalid manifest (evaluation failed)
supported platforms can't be empty
error: invalid manifests at [<AbsolutePath:"/Users/sas/Projects/SPI/spi-server/SPI-checkouts/github.com-kudit-particleeffects">]
```

I've opened a PR to fix it: https://github.com/kudit/ParticleEffects/pull/1

**Comment by kudit** [comment]
I've approved the pull request.  Will that allow swiftpackageindex to work?  How long does it take to update typically?  How can I get it to update in the future?  Thank you.

**Comment by daveverwer** [comment]
I can see that the 1.0.4 tag has been picked up now. You should not need to do anything else except to make sure the Package.swift remains valid. We will constantly poll for changes.

**Comment by kudit** [comment]
Thank you.  Any idea why it's failing for everything but macOS?  It builds and works on iOS and visionOS and watchOS and tvOS and Xcode so I'm not sure why it's failing your checks.  Is there something specifically your checks are looking for?  Is there a way for me to test other than adding to projects and building and running on those devices (which works)?

**Comment by finestructure** [comment]
Have you tried running the build command as it is given at the top of the build details page locally to see if that works for you? That's the command that would need to succeed in order for the build to succeed.

**Comment by kudit** [comment]
Thank you for replying.  I have run the build command and it does appear to only run the current system build.  Is there something I can add to the Package.swift file to instruct `swift build` to build for platforms other than the current one?  I tried `swift build` on this package (https://swiftpackageindex.com/Frizlab/swift-fraction-number) which shows full compatibility and it similarly only built for my current platform so I'm trying to figure out why that package shows compatibility for all platforms where mine does not...

**Comment by finestructure** [comment]
If you click on the build matrix on the package page you can see the [list of all the builds](https://swiftpackageindex.com/kudit/ParticleEffects/builds) we run:

![CleanShot 2024-05-23 at 08 08 19@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/175fdf09-73c6-4770-8b41-17cd91d2d3b0)

On this page you can click through to the various builds for more details (1, 2, 3, ...):

![CleanShot 2024-05-23 at 08 09 05@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/ee97783c-75fa-48a1-9be1-98e3b4963534)

On each page you can see the exact build command we run (1) and the build log we produce (2).

When I run this build command for example for the iOS build

```
env DEVELOPER_DIR=/Applications/Xcode-15.3.0.app xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride=$workDir/.dependencies -skipMacroValidation -skipPackagePluginValidation -derivedDataPath $workDir/.derivedData build -scheme ParticleEffects-Package -destination generic/platform=ios
```

I get the same output locally as we do with our build system.

From looking at your packages schemes via `xcodebuild -list -json`:

```
{
  "workspace" : {
    "name" : "ParticleEffects",
    "schemes" : [
      "ParticleEffects",
      "ParticleEffects Library",
      "ParticleEffects-Package"
    ]
  }
}
```

it seems like perhaps your packages main scheme is `ParticleEffects Library` instead of the one we pick, `ParticleEffects-Package`.

If that's the case, you can configure which scheme we build via a `.spi.yml` file:

```
version: 1
builder:
  configs:
  - scheme: ParticleEffects Library
```

You can find out more about this file and target and schemes in particle in our [SPIManifest documentation](https://swiftpackageindex.com/swiftpackageindex/spimanifest/1.4.1/documentation/spimanifest/commonusecases#Control-Targets-and-Schemes).

I've opened a PR with the change here https://github.com/kudit/ParticleEffects/pull/2

Hope that helps!

**Comment by kudit** [comment]
This helped a lot!  Thank you so much!!!
