### ISSUE TITLE
[WWTextDropView / WWDetectDevice] Two Packages not in Swift Package Index, thanks.

### ISSUE THREAD

**Issue by William-Weng** [SwiftPackageIndex/SwiftPackageIndex-Server#3107]
**Please describe the bug**

- Please ask, because there are two programs that were added a few days ago, but they are not displayed on the web page and cannot be queried.

- WWTextDropView - #6677 (2024/3/27)
- WWDetectDevice - #7006 (2024/5/7)

**Screenshots**
<img width="963" alt="WWTextDropView" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/18256962/f3fb7a84-b3b2-4f0b-997e-88b79f862e9e">

Thanks.

**Comment by daveverwer** [comment]
Thanks for spotting this @William-Weng! I'm not quite sure why, but the original two PRs that were merged did not include the additions to the package list, only whitespace changes. See https://github.com/SwiftPackageIndex/PackageList/pull/6677/files and https://github.com/SwiftPackageIndex/PackageList/pull/7006/files. Neither contain the package lines.

I have now successfully added both packages with https://github.com/SwiftPackageIndex/PackageList/pull/7181/files and https://github.com/SwiftPackageIndex/PackageList/pull/7183/files and you can now see the packages live in the index here:

* https://swiftpackageindex.com/William-Weng/WWDetectDevice
* https://swiftpackageindex.com/William-Weng/WWTextDropView

**Comment by William-Weng** [comment]
Thanks.

Dave Verwer ***@***.***> 於 2024年6月4日 週二 下午12:39寫道：
