### ISSUE TITLE
PackageList "add package" action is not detecting packages correctly

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#3109]
This first happened with these two pull requests:

* https://github.com/SwiftPackageIndex/PackageList/pull/6677
* https://github.com/SwiftPackageIndex/PackageList/pull/7006

Just now it happened with this one, too:

* https://github.com/SwiftPackageIndex/PackageList/pull/7186

The actions run for that PR is:

* https://github.com/SwiftPackageIndex/PackageList/actions/runs/9363934435/job/25775805765

Nothing obviously wrong, but there's clearly something about this format that the script isn't coping with. I noticed it does not have the `.git' extension, but I'm sure we cope with that, so it's possibly some of the other text surrounding the URL that's upsetting it.

**Comment by finestructure** [comment]
I believe the problem is the extra text that was added to the [submission field](https://github.com/SwiftPackageIndex/PackageList/pull/7186):

![CleanShot 2024-07-01 at 09 40 23@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/52881c2e-f5b7-4c5e-833c-130621847764)
