### ISSUE TITLE
Can't view Swift Syntax documentation.

### ISSUE THREAD

**Issue by rpati99** [SwiftPackageIndex/SwiftPackageIndex-Server#3167]
**Please describe the bug**
Not able to browse Swift Syntax documentation. 

Please give a clear and concise description of what went wrong.
I am working on an academic project that involves using SwiftSyntax, and the sole source of using it. When i reverted to the Swift Package Website, it gave me a 404 error. 

**Explain the steps needed to reproduce the bug**

1. Navigate to '[Swift Syntax GitHub page](https://github.com/swiftlang/swift-syntax)'
2. Click on '[You can read SwiftSyntax’s documentation on (the link)](https://swiftpackageindex.com/apple/swift-syntax/documentation)'
3. See an error…

**What was the expected behaviour?**

**Screenshots**

If applicable, please add screenshots to help explain your problem.
https://imgur.com/gallery/bug-screenshot-enfO3JR

**What web browser were you using? (if relevant)**
Safari 

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop/Tablet/Smartphone - MacOS Sonoma
- Browser: Safari
- Version: 14.5

**Additional context**

Is there anything else we might find useful?

**Comment by finestructure** [comment]
Thanks for the report, @rpati99 . The repository was moved to the swiftlang org and the link is still using the preview `apple` org. I'll open a pull request to update the documentation link.

**Comment by rpati99** [comment]
Thank you!

**Comment by finestructure** [comment]
This will be addressed via https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3167

Thanks again for the report!
