### ISSUE TITLE
SharedGraphicsTools Missing Documentation

### ISSUE THREAD

**Issue by eugenebokhan** [SwiftPackageIndex/SwiftPackageIndex-Server#3179]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/computer-graphics-tools/shared-graphics-tools

**Please explain what data is incorrect and what you expected to see**

The iOS build failed for some reason. Also, the documentation is missing on the SPI.

**Screenshots**

<img width="571" alt="Screenshot 2024-07-02 at 11 25 26" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/8983647/77322869-bbe5-457e-9bb5-a0a72f3d2f66">

**Additional context**

Maybe SPM cache should be cleaned?

**Comment by finestructure** [comment]
Thanks for the report, @eugenebokhan . It looks like the configured scheme name is incorrect. I've opened a PR to fix it.
