### ISSUE TITLE
Link points to old Swift 6 configuration document

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#3193]
**Please describe the bug**

The last link at the end of this section points to a page that will eventually be retired.

https://swiftpackageindex.com/docs/builds#data-race-safety

old: https://www.swift.org/documentation/concurrency/
new: https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guide/completechecking

I'm pretty sure it will end up just being a redirect. But, still seems like its worth updating.

**Explain the steps needed to reproduce the bug**

**What was the expected behaviour?**

**Screenshots**

**What web browser were you using? (if relevant)**

**Additional context**

**Comment by daveverwer** [comment]
Thanks @mattmassicotte. Fixed in #3194!
