### ISSUE TITLE
Non-building package: Kass

### ISSUE THREAD

**Issue by nmggithub** [SwiftPackageIndex/SwiftPackageIndex-Server#3213]
Hello!

I recently submitted my package [Kass](https://swiftpackageindex.com/nmggithub/Kass) to the index. It took a while to show up on the website, but [it is now appearing in the index](https://swiftpackageindex.com/nmggithub/Kass). Unfortunately, the builds are not, and it looks like it hasn't been built at all. The only thing I can thing of that would cause this is [the additional flag I added](https://github.com/nmggithub/Kass/blob/main/.spi.yml#L6) in my `.spi.yml` file.

It's intended purpose is to be fed into the `docc` command, by way of `swift generate-documentation`. According to [the DocC plugin documentation](https://github.com/swiftlang/swift-docc-plugin/blob/5761ba99b5ae31a294fe136a57b191b69ac159f9/README.md#converting-documentation):
> Any flag passed after the generate-documentation plugin invocation is passed along to the docc command-line tool.

The `docc` tool provides the option to specify a specific `*.docc` folder to use. I am not sure where your build process adds `custom_documentation_parameters`, and I have been unable to find anything in your public repositories that specify as such.

However, I would expect this to cause a build failure, or at least a failure in the build pipeline (as documentation generation is not a build-time step). [The site reports zero builds](https://swiftpackageindex.com/nmggithub/Kass/builds), and has done so for at least the past 30 minutes. Can you please confirm why this is happening?

To note, [the main page for my package](https://swiftpackageindex.com/nmggithub/Kass) currently displays this message under Compatibility:
> This package currently has no compatibility information. Builds to determine package compatibility are starting, and compatibility information will appear soon. If this message persists for more than a few minutes, please [raise an issue](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/new/choose).

As it has been at least half an hour, which is more than a few minutes, I am raising this issue.

**Comment by finestructure** [comment]
Thanks for the report, @nmggithub . We're currently processing builds for Xcode 16b3 for our [Ready for Swift 6](https://swiftpackageindex.com/ready-for-swift-6) project, which delays things a bit. Builds are going to take longer to be picked up than usual for a few more days.

Also note that we don't build default branch changes immediately but rather coalesce them over a maximum of 24 hours.

**Comment by nmggithub** [comment]
Ok, builds have finally appeared. Documentation hasn't for some reason, but that's ok for now. Closing this.

**Comment by daveverwer** [comment]
It looks like your package has actually uncovered a small bug! Logged here: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3215

**Comment by nmggithub** [comment]
> It looks like your package has actually uncovered a small bug! Logged here: #3215

Cool to know! Glad I could be of help, however accidental it was.
