### ISSUE TITLE
visionOS builds failure (missing simulator or passing incorrect `-destination`)

### ISSUE THREAD

**Issue by jessesquires** [SwiftPackageIndex/SwiftPackageIndex-Server#3216]
It appears that the visionOS simulator / runtime is not installed on the build machines. Or, the build command is incorrect. 

(I'm not sure if `-destination generic/platform=xrOS` is valid.)

**Example builds from [Foil](https://swiftpackageindex.com/jessesquires/Foil):** 
- Xcode 15 + Swift 5: https://swiftpackageindex.com/builds/1C276595-2921-4B6B-8435-3AB608F1046E
- Xcode 16 + Swift 6: https://swiftpackageindex.com/builds/14A2455A-74CE-425C-99C5-8EEB74ED45F4

**Build command:**

(This is for Xcode 15, but the results are the same for Xcode 16)

```
env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride=$workDir/.dependencies -skipMacroValidation -skipPackagePluginValidation -derivedDataPath $workDir/.derivedData build -scheme Foil -destination generic/platform=xrOS
```

**Build logs:**

```
Running build ...
env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride=$workDir/.dependencies -skipMacroValidation -skipPackagePluginValidation -derivedDataPath $workDir/.derivedData build -scheme Foil -destination generic/platform=xrOS
Command line invocation:
    /Applications/Xcode-15.4.0.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=/Users/admin/builder/spi-builder-workspace/.dependencies -skipMacroValidation -skipPackagePluginValidation -derivedDataPath /Users/admin/builder/spi-builder-workspace/.derivedData build -scheme Foil -destination generic/platform=xrOS
User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/admin/builder/spi-builder-workspace/.dependencies
    IDEDerivedDataPathOverride = /Users/admin/builder/spi-builder-workspace/.derivedData
    IDEPackageSupportUseBuiltinSCM = YES
2024-07-12 15:13:47.990 xcodebuild[522:2976] Writing error result bundle to /var/folders/fs/0w3t9t1d28xc3bj0tgb8hcrw0000gn/T/ResultBundle_2024-12-07_15-13-0047.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ generic:1, platform:xrOS }
```

**The package does successfully build for visionOS:**
https://github.com/jessesquires/Foil/actions/runs/9922682031/job/27412014695

**Comment by finestructure** [comment]
Hi @jessesquires , I'm confused - the builds you're linking to don't exist and the [build details for Foil](https://swiftpackageindex.com/jessesquires/Foil/builds) show visionOS as `succeeded`. Did you mean to link to another package? Or were you perhaps looking at outdated builds of a version that failed for another reason?

 
![CleanShot 2024-07-14 at 09 58 36@2x](https://github.com/user-attachments/assets/d7e55199-8b11-4c8c-8f94-bd61b5584432)

**Comment by jessesquires** [comment]
@finestructure oh hm. 

I'm not sure how the site works, but I guess builds are ephemeral and only the most recent show up? 

The page you screenshotted was definitely showing visionOS failures yesterday. I copied the logs above directly from the site. (You can see `-scheme Foil` in both.)

Anyway, it all looks correct now! 😊 Sorry for the noise.

**Comment by finestructure** [comment]
> I'm not sure how the site works, but I guess builds are ephemeral and only the most recent show up?

Yes, we delete builds when new versions come in. I guess your links were to main branch builds which had updates.

Perhaps that version had some other build failure and it looked like a simulator setup issue because our build command doesn't select the sim on your machine? Anyway, glad to see it's working now :)

**Comment by daveverwer** [comment]
This made me go and double check I installed all the platform SDKs and simulators OK. We're good 👍

![Screenshot 2024-07-15 at 08 33 02@2x](https://github.com/user-attachments/assets/1639477c-88f0-4e7f-a72b-7b893139d469)
