### ISSUE TITLE
Publish documentation updates without releasing a new semver version

### ISSUE THREAD

**Issue by groue** [SwiftPackageIndex/SwiftPackageIndex-Server#3235]
Hello, I open this issue after the conversation with @finestructure at https://mastodon.social/@finestructure/112824515154640738.

**Please describe the bug**

I pushed a tag `0.9.0+doc-update-1` on groue/GRDBQuery, following `0.9.0` that contains a few typos. Note the plus sign, because this is not a pre-release version. It is a doc update. The hope was that SPI would build and publish the DocC changes under the `0.9.0` semver version. Precisely, after the new tag is pushed and processed, I would have expected that:

1. https://swiftpackageindex.com/groue/GRDBQuery keeps on displaying the 0.9.0 version.
2. https://swiftpackageindex.com/groue/GRDBQuery links to the documentation of `0.9.0+doc-update-1`, so that users don't read the typos.
3. https://swiftpackageindex.com/groue/GRDBQuery/documentation/grdbquery (without specific version) displays the documentation of `0.9.0+doc-update-1`, so that links to a stable url, that can be clicked months after they were published, always display the latest doc version, with eventual typos fixed.

What happens instead is that the new tag did not trigger a doc rebuilt by itself: https://mastodon.social/@finestructure/112824698710275787

**Comment by groue** [comment]
The more I think about it, the less I'm positive that this issue is a sensible request.

The argument _against_ is the following:

Packages and apps that depend on groue/GRDBQuery 0.9.0 should have `0.9.0` cloned on their machine. They would not get the same documentation as the documentation hosted on SPI, if SPI would build and display `0.9.0+doc-update-1` for `0.9.0`. There is no good reason for this inconsistency. We're no longer in the "good old days" where we just had to publish the doc online on some website - no: now the doc is embedded right into the clone.

In this trend of thought, a documentation update should be published as a patch release (`0.9.1` here), which is already correctly handled by SPI.

**Comment by daveverwer** [comment]
I think this is a very sensible approach. We don't want to put an onerous burden on package authors, but I think in this case you're correct that a patch release (which is, as you say, exactly what it is) is the most appropriate.

Thanks for putting thought into this @groue!

**Comment by groue** [comment]
That's fine for me. I'll let you discuss with @finestructure, and decide whether this issue should be closed, or if it can create other ideas - I'm not fully aware of the consequences of the surprise that a doc was not rebuilt on the push of `0.9.0+doc-update-1`.

**Comment by daveverwer** [comment]
Yes, I deliberately didn't close it in case @finestructure had any more thoughts. 

I'd be surprised if the release had any consequences when it wasn't picked up. We either pick up a tag based on our rules or we let it go past, and this one went past.

**Comment by finestructure** [comment]
Creating a new patch version is definitely the easiest solution for us :) And it certainly makes sense for the reason you lay out, @groue!

I'll go ahead and close this then.

**Comment by groue** [comment]
Thank your both for your support - three minds are better than one 👍
