### ISSUE TITLE
Add a Package page links to outdated info about generating documentation 

### ISSUE THREAD

**Issue by dempseyatgithub** [SwiftPackageIndex/SwiftPackageIndex-Server#3241]
The documentation callout on the Add a Package page (https://swiftpackageindex.com/add-a-package) has a [More information here](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/) link to the blog post announcing documentation hosting.

The top of that page has the message:

> The information in this blog post is superceded by our [official documentation](https://swiftpackageindex.com/SwiftPackageIndex/SPIManifest/documentation/spimanifest/commonusecases). Please refer to the documentation rather than this blog post.

The 'More information here' link should be updated to link to the official documentation.

**Comment by daveverwer** [comment]
Thanks @dempseyatgithub, I'll get this fixed 👍

**Comment by daveverwer** [comment]
Thanks for reporting this @dempseyatgithub! Fixed with #3247
