### ISSUE TITLE
Pre-1.0.0 versions are described as "stable" releases

### ISSUE THREAD

**Issue by stmontgomery** [SwiftPackageIndex/SwiftPackageIndex-Server#3261]
Swift packages whose latest tag is less than 1.0.0 have that version shown as the "latest **stable** release" on the SwiftPackageIndex website. Considering a pre-1.0.0 version "stable" seems in conflict with [SemVer item 4](https://semver.org/#spec-item-4):

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

For example: The package I primarily contribute to, [swift-testing](https://github.com/apple/swift-testing), currently has version 0.11.0 as its latest tag as of this writing. But on [its SPI page](https://swiftpackageindex.com/apple/swift-testing), that version is considered "stable".

**Explain the steps needed to reproduce the bug**

1. View the SwiftPackageIndex page for some package whose latest tag is less than 1.0.0. [swift-testing](https://swiftpackageindex.com/apple/swift-testing), for example.
2. View its latest tag information on the right hand column.
3. Notice that it says "stable".

**What was the expected behaviour?**

I would suggest special-casing this so that pre-1.0.0 versions are not considered stable. It can just say "latest release" instead of "latest **stable** release" for such versions, or similar phrasing. Versions ≥ 1.0.0 can still be described as stable.

**Screenshots**

<img width="550" alt="Screenshot 2024-07-31 at 1 53 25 PM" src="https://github.com/user-attachments/assets/edc80ec2-c7f9-45bf-bf00-28260d6bc372">

**What web browser were you using? (if relevant)**

n/a

**Additional context**

n/a

**Comment by daveverwer** [comment]
TIL something about SemVer. Thanks for pointing this out, @stmontgomery!

I think a potentially better fix for this would be to remove the word stable altogether, leaving Latest Release, Latest Pre-Release, and Default Branch for all packages.

Thanks for the report. We'll get it changed.
