### ISSUE TITLE
Check what happens if a force push changes upstream revisions

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#33]
Can we handle changes in tags or branches?

**Comment by daveverwer** [comment]
This looks like a possible way to solve this without a re-clone.

https://stackoverflow.com/a/9813888/4496

**Comment by finestructure** [comment]
Ah great, that should do!

**Comment by daveverwer** [comment]
If we want a package to test this with, I have a test package I made last year when I was thinking about the metadata issue that I'd be happy to do some force pushes to.

https://github.com/daveverwer/LeftPad

It's not in the index for obvious reasons but we could add it play with it on staging and remove it.

**Comment by finestructure** [comment]
I've just tested this locally and we'd be having problems with this scenario:

```
❯ git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Merge made by the 'recursive' strategy.
 test2 | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 test2
```

This is bringing up a commit prompt to complete a merge (because it can't fast-forward).

**Comment by finestructure** [comment]
Re: the package - that'd be a nice thing to have and to test the implementation!

**Comment by daveverwer** [comment]
There's always the nuclear option, which is actually what I did in the SwiftPM Library. If the pull fails, `rm -rf` the cloned repository and re-clone it. It doesn't happen often enough to be a stress on anything, and it always works.

**Comment by finestructure** [comment]
Yes, that would do - although I wonder how reliably we'd be able to detect the issue.

In any case, I think just ran a few tests and I believe the following updated command sequence should _always_ (FLW) bring us up to date with the upstream:

```
git fetch
git checkout "foo"
git reset "origin/foo" --hard
```

(For reference, out current sequence is:
```
            git reset --hard
            git fetch
            git checkout "main"
            git pull
```
So this would be shorter _and_ safer)


Here are the test cases I've run through:

- new branch:

```
❯ git fetch
  git checkout "foo"
  git reset "origin/foo" --hard

From github.com:finestructure/LeftPad
 * [new branch]      foo        -> origin/foo
Branch 'foo' set up to track remote branch 'foo' from 'origin'.
Switched to a new branch 'foo'
HEAD is now at bbb8de1 Test 4
```

- existing branch with updates

```
❯ git fetch
  git checkout "foo"
  git reset "origin/foo" --hard

remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), 250 bytes | 125.00 KiB/s, done.
From github.com:finestructure/LeftPad
   bbb8de1..cb50798  foo        -> origin/foo
Already on 'foo'
Your branch is behind 'origin/foo' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at cb50798 Test 5
```

- rewritten branch

```
❯ git fetch
  git checkout "foo"
  git reset "origin/foo" --hard
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), 252 bytes | 126.00 KiB/s, done.
From github.com:finestructure/LeftPad
 + cb50798...bdaa26f foo        -> origin/foo  (forced update)
Already on 'foo'
Your branch and 'origin/foo' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
HEAD is now at bdaa26f Test 5b
```

Can you think of any other scenarios we need to cover?

**Comment by daveverwer** [comment]
> Yes, that would do - although I wonder how reliably we'd be able to detect the issue.

Wouldn't the `git` command return a non-zero?

**Comment by finestructure** [comment]
I don't think it would in case of a rewritten upstream that it can merge successfully. Best case we'd stall on the commit message prompt, if there is one.

**Comment by daveverwer** [comment]
> Can you think of any other scenarios we need to cover?

Those all look good, but it's hard to know how the internet will tie itself into knots when given a length of rope as long as `git` 😂 

Can we raise a Rollbar if we encounter a situation other than these?

**Comment by finestructure** [comment]
I think we already to but I'll def double check as part of this!

**Comment by finestructure** [comment]
Just re-opening this so we can give the mechanism a spin on staging.

Test scenario:

- add `LeftPad` to index
- wait for it to be indexed
- force push a change on the default branch
- observe the change in staging

**Comment by daveverwer** [comment]
Added you as a maintainer on LeftPad... Use your newly granted power for good Sven! 😂

**Comment by finestructure** [comment]
I'm using an old package of mine, `ValueCodable`, instead so I can push to the default branch.

**Comment by finestructure** [comment]
Staging has nicely taken and rolled back a change to the platforms that I force reset:

Initial:

<img width="1247" alt="Screenshot 2020-06-21 at 17 16 33" src="https://user-images.githubusercontent.com/65520/85250756-c8aa9b80-b457-11ea-9d90-baa62cba2096.png">

Added `platforms:`

<img width="1247" alt="Screenshot 2020-06-21 at 18 56 02" src="https://user-images.githubusercontent.com/65520/85250780-d829e480-b457-11ea-80ce-1dcb0a92a449.png">

Forced pushed back to the original revision:

<img width="1247" alt="Screenshot 2020-06-22 at 07 11 23" src="https://user-images.githubusercontent.com/65520/85250823-eb3cb480-b457-11ea-8d59-c1cdd0f3fc29.png">

By contrats, prod is now stuck on the version _showing_ the platforms:

<img width="1247" alt="Screenshot 2020-06-22 at 07 11 33" src="https://user-images.githubusercontent.com/65520/85250854-00194800-b458-11ea-9281-49bd4c0cad02.png">

**Comment by finestructure** [comment]
I've checked and we're not rollbarring any errors here. The problem is that either we rollbar and get easily flooded by errors that break our API limit or we leave it to the console logs. It's very fiddly to decide whether to rollbar by error content: either we report all or we report only in isolated sections where we know the rate is going to be very small and the errors are going to be critical.

I think the console logs are the way to go here. I'm going to groom them a bit as part of #373 and then we can (should) also look into setting up alerts via Grafana/Loki.
