### ISSUE TITLE
Missing documentation for Empire package

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#3323]
I was expecting to my find DocC pages here, but they aren't present for https://swiftpackageindex.com/mattmassicotte/Empire.

https://swiftpackageindex.com/mattmassicotte/Empire/main/documentation

I'm not certain what I've done differently, but I've set up many other packages with docs and they all seem to work. Something is special here...

**What was the expected behaviour?**

Documentation is built and published.

**Screenshots**

**What web browser were you using? (if relevant)**

**Additional context**

Is there anything else we might find useful?

**Comment by daveverwer** [comment]
This is because we still use Swift 5.10 for the default documentation builds, and will do until 6 is out of beta. I raised a PR to fix the issue.

**Comment by mattmassicotte** [comment]
Ahhh of course! And so amazing you fixed it too. I really appreciate it!

**Comment by daveverwer** [comment]
My pleasure!

I won't manually clear the builds as we have a huge backlog right now with the Xcode 16 beta 6 run for Ready for Swift 6, but it will be eligible for a main branch build in a day or so.

I've added a reminder to check in on it over the weekend. I'll leave this open until then.

**Comment by daveverwer** [comment]
Docs are all there now. 🎉

https://swiftpackageindex.com/mattmassicotte/Empire/main/documentation/empire

Closing this.

**Comment by mattmassicotte** [comment]
Amazing! Thank you **so** much!
