### ISSUE TITLE
Issue with main branch - Swift 5.10 to 5.8

### ISSUE THREAD

**Issue by sabapathyk7** [SwiftPackageIndex/SwiftPackageIndex-Server#3335]
**Please describe the bug**

Please give a clear and concise description of what went wrong.

**Explain the steps needed to reproduce the bug**

1. Navigate to to '[…](https://swiftpackageindex.com/sabapathyk7/NetworkKit/builds)'
2. Click on '[…](https://swiftpackageindex.com/builds/5107C2C3-E78D-4AB2-A79A-B82D67830C50)'
3. See an error…Failed to build [NetworkKit](https://swiftpackageindex.com/sabapathyk7/NetworkKit), reference main (9f70ad), with Swift 5.10

**What was the expected behaviour?**
It should succeeds in the Swift 5.10 to 5.8 for main branch
**Screenshots**
<img width="891" alt="image" src="https://github.com/user-attachments/assets/ff83ac08-7293-4e76-bb6f-23209221b19b">

If applicable, please add screenshots to help explain your problem.

**What web browser were you using? (if relevant)** Chrome

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop/Tablet/Smartphone
- Browser [e.g. Chrome, Safari]
- Version [e.g. Version 15.1]

**Additional context**

Is there anything else we might find useful?

**Comment by finestructure** [comment]
Thanks for the report, @sabapathyk7 . It looks like this was a problem on your main branch and is fixed now:

<img width="751" alt="Screenshot 2024-08-27 at 09 27 28" src="https://github.com/user-attachments/assets/ac3ce689-e15f-4e66-a42c-968d651559a9">

Please reopen if you're seeing issues again!
