### ISSUE TITLE
Images aren't rendering in DocC

### ISSUE THREAD

**Issue by leogdion** [SwiftPackageIndex/SwiftPackageIndex-Server#3375]
**Please describe the bug**

It appears that images which are stored in the DocC Resources directory are not getting rendered on the DocC web site.

**Explain the steps needed to reproduce the bug**

Navigate to [the **SublimationBonjour** DocC Documentation page.](https://swiftpackageindex.com/brightdigit/SublimationBonjour/1.0.0/documentation/sublimationbonjour)

Here's the markdown which should display the image:

```markdown
# ``SublimationBonjour``

Use [Bonjour](https://developer.apple.com/bonjour/) for [Sublimation](https://github.com/brightdigit/Sublimation) for automatic discovery of your [Swift Server](https://www.swift.org/documentation/server/).

## Overview

![SublimationBonjour Logo](SublimationBonjour.svg)

When the Swift Server begins it will tell Sublimation the ip addresses or host names which are available to access the server from (including the port number and whether to use https or http). This is called a ``BonjourSublimatory``. 

![SublimationBonjour Diagram](SublimationBonjour-Diagram.svg)

The ``BonjourSublimatory`` then uses `NWListener` to advertise this information both by send the data encoded using Protocol Buffers as well as inside the Text Record advertised.

The iPhone or Apple Watch then uses a ``BonjourClient`` to fetch either an  `AsyncStream` of `URL` via ``BonjourClient/urls`` or simply get the ``BonjourClient/first()`` one available.
```

You can see the images in [the DocC Resources directory](https://github.com/brightdigit/SublimationBonjour/tree/main/Sources/SublimationBonjour/Documentation.docc/Resources).

**What was the expected behaviour?**

**Screenshots**

**Actual:**
<img width="1505" alt="Screenshot 2024-09-09 at 15 25 41" src="https://github.com/user-attachments/assets/cf54d11f-8bea-45da-a95b-3a8b953627d5">

**Expected**
<img width="1630" alt="Screenshot 2024-09-09 at 15 25 01" src="https://github.com/user-attachments/assets/3cfd7cee-4e30-458b-885d-2f4567959e63">

**What web browser were you using? (if relevant)**

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop
- Browser: Safari
- Version 18.1 (20619.2.1)

**Additional context**

Is there anything else we might find useful?

Not sure if this is an issue with the server or possibly the DocC web site builder.

**Comment by finestructure** [comment]
The problem is that we're sending SVGs like other images with a content type of `application/octet-stream`. When sending that as `image/svg+xml` they display correctly. I'm preparing a patch.

**Comment by leogdion** [comment]
Is there a way for me to see this fix? 

I'm not seeing any changes [here](https://swiftpackageindex.com/brightdigit/SublimationBonjour/1.0.0/documentation/sublimationbonjour)

**Comment by finestructure** [comment]
The fix now live:

<img width="1319" alt="Screenshot 2024-09-12 at 17 01 19" src="https://github.com/user-attachments/assets/37aea55f-4573-4aad-998f-0c9fa89a97e8">

**Comment by leogdion** [comment]
Thank you! 🙇
