### ISSUE TITLE
Include the number of stars as top level metadata

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#338]
How on earth did this not cross my mind when I was designing the new package page?!? I must be losing it.

The bullet point should be in the top section, and let's put it at the bottom, after all the others. The text will be short and it'll look good at the bottom. We can always move it later. The bullet should simply say:

* XXX stars.

I'll knock an icon together for this before launch, and also tackle #150 at the same time. @finestructure, if you could handle the bringing of the data through from the query into the HTML that'd be much appreciated!

**Comment by finestructure** [comment]
Heh, I've been suffering from product blindness as well 😅 

I'll wire that up, no problem.
