### ISSUE TITLE
Support Request: Why Doesn't "Documentation" CTA Render?

### ISSUE THREAD

**Issue by NicoHinderling** [SwiftPackageIndex/SwiftPackageIndex-Server#3393]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/EmergeTools/SnapshotPreviews-iOS

**Please explain what data is incorrect and what you expected to see**

For [our package](https://github.com/EmergeTools/SnapshotPreviews-iOS), I've added the .spi.yml file that is required as well as made sure that my documentation is indeed available via xCode. I looked at another package as an example ([spimanifest](https://swiftpackageindex.com/swiftpackageindex/spimanifest)) and while it has the "Documentation" link, [ours does not](https://swiftpackageindex.com/EmergeTools/SnapshotPreviews-iOS) :( 

I tried changing the structure of the .spi.yml file a few times and haven't been able to resolve this. I'm hoping I've missed some simple step, but at this point I'm not sure

**Comment by finestructure** [comment]
Thanks for the report, @NicoHinderling !

It looks like one of your targets isn't properly generating docs:

```
error: 'PreviewGallery' does not contain any documentable symbols or a DocC catalog and will not produce documentation
```

This is from the build logs here: https://swiftpackageindex.com/builds/F3A1FB40-386E-427A-B26B-4E01025C030A

You can see which builds are generating the docs via the little "document" symbol on the [build overview page](https://swiftpackageindex.com/EmergeTools/SnapshotPreviews-iOS/builds):

<img width="286" alt="Screenshot 2024-09-18 at 08 02 29" src="https://github.com/user-attachments/assets/c33be6ee-651b-4edb-b873-2659bfdef526">

**Comment by NicoHinderling** [comment]
Firstly, thank you for the super fast response! I scoured the configuration settings for my different targets and can't find a difference between the the ones that worked and the `PreviewGallery` target. I also tried generating the documentation locally both via xcode and CLI and both worked

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/78a35379-441f-480c-919d-a57ff1073801">
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/f8092ff2-ac9f-4190-8083-cae54661778c">

so I'm not really sure what could be causing the documentation for it to not be found. I have docc style documentation [in this file for example](https://github.com/EmergeTools/SnapshotPreviews-iOS/blob/main/Sources/PreviewGallery/PreviewData.swift#L12), so yeah I'm not sure why it isn't being picked up.

I can settle on just omitting this target, but I am curious what the cause could be.. 🤔

**Comment by finestructure** [comment]
I'm not sure why exactly the error is happening but I can reproduce the same error we're seeing when generating the docs via just `swift package preview-documentation`:

```
❯ env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun swift package \
      --disable-sandbox \
      --allow-writing-to-directory \
      ./docs \
      preview-documentation \
      --emit-digest \
      --disable-indexing \
      --output-path ./docs \
      --target PreviewGallery
Fetching https://github.com/apple/swift-docc-plugin from cache
Updating https://github.com/swhitty/FlyingFox.git
Updating https://github.com/EmergeTools/AccessibilitySnapshot.git
Updated https://github.com/EmergeTools/AccessibilitySnapshot.git (0.86s)
Updated https://github.com/swhitty/FlyingFox.git (0.86s)
Fetched https://github.com/apple/swift-docc-plugin from cache (0.95s)
Computing version for https://github.com/EmergeTools/AccessibilitySnapshot.git
Computed https://github.com/EmergeTools/AccessibilitySnapshot.git at 1.0.2 (0.02s)
Computing version for https://github.com/swhitty/FlyingFox.git
Computed https://github.com/swhitty/FlyingFox.git at 0.16.0 (0.02s)
Computing version for https://github.com/apple/swift-docc-plugin
Computed https://github.com/apple/swift-docc-plugin at 1.4.3 (0.62s)
Fetching https://github.com/swiftlang/swift-docc-symbolkit from cache
Fetched https://github.com/swiftlang/swift-docc-symbolkit from cache (1.10s)
Computing version for https://github.com/swiftlang/swift-docc-symbolkit
Computed https://github.com/swiftlang/swift-docc-symbolkit at 1.0.0 (0.50s)
Creating working copy for https://github.com/apple/swift-docc-plugin
Working copy of https://github.com/apple/swift-docc-plugin resolved at 1.4.3
Creating working copy for https://github.com/swiftlang/swift-docc-symbolkit
Working copy of https://github.com/swiftlang/swift-docc-symbolkit resolved at 1.0.0
Building for debugging...
[61/61] Applying snippet-extract
Build complete! (17.21s)
Building for debugging...
[43/43] Compiling PreviewGallery ModuleScreens.swift
Build complete! (8.67s)
error: 'PreviewGallery' does not contain any documentable symbols or a DocC catalog and will not produce documentation
```

Make sure to append

```swift
package.dependencies.append(
    .package(url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0")
)
```

to your `Package.swift` file to be able to run this command.

**Comment by finestructure** [comment]
FWIW, I can fix this by switching to doc generation on `iOS` instead of the default, `macOS` with SwiftPM:

```yml
# .spi.yml
version: 1
builder:
  configs:
    - documentation_targets: [SnapshotPreferences, Snapshotting, SnapshottingTests, PreviewGallery]
      platform: iOS
```

Although it looks like your package is (despite its name mentioning `iOS`) macOS compatible 🤷‍♂️

**Comment by finestructure** [comment]
I'm guessing when you're generating docs via Xcode's command you're running it in a way that's similar to our doc gen process on iOS and that's why it works there as opposed to via `swift package generate-documentation`.

**Comment by NicoHinderling** [comment]
Gotcha... yes the PreviewGallery target is really only supported for iOS right now, so I guess that makes sense. We recently added macOS support to the rest of the targets though.

I was able to reproduce it on our side. It seems like there isn't a way to specify two sets of targets (one group with "all" platform, one with just "ios" as the platform) looking at the docs. If I'm wrong please let me know & I'll be happy to do so!

for now though, we'll just omit the PreviewGallery target's docs by removing it from the `.spi.yml` file. Thank you for the guidance @finestructure !

**Comment by finestructure** [comment]
Ah, that makes sense then. You'd either have to skip the target or switch generation over to iOS, as indicated. Glad it's sorted!
