### ISSUE TITLE
The sitemap isn't showing any packages

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#340]
I see no packages at all on the sitemap.xml now it's deployed to production. This is the entire content of it:

```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <url>
    <loc>https://swiftpackageindex.com/faq</loc>
    <changefreq>weekly</changefreq>
  </url>
  <url>
    <loc>https://swiftpackageindex.com/</loc>
    <changefreq>hourly</changefreq>
  </url>
  <url>
    <loc>https://swiftpackageindex.com/privacy</loc>
    <changefreq>monthly</changefreq>
  </url>
</urlset>
```

**Comment by finestructure** [comment]
For some inexplicable reason while implementing it I thought, well, we're not going to want to generate that for all 2.6k packages. When of course that's exactly what we want to do and I even said I want to use it to generate a test file from it 🤦
