### ISSUE TITLE
Missing documentation for GRDB 7 beta

### ISSUE THREAD

**Issue by groue** [SwiftPackageIndex/SwiftPackageIndex-Server#3407]
Hello,

I released GRDB 7.0.0-beta a few hours ago (Xcode 16+), and it was eventually built by SPI: https://swiftpackageindex.com/groue/GRDB.swift/builds

However, this beta release is nowhere to be seen in the documentation menu: https://swiftpackageindex.com/groue/GRDB.swift/documentation/grdb

And the documentation for the master branch does not reflect the latest state of that branch: https://swiftpackageindex.com/groue/GRDB.swift/master/documentation/grdb (that's not obvious, but I see outdated text and missing articles).

<img width="311" alt="Capture d’écran 2024-09-29 à 13 41 36" src="https://github.com/user-attachments/assets/a3ef1eaf-76be-4c36-bff4-94a311c1fbd0">

I really wish DocC was properly updated, so that I can announce the new release, and link to important new DocC pages.

I could not find traces of the problem in https://swiftpackageindex.com/groue/GRDB.swift/builds or https://swiftpackageindex.com/builds/9A5AA444-A305-4D26-A70B-B2E7B63D5D7D

Is there something I should do on the GRDB repo in order to have documentation properly generated?

**Comment by groue** [comment]
Unrelated question :-)

The page https://swiftpackageindex.com/builds/9A5AA444-A305-4D26-A70B-B2E7B63D5D7D mentions "Swift 6 data race errors: 9". I'd be curious to know about them, if it's possible to have this information.

**Comment by finestructure** [comment]
> The page https://swiftpackageindex.com/builds/9A5AA444-A305-4D26-A70B-B2E7B63D5D7D mentions "Swift 6 data race errors: 9". I'd be curious to know about them, if it's possible to have this information.

That's very likely this issue here, which unfortunately we can't fix ourselves: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3233

**Comment by groue** [comment]
Oh, thank you very much @finestructure, I did not think about that at all. Let's fix my other libs as well :-)

**Comment by groue** [comment]
I reopen, because v7.0.0-beta.2 was processed, and documentation is still not online.

There is no urgency.

**Comment by finestructure** [comment]
Probably just a caching delay, I can see it now:

![CleanShot 2024-09-29 at 20 12 05@2x](https://github.com/user-attachments/assets/3c667ae4-1620-4405-a4d1-8157e6f544c6)

**Comment by finestructure** [comment]
(Make sure to clear your browser cache, too. Sometimes the switcher at the top is cached and doesn't have the latest version.)

**Comment by groue** [comment]
💯🥳 Thank you very much!
