### ISSUE TITLE
Change platform and Swift version shields.io badge colour

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#3411]
### Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/3410

Change the colour of the background for the badges to blue to indicate information rather than any other kind of status.

![Screenshot 2024-10-01 at 10 18 41@2x](https://github.com/user-attachments/assets/b1e24c77-f417-4554-a5dc-69c2b94ae388)

The logo colour should not be changed, only the background.

**Comment by daveverwer** [comment]
The mid-blue is far too strong 😬

![Screenshot 2024-10-01 at 11 09 02@2x](https://github.com/user-attachments/assets/3a7a106a-44a9-4d87-99ad-fb8ca38b6a9d)

**Comment by hassila** [comment]
What about the blue at the button you use?

<img width="193" alt="image" src="https://github.com/user-attachments/assets/8db54fc5-1737-4458-b5fb-7f838d161087">

**Comment by daveverwer** [comment]
That's the same mid-blue, just the dark mode version of it.

Shields.io have a standard "blue". I'm trying that, but it takes a while to iterate as it needs to be deployed to staging every time.
