### ISSUE TITLE
Compatibility on the site

### ISSUE THREAD

**Issue by eugene-software** [SwiftPackageIndex/SwiftPackageIndex-Server#3426]
There are compatibility issue persists for my package:

"This package currently has no compatibility information. Builds to determine package compatibility are starting, and compatibility information will appear soon. If this message persists for more than a few minutes, please [raise an issue]"

This banner persists more than 1 hr

Package url: https://swiftpackageindex.com/eugene-software/EZANetwork#readme

**Comment by daveverwer** [comment]
We're under a heavy build load at the moment and that message is showing for new packages for longer than it normally does. I'll check in again on this in the morning, but I'm confident it'll be gone by then.

Sorry for the bad luck of submitting while we're under load!

**Comment by daveverwer** [comment]
All but one builds are now done, so I'll close this. Apologies for the slower than usual results.
