### ISSUE TITLE
Swift 6.0 builds have been stuck in "Pending" for a long time

### ISSUE THREAD

**Issue by DevYeom** [SwiftPackageIndex/SwiftPackageIndex-Server#3427]
**Please describe the bug**

I checked why the Swift 6.0 badge wasn't showing up, and it turns out the Swift 6.0 build is stuck in a pending state.

**Explain the steps needed to reproduce the bug**

1. https://swiftpackageindex.com/DevYeom/OneWay/builds

**What was the expected behaviour?**

- Build succeeded

**Screenshots**

<img width="857" alt="Screenshot 2024-10-11 at 10 07 19" src="https://github.com/user-attachments/assets/5b2b0799-0c16-4b8a-87a6-66be46cd1867">

**What web browser were you using? (if relevant)**

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop
- Browser: Safari
- Version: 17.6

**Additional context**

Is there anything else we might find useful?

**Comment by finestructure** [comment]
Thanks for the report, @DevYeom ! During the introductory phase of Swift 6, we're rebuilding all Swift 6 builds periodically, which takes about 7 days. During that time, Swift 6 builds may show pending until we've completed that processing run. Sorry for the inconvenience!

**Comment by DevYeom** [comment]
Thanks!
