### ISSUE TITLE
CacheAdvance build results are "pending"

### ISSUE THREAD

**Issue by dfed** [SwiftPackageIndex/SwiftPackageIndex-Server#3428]
Not sure why, but the build results here are "pending": https://swiftpackageindex.com/dfed/CacheAdvance/builds

Latest commit was two weeks ago.

**Comment by finestructure** [comment]
Thanks for the report, @dfed !

We're currently reprocessing Swift 6 builds to capture the latest data for the [Ready for Swift 6 page](https://swiftpackageindex.com/ready-for-swift-6). This meant resetting all the builds and created a big backlog.

We should be caught up by Tuesday. Thanks for your patience!

**Comment by dfed** [comment]
Understood! Thanks for the explanation + for providing this seriously awesome community service 😄
