### ISSUE TITLE
Avoid 404s during version reconciliation

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#343]
The [last smoke test](https://gitlab.com/finestructure/swiftpackageindex/-/jobs/586574984) picked up a few 404s:

- https://swiftpackageindex.com/BenEmdon/CenteredCollectionView (still 404)
- https://swiftpackageindex.com/GEOSwift/GEOSwift (now 200)
- https://swiftpackageindex.com/Moya/Moya (now 200)
- https://swiftpackageindex.com/ashleymills/Reachability.swift (now 200)
- https://swiftpackageindex.com/llvm-swift/LLVMSwift (now 200)
- https://swiftpackageindex.com/pointfreeco/swift-tagged (now 200)
- https://swiftpackageindex.com/square/Valet (now 200)
- https://swiftpackageindex.com/stephencelis/SQLite.swift (now 200)

**Comment by finestructure** [comment]
A [rerun](https://gitlab.com/finestructure/swiftpackageindex/-/jobs/586893074) triggers 404 on the same https://swiftpackageindex.com/BenEmdon/CenteredCollectionView and then 6 other different urls.

Weird.

**Comment by daveverwer** [comment]
Intermittent 404s isn't a great sign. I can't think what could be causing that.

**Comment by daveverwer** [comment]
https://github.com/BenEmdon/CenteredCollectionView is a valid package too. It also doesn't show up in search results.

**Comment by finestructure** [comment]
The good news is we know exactly when it started, because that test has been running since 3c6510c0d2e33565932ba5832a78af20d46f66ea 5 days ago, over many releases. It must be something that came with last night's 0.4.3 release.

**Comment by finestructure** [comment]
I wonder if it's the ErrorMiddleware change. I'll try and repro locally and see if a roll back fixes it.

**Comment by daveverwer** [comment]
That's certainly the most likely of yesterdays change to cause this behaviour.

But that wouldn't explain why BenEmdon/CenteredCollectionView is being excluded from search results. I just checked on SwiftPM.co to see if that struggled, but it's fine. https://swiftpm.co/?query=CenteredCollectionView

**Comment by finestructure** [comment]
That is very likely due to the query rejecting it because of a nil value. I suspect that's a separate issue.

**Comment by finestructure** [comment]
I can repro everything locally, just a matter of debugging through now.

**Comment by finestructure** [comment]
So, CenteredCollectionView has no versions in the db, which leads to

```
                guard let title = p.name() else { return nil }
```

returning `nil` and then a 404, because `func name() -> String? { defaultVersion()?.packageName }`.

I'll create a separate issue to follow up why there's not even a default branch version. The branch is `master` in `repositories`, so we do have a value.

**Comment by finestructure** [comment]
Important note: when copying the prod db it can happen that a snapshot is taken during an analysis phase. For instance I've just looked at a package locally that gave a 404 but worked in prod. That was because I snapped right before versions were written. Stopping processing, taking a snapshop, and then restarting fixes that.

```
# on mini
docker stop spi_analyze_1 spi_ingest_1 spi_reconcile_1
```
- snapshot
```
# on mini
docker start spi_analyze_1 spi_ingest_1 spi_reconcile_1
```

**Comment by daveverwer** [comment]
Better than that, let's auto snapshot every 24 hours. It's rare we'll need one more recent than that and if we do, this is the way to do it.

Added as #346

**Comment by finestructure** [comment]
Oooh, it's dawning on me what's happening. We're opening ourselves up to a 404 when a package is visited in the short interval between removing the versions and refreshing them.

Since we're mass-testing urls in the smoke test that's why we're seeing it.

And the reasing we're seeing it after 0.4.3 is that now we're actually reporting them as 404s. Before we were just masking them as error pages which the smoke tester looking for 200s accepted.

**Comment by finestructure** [comment]
That needs proper fixing.

**Comment by daveverwer** [comment]
Yep, this sounds like a perfect case for a transaction. There's probably a few places where we need to do this.

**Comment by daveverwer** [comment]
> That needs proper fixing.

I think in this case a transaction is a fine fix. Since it's not processing any kind of user data at all the cost of a failed transaction is minimal. If it fails for some reason, we'll just get to whatever it was next time it runs.

**Comment by finestructure** [comment]
So this seems to have helped a lot. However, having run the smoke test a good dozen times now, I still see the occasional run where _one_ (random) test will 404 out of the bunch. Whenever I check manually the url is served just fine.

I feel like the tx certainly helped, because prior to this fix we got 7-8 errors per run.

FWIW, it hasn't failed when running the same set of tests locally (where I have no processing running).

I'll take look into whether we need to guard the read query as well. But I think a single select does get a consistent snapshot in Postgres.

There's no other delete than the versions that could mess up a fetch as far as I can see. The reconciler deletes only whole package trees (and there was no change in the master list today, let alone a deletion) and ingestion doesn't delete anything.

**Comment by daveverwer** [comment]
Could it be the products table? I think the transaction was only around versions in the PR?

**Comment by finestructure** [comment]
I don't think so. Missing products would lead to gaps in the package page but the only way it would be a 404 is if either of Package/Repositor/Version is missing or if `package_name` is `NULL` for the version tracking the default branch.

In fact, just to be sure, I've update the tests and removed the products for the happy path. https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/349

**Comment by finestructure** [comment]
Oh, I see. I wrote it right there: "if package_name is NULL for the version tracking the default branch".

There's the version creation step but it's created with `package_name` = `NULL` and only later updated 🤦

**Comment by finestructure** [comment]
This is going to be hard to get into the same transaction, due to method boundaries.

**Comment by finestructure** [comment]
Actually, it's not that bad.

**Comment by finestructure** [comment]
Ok, I've run the smoke test a dozen times now without any more errors. I think we're in the clear here now.

**Comment by daveverwer** [comment]
We'll know over time if there's a subtle problem too as it's running after every deploy
