### ISSUE TITLE
The documentation is not generated for the Benchmark package

### ISSUE THREAD

**Issue by hassila** [SwiftPackageIndex/SwiftPackageIndex-Server#3431]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/ordo-one/package-benchmark

**Please explain what data is incorrect and what you expected to see**

When clicking on the documentation link, it shows documentation for 125.0.0 and main, but in reality the documentation is stale for both of those - it was updated in 127.0.0, but those changes aren't visible.

Also, the package is not built with the 6.0 toolchain, it just is stuck in "pending", not sure it is related, but thought I'd mention it if it's related.

Specifically this page in the documentation was updated in 127.0.0:

<img width="1118" alt="image" src="https://github.com/user-attachments/assets/7ba33859-af73-4dec-8eb2-e5725090712d">

(here generated with Xcode)

**Comment by finestructure** [comment]
Thanks for the report, @hassila !

We're currently reprocessing Swift 6 builds to capture the latest data for the [Ready for Swift 6 page](https://swiftpackageindex.com/ready-for-swift-6). This meant resetting all the builds and created a big backlog.

Unfortunately, this also impact documentation generation. We start this process last Tuesday, so it might have impacted your 1.27.x releases. However, the 1.26.0 release should be up, so I'm guessing there's something else amiss with the documentation generation for your package on Linux.

We'll know once the Swift 6 pass is finished. (Note that with the release of Swift 6 we've changed to generating the docs with Swift 6, which might be relevant here.)

We're expecting to catch up with all the Swift builds later tonight (in ~14h).

I'll follow up with this when we're caught up.

**Comment by hassila** [comment]
Alright, that probably explains all, thanks for the quick response!

**Comment by hassila** [comment]
'''

SyncDocs
========================================
Doc archive source directory: $PWD/.docs/ordo-one/package-benchmark/1.27.2
File count: 426
Doc size:   5.0MB
Preparing doc bundle ...
Error while generating docs: Error Domain=NSCocoaErrorDomain Code=516 "A file with the same name already exists."
✅  Doc result (failed) reported
Done.
'''

**Comment by finestructure** [comment]
Interesting! I'll take a closer look at what's going on here, thanks for the details.

**Comment by finestructure** [comment]
Actually, another idea if it has to be Linux: You could generate your docs with Swift 5.10 for now, that should also fix it.

**Comment by hassila** [comment]
I'll go and try to find why we built docs on linux specifically, my memory is hazy at this point - thanks, will try with one of those

**Comment by hassila** [comment]
We did that in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2187

**Comment by hassila** [comment]
I'll try switching to 5.10 for now, let's see when it goes through the next iteration if it works.

**Comment by finestructure** [comment]
Great, feel free to ping me here and I'll give the doc gen a bump to the top of the queue and sorry for the inconvenience!

**Comment by hassila** [comment]
Np, ping :-)

**Comment by finestructure** [comment]
It’s reran this earlier but forgot to tell you! Have a look, I believe the main branch docs are now up to date. (Slightly different than your screenshot but looking at the source I think that page has changed since.)

**Comment by finestructure** [comment]
I've added a temporary workaround on our end to support generating docs on Linux/Swift 6.0 and with that I've been able to bring back the 1.27.2 docs as well.

![CleanShot 2024-10-17 at 11 07 27@2x](https://github.com/user-attachments/assets/2ab49c0f-4f55-45f6-ab36-379ec659c675)

I don't think there's a huge difference between 6.0 and 5.10 but you may want to undo that change to build with 5.10 again.

I'll keep this issue open to track the proper fix in the upstream package(s).

Thanks again for the report that helped us spot this problem!

**Comment by hassila** [comment]
Ok, thank you! Then I'll put back 6.0, the docs looks updates now.

**Comment by hassila** [comment]
Ok, super, will close this one then, thanks!
