### ISSUE TITLE
/BenEmdon/CenteredCollectionView returns 404

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#345]
Follow up of #343

So, CenteredCollectionView has no versions in the db, which leads to

```
                guard let title = p.name() else { return nil }
```

returning `nil` and then a 404, because `func name() -> String? { defaultVersion()?.packageName }`.

I'll create a separate issue to follow up why there's not even a default branch version. The branch is `master` in `repositories`, so we do have a value.

**Comment by finestructure** [comment]
NB that we could change that line to

```
                let title = p.name() ?? ""
```

or `"–"` to get one of the following:

<img width="975" alt="Screenshot 2020-06-09 at 09 20 55" src="https://user-images.githubusercontent.com/65520/84118058-bf223c00-aa32-11ea-8490-c82a1288fd4d.png">
<img width="975" alt="Screenshot 2020-06-09 at 09 21 39" src="https://user-images.githubusercontent.com/65520/84118072-c47f8680-aa32-11ea-8a5c-5560d9de6f8f.png">

That's not a great result but probably preferable over a 404.

**Comment by finestructure** [comment]
One argument _not_ to do that though is the only reason we're seeing this is the 404 we got in the test.

**Comment by daveverwer** [comment]
Yea I don't think we should do this, given that we're running a smoke test regularly the 404 is a good indicator that something needs looking at.

I don't get notifications when that smoke test fails, but I assume you do? I don't seem to get any notifications from GitLab apart from the successful deploy one, even though I'm subscribed to everything.

**Comment by finestructure** [comment]
This package has actually recovered in prod now.

**Comment by finestructure** [comment]
Yes, I'm getting emails for all of those. Weird that these don't come through... We could send alerts to a slack channel or some other messaging service.
