### ISSUE TITLE
Documentation building stuck on "Pending"

### ISSUE THREAD

**Issue by sindresorhus** [SwiftPackageIndex/SwiftPackageIndex-Server#3532]
The build for building the docs of v9 of Defaults package has been stuck on "pending" for many days: https://swiftpackageindex.com/sindresorhus/Defaults/builds

**Comment by finestructure** [comment]
We're currently running a full Swift 6 rebuild and are expecting to be caught up again late tomorrow evening. Sorry for the inconvenience!

**Comment by finestructure** [comment]
The builds have caught up now, thanks for the report.

**Comment by finestructure** [comment]
Yes, this is a known issue that we're actively trying to work around: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3529#issuecomment-2516703633
