### ISSUE TITLE
Debug RSS releases

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#354]
I'm still getting weird result from the Releases RSS feed.

It is mostly the same as our "Recent Releases" on the site but often there's something missing or something extra. I can't make sense of it.

<img width="582" alt="Screenshot 2020-06-10 at 07 18 40" src="https://user-images.githubusercontent.com/65520/84229765-b55c0f80-aaea-11ea-8c05-77e795bebcf3.png">

I'll capture the feeds output every hour to see if there's something funny going on.

**Comment by finestructure** [comment]
FWIF, the packages feeds seems to be working fine.

**Comment by finestructure** [comment]
```
#!/bin/bash

set -eu

while true; do
    date=$(date "+%Y-%m-%d %H:%M:%S")
    curl https://swiftpackageindex.com/sitemap.xml | xmllint --format - > sitemap.xml
    git add sitemap.xml
    git commit -m "Snapshot $date" 
    sleep 30*60
done
```

**Comment by daveverwer** [comment]
Yep, there's something not right... here's this morning's new items in Reeder, and on the site:

<img width="347" alt="Screenshot 2020-06-10 at 07 36 08@2x" src="https://user-images.githubusercontent.com/5180/84235003-11279800-aaed-11ea-9282-6ee5a5146536.png">

<img width="300" alt="Screenshot 2020-06-10 at 07 35 51@2x" src="https://user-images.githubusercontent.com/5180/84234978-0a992080-aaed-11ea-873a-b2158e1bd938.png">

Also, the version number isn't showing up in the title of the releases feed, and neither feed shows any body copy (in Reeder at least). I'll raise a separate bug for that.

**Comment by daveverwer** [comment]
Just checked the feed in Reeder and it's not great:

<img width="348" alt="Screenshot 2020-06-11 at 09 46 09@2x" src="https://user-images.githubusercontent.com/5180/84364868-8fa53800-abc8-11ea-9b1d-cb5317c9d73f.png">

Compared to:

<img width="315" alt="Screenshot 2020-06-11 at 09 47 38@2x" src="https://user-images.githubusercontent.com/5180/84364899-99c73680-abc8-11ea-8164-14fc29cc639e.png">

**Comment by finestructure** [comment]
???

<img width="659" alt="Screenshot 2020-06-11 at 16 15 19" src="https://user-images.githubusercontent.com/65520/84397363-eded0d80-abfe-11ea-996e-6ffc3acae698.png">

**Comment by daveverwer** [comment]
This RSS feed! What on earth... 🤯

If it's any help, mine all show the correct dates (in Reeder too) but I pass mine through Inoreader on the way to Reeder.

<img width="337" alt="Screenshot 2020-06-11 at 15 18 53@2x" src="https://user-images.githubusercontent.com/5180/84397740-f2adc380-abf6-11ea-8545-9b86b52fb0b0.png">

**Comment by finestructure** [comment]
Oh wait, today is the 11th 😅 . I thought it's from the future but it's probably just something old that's been flushed from my feed. Sometimes happens when it's resetting.

**Comment by finestructure** [comment]
Ok, this is looking better now after the reset. Not celebrating yet though. I just checked and the fix went up only at 3.15pm UK time. After that my feed looks ok:

<img width="782" alt="Screenshot 2020-06-11 at 18 08 20" src="https://user-images.githubusercontent.com/65520/84412349-6a87e800-ac0f-11ea-8ce1-bed56b24a531.png">

There are a couple of duplicates from earlier in the day but those are very likely from old local state.

**Comment by finestructure** [comment]
Another interesting aspect my feed watcher just highlighted is that we do produce "out of order" entries in that list, because we don't necessarily analyse package in release order. For instance see this diff here:

<img width="783" alt="Screenshot 2020-06-11 at 18 17 53" src="https://user-images.githubusercontent.com/65520/84412684-e124e580-ac0f-11ea-89f9-2537b424d128.png">

Combine comes in _second_ after Turf which appeared as new in the snapshot just before. But its release date was earlier, so it comes second in reverse chronological order.

I believe that should be fine for feed readers - is does seem to be ok, at least as of now.

One possible explanation is that due to the guids not having been unique before, the back insertions wreaked havoc with the order and pulled wrong things to the front?

**Comment by daveverwer** [comment]
As long as we output that feed ordered by the date of the release itself, not when we noticed it (which I think we are) then I think this will always be correct.

**Comment by finestructure** [comment]
BTW, that feed that you posted here https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/354#issuecomment-642689563 is the package one and that looks ok 🙂

I.e. as of right now both feeds look good on my end.
