### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#356]
Once the site is live we should consider setting up a staging environment for our default deploy location, with builds then being promoted to production.

**Comment by finestructure** [comment]
- [ ] set up new machine
- [ ] add GL runner
- [ ] tweak env variables to use same base set
- [ ] configure automatic deploy from any hash
- [ ]

**Comment by finestructure** [comment]
We decided to branch at the Gitlab repository level instead of at the env variables level.

Meaning:

set up spi-dev GL project
add variables
add GL runner with dev tag
configure automatic deploy from main
allow ad hoc deploy from any hash

later on: allow import from prod db snapshot

**Comment by finestructure** [comment]
- [ ] Add new Github account
- [ ] create `GITHUB_TOKEN`
- [ ] add to secrets

**Comment by finestructure** [comment]
FYI, I've changed the prod GH token account to `spi-prod` and created a new one `spi-test` (`spi-dev` was unavailable) for the dev token.
