### ISSUE TITLE
RSS feed granularity

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#360]
I would love to read a feed that included every major and minor feed release, but I don't care much about patch releases. We should have a query parameter on the releases feed that allows this:

* `https://swiftpackageindex.com/releases.rss` - All releases
* `https://swiftpackageindex.com/releases.rss?granularity=minor` - All major (x) and minor (x.x) releases, exclude patch (x.x.x) releases.
* `https://swiftpackageindex.com/releases.rss?granularity=major` - All major (x) releases, exlude minor (x.x) and patch (x.x.x) releases.

We should add two more autodiscovery meta tags for the two new feeds too.

**Comment by finestructure** [comment]
- [ ] add filter
- [ ] add query params
- [ ] add meta tags
