### ISSUE TITLE
Investigate tooManyRequests Rollbar item

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#365]
Started reporting a lot last night after we rolled out the alert change:

https://rollbar.com/finestructure/SPI-server/items/15/

**Comment by finestructure** [comment]
Not good, we are in fact at 0 at the moment:

```
Thu 11 Jun 2020 07:31:30 CEST
rate.remaining: 0
```

**Comment by finestructure** [comment]
Well, of course we're burning through our request budget at twice the rate...

🤦‍♂️

The Linode box is running with the same API key.

**Comment by finestructure** [comment]
I've stopped services there now. Our budget has reset 20 mins ago and I had stopped requests on the mini at that time. On the next deploy we'll go up again with just the mini, a pretty intect budget _and_ a 10 min cool-off.

That should keep everything in the clear and we can roll back to 5 min cool-off later on if we want.

**Comment by daveverwer** [comment]
I'm not sure if notifications are working this morning, but if you get this email do you wanna have a quick chat about this?
