### ISSUE TITLE
Off by one error in number of releases

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#375]
Was just checking out [this repository](https://swiftpackageindex.com/twostraws/Markdown) after it came back from the `main` branch issue and noticed that the number of releases is being misreported as 2 when it has only had 1.

https://swiftpackageindex.com/twostraws/Markdown

<img width="591" alt="Screenshot 2020-06-11 at 11 18 12@2x" src="https://user-images.githubusercontent.com/5180/84373986-43acc000-abd5-11ea-966b-6d554bbba9e6.png">

https://github.com/twostraws/Markdown/releases

---

So I checked a couple more repositories:

Alamofire was fine (always my go-to test package) is fine, 81 releases in both places:

https://swiftpackageindex.com/Alamofire/Alamofire 81
https://github.com/Alamofire/Alamofire 81

However several others were off by 1 too:

https://swiftpackageindex.com/belozierov/SwiftCoroutine 43
https://github.com/belozierov/SwiftCoroutine 42

https://swiftpackageindex.com/davidask/Futures 13
https://github.com/davidask/Futures 12

https://swiftpackageindex.com/SDGGiesbrecht/SDGCornerstone 70
https://github.com/sdggiesbrecht/sdgcornerstone 69

Looks like the majority are off by one. Alamofire was the only one that was correct from a quick look

**Comment by finestructure** [comment]
Oh, actually I'm pretty sure they're all off by one: I forgot to filter by sem ver. They're all including the default branch!
