### ISSUE TITLE
Autocomplete list overlaps "Recent" lists and can't be dismissed

### ISSUE THREAD

**Issue by manmal** [SwiftPackageIndex/SwiftPackageIndex-Server#392]
Just in case there's interest in a possible solution:
Personally, I'm used to the way Google's seach box works. If the textfield loses focus, the autocomplete list is hidden. Google only shows the autocomplete list again if the user enters another character, but that always annoyed me - I think the list should be shown as soon as the textfield regains focus.

**Comment by daveverwer** [comment]
> If the textfield loses focus, the autocomplete list is hidden. Google only shows the autocomplete list again if the user enters another character, but that always annoyed me - I think the list should be shown as soon as the textfield regains focus.

Yep, this is the fix 👍 Thank you

(I had noticed this one but it just didn't quite make it in for launch 😬)

**Comment by daveverwer** [comment]
Just realised this is already in the backlog. Moving your comment over there and closing this in favour of #218
