### ISSUE TITLE
Follow up on 4 smoke test 404s

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#399]
https://gitlab.com/finestructure/swiftpackageindex/-/jobs/593828863

- https://swiftpackageindex.com/ArtSabintsev/FontBlaster
- https://swiftpackageindex.com/ArtSabintsev/Freedom
- https://swiftpackageindex.com/ArtSabintsev/Guitar
- https://swiftpackageindex.com/ArtSabintsev/Zephyr

**Comment by finestructure** [comment]
Looking at Guitar, I see that we're parsing the releases but it seems to be lacking a `.branch("master")` default branch revision in `versions`.

Something wrong with the package file perhaps? https://github.com/ArtSabintsev/Guitar/blob/master/Package.swift

**Comment by finestructure** [comment]
Unlikely, we're properly indexing https://swiftpackageindex.com/ArtSabintsev/Siren which has

```
    platforms: [.iOS(.v8)],  
```

**Comment by finestructure** [comment]
Oh, interesting!

```
/Users/sas/Projects/SPI-Server/SPI-checkouts/github.com-artsabintsev-guitar/Package.swift:13:5: error: argument 'platforms' must precede argument 'products'
    platforms: [.iOS(.v9)],  
~~~~^~~~~~~~~~~~~~~~~~~~~~"
Output: """ (id: Optional(66AE3416-2D24-4663-B9D1-ED85B9C8BAFC))
```

FYI @ArtSabintsev - your package Guitar - and likely the other three as well - seem to be failing indexing because of this.

The release tags are coming through but if you swap around those two parameters in your `Package.swift` file the packages should be coming through ok.

**Comment by ArtSabintsev** [comment]
hey, sorry, mind telling me what I need to do to fix this issue? Where does `products` go? Thank you for letting me know.

**Comment by ArtSabintsev** [comment]
Oh, interesting, platforms goes _before_  products. Cool, will take care of this on my end and push.

**Comment by ArtSabintsev** [comment]
ok, I updated it for:

https://swiftpackageindex.com/ArtSabintsev/FontBlaster
https://swiftpackageindex.com/ArtSabintsev/Freedom
https://swiftpackageindex.com/ArtSabintsev/Guitar
https://swiftpackageindex.com/ArtSabintsev/FontBlaster
https://swiftpackageindex.com/ArtSabintsev/Freedom
https://swiftpackageindex.com/ArtSabintsev/Guitar
https://swiftpackageindex.com/ArtSabintsev/Siren
https://swiftpackageindex.com/ArtSabintsev/Zephyr

**Comment by ArtSabintsev** [comment]
Assume version tags will be pushed in 5 minutes from this message, as I need to update it for CocoaPods as well.

**Comment by finestructure** [comment]
Hi @ArtSabintsev - no need to tag, the issue was actually with indexing the default branch.

It should correct itself within the couple of hours or so. Thanks for taking a look!

**Comment by ArtSabintsev** [comment]
Got it - tagging anyway since I made minor changes anyway! Mind pinging me once you know if the issue has resolved or if further tweaks are needed? Thanks!

**Comment by finestructure** [comment]
Definitely, thanks @ArtSabintsev !

**Comment by finestructure** [comment]
@ArtSabintsev Everything except Guitar has now recovered. I’ll have a look what’s going on with that one tomorrow.

**Comment by ArtSabintsev** [comment]
I figured it out - the manifest was missing the preceding period around the `.tvOS(.v10)` line.

**Comment by finestructure** [comment]
Ah excellent. It just occurred to me that you could also run `swift package dump` to verify it’s ok but too late :)

**Comment by ArtSabintsev** [comment]
I just ran `swift dump-package` and the JSON was spit out properly, so I think we're golden. I don't see any changes yet for that one library, but it's only been 2 hours.

**Comment by ArtSabintsev** [comment]
Ok, confirmed that it's working now. We're good to close this issue. Thanks again for letting me know! 

This is an awesome idea - just wanted to say that as well.

**Comment by finestructure** [comment]
Great, thanks @ArtSabintsev !
