### ISSUE TITLE
Display README on package page

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#410]
Depends on #409

**Comment by emma-k-alexandra** [comment]
Looking forward to this addition. README and docs are probably the most important factor to me when choosing a package.

**Comment by Sherlouk** [comment]
Is it valuable to report some broken READMEs or would you rather wait until more improvements are made?

Another one here which is a bit funky: https://staging.swiftpackageindex.com/appcompany/swift-sky

The top image spans much wider than the site's layout (so we would need to enforce a max-width or something?) there's also a button at the bottom which is a URL with a HTML image inside of it which doesn't get handled.

Source for comparison: https://github.com/appcompany/swift-sky/blob/master/README.md

**Comment by daveverwer** [comment]
Max width is, of course, something we'll handle. No styling at all has been done yet, so that's expected. Image stuff too I'm fully expecting to need styling. 

That said, please do! I need to know what's broken so I can build a list of what needs handling.

**Comment by Sherlouk** [comment]
https://staging.swiftpackageindex.com/alamofire/alamofire#communication

* Anchor links do not work
* Checkmarks will probably want a style at some point
* There seems to be an issue with detecting the closing of the code block (See Alamofire and you'll quickly see what I mean!)

https://staging.swiftpackageindex.com/moya/moya

* Relative URLs do not work (both links and image URLs etc)
* Fails soon as it gets to the table (doesn't render anything below that point)

**Comment by daveverwer** [comment]
Implemented
