### ISSUE TITLE
Support GitHub release information

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#414]
This isn't a bug but is worth a discussion.

I saw @freak4pc [tweet about the release of Prism 0.4.0](https://twitter.com/freak4pc/status/1272921165238018048) yesterday and thought it would be a good little real-world test to watch that release progress into the index. I checked a couple of times yesterday, and again this morning and it never made it to the list recent releases.

We know this as we talked about it the other day, but our version/release date is based on the date of the commit, not the date when the tag was added. The release was [tagged yesterday](https://github.com/GettEngineering/Prism/releases/tag/0.4.0), but the tag was added to a commit made [15 days ago](https://github.com/GettEngineering/Prism/commit/a60191d12c19d6b3a7ab68be82545c67cf8fdbc2). By the time we saw the release, the release would never have made the list of recent packages because it only shows the last 7 releases, ordered by the commit time.

The solution to this is [annotated tags](https://www.git-scm.com/book/en/v2/Git-Internals-Git-References#_tags) which can then be queried with `git cat-file`, but annotated tags are rare. The Prism release was not an annotated tag and looking through several popular repositories I couldn't find a single one using annotated tags.

So, I don't think there's an easy fix to this, without relying on the GitHub API to query for release information. This is less than ideal as it requires yet more API calls where we are already struggling with our API limits, and makes it harder to support repositories hosted outside GitHub.

**Comment by freak4pc** [comment]
I don't know the specific code but isn't this API helpful for this case? 
https://developer.github.com/v3/repos/releases/#list-releases

**Comment by daveverwer** [comment]
> So, I don't think there's an easy fix to this, without relying on the GitHub API to query for release information. This is less than ideal as it requires yet more API calls where we are already struggling with our API limits, and makes it harder to support repositories hosted outside GitHub.

Yep, 100%, but as I mentioned here we're already running up against our API limits pretty hard without querying for release information. We could potentially grab it via a GraphQL aggregate query (which we're discussing in #284) but it would still make supporting new repository hosting platforms harder.

**Comment by freak4pc** [comment]
Oh, sorry, I missed that last sentence. I wonder if GitHub would be open to extending your limits given this is a community-wide project. Not sure who'd be the right contact for that, but I heard of some projects that get this.

**Comment by finestructure** [comment]
It looks like even _with_ this extra request we'd only capture the same info we have now unless projects use annotated tags, right?

> This returns a list of releases, which does not include regular Git tags that have not been associated with a release. To get a list of Git tags, use the Repository Tags API.  https://developer.github.com/v3/repos/#list-repository-tags

I think what we can do (and have previously discussed), also for other reasons is not wipe and recreate versions on each refresh. If we reconcile `(tag, revision)` pairs against the upstream we can both avoid recomputing for unchanged pairs but also "see" new pairs and then report on the date we see them.

Of course, that then introduces the trade-off that release dates will depend on our ingestion cycle, which isn't great.

Right now, for instance, we're free to process whenever and with whatever gaps and the state of the db will be the same. That wouldn't be the case any longer.

**Comment by daveverwer** [comment]
> It looks like even _with_ this extra request we'd only capture the same info we have now unless projects use annotated tags, right?
> 
> > This returns a list of releases, which does not include regular Git tags that have not been associated with a release. To get a list of Git tags, use the Repository Tags API.  https://developer.github.com/v3/repos/#list-repository-tags

I don't think it's annotated tags that are flagging it to GitHub as a release. Taking the Prism example above, it does not use annotated tags, but that release was definitely logged as a release by GitHub and has the correct date/time for the release.

<img width="287" alt="Screenshot 2020-06-17 at 11 56 07@2x" src="https://user-images.githubusercontent.com/5180/84889900-8bc65980-b091-11ea-9f67-518ebed983ee.png">

So, I think that releases API would solve the problem. Looking at some common repositories again, they all have their releases listed in the Releases tab of their GitHub project.

**Comment by daveverwer** [comment]
> I think what we can do (and have previously discussed), also for other reasons is not wipe and recreate versions on each refresh. If we reconcile `(tag, revision)` pairs against the upstream we can both avoid recomputing for unchanged pairs but also "see" new pairs and then report on the date we see them.
> 
> Of course, that then introduces the trade-off that release dates will depend on our ingestion cycle, which isn't great.
> 
> Right now, for instance, we're free to process whenever and with whatever gaps and the state of the db will be the same. That wouldn't be the case any longer.

This (as you mention) would work and be generic across hosting providers, but (as you also mention) has other limitations 😬

**Comment by finestructure** [comment]
Ah great, if we can get the tag dates from the provider I'd much prefer that!

I'm sure providers other than GH would have something simliar - or else in that case we'll just do the best we can.

With respect to the rate limit, we might be able to bake all this into one efficient GraphQL query, which would be nice for several reasons.

**Comment by daveverwer** [comment]
> With respect to the rate limit, we might be able to bake all this into one efficient GraphQL query, which would be nice for several reasons.

Sounds good!
