### ISSUE TITLE
Reconcile versions

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#422]
We’re currently deleting and recreating all of a package’s versions on each analysis pass for sake of simplicity.

This is not terribly efficient but also not a problem, at least currently.

However, going forward if/when we perform more work per version we’ll want to reconcile versions like we do for packages, such that we diff for removed/added versions - and also check that no versions have moved (re-tagging, default branch updates).

The invariant to look for is probably: reference, commit. I don’t think we need to look at the commit date.

So, we’d look for deleted versions, added versions and any versions where (reference, commit) has changed. Those we then delete and re-analyse.

This is a pre-requisite for the builder.

**Comment by daveverwer** [comment]
Yep, this is how the SwiftPM Library did it and it's certainly more efficient. 

But I wasn't as diligent with changed versions as I needed to be, so you're right that we need to be careful about that to not lose that advantage over the old system that we have right now. 👍 I think watching for the commit hash changing is enough.
