### ISSUE TITLE
dyld: Library not loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink   Referenced from: /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon   Reason: Incompatible library version: Carbon requires version 1.0.0 or later, but Ink provides version 0.0.0

### ISSUE THREAD

**Issue by VineFiner** [SwiftPackageIndex/SwiftPackageIndex-Server#431]
```
swift package generate-xcodeproj
```

```
Run
```

**Comment by finestructure** [comment]
Hi @VineFiner !

I believe this issue arises because there's a system library called Ink - the same as John Sundell's library Ink that we're using.

The way to fix it is simply not to try and generate an Xcode project: it is not necessary anymore. You can simply open the `Package.swift` file to launch the project in Xcode, or type `xed .` in the project folder.

Hope that helps!

**Comment by VineFiner** [comment]
Okay thank you. open the `Package.swift` can work.

**Comment by VineFiner** [comment]
@finestructure 

Hello, do you need to perform additional operations on `Reconciliation`? For example `Linux Crontab`

**Comment by daveverwer** [comment]
It depends what you're trying to do. If you just want to run it locally then you can run the `test-e2e` command to make sure everything is working, and then the `scripts/ingest-loop.sh` and `scripts/analysis-loop.sh` to start the two processes looping.

If you want to run it as a server available to the internet, that's a whole different thing.

Would you mind going into your plans in a little more detail?

**Comment by VineFiner** [comment]
@daveverwer 

Hello, I am interested in Crawler. For example, collecting accommodation information. But how to deal with timeliness is a problem.

**Comment by daveverwer** [comment]
Timelines in terms of git history?

What is the problem you’re trying to solve?

**Comment by VineFiner** [comment]
Sorry, what I want to express is how to deal with crawlers. It's not a problem with git. How to update in time.

**Comment by VineFiner** [comment]
@daveverwer 

I want to crawl Airbnb data to display cheap rental information.

**Comment by daveverwer** [comment]
Ahh I understand, thank you for clarifying. 👍

I'm afraid that this project doesn't crawl in that way. it uses a [defined list of packages](https://github.com/SwiftPackageIndex/PackageList) and does not do any discovery of new URLs at all.

The techniques around running Vapor commands in this repository might be useful on a general level, but I'm afraid that you won't find a crawler in a traditional sense here. I'm not sure we can be much more help, I'm sorry.

**Comment by VineFiner** [comment]
@daveverwer 

Okay thank you. I noticed that vapor has a timed queue. Why not write scheduled tasks?

**Comment by finestructure** [comment]
It fits or processing method better not to have the three processing stages running in the same process as the web server. None of the work they do (which includes running shell commands and many network requests) should be able impact the web site.
