### ISSUE TITLE
Include the score in an HTML comment

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#440]
I was investigating some suspicious ordering in the search results tonight and it would be useful to have the score inserted as an HTML comment somewhere in the package page so it can be more easily checked.

**Comment by finestructure** [comment]
Or we add score to the results and then you can visit the search url to see the raw data? Feels a bit cleaner :)

https://swiftpackageindex.com/api/search?query=alamo

**Comment by daveverwer** [comment]
I want to be a little careful with exposing that search score too publicly before it's a little more mature. I'm not even sure we'll ever expose a raw search score like that, I'd rather make it into something a little less directly comparable, like a "grade" or something a little softer than an integer.

Also, people build stuff with public APIs which makes it much harder to change in the future.
