### ISSUE TITLE
Robots.txt should disallow all crawlers on staging

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#458]
We don't want Google or other search engines to know about the staging pages.

Unfortunately, this might mean we need to dynamically generate robots.txt unless we add a step to deployment to copy a new version over.

**Comment by daveverwer** [comment]
The sitemap should not need changing, disallowing crawlers via the robots.txt should be enough.

**Comment by finestructure** [comment]
Could we block this at the cloud flare level?

**Comment by daveverwer** [comment]
We need to provide different content for the file, explicitly disallowing robots. The absence of a robots.txt file is a green light for crawlers.

**Comment by daveverwer** [comment]
Checking whether we can do this with Google Search Console instead.
