### ISSUE TITLE
Design for showing version compatibility

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#459]
Need to show multiple versions of Swift compatibility next to each set of versions where the compatibility changes.

**Comment by daveverwer** [comment]
Alright, I've been playing with this today and this is the best I've come up with so far. First, desktop:

![Swift Version Compatibility](https://user-images.githubusercontent.com/5180/85537304-c1c48a00-b60b-11ea-972e-ea380fa4fc5f.png)

then, mobile:

![Swift Version Compatibility Mobile](https://user-images.githubusercontent.com/5180/85537330-c5f0a780-b60b-11ea-82ea-96f269645297.png)

It's not ideal to repeat the titles, both from a design perspective, but also from a markup (they'd need to be there on desktop, and hidden). So something like this may be easier to implement.

![Swift Version Compatibility Mobile 2](https://user-images.githubusercontent.com/5180/85537717-1d8f1300-b60c-11ea-95a2-265b4be262a8.png)

**Comment by finestructure** [comment]
This looks great! 🎉

**Comment by daveverwer** [comment]
One little iteration after our call earlier, I made the failed builds a darker grey so I could show a lighter grey for builds that we do not have data for.

![Artboard – 5](https://user-images.githubusercontent.com/5180/85571529-2099fb80-b62c-11ea-8c87-742c08a4bf99.png)

**Comment by daveverwer** [comment]
Hovering over the cells will show a tooltip:

* Build succeeded
* Build not available
* Build failed

**Comment by daveverwer** [comment]
This is how these ended up looking in the final markup

<img width="808" alt="Screenshot 2020-06-25 at 10 30 47@2x" src="https://user-images.githubusercontent.com/5180/85694459-0b29dd80-b6cf-11ea-9e61-223835bc1057.png">

<img width="375" alt="Screenshot 2020-06-25 at 10 30 25@2x" src="https://user-images.githubusercontent.com/5180/85694469-0d8c3780-b6cf-11ea-8e9e-06faea4355de.png">

Must admit I'm pretty happy with them!

**Comment by daveverwer** [comment]
... and in dark mode:

<img width="814" alt="Screenshot 2020-06-25 at 10 42 21@2x" src="https://user-images.githubusercontent.com/5180/85696252-ad969080-b6d0-11ea-8ebf-18a11569c29c.png">

<img width="389" alt="Screenshot 2020-06-25 at 10 42 40@2x" src="https://user-images.githubusercontent.com/5180/85696261-af605400-b6d0-11ea-9180-221f3882125e.png">
