### ISSUE TITLE
What format should the extra metadata file be?

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#462]
It might feel obvious that this file should be in a JSON format. However, this file is going to be written entirely by humans and read by both humans and computers. The ability for a human to accurately read and input this data is important.

Another important feature of the format we choose is how it handles multiline strings. The summary/description fields will be multiline strings.

Finally, comments are also important. Package maintainers will probably be starting with a template file and we can provide guidance in comments.

## YML 

* Pros
	* Easy for a human to read and write.
	* Easy for a computer to read.
	* Good support for multiline strings.
	* Good support for comments.
* Cons
	* Requires a dependency for any Swift app that wants to read the metadata. For example, [Yams](https://swiftpackageindex.com/jpsim/Yams) or [Yaml](https://swiftpackageindex.com/behrang/YamlSwift). ([thanks Max](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648863835))
	* Quirks around interpreting some data formats (thanks [Sven](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648814944) and [Max](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648863835))

## TOML

* Pros
	* Easy for a human to read and write.
	* Easy for a computer to read.
	* Good support for multiline strings.
	* Good support for comments.
* Cons
	* Requires a dependency for any Swift app that wants to read the metadata. For example, [TOMLDecoder](https://swiftpackageindex.com/dduan/TOMLDecoder) or [Toml](https://swiftpackageindex.com/jdfergason/swift-toml). ([thanks Max](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648863835))

## JSON

* Pros
	* Trivial for computers to read.
* Cons
	* Harder for a human to read and write.
	* Multiline strings are awkward.
	* No support for comments.

## Swift (via [PackageConfig](https://swiftpackageindex.com/shibapm/PackageConfig) or similar)

* Pros
	* Easy for a human to read and write.
	* Trivial for computers to read.
	* Good support for multiline strings.
	* Good support for comments.
* Cons
	* Every package would need a dependency on [PackageConfig](https://swiftpackageindex.com/shibapm/PackageConfig). To be clear, this is very different from requiring a dependency for reading the metadata, this is a true package dependency. For example, Alamofire would become dependent on PackageConfig if they wanted to implement this metadata. ([thanks Gal](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648849887))

## Property Lists ([thanks James](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648891317))

* Pros
	* Easy for a human to read and write **using Xcode**.
	* Trivial for computers to read. (No third party libraries as we can use Codable)
	* Good support for multiline strings.
* Cons
	* Very Apple platform centric. ([thanks Max](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/462#issuecomment-648900957))
	* No support for comments.
	* Not super easy to read/write as a source file (XML)

**Comment by daveverwer** [comment]
For what it's worth, my vote would be for YAML.

My reasons? I don't think there's much in it between YAML and TOML, but YAML is familiar to more people than TOML is. I'd love to suggest Swift via PackageConfig, but having a forced dependency in every package is makes it an absolute non-starter in my opinion.

YAML seems a clear winner to me, but I'd love to hear your opinons.

**Comment by finestructure** [comment]
+1 for YAML. It has its quirks, especially around interpreting some data formats (integers with leading zeros...), but for our purposes where it's not a critical control file I think this isn't an issue.

**Comment by GalCohen** [comment]
> having a forced dependency in every package is makes it an absolute non-starter in my opinion.

Apologies if I'm misunderstanding, but doesn't YAML also require a dependency? (Yams, etc.)

**Comment by daveverwer** [comment]
It would require a dependency in the Swift Package Index so we could read it, and of course in any other project that wanted to read the file.

Adding metadata to the Package.swift file via PackageConfig would mean *every package* that wanted to support this metadata would need to be dependent on PackageConfig. That's very different IMO.

**Comment by MaxDesiatov** [comment]
+1 for JSON. Other than the quirks with YAML (which is going to cause issues for beginners, since there's no requirement to quote strings, but not all unquoted values are interpreted as strings), there's another disadvantage not mentioned in the OP, which is the requirement to bundle a YAML parser for anyone who'd like to read the metadata file. On the other hand, JSON parsers and serializers are available everywhere, including the Swift Foundation module.

**Comment by finestructure** [comment]
I think the thing to bear in mind is that there's going to very limited need to actually machine-read that file. Mostly people will be editing it with editors and we (the SPI) will read it with Yams. Other than that it's perhaps going to be inspected in Github's web UI (looking at the file), where YAML also has advantages (it displays well as plain text without any extra support).

**Comment by MaxDesiatov** [comment]
There's plenty of scenarios for this to become machine-readable. One could certainly build a ton of useful developer tools that parse package metadata and operate on it. SPI itself being a primary example of that, but I personally would love to build some tools for myself to produce stats on how the Swift ecosystem is evolving, i.e. how many packages declare platform support, what licenses are used, etc. If there was no need to make this machine-readable, there's no need for the metadata file in the first place, people could just as well write all these things in their `README.md`. Requiring those developer tools to unnecessarily bundle more dependencies with them would be unfortunate.

**Comment by daveverwer** [comment]
> +1 for JSON. Other than the quirks with YAML (which is going to cause issues for beginners, since there's no requirement to quote strings, but not all unquoted values are interpreted as strings)

This is a fair point but I think this is less of a real-world issue than not being able to include comments. With a well-commented template, that has quotes already inserted, the likelihood and impact of this going wrong is small. You're right that there's a balance to it though.

> there's another disadvantage not mentioned in the OP, which is the requirement to bundle a YAML parser for anyone who'd like to read the metadata file. On the other hand, JSON parsers and serializers are available everywhere, including the Swift Foundation module.

I've Added the dependency as a con to both YAML and TOML and clarified the issue around the con of dependencies on PackageConfig.

**Comment by MaxDesiatov** [comment]
JSON being a subset of YAML is a good thing. So at least if you settle with YAML after all, please allow YAML-haters like me (🙈) to use `.json` as an extension for their metadata files, you can still read and parse them with a YAML parser. That is, you'd look for `PackageMetadata.yaml` (if that's the base name you settle with), if that's absent you look for `PackageMetadata.json` and parse that one. The benefit is that at least I can enforce proper values quotation in my packages, while not imposing on any other package authors who can freely use YAML if they like it.

**Comment by Sherlouk** [comment]
Sorry to be *that guy* but is it worth considering property lists?

## Property Lists
* Pros
  * Easy for a human to read and write **via Xcode**.
  * Trivial for computers to read. (No third party libraries as we can use Codable)
  * Good support for multiline strings.
* Cons
  * Not super easy to read/write as a source file (XML)
  * No support for comments.

**Comment by mattpolzin** [comment]
@MaxDesiatov why not just use pure JSON in your “PackageManifest.yml” file? I think allowing the file to have either extension (or really just allowing it to have more than one name period) is an unfortunate complication even if it _sounds_ small.

**Comment by Sherlouk** [comment]
My opinion:

-1 for Swift (that extra dependency 😭)
-1 for TOML (I think on a survey of most iOS developers they wouldn't know this format already and I think it's easier to stick with what people already know)

Really I think YML, JSON and Plist all have their merits but I'm giving my vote for Plist as I'm often editing my project while in Xcode so having that helpful editor right there gives it an edge in my opinion.

**Comment by mattpolzin** [comment]
+1 for YAML from me; the commenting alone is enough, but I also just enjoy reading YAML more than JSON and am more familiar with it than TOML and it has clearly won the hearts and minds of many disparate developer communities so familiarity with YAML is really high.

**Comment by MaxDesiatov** [comment]
@mattpolzin the downside of that is that there's still a possibility of someone mixing in some YAML values in that same file, while naming it `.json` unambiguously points to the subset of YAML allowed in that file.

**Comment by daveverwer** [comment]
> Sorry to be _that guy_ but is it worth considering property lists?
> 
> ## Property Lists
> * Pros
>   
>   * Easy for a human to read and write **via Xcode**.
>   * Trivial for computers to read. (No third party libraries as we can use Codable)
>   * Good support for multiline strings.
> * Cons
>   
>   * Not super easy to read/write as a source file (XML)
>   * No support for comments.

Added Property Lists to the top post, thanks James.

**Comment by daveverwer** [comment]
> @mattpolzin the downside of that is that there's still a possibility of someone mixing in some YAML values in that same file, while naming it `.json` unambiguously points to the subset of YAML allowed in that file.

I wasn't going to weigh in on this one but I can't help myself 😂

No data format is perfect, but whatever we choose I feel strongly that it should be *one* choice, not multiple.

**Comment by MaxDesiatov** [comment]
I'd like to point out that property lists are very Apple-centric, I'm still not able to make those work in [the WebAssembly Swift target](https://swiftwasm.org). Even though plist reading code is available in the open-source version of Foundation, it's mainly coded in C in the CoreFoundation part and relies on CoreFoundation's `CFStream` support, which itself requires Dispatch/pthreads. The latter is unavailable in WebAssembly. There are no such problems with JSON though, Foundation's bits work fine, and can also defer to browser's JSON parser, which would be available in most WebAssembly environments. So while it may seem that plists don't require any dependencies, this is not the case for all platforms that Swift supports.

**Comment by MaxDesiatov** [comment]
Another benefit of JSON is that it is compatible with [JSON-LD](https://w3c.github.io/json-ld-syntax/), which would allow you to reuse the [SoftwareSourceCode](https://schema.org/SoftwareSourceCode) schema from [schema.org](https://schema.org/) as suggested [here](https://forums.swift.org/t/extend-swiftpm-packagedescription-to-introduce-metadata/37722/21) by @mattt.

This would mean that package metadata could also become indexable not only by SPI and other Swift-focused developer tools, but also by search engines such as GitHub, Google, Bing, DuckDuckGo, and also voice assistants such as Siri, Alexa etc.

**Comment by Sherlouk** [comment]
@MaxDesiatov I didn't know that, thanks for sharing!

**Comment by orta** [comment]
Hah, yeah +1 to YAML, I don't want PackageConfig to be _that_ popular

**Comment by Mordil** [comment]
I'm 55/45 between YAML and JSON, respectively.

Isn't YAML being picked in most SE pitches & proposals now, with the intention of using a parser lower in the stack? I could foresee a future when YAML will be supported directly in the STD Library (or Foundation) soon, which would lower the barrier to parse the format for those who ultimately will want it.

**Comment by MaxDesiatov** [comment]
>Isn't YAML being picked in most SE pitches & proposals now

Would you be able to link to a few pitches and proposals as an example please?

**Comment by filip-sakel** [comment]
I will go for Swift. I think it will allow for greater flexibility. I also don’t understand why having a dependency to the metadata parser is such a “non-starter”. SPM will provide the PackageConfig library - as it does for PackageDescription - which will be usable from “PackageMetadata.swift” or whatever it will be named. Any package that will require reading the package metadata will declare the parser as a dependency. Am I missing something here?

**Comment by daveverwer** [comment]
There's more interesting [discission happening over at the Swift forums](https://forums.swift.org/t/extend-swiftpm-packagedescription-to-introduce-metadata/37722/30?u=daveverwer) on this subject. Tagging here too just to keep everyone aware of the ongoing conversation.

**Comment by daveverwer** [comment]
Closing this as `.spi.yml` is now in use.
