### ISSUE TITLE
What should the extra metadata file be named?

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#463]
Let's discuss what it should be named. Here are some options to kick us off.

* `Package.extension` (where `extension` is `yml`/`toml`/`json`/etc... depending on the result of #462)
* `Metadata.extension`
* `PackageMetadata.extension`
* `ExtraMetadata.extension`

Any others?

**Comment by daveverwer** [comment]
My vote would be for `Package.extension`.

**Comment by MaxDesiatov** [comment]
`PackageMetadata.json` please 🙂

**Comment by daveverwer** [comment]
> `PackageMetadata.json` please 🙂

I think you mean `PackageMetadata.extension` 😂

**Comment by mattpolzin** [comment]
I like `PackageMetadata.extension`. 

Longer? Yes. Easy to spot at a glance? Yes. 

I am more interested in quickly spotting the file in a printout of file names (like the sidebar file manager in many simple editors) than I am in a slightly less awkward and shorter name. 

I also think there’s a there’s a weird possibility of near-miss with the package file used by npm/yarn. I don’t know how common it is, but at my current work we have some yarn tooling and a yarn workspace that touches all packages regardless of whether the package itself is a NodeJS project or a Python project, etc. With a hypothetical name of “Package.json” we would have both that file and “package.json” in the same folder.

**Comment by MaxDesiatov** [comment]
>With a hypothetical name of “Package.json” we would have both that file and “package.json” in the same folder.

Even worse, on macOS filesystem is case-insensitive by default, so these wouldn't be just in the same folder, they'd overwrite each other. And there are enough projects that need both Swift and Node.js, I currently work on [`carton`](https://github.com/swiftwasm/carton) which is one of those.

**Comment by erica** [comment]
Package metadata.????

**Comment by Mordil** [comment]
+1 on `PackageMetadata.<ext>`

**Comment by finestructure** [comment]
FYI, we've started directing package owners to use `spi.yml` to give hints to the build system (#686, #677)

**Comment by daveverwer** [comment]
Closing this as `.spi.yml` is now in use.
