### ISSUE TITLE
Add FAQ entry explaining how we do build testing

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#467]
Explain what parameters we use to build, and any other information that might help package authors if they are struggling to figure out why their build is failing.

**Comment by finestructure** [comment]
I've collected a number of questions I think people will ask (or have asked already):

- why does my package have no builds?
- what revision is the default branch built for?
- how is it being built? (build command)
- when was it last built?
- how long until builds are done after a new release/commit on default branch?
- how can I hide failing builds for platforms I don't support?
- the build it shown as failed but I know my package supports this platform, what do I do to fix it?
- I've fixed a build, how do I trigger a re-run?

We probably do need to have something up to explain these (I'll draft something up) but a couple we may actually be able to address by tweaking the info on the build pages (add the default branch revision, builds `updated_at`) as a stretch goal for launch.

**Comment by daveverwer** [comment]
All very good points 👍

This is one reason our FAQ page is running out of steam, these can go into the FAQ but these should really be on their own docs page eventually.

**Comment by finestructure** [comment]
I've written a first pass for the questions. Shall I stick them on the existing FAQ page for now, perhaps under a separate `Builds` bullet point?

# Build FAQ
* Why doesn’t my package show any builds?
	* The Swift Package Index picks up new default branch revisions and release automatically. However, it can take a little while for it to do so. New builds should appear within a few hours after a revision change.
* What revision is the default branch built for?
	* The Swift Package Index does not currently display which default branch revision has been built. If your default branch revision changed more than a few hours ago it is very likely the revision that has been built. It is best to rely on (pre-)releases to for precise Swift version and platform compatibility.
* How is my package being built?
	* We run `xcodebuild` and `swift build` if applicable for the platform for the specified Swift versions.
	* For `xcodebuild` we apply some heuristics to find the correct scheme to build. If your package contains a single scheme (as reported by `xcodebuild -list`) we will build that scheme.
	* If `xcodebuild -list` reports multiple schemes, we build the one ending in `-Package`. Otherwise we try removing existing Xcode project and workspace files and rely on SPM’s scheme discovery to autogenerate a package scheme for building.
* When was it last built?
	* The Swift Package Index does not currently display when a revision has been built. You can assume this to have happened a few hours after a revision change.
* How long until builds are done after a new release/commit on default branch?
	* New revisions are typically built within a few hours.
* How can I hide failing builds for platforms I don’t support?
	* This is currently not possible.
* The build is shown as failed but I know my package supports this platform, what do I do to fix it?
	* First, please try to replicate the build locally with the build command we show on the build details page. This may help reveal if there is some issue with the package set up or our way of discovering the build scheme.
	* If this is something you can correct, great! Simply make the change and we will re-process your builds.
	* If this is not possible, please get in touch so we can improve our build command and make it work with your package.
* The build shows an error that doesn’t seem to have anything to do with a build error. How can I fix this?
	* In some cases we may have encountered build issues unrelated to your package. Please confirm using the build command we show on the build page whether you can build your package successfully for a given Swift version and platform.
	* If this succeeds, please let us know so we can remove the faulty builds and schedule a rebuild.
* I’ve fixed a build, how do I trigger a re-run?
	* Simply commit a change to your default branch or make a new (pre-)release. In a few hours the Swift Package Index will revisit your package and rebuilt the new revision.

**Comment by daveverwer** [comment]
These are great 👍

I do have an idea just because this would add so many questions to the FAQ.  We should maybe add one question to the FAQ about "How does the build system work" and then another page for the "Builds FAQ" with all of these.

I do think it's almost time to split the FAQ page into a Docs section of the site, with this being one page of the docs.

**Comment by finestructure** [comment]
👍 I can have a look and prep something for that later today.
