### ISSUE TITLE
UX - hard to find all results when searching

### ISSUE THREAD

**Issue by izakpavel** [SwiftPackageIndex/SwiftPackageIndex-Server#477]
I wanted to check several logging libraries so I used the index website. 

It took me a significant amount of time to realize that the list of the results when searching for some term is scrollable. At first I was like: "how the hell can I display all results, not just 4?"

I would recommend to add there some visual key - either button "show all results" (with number) or flash scroll indicators or something like that ;)

**Comment by daveverwer** [comment]
So this leans towards where I want to go next with the search feature, in that it shouldn't always be *just* a dropdown like it is now. Making an intermediate search page is part of the plan (for a few reasons) but it would also solve this problem, I think. Here's what I'm thinking:

<img width="1366" alt="My Sketches 3 - 2020-06-26 09 06 11" src="https://user-images.githubusercontent.com/5180/85843866-bf903600-b799-11ea-842e-b82ad77a0b31.png">

(1): The existing search field, no changes here.
(2): A new row in the drop-down, which is automatically selected as soon as you start typing (shows the light blue highlight). When hitting enter, this takes people to an intermediate search page showing all search results for whatever was typed.
(3): A non-interactive row, distinguishing the freeform search above, from navigating directly to a package page.
(4): Search results, as normal.

There are several advantages to this design, it's still just as quick to get to a package if you know what you're looking for, but it allows much easier comparison of packages from the intermediate page if you're browsing, and also means people will be able to send links around that include a search term. 👍

I wish flashing the scroll indicators was possible on the web, that would be an easy little change to make this obvious, but I don't believe it's possible.
