### ISSUE TITLE
Run extra build for tagged releases

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#478]
A recent change to the deployment script skipped builds for tagged releases in favour of just re-tagging existing ones.

This has the side-effect of shipping the sha variant. For instance instead of 1.2.0 we get:

```
<!--Version: 80e7c024ea60f5d0970876221c8f7438081d9996→
```

It’s just a labeling issue but it’d be nicer to have the tag names back.

**Comment by daveverwer** [comment]
Yes, I actually use that little HTML comment in the source quite often to see what's deployed. 👍

**Comment by finestructure** [comment]
I’m confused. 1.2.1 now deployed and it’s showing 1.2.1 in the source. I wonder if it’s racing to pick up whichever completes first - or it might be because I had to retrigger the build step manually due to a GItlab network issue.
