### ISSUE TITLE
Package Search

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#48]
First up, how does search currently work in the SwiftPM Library?

* Information is donated from the various package/product/version records into a local ElasticSearch instance. The default branch is always the source search information as that's the most up to date.
* The following information is donated:
  * Package name (extracted from the Package.swift)
  * Package description (currently from the GitHub description)
  * The repository identifier (username/project, excluding github.com and other URL paraphernalia)
  * The search score (for ordering only, it's not searched).
* Search can be customised to look only in certain fields. For example, try [this search](https://swiftpm.co/?query=name%3Ahtml) compared to [this search](https://swiftpm.co/?query=description%3Ahtml), or [this search](https://swiftpm.co/?query=html).

The plan was that at some point you might also want to customise search by other useful metadata like, for example:

* Swift version
* Platform compatibility
* Authors real names, as well as the "free" search we get from including the repository identifier which includes a GitHub username.
* More... 

Without ElasticSearch, some of this becomes much harder (but not impossible) to achieve. As I was thinking about the design of the search form today, something struck me. Even though the colon syntax for searching is fairly standard, not everyone knows about it. So maybe we lean into a basic Postgres full-text search across a de-normalised version of the search data from the default branch, processed only to contain searchable data. Then, some checkboxes/input controls people can tick as they start to search. There's plenty of UI space on that home page for extra controls, and it might aid discovery of the feature.

Not all of this needs implementing straight away, but I want to discuss it about it as it affects the design.

**Comment by finestructure** [comment]
I agree to start off with PG search. I was a bit concerned about single source of truth in a denormalised schema but then I realised that we could use a materialised view. That should work and avoid any updating hassles.

**Comment by daveverwer** [comment]
Can we do things like parse and split a URL in a view? If we can't that's good, but also given how the data can only change from one source (the ingestor/analyser) it's not a complex de-normalisation process. I think integrity issues could be quite easily minimised.

**Comment by finestructure** [comment]
I think we could parse and split but I think it'd be good if we can avoid spreading that sort of logic into an SQL query. In that case I think we should either provide those parsed fields in the source of truth or just populate a search table on a schedule.

If we could manage with a view that'd be great, it's just less churn and one less refresh/update step to worry about.

We'll see, I think it'll fall naturally out of what we need to search for and where it lives :)

**Comment by daveverwer** [comment]
> just populate a search table on a schedule

This is how it works in the SwiftPM library. Every 10 minutes after the ingestion/analysis phase (which is the only thing that changes the database) I run a full ElasticSearch reindex, that effectively rebuilds the whole search index.
