### ISSUE TITLE
Smoke test failure 

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#482]
404 https://swiftpackageindex.com/broadwaylamb/OpenCombine

but looks valid at first glance: https://github.com/broadwaylamb/OpenCombine

https://gitlab.com/finestructure/swiftpackageindex/-/jobs/613501889

**Comment by finestructure** [comment]
Looks like the project has no releases

**Comment by finestructure** [comment]
Oh, hold on, it’s a name change + redirect. New name is https://github.com/OpenCombine/OpenCombine

This will probably autocorrect shortly.

**Comment by finestructure** [comment]
200: https://swiftpackageindex.com/OpenCombine/OpenCombine

**Comment by daveverwer** [comment]
> 200: https://swiftpackageindex.com/OpenCombine/OpenCombine

What's interesting about this is that on that page, we still show `https://github.com/broadwaylamb/OpenCombine.git` as the URL for the package.

It works, but it's probably not the right thing to do. Needs a bit of thought on how to fix it though, it's a weakness of `packages.json`. I'll update the PackageList for now.

**Comment by finestructure** [comment]
Yeah, we autocorrect the url when we ingest Github metadata where we get the new url but we don't update the package url. And we can't really, because reconciliation would then re-create the old package as a new entry.

I guess we could detect that there's a discrepancy between GH reported url and `packages.url` and in that case set up a redirect on our end (just like GH do) for the old url.

**Comment by daveverwer** [comment]
Yea, it feels like it's a more fundamental problem than we can solve while still using `packages.json`.

The only possible fix now would be to have a "true" package URL field that is the final package URL after redirects. That would mean the original URL could remain the key, and the page shows the correct URL to copy.

However, I think a small tool might be a better solution for now. We could go through the package list and detect any redirects. Then just manually merge that. I'd be happy to run that once a week for now. I'll think about knocking this tool up.

**Comment by finestructure** [comment]
We have that tool already :) We can run

```
swift run Run create-restfile -v all > all.restfile
env base_url=https://swiftpackageindex.com rester all.restfile
```

That'll highlight all 404s and all of those should now be from renames. The error reporting isn't super streamlined but should be good enough.

We could actually run that as a weekly pipeline automatically.

**Comment by finestructure** [comment]
I mean, that's basically our smoke test which is now flagging the issue, only that the smoke test doesn't crawl all 3k url, just about half.

**Comment by finestructure** [comment]
Or maybe we just have the smoke test crawl all - it's not like the extra 1.5k urls would make that much of a difference...

**Comment by daveverwer** [comment]
Let's make the smoke test crawl everything 👍
