### ISSUE TITLE
Determining which builds to run

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#483]
So I’ve been thinking about how we should determine which builds to run for every package. It’s complicated, because `swift build` will only work for pure Swift packages with no dependencies on Apple platforms.

If we’re using a successful `swift build` result to determine Swift version compatibility, we can’t know that compatibility unless we also understand what platforms that package requires.

I think I’ve come up with the logic that’ll work through:

1. We determine the Swift tools version declared in the manifest. (By running `swift package tools-version`). (See [note on what we do when the tools version changes](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/483#issuecomment-650531180)).
2. We look for the `platforms` key in the manifest. This key is reasonably widely supported (much more so than `swiftLanguageVersions`).
3. Before we determine Swift version compatibility, we first need to determine platform compatibility by:
	* If the `platforms` key exists, run `swift build` using the version of Swift specified in the tools version for each platform specified in the `platforms`. (See [note on excluding platforms](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/483#issuecomment-650531154)).
	* If the `platforms` key does not exist, run `swift build` for  all four (or five, if we include a version of linux).
4. Store platform compatibility in our database.
5. Then, for *one* of the supported platforms, determine Swift version compatibility. (See [note on which platform](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/483#issuecomment-650531254)).
	* Run `swift build` with the relevant platform flags on each version of Swift that we want to determine compatibility with.
6. Store swift version compatibility in our database, and maybe associate which platform it was tested on as well. It would be interesting to tell people what versions.

**OR…**

We just build up a full matrix of Swift versions and platform versions and run builds across *all* combinations. The logic for gathering the data is much simpler, obviously with much more building to do. But the trade off might be worth it in simplicity.

Of course, the logic for displaying version information becomes a little more complex with this method, but I think it might still be simpler than the first option overall.

**Comment by daveverwer** [comment]
**Note:**

* If the `platforms` key is specified, and Apple platforms are excluded from it we should take that as a sign that the package author does not desire compatibility with that platform. It may, or may not work, but we should declare it as incompatible.

**Comment by daveverwer** [comment]
**Note:**

* If we see a tools version change in the manifest, we should wipe all stored build data for that package and start again.

**Comment by daveverwer** [comment]
**Note:**

* In terms of which platform to choose for Swift version compatibility, they should be prioritised. If iOS is supported, use iOS. Then macOS, then watchOS and tvOS in that order.

**Comment by daveverwer** [comment]
Finally, how do we actually build the platform versions?

Two options:

* `xcodebuild`.
* `swift build` with extra parameters to specify SDK locations.

This works for building an iOS version:

```
swift test -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
```

That only uses `xcrun` to *report* the location of the platform SDK does not run `xcodebuild`. Of course, if we want to run with multiple platform SDKs then we need them installed, which I believe is possible.

**Comment by daveverwer** [comment]
Also... 😬

**Comment by finestructure** [comment]
I've just run some test builds with Gala on macOS 10.15 and I think this will work.

```
swift build
```

seems to be have the same as

```
swift build -Xswiftc "-sdk" -Xswiftc (xcrun --sdk macosx --show-sdk-path) -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.15"
```

and I can target other platforms as described above, with `iphonesimulator`, and `appletvsimulator`. What doesn't appear to work is the watch sdk:

```
sas@Ceres  ~/D/Gala  ⎇ main  swift build -Xswiftc "-sdk" -Xswiftc (xcrun --sdk watchsimulator --show-sdk-path) -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos13.0-simulator"
<unknown>:0: error: Swift does not support the SDK 'WatchSimulator6.2.sdk'
```

I guess we can live with that for now.

The `-target` parameter will allow us to crawl over the platform versions. One thing to figure out is how to get them onto the runners but I believe this is a simple download in Xcode settings - at least for iOS. I'm not so sure about macOS.

**Comment by finestructure** [comment]
NB: yes, the target doesn't match on the watchos build but I don't think that matters in this case. When I mixed this in other cases to test behaviour the error was specific to the target.

**Comment by daveverwer** [comment]
> One thing to figure out is how to get them onto the runners

Get what onto the runners? The SDKs should all be pre-installed

**Comment by daveverwer** [comment]
I've been plauing with this and I also couldn't get it working with a watchOS target. However, I just tried with the Xcode 12 beta and it worked like a charm!

```
swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk watchsimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-watchos7.0-simulator"
```

Works great 👍

**Comment by finestructure** [comment]
Ah, that's great! I was hoping it's just due to watchOS being a bit behind the rest.

Re: the runners: I'm referring to getting additional SDKs on the machine or updating to new ones. For instance, iOS, tvOS, watchOS are simple enough to do via Xcode (although CLI would be nice):

<img width="942" alt="Screenshot 2020-07-02 at 07 24 21" src="https://user-images.githubusercontent.com/65520/86319553-0ddb8400-bc35-11ea-8c45-f0d0f1bbd11e.png">

but I'm not sure about macOS. Would be need to bump the whole OS to get new SDKs? Can we copy them from another machine? How about past versions? Ceres only has 10.15 and I'm wondering how to get 10.13 etc for building against those.

**Comment by finestructure** [comment]
Heh, internet FTW https://github.com/phracker/MacOSX-SDKs

**Comment by daveverwer** [comment]
Do we want to get into compiling with different versions of the SDK? That matrix is going to be 4 dimensional. Or, do we just use the SDK based on the `platforms` key in the manifest?

**Comment by finestructure** [comment]
I thought we wanted to probe if there's a platform cutoff at some point? Something like this, to find the earliest supported version:

```
for sdk in "10.11 10.12 ..." ; do
   build.sh $sdk
done
```

Starting with the oldest one, because they'll fail fast and we can stop once we have the first success.

**Comment by daveverwer** [comment]
The problem with that is that we're testing with different SDKs there, which gives no guarantee of the platform required when executing the code on a device.

For example, Apple usually requires everyone to compile with the latest SDK (for the App Store) at least, a few months after the first final release of that version. But with that latest SDK, you can still support platforms many versions prior to that.

I think all we'd be testing here is **SDK** support, not **platform** support.

**Comment by finestructure** [comment]
This may be a bad idea after all: https://swiftpm.slack.com/archives/C14QU6CUU/p1591533004419300

<img width="633" alt="Screenshot 2020-07-02 at 15 27 29" src="https://user-images.githubusercontent.com/65520/86364505-8c0d4a00-bc78-11ea-8ae1-a2a103790ea3.png">

Ankit proposes an alternative which I’ll check now.

**Comment by daveverwer** [comment]
Closing. Obsolete as we are processing the entire matrix.
