### ISSUE TITLE
Also render `:emoji:` in search results

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#493]
<img width="284" alt="Screenshot 2020-06-29 at 12 32 19" src="https://user-images.githubusercontent.com/65520/85996375-fb7b0380-ba04-11ea-9372-a0ab762a3b8d.png">

**Comment by Sherlouk** [comment]
🤦 My bad!

Just a case of using that extension on the view for that
