### ISSUE TITLE
How can you view a list of all packages?

### ISSUE THREAD

**Issue by ygit** [SwiftPackageIndex/SwiftPackageIndex-Server#496]
Is there a page where all packages listed can be viewed?

**Comment by daveverwer** [comment]
There's the [packages.json file](https://github.com/SwiftPackageIndex/PackageList/blob/main/packages.json)!

Apart from that, there's no list of everything. Before we go ahead and turn this into a feature request, I'd be interested to know what you're trying to find out from a page listing all packages. At 2,600 packages, it feels like it's too many to browse by pages, so what would you see the purpose of a page like this being?

Thanks!

**Comment by daveverwer** [comment]
Closing this, but please feel free to re-open if there's a reason this information would be useful outside of it being a curiosity.
