### ISSUE TITLE
Do we need a build variant?

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#506]
I've been thinking a bit more about the various build command variants we're experimenting with and I wonder if we need a build variant in addition to platform in the builds table and as a trigger parameter.

For instance, while llbuild2 is experimental right now, we’ll still want to be able to report those builds up without aggregating them into the rest of the system. For that we need a key to be able to tell them apart from the builds we _are_ using for the build matrix.

We _could_ use the platform key to encode which build command was used but that doesn’t feel right. It also pushes some logic of what a platform is to the builder and away from the backend. I.e. this feels wrong:

```
platform:
	name: macOS
	version: 10.15-xcodebuild
platform:
	name: macOS
	version: 10.15-llbuid2
```

Should there be another key under platform to record the build variant? Or a separate key?

Also, and this is a more pressing concern tbh, what about architecture? Is that an attribute of the platform? Or do we make that part of the build variant? I.e.

```
build:
	platform:
		name: macOS
		version: 10.15
	variant:
		command: xcodebuild   # tool: xcodebuild ?
		architecture: x86
```

We’ll definitely want to record that _somewhere_.

I don’t think we need to record the full build command but at least a token of what we used. The build logs can contain the actual command so we can backtrace in case we need to figure out details.

**Comment by daveverwer** [comment]
Yea, I don't think it needs to be hierarchical, but I do think that storing both the build system used and especially the architecture would be smart.

Instead of `command` or `tool` how about being explicit as `buildTool`?

It does make flattening the data into something viewable into a 2D matrix one step harder than it was before, but it's probably only incremental complexity over the flattening we'll already have to do.

**Comment by daveverwer** [comment]
I'd probably do them as 3 fields in the build table as variant feels slightly wrong to me:

* `platform` (containing both a platform type and a version. As in your example above)
* `architecture`
* `build_tool`

**Comment by finestructure** [comment]
This has been sorted out for a while now - closing :)
