### ISSUE TITLE
yshrkt/NFCSupport 404

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#512]
This package is throwing a 404 in our smoke tests. We can’t display it, because we don’t have a title and the reason is that the package manifest is inconsistent on the main branch (and the latest version 0.7.0). We do have a correct parse for version 0.6.0.

The issue is a conflict between the declared swift-tools-version and the swift language version. For example:

```
// swift-tools-version:4.2
…
    swiftLanguageVersions: [.v5_2]
}
```

This leads to:

```
❯ swift package dump-package
/Users/sas/Downloads/NFCSupport: error: manifest parse error(s):
/Users/sas/Downloads/NFCSupport/Package.swift:23:30: error: type 'SwiftVersion' has no member 'v5_2'; did you mean 'v4_2'?
    swiftLanguageVersions: [.v5_2]
                             ^~~~
                             v4_2
PackageDescription.SwiftVersion:4:10: note: 'v4_2' declared here
    case v4_2
         ^
Fatal error: Index out of range
fish: 'swift package dump-package' terminated by signal SIGILL (Illegal instruction)
```

This is not a problem per se, except our smoke tests will flag this on every run now. I guess we have a few options:

1. do not run a full test after all (although that just reduces the chances of this happening, doesn’t eliminate it entirely - it’s just up to whether a problematic package ends up in the test set)
2. loosen the requirement for a package title. We could display an explainer when we can pull a package title from the db, just like we do for versions etc.
3. remove the package from the index
4. find the package name from another version

Option 3 seems harsh, because while the package seems to be old, there was activity last month, presumably to update it. That may have broken it but I think we need to be lenient WRT to breakage on the default branch. This is where package updates are being prepared.

Option 4 is probably the most graceful option but can get messy. When package names change (and we’ve seen this), we’ll need to make sure we find a consensus. In this case it’s not even the latest version 0.7.0 that would correct this. We’d need to pick 0.6.0.

Option 1: This has been our main mechanism to find parsing or package issues and until we find it’s flagging false negatives I think we should keep it.

Option 2: Seems to be the most sensible thing to do. It allows the package owner to see the issue or someone else to take it to them - even us, by linking to the package in an issue, which is harder to do now.

**Comment by finestructure** [comment]
I’ve raise an issue for the repo owner: https://github.com/yshrkt/NFCSupport/issues/1

**Comment by daveverwer** [comment]
Yea I think this is quite different from a package that gets deleted/goes private, and we should not remove it. It's only 3 months old and the mistake is just a typo.

> is probably the most graceful option but can get messy. When package names change (and we’ve seen this), we’ll need to make sure we find a consensus. In this case it’s not even the latest version 0.7.0 that would correct this. We’d need to pick 0.6.0.

Yea I think this would be too subtle, Xcode would still try and import 0.7.0 and then it'd fail. If the package is failing, it's failing. We should show a page for it, but not try and find working versions.

> loosen the requirement for a package title. We could display an explainer when we can pull a package title from the db, just like we do for versions etc.
 
This is my preferred option.

However, I'd like to get a sense of how often this happens before we fix it. Let's leave it as a 404 for now as I'd say it's likely the owner will fix this issue and it'll give us a chance to see how often this happens (my guess is "not very often").

**Comment by finestructure** [comment]
We should look into this soon by either allowing blank titles or disabling the smoke tests - they’re firing after each deploy and I’m now getting blind to them: they’re not serving a purpose right now because they’re too frequent (while still correctly failing).

**Comment by daveverwer** [comment]
I completely agree. 

I'll switch the title of this issue to make it more explicit what we want to do.

**Comment by daveverwer** [comment]
Actually, changing it back. There's too much noise in this thread. Creating a new issue for it.

**Comment by daveverwer** [comment]
Closing this in favour of #518 and #519.
