### ISSUE TITLE
Package pages should not 404 if the package has no valid package name

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#518]
If we end up in a situation where the package name can't be parsed for some reason (usually a bad package manifest) then it is currently excluded from the site search, and also returns a 404 error if the package page is loaded directly.

If a package has no package name, it should use the repository name (just name, not name and owner) as the package name as this is the most reasonable data we have and is better than showing an empty package name.

Package pages *should* show up in search as well, again with the repository name instead of the blank package name.

**Comment by finestructure** [comment]
Fixed #1048
