### ISSUE TITLE
Clean up the smoke test

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#520]
There are some interesting things coming up from my smoke test clean up today.

There are 6 failures currently:

* `Balancingrock/KeyedCache`
* `CoreKit/VIPERA`
* `achirkof/LoadableImage`
* `hooliooo/Astral`
* `johnfairh/TMLPersistentContainer`
* `twostraws/VisualEffects`

**Comment by daveverwer** [comment]
First failures, Swift 5.3 dependencies:

* `achirkof/LoadableImage`
* `twostraws/VisualEffects`

Fixed in [this PR](https://github.com/SwiftPackageIndex/PackageList/pull/465/files). We can add them back when we get 5.3 support on production.

**Comment by daveverwer** [comment]
Next, bad packages:

* `Balancingrock/KeyedCache` - Missing a comma in the manifest. [PR created](https://github.com/Balancingrock/KeyedCache/pull/2) on the package repository.
* `CoreKit/VIPERA` - This package had been deprecated, I have switched it to the new repo in [this PR](https://github.com/SwiftPackageIndex/PackageList/pull/466).
* `hooliooo/Astral` - This is a bad package manifest and it should not have been in the index (it would never have made it past validation, if validation existed). Removed in [this PR](https://github.com/SwiftPackageIndex/PackageList/pull/466).
* `johnfairh/TMLPersistentContainer` - Interesting situation, I have [created an issue](https://github.com/johnfairh/TMLPersistentContainer/issues/16) on the package repository.

If the PR on `Balancingrock/KeyedCache` isn't merged in a few days we should remove the package from the index, but we can leave it failing for a couple of days.

Same deal with `johnfairh/TMLPersistentContainer`, let's see what John says in the issue discussion and make a decision from there.

**Comment by daveverwer** [comment]
We're now down to just two failures in the smoke test:

* `Balancingrock/KeyedCache`
* `johnfairh/TMLPersistentContainer`

Both have fixes that are in progress.

**Comment by finestructure** [comment]
Latest smoke test is green https://gitlab.com/finestructure/swiftpackageindex/-/jobs/735631291 but we'll probably always get failures every once in a while simply because there's always a chance something gets renamed between the nightly cleanup and the smoke test.
