### ISSUE TITLE
PackageList validation - Check for redirects

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#522]
We should add one more validation to the new PackageList validator, a check for a 301 or 302 status code on the repository.

* Once we have verified that the URL ends with `.git`
* Strip the `.git` and make a request for the URL
* Fail validation if the status code is `3xx`

**Comment by Sherlouk** [comment]
Rather than failing the script, would it be terrible to detect the final URL, make sure that it's not already in the list and just replace it for the user?

**Comment by daveverwer** [comment]
That would work too. I did consider suggesting this but unlike sorting, or a missing `.git` extension this error is probably a little more unexpected/serious and might warrant more explicit flagging to the user.

Your suggestion is probably better though, as long as CI fails 👍

**Comment by Sherlouk** [comment]
That's a point, with the new "auto fixes" I don't think we end with a fail code -- I'll fix that too.

Out at the moment but will get a MR raised later today 👍

**Comment by finestructure** [comment]
I’m slight confused - should this be an issue in the PackageList repo or does this concern ingestion?

**Comment by finestructure** [comment]
Ah never mind - it looks like there are no issues in PackageList. I’m less confused now 😅

**Comment by daveverwer** [comment]
Yep! I disabled issues there a while ago as I wanted just one list really and there shouldn't be many issues on that repo.
