### ISSUE TITLE
Post package releases to the @PackageFirehose account

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#523]
We have two Twitter accounts for tweeting package updates and site updates. The accounts are:

* [@SwiftPackages](https://twitter.com/SwiftPackages) - Which will tweet edited highlights of package releases, and site news and updates.
* [@PackageFirehose](https://twitter.com/PackageFirehose) - Which will tweet every release of every package as the index discovers it.

This issue deals *only* with the @PackageFirehose account, automatically tweeting package releases.

The tweets should be driven by the same mechanism that drives the “all releases” RSS feed, here: https://swiftpackageindex.com/releases.rss.

Every time we discover a new package release, whether major, minor, patch, or pre-release, we should post a tweet in the following format:

```
[Package name] just released [Package version] - [Package summary] https://swiftpackageindex.com/[Repository owner]/[Repository name]
```

Maybe @finestructure can chime in on the best approach to where the code that posts the tweets could live.

**Comment by daveverwer** [comment]
The @PackageFirehose Developer account just got approved 👍 I'll send you the credentials @Sherlouk

**Comment by Sherlouk** [comment]
Happy to close this one down @daveverwer? or would you rather wait until the bug fixes are sorted and it's shipped into production?

**Comment by daveverwer** [comment]
Yep, we can close this. Thanks for your work on it @Sherlouk!
