### ISSUE TITLE
Don't set Package.status to `metadata_request_failed` if the GitHub API call fails with a "Forbidden" error

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#54]
The GitHub API key running out of API requests isn't a failure of the package, but we currently store `metadata_request_failed` against the package if that API call fails.

My gut feeling says that if the GitHub API fails because the API is down, or if it returns a 500, or anything that's not the fault of the package, then the record shouldn't be updated *at all*. We should just move on, and it'll still be a candidate for next time the ingestor runs.

Doing it as we do at the moment means the status field can be a little meaningless.

Of course, if it's a 404, that's fine because it means the project has *gone* and I'd expect it to be a `metadata_request_failed` at that point.

**Comment by finestructure** [comment]
I remember checking when this happened and it's a 403 - forbidden, IIRC. I was hoping to get a 429 for rate limiting to be able to tell if it's due to the API key. But maybe a 403 is good enough?

The issue with not updating the package at all in that case is that it won't be flushed from the candidate list and you'll turn around trying it again immediately/soon.

Maybe a different error code would help, one that we then take into account when selecting candidates.

**Comment by daveverwer** [comment]
A 429 would be ideal, but I'm also seeing 403s when the rate limit is reached.

> The issue with not updating the package at all in that case is that it won't be flushed from the candidate list and you'll turn around trying it again immediately/soon.

I think that's exactly what's needed. It *should* be the next one that's attempted. The rate limit, or if the GitHub API goes down for some reason shouldn't cause the package to lose its slot in thw queue.

The only issue I see with this is if there's a significant number of packages that were public, but then go private (which I think will also be a 403 error). We should be checking for those occasionally and removing them from the master package list if they stay private for a while.

**Comment by finestructure** [comment]
Mmm, I'm just a little concerned about not backing off on a 403. Without intervention it's not going to resolve itself and there's a chance to make it worse by earning an IP blacklist.

Say for some reason prod drops the api key or someone deletes it from the GH console. The server would fail and keep failing. If the fixed IP then gets blacklisted you can't even fix it by adding back the PAT.

I think immediate retry is ok only if you have reason to believe it'll sort itself out on its own.

Bear in mind the `metadata_request_failed` records should get retried in the current scheme whenever the deadtime is up (10mins to be changed to 60mins). (I def. agree we should make it a different error code, this one is misleading.)

Does that make sense?

**Comment by daveverwer** [comment]
> I think immediate retry is ok only if you have reason to believe it'll sort itself out on its own.

Which for a rate limit fail, or a timeout, or a 500 error from GitHub, it should.

I think what might be needed here is some actual checking for rate limit fails. The [documentation](https://developer.github.com/v3/#rate-limiting) says that if it's a rate limit failure, that it'll be a 403, but that it'll also have the `X-RateLimit-Limit`, `X-RateLimit-Remaining`, and `X-RateLimit-Reset` headers set.

So maybe if the connection times out, or for a 500, or for a 403 where the `X-RateLimit-Remaining` is 0 the record doesn't get touched. Otherwise, it acts as normal.

That said, I may be overengineering it 😂 I'm happy to do it the other way too.

**Comment by finestructure** [comment]
Ah nice, so there is a way to tell if it's a rate limit.

I'll add something to be able to differentiate the error scenarios and make it so we retry those where we can expect to succeed without intervention, starting with the 500s and header inspection shouldn't be too terrible to figure out either :) 👍

**Comment by finestructure** [comment]
This should have been partially (completely?) addressed by #361 , although I'd need to double check how this is reported up now and if it fixes this issue here entirely.

**Comment by daveverwer** [comment]
Yea, I hadn't had a chance to talk to you about the new "Post-launch" project yet. I didn't mean to indicate that any of those *should* be our next priorities, I just filled it with basically everything that was a quick win, or a bug, or something like this that we at least want to look at whether it's still a problem. 

Issues like this have a way of languishing in backlogs forever, so I wanted to have a discussion about it :) 

Let's keep it open until we've seen some packages start failing again so we can see what happens with them.

**Comment by finestructure** [comment]
Totally on board with that :) I dislike issue cruft!

Just wanted to leave a note here for future self to check that PR for reference.
