### ISSUE TITLE
Builder: TimelaneCombine false negative

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#544]
https://staging.swiftpackageindex.com/builds/06665663-1477-4661-8D61-0E322E2B4A01

Fails with

```
return OSLog(subsystem: "tools.timelane.subscriptions", category: OSLog.Category.dynamicStackTracing)
                                                                  ~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
```

This seems to be an issue with misaligned toolchain and installed SDKs. The build works when the build is run without `--toolchain` parameter (both for Xcode 11 and 12).

**Comment by finestructure** [comment]
One possible way to handle this could be:

```
if `swiftenv local x.y.z` == `swiftenv local system` (i.e. if the chosen swift version is the same as the system toolchain)
  swiftenv local system
  xcrun xcodebuild ...
else
  swiftenv local x.y.z
  xcrun --toolchain “org.swift.x.y.z” xcodebuild
```

We’d have to accept that for projects where this is an issue, only builds with the system toolchain would succeed.

**Comment by finestructure** [comment]
This might also pull back the watchos builds, which probably fail for the same reason.

**Comment by daveverwer** [comment]
This would work, but I think it's a less than ideal solution as it's just going to show potentially incorrect statuses for all other versions of Swift when the actual incompatibility isn't Swift, but the use of the SDK.

It's not a bad fallback if we fail to dig into the root cause, but let's try and dig in with Ankit and Boris to see if we can't figure out the correct series of runes we need to place to get it working correctly first.

**Comment by finestructure** [comment]
This passes:

```
env DEVELOPER_DIR=/Applications/Xcode_11.6.app xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.derivedData" build -scheme "TimelaneCombine" -destination "generic/platform=macos"
```

as does `Xcode_11.3.1` (which is Swift 5.1). Earlier versions of Xcode fail, because there’s no xcode project. This makes perfect sense - Xcode 10 had no support for packages.

The build logs also clearly indicate that the correct version of Xcode, Swift, and the SDKs are used. For instance:

```
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'TimelaneCore' from project 'TimelaneCore')
    cd /Users/sas/Downloads/TimelaneCombine/.derivedData/checkouts/TimelaneCore
    export DEVELOPER_DIR=/Applications/Xcode_11.3.1.app/Contents/Developer
    export SDKROOT=/Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
    /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name TimelaneCore -Onone -enable-batch-mode -enforce-exclusivity=checked @/Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Intermediates.noindex/TimelaneCore.build/Debug/TimelaneCore.build/Objects-normal/x86_64/TimelaneCore.o.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -DXcode -sdk /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -target x86_64-apple-macos10.10 -g -module-cache-path /Users/sas/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Index/DataStore -swift-version 5 -I /Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Products/Debug -F /Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Products/Debug -F /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -parse-as-library -c -j8 -output-file-map /Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Intermediates.noindex/TimelaneCore.build/Debug/TimelaneCore.build/Objects-normal/x86_64/TimelaneCore-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Intermediates.noindex/TimelaneCore.build/Debug/TimelaneCore.build/Objects-normal/x86_64/TimelaneCore.swiftmodule -Xcc -I/Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Products/Debug/include -Xcc -I/Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Intermediates.noindex/TimelaneCore.build/Debug/TimelaneCore.build/DerivedSources-normal/x86_64 -Xcc -I/Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Intermediates.noindex/TimelaneCore.build/Debug/TimelaneCore.build/DerivedSources/x86_64 -Xcc -I/Users/sas/Library/Developer/Xcode/DerivedData/TimelaneCombine-asteteamhidsbjdxapfnprsoetgt/Build/Intermediates.noindex/TimelaneCore.build/Debug/TimelaneCore.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -working-directory /Users/sas/Downloads/TimelaneCombine/.derivedData/checkouts/TimelaneCore
```

So it seems like simply replacing `--toolchain ...` with `env DEVELOPER_DIR` will get us there!

**Comment by finestructure** [comment]
This also fixes the reported AWS SDK build issue

![DE861834-AA95-4285-AE7E-8330D7538DAB](https://user-images.githubusercontent.com/65520/88041551-ddf41200-cb4a-11ea-93e9-e8956385c649.jpeg)

**Comment by daveverwer** [comment]
This is such fantastic news 🚀 I feel so good about this solution! It has very few downsides.

So, from doing a bit of digging both [here](https://en.wikipedia.org/wiki/Swift_(programming_language)) and [here](https://xcodereleases.com) I think we can probably support the following Swift versions, with the following Xcode releases.

* Swift 5.1 - Xcode 11.3.1 (this should be the last version of Swift 5.1.x
* Swift 5.2 - Xcode 11.6 (the latest version of Xcode 11, which includes Swift 5.2)
* Swift 5.3 - Xcode 12

I don't think it'll be possible to test with anything less than that for the reasons you bring up, but I also think that's absolutely fine.

**Comment by finestructure** [comment]
I’d be happy to drop Xcode 10.1 and 10.3 (Swift 4.2 and Swift 5.0 respectively). One thing to bear in mind though is that some packages, for instance one that we have in our tests, `AECoreDataUI`, come with an xcodeproj file and due to that have a chance to work with those Xcodes. I’m just about to push the change to CI to see if `AECoreDataUI` still passes with this change. (I can’t test this locally, because Xcode 10.x crashes on launch on Big Sur 😅)

**Comment by finestructure** [comment]
Yes, [that still passes](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/649193788), so we could keep 10.1 and 10.3 around for those packages that come with project files.

**Comment by daveverwer** [comment]
That's great news! Let's chat about it in the morning a bit further but this is 👍👍👍.

**Comment by finestructure** [comment]
In order to close this one we also need to extend the builds page to split out the spm builds. After reprocessing, it's still showing macOS as failing, but that's because it's picking up the spm build instead of the xcodebuild (which I believe is an ordering issue).

https://staging.swiftpackageindex.com/icanzilb/TimelaneCombine/builds

<img width="454" alt="Screenshot 2020-07-22 at 14 15 48" src="https://user-images.githubusercontent.com/65520/88175247-e66d4b00-cc25-11ea-94e1-37f3e74d3ea9.png">

**Comment by finestructure** [comment]
That's the macOS build log after today's processing run:

<img width="705" alt="Screenshot 2020-07-22 at 14 16 38" src="https://user-images.githubusercontent.com/65520/88175373-0b61be00-cc26-11ea-9a84-2802bfc4b505.png">

**Comment by finestructure** [comment]
Oh no, this is bad. I just realised that we're not reporting builds by build tool but by platform. I.e. the spm build is currently overwriting the xcodebuild for macOS.

**Comment by finestructure** [comment]
The simplest solution is probably to use the platform version field to distinguish this. Which is not as hacky as it may sound - this field was intended for macOS 10.11, 10.12 etc but that's not what we're using it for. We could stick it in there, which is also what we're intending to do for ARM.

But it may be better to change `Platform` from

```
struct Platform {
  var name: Name
  var version: String
}
```

to

```
struct Platform {
  var name: Name
  var buildTool: BuildTool
  var architecture: Architecture
}
```

Although that’s also not great, because we’ll have states that shouldn’t be representable, like for instance

```
Platform(name: .linux, buildTool: .xcodebuild, architecture: .x86_64)
```

Perhaps we should move simply enumerate the platforms we have?

```
struct Platform {
  static var ios
  static var macosArmSpm
  static var macosArmXcodebuild
  static var macosSpm
  static var macosXcodebuild
  static var tvos
  static var watchos
  static var linux
}
```

**Comment by daveverwer** [comment]
> Perhaps we should move simply enumerate the platforms we have?
> 
> ```
> enum Platform: String {
>   case ios
>   case macosArmSpm
>   case macosArmXcodebuild
>   case macosSpm
>   case macosXcodebuild
>   case tvos
>   case watchos
>   case linux
> }
> ```

Yep, I'd be strongly in favour of this approach. It's simple 👍

**Comment by finestructure** [comment]
This is now fixed

<img width="1235" alt="Screenshot 2020-07-23 at 16 25 19" src="https://user-images.githubusercontent.com/65520/88298242-353be300-cd01-11ea-8d62-dce5ba5bff1c.png">
