### ISSUE TITLE
Show if a package is archived

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#552]
The repo API tells us if a repo has been marked as archived/read-only by the repo owner.

https://github.com/Ch0uti/ChouTi is a known archived repo in our index.

In a discussion with Dave we believe it's best that we don't completely exclude these from the index, but is important that we highlight this information to users of the site to make a more informed decision.

Changes:
- [ ] Record a `archived` field in the repositories table and populate it from the GitHub API call.
- [ ] Reduce the package's search score (-5) if it's archived (?? - I've made this requirement up)
- [ ] Display whether a repository is archived on the Package page.

This does likely link up to the "extra package metadata" conversations which are ongoing (#435) as people may wish to label their repo as archived from there too. I believe this is an acceptable interim solution which can be evolved to include that at a later date.

**Comment by daveverwer** [comment]
> In a discussion with Dave we believe it's best that we don't completely exclude these from the index, but is important that we highlight this information to users of the site to make a more informed decision.

Just to clarify my position on this a little. I think it's certainly something we could highlight on the package page, but I don't think it's a particularly pressing issue. It's good to log it and I agree it should be done at some point, but I don't think we're trying to completely replicate every bit of metadata on Package pages, just the highest value bits.

If it's the case that someone gets to the GitHub page for this package and realises it's archived, that's OK. Especially while there's only a small number of archived packages in the index.

**Comment by Sherlouk** [comment]
@daveverwer - is this still something you're not fussed about including at this moment in time? or would you be happy for me to pick it up?

I think now that the GraphQL work is all done this *should* be fairly easy 🙏  (If not slightly frustrating when I have to request yet another db dump from you 😛)

**Comment by daveverwer** [comment]
I think it's still a fairly low priority, but if you'd like to pick it up then it'd be great to have!

In terms of the front end, I think we should load this into the first bullet point on the package page. Where it currently says:

> In development for 5 years, with 680 commits and 10 releases.

It should say something like this for archived packages:

> **No longer in active development.** The package author has archived this package and the repository is read-only. It had 680 commits and 10 releases before being archived.

@finestructure do you have any implementation guidance?

**Comment by finestructure** [comment]
With respect to implementation, pulling in the data is hopefully easy as it should be just another field in the GraphQL query (there's a link to the explorer near the query method to check it out beforehand). It'd be good to fetch an updated json for the fixture in the test.

Then routing it through to the db and PackageShow+Model should hopefully be quite straightforward. I believe you mentioned having trouble running ingestion locally, @Sherlouk , so please give a shout if that remains to be an issue. I fixed an issue yesterday where the absence of the metrics push gateway led to an error being thrown, so perhaps that was what derailed you.

**Comment by Sherlouk** [comment]
Thanks Sven - aye I managed to get past the metrics issue (just commented out that part of the troublesome code) but ran into issues further downstream but will give you a shout with specifics if I can't get past it this time!

Done quite a bit with GitHub's GQL before so I'm not sensing too many problems but feels like a fun little piece to pick up (I'm also just slightly curious how many packages are archived!)
