### ISSUE TITLE
Deployment automation

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#57]
I've started having a look at out deployment options.

What I know works without any further research is the following:

- mirror repo to Gitlab
- instrument Linode box as a runner
- drive deployment to it via `.gitlab-ci.yml`
- run docker-compose up on the runner (the Linode box)

I'm doing this for several projects and it works well. The downside is that deployment runs separate-ish. While `.gitlab-ci.yml` could happily live inside the repo, what it triggers happens elsewhere. (Although arguably it has to happen elsewhere by definition - the Linode box - it's just a question of how much of it does.)

For Github actions I believe we can go the following:

- build docker image as we do now
- push to docker hub
- set up ssh action that runs on Linode box
- pull docker image
- run docker-compose up

The slight issue I'm seeing right now is that there's no built in ssh action (AFAICT) and I'm not excited to use a 3rd party one that handles private keys as an input. However, I think it shouldn't be too hard to either fork one and use a version we control or just run the key handling inline.

Or maybe I'm to sensitive about the key? B/c unless we host our own runner (which we easily could, I'm doing it for three other GH projects) we'll always be passing our private key to some machine we don't control.

**Comment by daveverwer** [comment]
Both of these sound reasonably complicated! As someone who hasn't deployed via Docker before I'm not sure I can really be much help here.

I do think that keeping the SSH key protected is important though. Yes, it's an open-source project that collects publicly available data, but the issues someone could cause on the server are not trivial.

**Comment by finestructure** [comment]
So variant 1) is simple - I'd just need to mirror existing setup to our situation. I'm using this on a number of projects and know how to set this up quickly.

Variant 2) should be equally possible, it's just something that needs a bit more research and elbow grease.

I'll do a little more digging into setting up GH today but if you don't have a strong preference I'd go for tried and true unless I come up with something soon, ok?

**Comment by daveverwer** [comment]
Simple sounds better, and more things will become simple in the future. It's not ideal to have the project mirrored on GitLab, but if it's only used for deployment (could it even be a private mirror?) then I think it's the best solution.

**Comment by finestructure** [comment]
Yeah, I was thinking it could actually be beneficial to have that in a private repo, segregated away. I'll start there then 👍
