### ISSUE TITLE
Mark significant versions

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#574]
We have started making heavy use of the following [“client side” (i.e. code side vs SQL side) logic](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/2e0f3f528860eb458791457aa65c96ede41bc738/Sources/App/Views/PackageController/Package%2BModelSupport.swift#L107) to find the (up to) three “significant versions” of a package:

```swift
    func releases() -> (stable: Version?, beta: Version?, latest: Version?) {
        guard let versions = $versions.value else { return (nil, nil, nil) }
        let releases = versions
            .filter { $0.reference?.semVer != nil }
            .sorted { $0.reference!.semVer! < $1.reference!.semVer! }
        let stable = releases.reversed().first { $0.reference?.semVer?.isStable ?? false }
        let beta = releases.reversed().first {
            // pick first version that is a prerelease *and* no older (in terms of SemVer)
            // than stable
            ($0.reference?.semVer?.isPreRelease ?? false)
                && ($0.reference?.semVer ?? SemVer(0, 0, 0)
                        >= stable?.reference?.semVer ?? SemVer(0, 0, 0))
        }
        let latest = defaultVersion()
        return (stable, beta, latest)
    }
```

As part of looking into “build reconciliation” in issue #561 it’s becoming increasingly awkward having to pull down all versions of a package and then identify the three ones we’re interested in. Since these significant versions never change on their own, we could simply set a flag on the version record as part of the analysis stage. This would make downstream selections _a lot_ easier.

**Comment by finestructure** [comment]
Something like

```swift

final class Version: Model, Content {
  …

  enum Kind: String {
    case latestRelease
    case latestDefaultBranch
    case latestBeta
    case generic
  }

  @Field(key: “kind”)
  var kind: Kind
 
  …
}
```

Not sure about the exact names.

**Comment by finestructure** [comment]
Or maybe

```swift
final class Version: Model, Content {
  …

  enum Kind: String {
    case release
    case defaultBranch = ‘default_branch'
    case beta
  }

  @Field(key: “latest”)
  var latest: Kind?
 
  …
}
```

```
select * from versions where latest in (‘release’, ‘default_branch’, ‘beta’)
```

**Comment by daveverwer** [comment]
Or even easier 

```
select * from versions where latest is not null;
```

I love this idea. I'm always a fan of letting the database take the load off, and this feels like a perfect situation. This data can never change anywhere apart from the analysis phase, and so it feels like a pretty safe thing to do.

👍 from me!

**Comment by finestructure** [comment]
Excellent. I’ll tackle that next then, as it’s pretty much a prerequisite for the build trigger mechanism.
