### ISSUE TITLE
`GIT_TERMINAL_PROMPT=0` leads to crash on Linux

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#58]
Triggering repository is our friend https://github.com/SwiftyBeaver/AES256CBC.git

```
analyze_1    | Fatal error: Error raised at top level: ShellOut encountered an error
analyze_1    | Status code: 128
analyze_1    | Message: "fatal: could not read Username for 'https://github.com': terminal prompts disabled"
analyze_1    | Output: "": file /home/buildnode/jenkins/workspace/oss-swift-5.2-package-linux-ubuntu-18_04/swift/stdlib/public/core/ErrorType.swift, line 200
analyze_1    | Current stack trace:
analyze_1    | 0    libswiftCore.so                    0x00007ff392e15db0 swift_reportError + 50
analyze_1    | 1    libswiftCore.so                    0x00007ff392e87f60 _swift_stdlib_reportFatalErrorInFile + 115
analyze_1    | 2    libswiftCore.so                    0x00007ff392b9cdfe <unavailable> + 1383934
analyze_1    | 3    libswiftCore.so                    0x00007ff392b9ca07 <unavailable> + 1382919
analyze_1    | 4    libswiftCore.so                    0x00007ff392b9cfe8 <unavailable> + 1384424
analyze_1    | 5    libswiftCore.so                    0x00007ff392b9b2d0 _assertionFailure(_:_:file:line:flags:) + 520
analyze_1    | 6    libswiftCore.so                    0x00007ff392be3c4c <unavailable> + 1674316
analyze_1    | 7    Run                                0x000055e446ed5f51 <unavailable> + 7941969
analyze_1    | 8    libc.so.6                          0x00007ff39086eab0 __libc_start_main + 231
analyze_1    | 9    Run                                0x000055e4468619ea <unavailable> + 1173994
analyze_1    | 0x7ff39283e88f
analyze_1    | 0x7ff392b9b4e5
analyze_1    | 0x7ff392be3c4b
analyze_1    | 0x55e446ed5f50, main at /build/<compiler-generated>:0
analyze_1    | 0x7ff39086eb96
analyze_1    | 0x55e4468619e9
analyze_1    | 0xffffffffffffffff
swiftpackageindex-server_analyze_1 exited with code 132
```

**Comment by daveverwer** [comment]
It's weird why this doesn't work. Does it suppress the prompt when running it directly from the command line on the server? It looks like it's not doing that from that output.

**Comment by finestructure** [comment]
Yes, that's odd. It should look like this:

```
spi@localhost ~/temp [SIGINT]> env GIT_TERMINAL_PROMPT=0 git clone https://github.com/SwiftyBeaver/AES256CBC.git
Cloning into 'AES256CBC'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

And that's what I got on macOS IIRC. What's weird is that it crashes instead of hanging - but that might be an artefact of stdin issues at the prompt.

I'll try to figure out a way to actually set up a proper test for it rather than just manual testing.

**Comment by daveverwer** [comment]
Ah, I actually read the original output wrong. I read `fatal: could not read Username for 'https://github.com'` and assumed that was the prompt for input, I didn't scroll right.

My theory was that it was crashing because of trying to read stdin.

So, analysis *always* follows ingestion, and we can tell whether a repo is switched to private in the ingestion stage. We could flag that during ingestion (a new `status` code for private repositories, and we just skip analysis (and everything else) for repos that now identify as private 😂

**Comment by finestructure** [comment]
Actually, I read it wrong as well 🤣 So the prompt disabling _is_ working correctly - but crashing on the result. I think you're right, it's the read from stdin that kills is and it might have to do with the docker env.

That's bad 😞 That means any repo going private at an inopportune time would crash the service. I'll need to figure out where this is going wrong.

**Comment by daveverwer** [comment]
> We could flag that during ingestion (a new status code for private repositories

I think even if we stop this crash, that's a good idea as it'll allow us to easily identify and remove private repos from the master list occasionally.
