### ISSUE TITLE
Report build error for unavailable repos

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#586]
If a repo is unavailable (404), we shoud report back a build error rather than bailing out and not reporting back at all.

https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/670084762

```
$ ./build.sh
Error: ShellOut encountered an error
Status code: 128
Message: "fatal: could not read Username for 'https://github.com': Device not configured"
Output: ""
Clone URL: https://github.com/ole/PropertyWrappers.git
Reference: master
ERROR: Job failed: exit status 1
```

**Comment by finestructure** [comment]
Do we even need to bother? I don't think it's a problem if builds aren't reported back for a non-existent package which will be "garbage collected" anyway.

I'll close it for now.

**Comment by daveverwer** [comment]
Yea this seems fine.
