### ISSUE TITLE
Lots of new packages in RSS feed

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#600]
I’ve noticed something weird about the RSS feed, for the second time: An whole bunch of packages (45 in all) showed up as new:

![IMG_0113](https://user-images.githubusercontent.com/65520/89458840-02193b00-d768-11ea-8414-01ea04fc655c.png)

Are you seeing this as well or does this have something to do with my RSS setup (Reeder via feedbin)?

**Comment by finestructure** [comment]
What’s weird is that this goes back a few days. Oh, and notice the 0.0.0 version number? Is that a real package version?

**Comment by finestructure** [comment]
Ah no, false alarm - I was looking at the “All Releases” feed, not “New Packages”. I guess we really had that many new releases.

**Comment by daveverwer** [comment]
I haven't noticed it, what feed are you subscribed to?

I am subscribed to the following feeds:

* `https://swiftpackageindex.com/releases.rss?major=true`
* `https://swiftpackageindex.com/releases.rss?minor=true`
* `https://swiftpackageindex.com/releases.rss?patch=true`
* `https://swiftpackageindex.com/releases.rss?pre=true`

**Comment by daveverwer** [comment]
Ah yes, there are *lots* of releases every day. It moves quickly
