### ISSUE TITLE
Add support for Apple Silicon builds

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#605]
- [x] set up runner on DTK
- [x] add job to builder CI config
- [x] test and confirm ARM builds on DTK
- [x] add cases (xcode, spm) to supported platforms
- [ ] tweak concurrency on `spi-dtk-builder`

**Comment by finestructure** [comment]
I'm wondering: where does ARM fall here? Does it even show up? I'd be weird if it didn't but an extra column `macOS/ARM` or something also falls out of line a bit:

<img width="709" alt="Screenshot 2020-08-09 at 11 47 47" src="https://user-images.githubusercontent.com/65520/89729457-27db6400-da36-11ea-8608-6f4c89c56a15.png">

Or should the basic assumption just be that ARM is under macOS and we only show it in the builds?

I think I'd slightly prefer that, actually.

**Comment by daveverwer** [comment]
> Or should the basic assumption just be that ARM is under macOS and we only show it in the builds?

I think that eventually, this is where that should live. That it should bubble up to simply be part of macOS. However, in the transition period, it's important enough to deserve its own column.

> I'm wondering: where does ARM fall here? Does it even show up? On the one hand it'd be weird if it didn't but an extra column `macOS/ARM` or something also falls out of line a bit:

Yes, I think a new column to the right of macOS titled macOS/ARM would be my vote.

**Comment by finestructure** [comment]
One thing that's obvious but I'd forgotten until I just ran a test is that we'll only be building ARM for Swift 5.3:

```
builder@spi-dtk ~/Downloads> ./builder build -p checkout --platform macos-spm-arm -s 5.2.4
Selected platform:         macosSpmArm
Swift version:             v5_2
Building package at path:  checkout
Running build ...
env DEVELOPER_DIR="/Applications/Xcode_11.6.app" xcrun swift build
Error: ShellOut encountered an error
Status code: 1
Message: "xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode_11.6.app"
Output: ""
```

So in the Build Index View we'll have gaps for the other swift versions unless we suppress them manually. That might be a bit fiddly, I'll need to check what level of control we have right now and how much that'd need to be reworked.

**Comment by finestructure** [comment]
Builder test details here: https://gitlab.com/finestructure/swiftpackageindex-builder/-/issues/13

**Comment by finestructure** [comment]
About to roll this out to staging but following up with a tag shortly after, because we won't trigger on staging anyway.

Error scenarios:

1. arm builds not triggered
2. arm builds not picked up

Case 1 isn't time sensitive. We can diagnose and troubleshoot without rush.

Case 2 is time sensitive: worst case we're queueing up to 2-4 arm builds per minute, say 180/hour. This number will be a lot lower in practise though, because on a lot of cycles we don't actually enqueue because we're at the queue limit.

We should have an hour or two to react before having to consider rolling back.

We could also cancel arm builds manually in Gitlab if need be.

**Comment by finestructure** [comment]
Concurrency on the DTK is 2 but it could easily handle more. The thing is - even so it's going to be sitting idle, because for the set of 32 builds we have to do for a given revision, it's done with its two builds way faster than the other 30 builds.

Not suggesting we do, but if we wanted to add build capacity, we should let the DTK run intel builds :D
