### ISSUE TITLE
Investigate nightly 500s

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#612]
For a while now we've been seeing small batches (around 10) of 500s showing up at around 6am CET

https://rollbar.com/finestructure/SPI-server/items/20/

Might be related to the nightly job perhaps. Maybe the smoke test is triggering some errors when hitting a certain package?

Unfortunately, the error message is sparse: `Abort.500: Internal Server Error`

A few options:

- try and find the server logs around that time (may need to fix the persistence issue or keep a tmux session on it)
- revisit logging more details
- trigger a smoke tests and observe the logs

**Comment by finestructure** [comment]
Actually, this morning we had ~65 occurrences.

**Comment by daveverwer** [comment]
I've noticed these for the last two nights. At the same time, the site itself goes down for maybe 5 minutes. The sure goes down, something crashes multiple times, then the site is available again. 

An extra bit of information that might help.

**Comment by finestructure** [comment]
Ah, interesting. I've just checked and we didn't actually run the smoke test this morning: https://gitlab.com/finestructure/swiftpackageindex/-/pipelines/176449475

The build didn't complete, so we didn't reach that stage. However, the db backup ran at about exactly the time the errors started appearing: https://gitlab.com/finestructure/swiftpackageindex/-/jobs/679999530

We may be putting too much stress on the box all at the same time. I'll make it skip the backup tomorrow to see if it's related.

**Comment by Sherlouk** [comment]
We can temp disable the nightly job if you think it's causing problems?

**Comment by daveverwer** [comment]
The nightly job is absolutely fine, it's the torture that we're putting the main boxes through that it's struggling with. Another week or so and it should calm down though.

**Comment by Sherlouk** [comment]
👍 Just wanted to double check with what was said above, thanks Dave

**Comment by finestructure** [comment]
Just to clarify: I was referring to a different nightly job, @Sherlouk - one that we run on the SPI project, not the package list project :)

**Comment by Sherlouk** [comment]
Aha sorry for the confusion there 😄

**Comment by finestructure** [comment]
Stopping the backup has certainly had an effect.

But I think I know what these are now. They just popped up as I was rolling out a new version on `dev`, which was slow.

We've got multiple containers running that make up the system. When we update, they get updated in turn. Because they talk to each other (build trigger for instance pings the api), they have request failures and believe that's what we're seeing here.

When this is happening over night it could be down to load - like we have seen with the db backup.

**Comment by finestructure** [comment]
I think we can call this fixed. The issue was the backup and the remaining 500s that we sometimes get are typically dev struggling a bit.
