### ISSUE TITLE
AWS SDK builds timing out

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#613]
I closed the tabs for the first few AWS SDK builds but they hit the 1 hour queue time limit. This is configurable but 1h is probably a good safety measure anyway.

Here are some currently running builds that will probably time out as well:

- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/680098108
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/680098109
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/680098114
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/680098125

There are a couple of ways I can see us try and deal with this:

- Spread out builds. Don't trigger all build candidates from a package but a sample. The way this would work is that we schedule 5 builds from a particular package (a low enough number to ensure we have a good chance of them not clogging up a single runner). We'd try to go bredth first (across packages) and then fill in build gaps in subsequent passes. The downside is that build times across a package could be wildly different. Also, depending on release frequency, chances of holes would be higher I think.
- Don't build AWS SDK but instead work with them to get supported swift version and platform signals from them upstream.
- Find ways the package build can be broken down, perhaps by building indiviual products. This would require significant re-architecturing.

**Comment by Sherlouk** [comment]
For whatever it's worth: both AWS and Emcee caused issues timing out on the nightly/validate scripts.

**Comment by finestructure** [comment]
Update: they have indeed timed out. We'll have gaps in the matrix until they come up for re-building. I guess that'll spread them out somewhat eventually.

@Sherlouk This is a different setup entirely and purely related to run times on our builders :)

**Comment by finestructure** [comment]
It just occurred to me that we successfully processed the AWS SDK quite a number of times while testing on staging. I think what's different now is that we're running the machines a lot hotter. I suspect we're close or past the point of dimishing returns here where we run more builds per machine in total but they all take longer and we're not gaining much if anything.

I'm not suggesting to change anything now since we're halfway through but once we are, I think we should scale the runners back a bit. This might sort itself out on its own then, because if staging managed in earlier testing, all other machines will too.

**Comment by daveverwer** [comment]
> It just occurred to me that we successfully processed the AWS SDK quite a number of times while testing on staging. I think what's different now is that we're running the machines a lot hotter. I suspect we're close or past the point of dimishing returns here where we run more builds per machine in total but they all take longer and we're not gaining much if anything.

This makes perfect sense with the number of runners and the slightly strange staging/prod capacity issues we found, plus the fact that we've now had multiple panic events on the staging box. I suspect we're over the point of diminishing returns with staging and very close to it with prod.

> I'm not suggesting to change anything now since we're halfway through but once we are, I think we should scale the runners back a bit. This might sort itself out on its own then, because if staging managed in earlier testing, all other machines will too.

Yep, I think everything will be much more manageable like 7/5 on prod/staging after the backlog is done.

**Comment by finestructure** [comment]
AWS SDK has come around again and this time be managed to get a few builds through: https://swiftpackageindex.com/swift-aws/aws-sdk-swift/builds

A lot of them took 40mins to almost an hour on prod. That should be ~10mins without load, so it goes to show how much we're stressing the machines. `dev` builds are likely not making it with current concurrency.

I've dialled dev back by one and prod by two for now (7/4), to start easing up the load as we're approaching completion.

From looking at the AWS build times it's clear that we're not gaining anything from the concurrency, on the contrary (at least for AWS SDK).

**Comment by finestructure** [comment]
We've got a couple of options here, both of which are actually implemented:

1. Select target/scheme building
1. Build downscaling

Option 1 is what I discussed with Adam and it would mean that we build only the products the package owners speficy, supporting configs like this:

```
builder:
  configs:
  - platform: macos-spm
    targets:
    - AWSS3
    - AWSSNS
    - AWSDynamoDB
```

This is for building specific targets with SPM. However, in order to support the same for xcodebuild we would need to add the same syntax for schemes:

```
  - platform: macos-xcodebuild
    schemes:
    - AWSS3
    - AWSSNS
    - AWSDynamoDB
```

This then raises the question whether we require `schemes` in general or, see the protobuf change where we are using `scheme:`, maybe both (meh)?

Also, the builder then doesn't just run one build command but loops over a set of commands, as steered by `targets` or `schemes`. I've implemented it and while it feels a bit hacky is it workable.

Notably, the build command field in the build details would show a multi-line string ('\n' separated) of the build commands. Not terrible because it's going to be rare, but not great either.

All in all this feels like we're patching things up in the builder a bit too much. What if one of the libraries really doesn't build? Wouldn't we want to report that? I've re-run the builds a few times and it runs in 5-8 mins on my MBP (depending heavily on thermals) and in 4 mins on two of our fast builders (!). The reason it's sometimes taking really long is simply because we're oversubscribed when 96 AWS SDK builds land at the same time.

I think _that's_ the problem we should rather solve. Which is

Option 2: downscaling of incoming builds based on url. This is a simple env variable config for the builder of the form

```
{
"https://github.com/swift-aws/aws-sdk-swift.git": 0.2
}
```

On each build we roll the dice if it's going to be built or not and in this example the build rate would be 20%. We simply spread out the builds over a longer stretch of time, opening the queue for other packages to get in.

The builds rejected by downscaling will automatically re-triggered when their pending state is cleared after 6h. With the given parameters a build would have an ~74% (93%) chance to be processed with one (two) days.

This mechanism also gives us a very simple way of blocking a build by setting its downscaling factor to zero.

**Comment by daveverwer** [comment]
Fantastic work Sven, and I think we're getting to the bottom of a plan for this, and the plan is simple. ❤️

> All in all this feels like we're patching things up in the builder a bit too much. What if one of the libraries really doesn't build? Wouldn't we want to report that? I've re-run the builds a few times and it runs in 5-8 mins on my MBP (depending heavily on thermals) and in 4 mins on two of our fast builders (!). The reason it's sometimes taking really long is simply because we're oversubscribed when 96 AWS SDK builds land at the same time.

I think this sums it up perfectly. This package isn't a problem, it's only a problem if you try and process it too many times concurrently.

I think this comes in two stages. First, we should *really* dial back the concurrency on both staging and prod as step one. That means that when a builder gets a build, it should genuinely have the resources it needs to get it processed in a timely fashion.

> On each build we roll the dice if it's going to be built or not and in this example the build rate would be 20%. We simply spread out the builds over a longer stretch of time, opening the queue for other packages to get in.
> 
> The builds rejected by downscaling will automatically re-triggered when their pending state is cleared after 6h. With the given parameters a build would have an ~74% (93%) chance to be processed with one (two) days.

This is the second part of it, and I love it. Especially that we can play with moving this number up and down to get things running smoothly. I love this idea. It's still real-world data (compiling all products), but it keeps the load back on the servers until we manage to persuade MacStadium that we really *do* need that fully stacked $50,000 Mac Pro 😱

> This mechanism also gives us a very simple way of blocking a build by setting its downscaling factor to zero.

This is effectively the build system kill switch all in one feature. Amazing work!

**Comment by finestructure** [comment]
I think a 10 or 20k Mac Pro would do 😅  I'll get ready to roll this out then!

**Comment by finestructure** [comment]
Of course an AWS SDK release landed just before I could push this :D
