### ISSUE TITLE
Avoid error page on deployment

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#614]
We have a brief window as containers are rolled out where we show the following error page for the site:

<img width="1184" alt="Screenshot 2020-08-11 at 10 38 04" src="https://user-images.githubusercontent.com/65520/89877907-15416600-dbc1-11ea-8160-3c3922909437.png">

This is because docker-compose doesn't support the `start-first` deployment keys.

We could

1. switch to docker swarm
2. see if we can show a stand-in page in Cloudflare alerting about a deployment

Option 1 should give us a seamless deployment, although there is still a slight chance of users getting an error page (one of ours) if we make a backward-incompatible deployment (for instance a schema change) and they hit a page that throws a 500.

It's not a huge change: docker swarm uses a super-set of the docker compose file format to power the services. Configuration would perhaps need to be slightly reworked.

Option 2 is simpler, if it is possible at all. Perhaps there is a way to configure a stand-in page in Cloudflare that we can trigger at the start of a deployment, putting up an "update in progress" page or something.

**Comment by finestructure** [comment]
This is one way to do it: https://www.resdevops.com/2018/03/20/Cloudflare-workers-maintenance-mode-static-page/

Or maybe we can just set up a static page in Gihub (maybe a blog.../maintenance url) and manually set a global redirect whenever we're doing maintenance?

**Comment by finestructure** [comment]
I guess the simplest solution would be to just add a custom error page for the 521 but I think that requires a paid Cloudflare plan.

**Comment by daveverwer** [comment]
It does, but they aren't super expensive at the low end, and custom error pages are included in that. It's $20 a month. If we decide this is important, that's not a huge price to pay.

**Comment by finestructure** [comment]
This is now fixed due to `start-first` docker swarm deployment in production.
