### ISSUE TITLE
Stuck ARM pipelines / queue buildup

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#615]
The following job has been running for 50mins now on the DTK and it looks like it'll time out: https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/680473477

Running it locally with the same parameters (but on intel), shows the following:

```
❯ ./builder checkout -c https://github.com/thread/Composed.git -r 1.0.33 -f
Clone URL: https://github.com/thread/Composed.git
Reference: 1.0.33
Cloned https://github.com/thread/Composed.git into ./checkout
~/P/ssas/Projects/spi-builder on  main took 3s ▹ fish 
❯ ./builder build -p checkout/ --platform macos-xcodebuild --swift-version 5.3
Selected platform:         macosXcodebuild
Swift version:             v5_3
Building package at path:  checkout/
Running build ...
env DEVELOPER_DIR="/Applications/Xcode_12_beta_4.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" build -scheme "Composed" -destination "generic/platform=macos"
Error: ShellOut encountered an error
Status code: 65
Message: "** BUILD FAILED **
"
Output: "Command line invocation:
    /Applications/Xcode_12_beta_4.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=/Users/sas/Projects/spi-builder/checkout/.dependencies -derivedDataPath /Users/sas/Projects/spi-builder/checkout/.derivedData build -scheme Composed -destination generic/platform=macos

User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/sas/Projects/spi-builder/checkout/.dependencies
    IDEDerivedDataPathOverride = /Users/sas/Projects/spi-builder/checkout/.derivedData

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "XD2B49EJ3F" with a private key was found. (in target 'Composed' from project 'Composed')
"
```

It looks like this is a genuine failure case but one that we're not capturing.

Also, this is a case where it would help if we streamed the logs.

**Comment by finestructure** [comment]
I've checked that the DTK isn't stuck on some popup prompt or alert. There is nothing.

**Comment by finestructure** [comment]
We're actually correctly reporting this up in general: https://swiftpackageindex.com/builds/173C14FC-483A-4B48-9834-0B3EBB99EB2B

<img width="1127" alt="Screenshot 2020-08-12 at 10 35 52" src="https://user-images.githubusercontent.com/65520/89993841-9c591180-dc87-11ea-9686-c9ce26b797c2.png">

I think it's just that particular job that got stuck. I should get cleared and retried automatically.

<img width="1127" alt="Screenshot 2020-08-12 at 10 36 53" src="https://user-images.githubusercontent.com/65520/89993997-ce6a7380-dc87-11ea-97f4-33cfbfd761eb.png">

**Comment by finestructure** [comment]
Just noticed that we were down to 6 runners and the problem was an ARM backlog.

Looking at the jobs I noticed another one that seems to be stuck: https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/682294428

It's hard to tell what it's doing without log streaming but I don't want to interrupt it. However, the problem with only 2 concurrency was that we seem to have gotten stuck on a couple of these hour long jobs that time out. While they were sitting there, we build up a huge ARM backlog which lead to the regular jobs running down their queues.

Not a huge problem, just a little lost capacity.

Will need to check what's going on with this.

I've bumped concurrency on the DTK to 4 to see if that helps with the backlog. We seem to be doing ok cpu wise:

<img width="81" alt="Screenshot 2020-08-12 at 18 16 21" src="https://user-images.githubusercontent.com/65520/90040182-eeba2280-dcc7-11ea-8478-799d8a99c4aa.png">

(Does iStat Menus run on ARM?)

**Comment by finestructure** [comment]
More timeouts (I've reduced it to 30mins to shorten the time the queue is blocked):

- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/682964837
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/682964851
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/682982700

The load on the DTK is fine and these are different packages. Are they really all taking this long or is something up with ARM builds?

I did notice that on my intel MBP sometimes builds with 12b3 takes very long when run via our build mechanism. I wonder if there's something specific to 12b4 that's causing builds to stall.

Need to do some testing on this.

**Comment by daveverwer** [comment]
> (Does iStat Menus run on ARM?)

I spoke to Marc about this and they don't have an ARM build ready, but he said the regular Intel build works fine. 👍

**Comment by finestructure** [comment]
I've reduced job timeout even further (10m for ARM atm, 30m for Linux) to ensure the main platform builds aren't held up by ARM and/or potentially Linux queues.

The purpose here is to make jobs that will time out anyway timeout faster. There may be legitimate build times of 15m or longer but we can get to these later by lifting the limit after we're done with the backlog. The problem isn't the long build times per se, it's just that they lead to a backlog in a particular queue that then runs up against the 300 job limit, with all 300 jobs arm jobs serviced by a frequently stalling worker. The same can happen for Linux, or just a combination of the two to pile up to 300.

I've also considered shortening the garbage collection time for pending queues but realised that this will do no good unless we also cancel those jobs. Best leave this be for now so we don't change too many things at a time and/or introduce more churn as we enqueue and delete jobs.

**Comment by finestructure** [comment]
I'm going to go ahead and close this one. We've seen similar hangs across all builders now and it doesn't seem particular to ARM. In any case, the particular builds weren't the issue. They've finished at other times and so it's not a reproducible error. I don't think there's anything in particular we can do here at this time.
