### ISSUE TITLE
Build badges

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#619]
Just recording that here as a reminder

<img width="271" alt="Screenshot 2020-08-12 at 09 00 45" src="https://user-images.githubusercontent.com/65520/89984823-5053a000-dc7a-11ea-9c93-11eaea0188ae.png">

**Comment by finestructure** [comment]
I've had a brief think about this and I'm not sure pre-rendering is going to scale. Not only do we have quite a number of combinations here, these badges _also_ come in various sizes and styles. For widest adoption I think we need to support the full range of badges and for that to work I think we either need to render the SVG otherselves or forward the request.

If a redirect works I think this is best not only because we don't have to deal with rendering at all but also because we don't have to deal with any new styles etc.

**Comment by finestructure** [comment]
I think this might be what we need: https://shields.io/endpoint

**Comment by finestructure** [comment]
I.e. we add endpoints that return for instance

```
# get https://swiftpackageindex.com/Alamofire/Alamofire/badges?type=swift-version-compability
{"schemaVersion":1,"label":"Swift Compatibility","message":"5.3 | 5.2 | 5.1","color":"blue","cacheSeconds":3600}
```

and the shield url is

```
https://img.shields.io/endpoint?url=https%3A%2F%2Fswiftpackageindex.com%2FAlamofire%2FAlamofire%2Fbadges%3Ftype%3Dswift-version-compability
```

**Comment by finestructure** [comment]
We'll probably want to add some sort of copy badge button, because getting the url-escaped api link isn't something you want to do by hand.

**Comment by daveverwer** [comment]
> We'll probably want to add some sort of copy badge button, because getting the url-escaped api link isn't something you want to do by hand.

Absolutely! This is amazing progress but I think we need to plan how the feature might work in more detail before pushing it out to everyone.
