### ISSUE TITLE
Admin API

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#621]
Add an admin interface to schedule packages/versions for rebuilding (by wiping their existing build records)

Things we'll need:

- [ ] API admin auth mechanism
- [ ] API to delete builds for a given version
- [ ] API to delete builds for a given package
- [ ] API to trigger missing builds for a package
  - [ ] including override flag to bypass pipeline capacity check
- [ ] API client to perform these actions

**Comment by daveverwer** [comment]
Is the plan still to do this through the authenticated API and wrapper client app?

**Comment by finestructure** [comment]
Yes, exactly!

**Comment by finestructure** [comment]
Regarding then admin auth mechanism, we've got a few options here

1. add an admin token just like we do for the builders
2. create a users table where we configure admins and add a login endpoint that issues JWTs
3. integrate with GH

#1 is simple - we just create another `TokenAuthenticator` and inject the token value via secrets per env. While it's simple, this doesn't scale very well in two dimensions: if we need further scopes we'll end up creating more and more token types with more and more injected secrets.

Also, we have only one token per scope. For the builders that's fine but for admins it's not great in the long run.

#2 is a bit more complex than #1 but not terribly so. The main problem is that we're stepping into the realm of PII (although arguably for a very small and consenting "crowd") and keeping data that isn't derived.

#3 I don't know how to do (yet). Would take some research. We'd also need to record what accounts are admins somewhere (presumably in the db), so there's also the aspect of non-derived data.

**Comment by finestructure** [comment]
I think I'm leaning towards option 2 at the moment, mainly because we'd be sticking what is essentially per user config in the secrets and it's already cluttered there. We will soon also need a prometheus monitoring endpoint and that will require another token in the secrets. It's getting crowded.

Option 1 would be ok as well, but I think we should only do it that way if we intend to keep it. If it's transitional, I'd rather make the extra effort and go for option 2.

Option 3 I'm not super happy with mainly because I can't judge how complex that is right now _and_ it ties us to a vendor.

**Comment by daveverwer** [comment]
> Option 3 I'm not super happy with mainly because I can't judge how complex that is right now _and_ it ties us to a vendor.

Of all of the "Sign in with ..." GitHub is the only one I've ever used. I trust them, and they're not going anywhere so I don't fear being tied to *that* vendor very much. It's definitely more work though.

If/when we do need user data for end-users of the system, I can see us using "Sign in with GitHub" for that, so there's the possibility that we'll need to do this work one day, but that's a long way away, and I'm not even 100% about *what* kind of end-user authenticated functionality we'd end up implementing (there are lots of ideas, but some are bad ideas 😂)

> I think I'm leaning towards option 2 at the moment, mainly because we'd be sticking what is essentially per user config in the secrets and it's already cluttered there. We will soon also need a prometheus monitoring endpoint and that will require another token in the secrets. It's getting crowded.

Would you see transitioning GitLab to use the option 2 model too?

**Comment by finestructure** [comment]
No, I’d leave the builders as is, because we don’t want them to have to go through login/token refresh steps. And there’s no need to manage them separately.

**Comment by finestructure** [comment]
Renaming - PR #655 is taking care of the "better (good enough) rebuild mechanism" and this should cover the wider task of a proper admin interface.

**Comment by finestructure** [comment]
Closing for now, not planning to add an admin API at this time
