### ISSUE TITLE
Notifications when new versions are released

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#634]
There are lots of possibilities here, but one that I have a need for right now is I think an interesting way to approach the very beginning of a set of features around notifications when packages are updated.

I've just switched one of our dependencies in the blog to track a branch as I need a feature that's not deployed on a tagged version. I'd love to be able to sign up for an email/push notification when the next tagged release is available. I don't like tracking a branch, and so I want to get back on a tag as soon as possible, but I'll never remember to check that repository again. I need notifications.

Email is going to be better for this than a push. I'm likely not at my computer when a push arrives, and email is a little bit more permanent than a notification. Plus I 💌 email.

This is a practical use of notifications, and I think we should focus on real-world uses when it comes to any kind of notification features.

This needs more discussion, but logging here for now.

**Comment by Sherlouk** [comment]
Linking to #523 (and vice versa) since they both rely on the same hook into the new version flow.

**Comment by daveverwer** [comment]
I think we can close this one too. Thinking about it I'd never want an email for every release. Email is still interesting, maybe for a weekly update which I have some ideas on, but this issue is done.
