### ISSUE TITLE
Integrate the intermediate search results page with DDG bangs

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#638]
Depends on #635 in the [Intermediate Search Results project](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/projects/5).

As [suggested here](https://twitter.com/helje5/status/1294788856018075649) by @helje5 🙏, after #635 is implemented. It [looks like `spi` is taken](https://twitter.com/_sa_s/status/1294882412737040384), as is `sp` and a few others I just tried. Best I could find was `swpi` which isn't ideal, but might work.

More [information over on the DDG site](https://duckduckgo.com/bang)

**Comment by finestructure** [comment]
`spix` is currently also available

**Comment by daveverwer** [comment]
Done! Submitted to DDG and awaiting approval there. Also also as a [script for Raycast](https://github.com/raycast/script-commands/pull/427).

**Comment by Cueball** [comment]
@daveverwer was this ever formally accepted by DDG? If so, it's no longer working.

I looked for a relevant !bang without success - !swpi and !spix are neither functional nor visible in the [!bang search list](https://duckduckgo.com/bangs)

[I was about to try to create one before I thought to check here first...]

**Comment by daveverwer** [comment]
What a long time ago I did this!

I never heard anything back 😬
