### ISSUE TITLE
Add two RSS feeds

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#64]
* Newly added packages.
* New package versions.

**Comment by finestructure** [comment]
I might start looking into this one, unless you're keen on tackling it?

**Comment by daveverwer** [comment]
Go for it!

A couple of points for implementation:

* Include 100 posts in a feed, but it'd be great if this were easily customisable (by us, it doesn't need to be a user-configurable thing or a URL parameter).
* Every URL in the feed, including ones in the body should be a fully qualified, absolute URL.
* For the "Recent Packages" feed I was thinking the fields would be something like this:
  * Title: [Package Name]
  * Link: https://swiftpackageindex.com/[Repository Owner]/[Repository Name]
  * Description:
```html
<h2><a href="https://swiftpackageindex.com/[Repository Owner]/[Repository Name]">[Package Name]</a></h2>
<p>[Package Summary]</p>
<small><a href="https://swiftpackageindex.com/[Repository Owner]/[Repository Name]">[Repository Owner]/[Repository Name]</a></small>
```
* For the "Recent Releases" feed I was thinking the fields would be something like this:
  * Title: [Package Name] - [Version X]
  * Link: https://swiftpackageindex.com/[Repository Owner]/[Repository Name]
  * Description:
```html
<h2><a href="https://swiftpackageindex.com/[Repository Owner]/[Repository Name]">[Package Name] - [Version X]</a></h2>
<p>[Package Summary]</p>
<small><a href="https://swiftpackageindex.com/[Repository Owner]/[Repository Name]">[Repository Owner]/[Repository Name]</a></small>
```

We can look at adding some of the other available metadata later. This would be a great start.

Also, here's the official RSS validator. If it passes that, we're good! https://validator.w3.org/feed/

**Comment by finestructure** [comment]
In RSS terms, recent packages and release would each go into its on `channel`, right?

**Comment by daveverwer** [comment]
There would be completely separate feeds for each of these, with separate autodiscovery meta tags.

**Comment by finestructure** [comment]
We have a couple of data gaps here, if we're looking to drive both feeds by our recent views:

- package summary
- released version

We'll need to extend the view to provide those or create another view with those available.

**Comment by daveverwer** [comment]
Let's drop package summary then.

Package version is important, and should also probably be shown in Recent Releases on the home page too.
