### ISSUE TITLE
Fast track popular packages

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#645]
We've got pretty decent build coverage of popular packages at this point (~85%) but we could easily improve it a bit by specifically triggering some of those package manually.

Here's a query to find popular*) packages without builds (top 100):

```sql
-- build coverage of popular packages
select s.id, s.package_name, count(*)
from (
  select *
  from search
  order by score desc
  limit 100
) as s
join versions v on v.package_id = s.id
left join builds b on b.version_id = v.id
where v.latest is not null
group by s.id, s.package_name
having count(*) <= 3
order by count(*)
```

*) using `score` as a proxy for popular.

**Comment by daveverwer** [comment]
Sounds good.

**Comment by finestructure** [comment]
We're now covering the top 300 and missing just 7 in the top 400.

With #653 we can close the remaining gap much more easily and so I'll go ahead and close this one.
