### ISSUE TITLE
Fix build count

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#646]
Bit of a stretch ;)

<img width="720" alt="Screenshot 2020-08-17 at 11 21 12" src="https://user-images.githubusercontent.com/65520/90380073-e5400a00-e07b-11ea-8e79-d8109bfdb322.png">

**Comment by daveverwer** [comment]
Is that number really adding anything? I'm not sure it is.

**Comment by daveverwer** [comment]
It does make a good start to that sentence where we get a link back to the package though, and that's important. Let's fix it up 👍
