### ISSUE TITLE
Prod out of application memory

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#649]
Prod ran out of app memory this morning. It was slow on SQL queries and threw a 521 when I checked. Not sure how long it was offline.

We're currently processing packages that take quite a while to compile it seems and may be eating into memory:

<img width="1201" alt="Screenshot 2020-08-18 at 09 04 09" src="https://user-images.githubusercontent.com/65520/90481266-c8660e00-e131-11ea-9ffb-9450861991d5.png">

The two packages built across those jobs are

- https://github.com/CoreOffice/CryptoOffice.git
- https://github.com/nodes-vapor/nstack.git

(mostly CryptoOffice).

**Comment by finestructure** [comment]
Prod was unresponsive just now. I cancelled four CryptoOffice jobs to bring it back.

**Comment by daveverwer** [comment]
Do we want to reduce the number of runners? We're almost there with the main processing anyway.

**Comment by finestructure** [comment]
dev also seems to have crashed, uptime is 1:09 - since I brought the builders back online this morning. I'm guessing it also choked on one of those two packages.

**Comment by daveverwer** [comment]
I think 5 and 4 (prod/staging) is probably the right choice for everyday running, we could move to that now.

**Comment by finestructure** [comment]
I'll try and figure out which package killed us and then I think we need to add something to protect us when they come around again. I don't think we can scale back enough to save the box while also keeping a good rate during normal operations.

The main issue is that we'll be hitting the builders with 64 of these massive compiles and we need to spread them out somehow without reducing our capacity to 1-2 per machine. I.e. I fear 4-5 of those in parallel might also kill prod.

**Comment by finestructure** [comment]
Doesn't appear to be CryptoKit:

```
❯ ./builder checkout -c https://github.com/CoreOffice/CryptoOffice.git -r 0.1.0 -w checkout -f
...
❯ ./builder build -p checkout --platform macos-spm -s 5.2
...
[555/569] Merging module XMLCoder
[561/569] Compiling CryptoSwift SHA1.swift
[562/569] Compiling CryptoSwift SHA2.swift
[563/569] Compiling CryptoSwift SHA3.swift
[564/569] Compiling CryptoSwift Scrypt.swift
[570/570] Merging module CryptoSwift
[571/573] Compiling CryptoOffice CryptoOfficeError.swift
[572/573] Compiling CryptoOffice CryptoOfficeFile.swift
[573/573] Compiling CryptoOffice ECMA376Agile.swift
[574/574] Merging module CryptoOffice
✅  build complete
/V/L/U/s/P/spi-builder on  stream-logs took 53s ▹ fish
```

-> 53s on my MBP

CryptoKit build times (2018 MBP):

- 5.2 macos-spm: 53s
- 5.2 macos-xcodebuild: 1m5s
- 5.2 linux: 54s
- 5.3 macos-spm: 34s
- 5.3 macos-xcodebuild: 41s
- 5.3 linux: 37s

**Comment by finestructure** [comment]
At first glance it doesn't look like it was https://github.com/nodes-vapor/nstack.git either: https://swiftpackageindex.com/nodes-vapor/nstack/builds

It seems to be a very old package and only passed on Linux 4.2.

Running that build locally now but could it be that this package (which builds all of Vapor) tripped the box when building 4.2/Linux and it all spiralled out of control from there?

**Comment by finestructure** [comment]
Doesn't look like it:

```
❯ ./builder build -p checkout --platform linux -s 4.2
...
Compile Swift Module 'NStack' (14 sources)
✅  build complete
/V/L/U/s/P/spi-builder on  stream-logs took 2m10s ▹ fish
```

So, not sure what brought prod down but it doesn't look like it was either of those two packages.

**Comment by finestructure** [comment]
My first instinct was that we perhaps need to add a "slow" queue that we can target with packages that take a lot of resources.

The way this would work is that we configure a runner with low(er) concurrency that handles "heavy" packages and target it when triggering. We could to this by adding a "QoS" variable to the trigger command.

On the other hand, I just reminded myself of what I said in #613 : we handled the AWS SDK just fine multiple times during beta testing. I think you're right and we just need to dial it back a little for normal operations and bring out the bigger guns of a slow queue if we keep having issues.

One thing to note though: during the beta we didn't run Linux jobs on dev and prod and I wonder if this plays a part in this.

Closing this for now, #613 is the long term tracker for these issues.

**Comment by daveverwer** [comment]
Yep. I think this is something we can reopen if/when we get issues after the backlog is clear, but I don't think it'll be as big an issue at that point. We've pushed those machines really hard and it's not surprising that something went awry today.
