### ISSUE TITLE
Badge Endpoint Empty String Fix

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#651]
GET https://staging.swiftpackageindex.com/api/packages/Sherlouk/SwiftProvisioningProfile/badge?type=swift-versions
```
{
  "cacheSeconds": 21600,
  "color": "blue",
  "message": "",
  "schemaVersion": 1,
  "label": "Swift Compatibility"
}
```

https://img.shields.io/endpoint?url=https%3A%2F%2Fstaging.swiftpackageindex.com%2Fapi%2Fpackages%2FSherlouk%2FSwiftProvisioningProfile%2Fbadge%3Ftype%3Dswift-versions
![image](https://user-images.githubusercontent.com/15193942/90569843-7c08e580-e1a6-11ea-9eb5-35695706e5d9.png)

In this instance the library hasn't had any builds done or owt. It might be good to return a default message in this instance (for both types of badges) to make shields happy and render something half decent?

**Comment by finestructure** [comment]
Ah, good catch! I'll fix that up.

**Comment by finestructure** [comment]
Deployed on staging:

[![](https://img.shields.io/endpoint?url=https%3A%2F%2Fstaging.swiftpackageindex.com%2Fapi%2Fpackages%2FSherlouk%2FSwiftProvisioningProfile%2Fbadge%3Ftype%3Dswift-versions)](https://staging.swiftpackageindex.com/SwiftProvisioningProfile/Sherlouk)

[![](https://img.shields.io/endpoint?url=https%3A%2F%2Fstaging.swiftpackageindex.com%2Fapi%2Fpackages%2FSherlouk%2FSwiftProvisioningProfile%2Fbadge%3Ftype%3Dplatforms)](https://staging.swiftpackageindex.com/SwiftProvisioningProfile/Sherlouk)

**Comment by finestructure** [comment]
Links are fixed now:

[![](https://img.shields.io/endpoint?url=https%3A%2F%2Fstaging.swiftpackageindex.com%2Fapi%2Fpackages%2FSherlouk%2FSwiftProvisioningProfile%2Fbadge%3Ftype%3Dswift-versions)](https://staging.swiftpackageindex.com/Sherlouk/SwiftProvisioningProfile)

[![](https://img.shields.io/endpoint?url=https%3A%2F%2Fstaging.swiftpackageindex.com%2Fapi%2Fpackages%2FSherlouk%2FSwiftProvisioningProfile%2Fbadge%3Ftype%3Dplatforms)](https://staging.swiftpackageindex.com/Sherlouk/SwiftProvisioningProfile)
