### ISSUE TITLE
View model architecture

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#66]
Continuation of discussion that started [here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/65#discussion_r425626949)

---

My gut feeling says that the view models shouldn't construct full sentences that are going to be used, but instead populate everything that might be needed. 

Maybe something like this:

To construct this sentence:

"In development for over 5 years, with 1,433 commits and 79 releases."

The view model could contain:

* First commit date (`Date`)
* Number of commits (`Int`)
* Number of releases (`Int`)

and to construct this sentence:

"By Christian Noon, Mattt, Jon Shier, Kevin Harwood, and 186 other contributors."

* Array of:
  * Full Name (`String`)
  * Profile URL (`URL`)
* Number of other contributors (`Int`)

Is that what you were thinking?

**Comment by finestructure** [comment]
Yes, exactly. A view model would be a collection of fields specific to the view and populated via a db query using the db models.

The job of forming the actual view expressions would be extensions on the view model or some functions elsewhere. Extensions are probably a good place to put them.

So essentially the working interface would be a struct defined by you with what's needed and I'll go look into filling it from the database. I'm sure we'll run into some tricky bits but given our model isn't that spread out we should be fine!

**Comment by daveverwer** [comment]
Perfect!

**Comment by finestructure** [comment]
I think we've got this down and can close this now?

**Comment by daveverwer** [comment]
Yep!
