### ISSUE TITLE
New db backup strategy

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#663]
- backup is too heavy now - takes 10mins and causes outage
- 270 MB compressed file

Need a new strategy.

Would sending it uncompressed work and then compressing it on the receiving end? Or is the dump server-side itself the issue?

We could copy the db files directly from the container and then either have another instance perform the dump or use the files directly. Probably the former.

**Comment by finestructure** [comment]
Just tested this again - pg_dump kills the server (500s on requests) even without any other load. The db seems to be locking.

**Comment by finestructure** [comment]
While it seems to work better initially if we drop `-Fc` from the dump (compression) it still leads to 500s eventually.

**Comment by finestructure** [comment]
I've looked through and tested a range of options.

What we need is a reasonably reliable way of snapshotting the database every few days. We don't store anything that we cannot recompute and the point of the snapshot is faster recovery in case disaster strikes. In particular, we wouldn't want to lose all of the processing that went into the builds table.

We want to avoid downtime while we perform the backup.

Actually using the backup should be fairly simple, both from a disaster recovery point of view and for development/debugging purposes.

As far as I can tell, there are four options:

- pg_dump
- pg_basebackup
- hot/warm standby with log replication/streaming
- file system level copy

Option 1, `pg_dump`, is what we have now and is causing downtime in all modes that I've tried. Other than that it works perfectly for our use case: creating the backup is automated and installing it locally is a one-line command.

Option 2, `pg_basebackup`, is a backup command typically used to prime a hot/warm replica. I suspect we could run it without downtime but I've only tested this on dev, where the data volume probably isn't large enough to surface the problems. It creates a safe file level backup of a database.

It does require some setup on the primary server side, namely setting up a relication user and potentially adding host access to `pg_hba.conf`. Neither is critical or difficult.

Using the backup is fairly simple: untar the data into for instance `db_data` and launch a db instance using it as its `pgdata` directory:

```
docker run --rm --name backup-db -v "$PWD/db_data:/var/lib/postgresql/data" -p 5432:5432 postgres:12.1-alpine
```

Different to `pg_restore` there is no option to re-ingest the data under a new user. I.e. this backup data, even if used locally, would be hosted under the `spi_prod` user unless it was dumped and restored via the current mechanism from this backup database first. (That would certainly be an option and probably a good mechanism to adopt.)

Option 3, hot/warm standby, is quite a bit more involved to set up and does way more than we need. It would also definitely require a `pg_dump`/`pg_restore` cycle to reuse the data.

I'd love to have this and just point our current `pg_dump` at it but I don't really want to go through the setup process.

Option 4, file system level copy, is essentially a simplified variant of option 2 - `pg_basebackup` in the sense that it doesn't require any changes on the primary server side. We can attach to the db container and `tar` the db directory.

It has the same downsides in that it keeps the `spi_prod` user and would benefit from another `pg_dump`/`pg_restore` to transform it.

Another significant downside is that the Postgres docs state you _must_ shut down the db server while performing this copy.

In practise, this requirement isn't quite as strict: Postgres can recover from partially written files:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-08-28 09:50:49.538 UTC [1] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
2020-08-28 09:50:49.538 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-08-28 09:50:49.538 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-08-28 09:50:49.555 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-28 09:50:49.678 UTC [22] LOG:  database system was interrupted; last known up at 2020-08-28 09:37:38 UTC
2020-08-28 09:50:56.503 UTC [22] LOG:  database system was not properly shut down; automatic recovery in progress
2020-08-28 09:50:56.584 UTC [22] LOG:  redo starts at 45/7F5B9A50
2020-08-28 09:51:09.035 UTC [22] LOG:  invalid record length at 45/7F987CB0: wanted 24, got 0
2020-08-28 09:51:09.035 UTC [22] LOG:  redo done at 45/7F987C78
2020-08-28 09:51:09.367 UTC [1] LOG:  database system is ready to accept connections
```

It's basically a bit like crash recovery, although there are probably significant differences and risks.

However, since our backup is merely intended as a time saver it likely wouldn't matter all that much if it produced unusable backups 10% or even 20% of the time.

**Comment by finestructure** [comment]
I think what I'll do is look if I can set up a file level snapshot mechanism that runs nightly and then we point our existing backup at a back db instance that we run solely for the purpose of service the snapshot for `pg_dump`.

We'll retain the simplicy of the current mechanism and avoid the downtime while we snapshot.

We can run this for a while to see if the snapshots are usable. If they aren't, the backup server will fall over and the dump will fail - so it won't be a silent failure.

If we find we're getting too many bad snapshots we can switch to the slightly more complicated setup using `pg_basebackup` and just feed its result into the backup db instead.

**Comment by daveverwer** [comment]
I know I pushed for logs being in the database, but this is what caused this issue. Sorry! If we were storing them on AWS, this wouldn't even be a problem. I do wonder if that's something we should change.

Let's chat about it next time we talk. This doesn't need to be an all-at-once change, we could do it gradually by only shipping new build logs out to AWS, which would gradually shrink the size of the DB. At some point we'd need to make a decision when to rebuild the branches that are very stable/very old, but we'd be in no rush as I'm sure the DB could be backed up with *some* level of logs in place.

Worth thinking about.

**Comment by daveverwer** [comment]
Actually, there might be an intermediate step between something like AWS and where we are now. Could we just write the logs to the file system and serve them in the page from there?

**Comment by finestructure** [comment]
That's certainly an option but unless we make it an all-at-once change we'd still need to implement the alternative backup or live without it.

Also, our builds detail page would get a quite a bit slower unless we load the logs asynchronously somehow.

Maybe something worth exploring would be ways to trim and that way also prettify the xcodebuild logs - and make them more usable. (And it's pretty much exclusively the xcodebuild logs that are massive.)

Which is an issue in and of itself - they're not really very usable as they are. You can find what you need but it's just hidden in a pile of file system paths.

I was thinking something like `xcpretty` or https://github.com/thii/xcbeautify. Probably the latter, because we could build it right in or at least won't need any installation on the builders.

I'm not sure though if that would help enough to get us back to `pg_dump`. Maybe that ship has just sailed - or we'd hit it again with the next bigger feature anyway.

**Comment by finestructure** [comment]
I think I'd prefer S3 or some other online storage over the file system because it keeps the backup intact if you have access from the replica. If we copy the db with filesystem storage we inevitably break the links.

**Comment by finestructure** [comment]
That's actually quite compelling:

```
❯ swift run builder build -p ios -s 5.3 | xcbeautify
[Gen] Compiling AnyRandomNumberGenerator.swift
[Gen] Compiling Gen.swift
[Gen] Compiling LCRNG.swift
[Gen] Compiling UIKit.swift
[Gen] Compiling Gen.swift
[Gen] Compiling UIKit.swift
[Gen] Linking Gen.o
[Gen] Linking Gen.o
[GenTests] Compiling GenTests.swift
[GenTests] Processing empty.plist
[GenTests] Linking GenTests
[GenTests] Linking GenTests
[GenTests] Generating GenTests.xctest.dSYM
```

**Comment by finestructure** [comment]
Continued in #688
