### ISSUE TITLE
Alamofire Shows Inaccurate watchOS Support

### ISSUE THREAD

**Issue by jshier** [SwiftPackageIndex/SwiftPackageIndex-Server#668]
The new compatibility matrix (awesome, BTW!) shows Alamofire as not supporting watchOS. This appears to be due to a build failure when attempting to test for that platform, with much of this output repeated:

```
/Applications/Xcode_11.6.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS6.2.sdk/usr/lib/swift/XCTest.swiftmodule/arm64_32.swiftinterface:6:19: error: no such module 'XCTest'
@_exported import XCTest
```

This should be expected, as XCTest isn't available on watchOS at all. However, building Alamofire normally for watchOS works just fine. So what do I need to do to make this accurate for Alamofire? (And how is anyone passing this build at all?)

**Comment by finestructure** [comment]
This is deployed now and picking up watchOS correctly: https://swiftpackageindex.com/Alamofire/Alamofire/builds

What I've done is add a special scheme mapping for Alamofire for the `watchos` platform builds - something we intend to make configurable for the package owners.

Please let me know if there are other builds that need a custom scheme mapping!

**Comment by jshier** [comment]
It may also be possible to use SPM directly for these builds. I've seen this on the SPM Slack:

```
Requirements:
ToT SwiftPM
Xcode 11.4 Beta

Build and test on macOS:
$ swift package init
$ swift test --build-system xcode

Build and test on iOS:

$ swift package init
$ cat params.json

{
    "configurationName": "Debug",
    "activeRunDestination": {
        "platform": "iphonesimulator",
        "sdk": "iphonesimulator",
        "sdkVariant": null,
        "targetArchitecture": "x86_64",
        "supportedArchitectures": ["x86_64"],
        "disableOnlyActiveArch": false
    },
    "overrides": {}
}

$ swift build --build-tests --build-system xcode -Xxcbuild --buildParametersFile -Xxcbuild $PWD/params.json
$ xcrun simctl spawn --standalone 'iPhone 8' $(xcode-select -p)/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents/xctest $PWD/.build/apple/Products/Debug-iphonesimulator/fooTests.xctest
```

It seems to work for builds only for watchOS, but it's hard to be sure.

**Comment by finestructure** [comment]
Yes, we were considering that until Ankit and Boris told us not to use SPM to build for anything other than macOS :) That’s why we’ve got the two parallel builds going on. I really hope that gets consolidated into a single way to build across all platforms at some point...

**Comment by jshier** [comment]
Interesting, thanks.
