### ISSUE TITLE
Builder maintenance routine

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#670]
Need to set up a maintenance routine/mechanism

- Timed out jobs often don't collect their jobs. We need to pause the builder queue and then `killall xcodebuild` and `killall swift-build`
- Docker jobs can also stick around:

```
spi@spi-dev ~> dpsa
NAMES                          STATUS              IMAGE
serene_perlman                 Up 5 hours          swift:4.2.4
spi_analyze_1                  Up 15 hours         registry.gitlab.com/finestructure/swiftpackageindex:2.0.0
spi_reconcile_1                Up 15 hours         registry.gitlab.com/finestructure/swiftpackageindex:2.0.0
spi_trigger_builds_1           Up 15 hours         registry.gitlab.com/finestructure/swiftpackageindex:2.0.0
```

- This can probably be automated (but we'd need to name the jobs) to kill anthing older than 1.5h that isn't the infra

**Comment by finestructure** [comment]
FWIW, the last few days have been free of zombie jobs. I think the downscaling helps in general, although there was a case of dev panicking even with downscaling in effect and the runner count reduced.

Right now I don't see of any further automation (just regular checking). Will keep this open a few days longer as a reminder to report observations.

**Comment by finestructure** [comment]
Another staging panic (which required to login the builder account for it to pick up builds after the reboot) and a stuck docker job. The docker jobs in particular seem to be sucking a lot of performance out of machines where they happen.

**Comment by finestructure** [comment]
It probably makes sense to check for the following every few days (at least twice a week):

- excess load when there are no jobs running
- `docker ps -a` to check for any jobs that aren't `spi_*` and running for longer than 1h
- builder accounts being logged in (which isn't automatic on dev + prod) - i.e. just ensure that dev hasn't crashed and rebooted into the spi account only *)

*) On that note, perhaps we should default booting into the `builder` account instead of `spi`. Operationally, that's the more important one. Also, we'll automatically be notified about staging and can correct that easily when it happens. That's better than the silent failure.

**Comment by daveverwer** [comment]
Rather than change the default user, I wonder if we should just regularly run a script that checks `who` for the `builder` account being logged in, sending us an email (or some kind of notification) if it's not?

**Comment by finestructure** [comment]
Mmm, that feels like it's quite a bit more complicated, mainly because we'd need to configure some sort of authentication to use an SMTP server.

**Comment by finestructure** [comment]
I've set up a reminder to check the machines at least twice a week. I think that's the extent we can automate this to. Still think it'd be helpful to set `dev` to auto-login to `builder` to make it recover after a reboot but that's a detail. (Just to be clear: this was for `dev` only. `prod` doesn't really have crashing issues and of course we wouldn't want to risk the downtime there.)

**Comment by daveverwer** [comment]
I wonder if `dev` is the only machine that still has crashing issues on a regular basis whether we should look into those in a bit more detail? I wonder if further reducing the number of builders on that machine might help?

Manual ops tasks like this aren't great, of course, and I'm not super happy that they're falling to you by default either.

I wonder if it might be worth a conversation with MacStadium to see if we could sneak in one more machine with a spec similar to the prod machine that could take *all* of our Intel build tasks now that the backlog is done. That could be configured to boot into the builder user by default, as that'd be the only user with any kind of responsibility on that box.

**Comment by finestructure** [comment]
`dev` crashed again earlier this morning (around 13:00 CET)

**Comment by finestructure** [comment]
Also, I've been unable to connect to prod via Screens for a couple of days now. It's working fine otherwise - is processing jobs and handling requests and I'm able to connect via ssh. Just VNC isn't working :shrug:.

**Comment by daveverwer** [comment]
Yea I tried to connect to prod yesterday too and had the same. I checked everything was working ok, and was going to mention it to you. I guess it needs a reboot.
