### ISSUE TITLE
Any thought to how to deal with packages with executables?

### ISSUE THREAD

**Issue by thomasvl** [SwiftPackageIndex/SwiftPackageIndex-Server#677]
SwiftProtobuf seems to be failing for 5.3 for watchOS and iOS because our package also has executables and thus the watchOS, tvOS, and iOS builds fail.  Since SwiftPM doesn't have a way to indicate this, any thoughts for how to avoid this and only build the valid subset?

https://swiftpackageindex.com/builds/28D5E7F0-04B9-413B-B04E-59DDF1154C03

**Comment by finestructure** [comment]
I've just had a quick look and the reason iOS, tvOS, and watchOS are failing is that we're not picking the correct scheme. I can build all three by adjusting that.

I can fix this up with an override but we're also trialling a config file that you could ship with the repo, if you'd like to give that a go: Add `.spi.yml` at the root of the package with the following content:

```
version: 1
builder:
  configs:
  - platform: ios
    scheme: SwiftProtobuf_iOS
  - platform: tvos
    scheme: SwiftProtobuf_tvOS
  - platform: watchos
    scheme: SwiftProtobuf_watchOS
```

**Comment by thomasvl** [comment]
So it will use a checked in Xcode project also?  It wasn't clear if there was a way to get it to do that vs. using the Package.swift and newer Xcode support.

Should we just land this file and check in a few days to see if things do any better?

**Comment by finestructure** [comment]
Yes, we also use checked in project/workspace files. There's a little more detail [here](https://swiftpackageindex.com/docs/builds#built-how) but essentially, we check `xcodebuild -list` but give up if there are multiple schemes and ignore project files altogether.

If you'd like to give that file a spin that'd be great. It'll only affect the default branch until release obviously. If you'd like the correct status reflected sooner I can also bring in the override (which I can set to affect all revisions) - let me know what you prefer. (The override will be ignored if you ship your own file later.)

**Comment by finestructure** [comment]
Also, please be aware that we may need to tweak this file quite a bit potentially. Hence the version number :)

**Comment by thomasvl** [comment]
> If you'd like to give that file a spin that'd be great. It'll only affect the default branch until release obviously. If you'd like the correct status reflected sooner I can also bring in the override (which I can set to affect all revisions) - let me know what you prefer. (The override will be ignored if you ship your own file later.)

We're likely gonna have a release in the near future, so I'm good waiting for that to reflect it in the future.

> Also, please be aware that we may need to tweak this file quite a bit potentially. Hence the version number :)

Yup, no worries, glad to see it thought of.  👍 

Hopefully not overloading this issue too much the 5.0 and 4.2 builds generally seemed to fail with lots of issues.  Is the spi.yml likely to help those, or will it need some more tweaking to get things right?  We've got linux CI via github actions covering those versions, so they should be green.  And last time I did manually checks in Xcode versions I thought things were working.

**Comment by finestructure** [comment]
PS: I ran all these against 1.11.0

**Comment by thomasvl** [comment]
> error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'SwiftProtobuf_iOS')

Yea, so this is the problem with having to have a checked in Xcode project, we have to set the language version to something, right now it is set to 5 because that's the best choice for all our supported toolchains except the 4.2 one.  And forcing all the newer Xcode's to use the older Swift Language Version also isn't right.

This is where it would be nice to build via SwiftPM and have it just ignore the executables since those are only buildable for Linux/macOS in general, but SwiftPM doesn't really express that.  Is there a way to tell it to use the `SwiftProtobuf` instead of the `SwiftProtobuf-Package` scheme from the Package.swift?  (although the 4.2 toolchains didn't have direct Xcode+SwiftPM support, so I guess you'd need to generate a project first also?)

**Comment by finestructure** [comment]
Mmm... the recommendation we got from the Apple SPM team was _not_ to use SPM to build anything other than for macOS 😅 - if that was what you're suggesting.

One thing I tried just now was to remove the xcodeproj and regenerate it with 4.2's `package generate-xcodeproj` - and then build with `xcodebuild`. But that fails in a similar way to how iOS fails in later Swift versions when built with a `-Package` scheme:

```
 sas@Ceres  ~/D/checkout  ⎇ *…  env DEVELOPER_DIR="/Applications/Xcode_10.1.app" xcrun swift package generate-xcodeproj
generated: ./SwiftProtobuf.xcodeproj
 sas@Ceres  ~/D/checkout  ⎇ *…  env DEVELOPER_DIR="/Applications/Xcode_10.1.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" build -scheme "SwiftProtobuf-Package" -destination "generic/platform=ios"
User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/sas/Downloads/checkout/.dependencies
    IDEDerivedDataPathOverride = /Users/sas/Downloads/checkout/.derivedData

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos' (in target 'protoc-gen-swift')

Build system information
error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos' (in target 'Conformance')

Build system information
error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos' (in target 'protoc-gen-swift')

Build system information
error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos' (in target 'Conformance')

Build system information
warning: duplicate output file '/Users/sas/Downloads/checkout/.derivedData/Build/Products/Debug-iphoneos' on task: Ld /Users/sas/Downloads/checkout/.derivedData/Build/Products/Debug-iphoneos normal arm64 (in target 'Conformance')

Build system information
warning: duplicate output file '' on task: Ld /Users/sas/Downloads/checkout/.derivedData/Build/Products/Debug-iphoneos normal arm64 (in target 'Conformance')

** BUILD FAILED **
```

Do you have a sequence of commands that'll get a passing build with 4.2/ios? I can try and map that to our build system to see if we could make that configurable.

**Comment by thomasvl** [comment]
Our primary means of support has been SwiftPM and CocoaPods. The checked in Xcode project is mostly there for folks that want to use Carthage (or do their own thing/manual project work so it is a reference for them).  If folks have needed the Xcode project with old toolchains, we just assume they "fix" that one value (or pass an override if they command line things).  For those older toolchains, I think most folks on those older toolchain use CocoaPods and thus avoid some of these issues.

For all but the 4.2 case, I was thinking use xcodebuild but us the built in SwiftPM support.  I believe it makes a `*-Package` scheme to build everything, but also makes schemes for the library `product`s, so I was thinking for iOS, tvOS, & watchOS, maybe just building the schemes related to the non executable products would work to avoid the executable problems for platforms where those don't make sense.  4.2 is just generally hard since there aren't as many options since it didn't have as rich of support for all the Apple platforms.

**Comment by finestructure** [comment]
Ok, so the change was picked up and `master` is all green now, except for the outstanding issues with the non-SPM builds: https://swiftpackageindex.com/apple/swift-protobuf/builds

I'm not sure there's much we can do here and if I understood your last comment correctly you're ok with that?

Let me know and I'll close this one :)

**Comment by thomasvl** [comment]
I don't suppose there's a way to tweak the `xcodebuild` command line for the 4.2 builds specifically in that YML file?  We could add `SWIFT_VERSION = 4.2` to the end of the command line, it likely would pass.

Anyways, yea go ahead and close this.

**Comment by finestructure** [comment]
Oh, that's actually great - and works, too. Do you know if that should work universally? I.e. I'm thinking I could just

```
env DEVELOPER_DIR="/Applications/Xcode_10.1.app" ... SWIFT_VERSION=4.2
env DEVELOPER_DIR="/Applications/Xcode_10.3.app" ... SWIFT_VERSION=5.0
env DEVELOPER_DIR="/Applications/Xcode_11.3.1.app" ... SWIFT_VERSION=5.1
env DEVELOPER_DIR="/Applications/Xcode_11.6.app" ... SWIFT_VERSION=5.2
env DEVELOPER_DIR="/Applications/Xcode_12_beta_4.app" ... SWIFT_VERSION=5.3
```

At the very least we could add that as part of the config but if it work generally I can just make it part of the build command. I'll give that a spin.

**Comment by thomasvl** [comment]
The only downside I know of is if someone's Xcode project for newer Xcode's still explicitly says to us 4.2 syntax because they hadn't updated their code.  You'd potentially be forcing a version something like 5 on a project doesn't actually support for their own compilation.

p.s. - Since this is the `--swift-version`, I believe the only valid values are still 3.0, 4.0, 4.2, and 5.0 (depending on what the toolchain supports - i.e. - like the current error message).

**Comment by daveverwer** [comment]
Yea I'm a little reluctant to do this. I think since we have the config override file rapidly becoming "a thing" we might want to make this something that's triggered via that rather than imposing it on every build.

I haven't looked into the implications (been busy all day), but unless this a truly a move without downsides I think we should approach this with caution.

**Comment by thomasvl** [comment]
Yea, I was originally asking just if there was a way for us to opt into this by setting it up since we know it will fix things since we have to use the checked in project for validations.

**Comment by finestructure** [comment]
I've got an override which works in my initial testing and is ready for review and roll-out here: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/29

However, I also thought about this a bit more this morning and I think there's one question is worth discussing: By adding this particular override we turn a lamp green that won't be green for users. The scheme overrides are different, because there we're correcting towards a situation that users of the package would normally see.

Here, on the other hand, we're tweaking a value that we know will fix the build for SPI - but users of the package won't have that same "out of the box" compile success. Should we aim to get everything green as much as possible or should we aim to replicate the common build experience users would have?

I lean towards the latter, not just because it'll keep the special configs minimal but also because it'll lead to "upstreaming" of fixes to get things to green, rather than pushing it into `.spi.yml` where only SPI benefits from it.

I realise that in this particular case there's no way to upstream a fix into the project. But maybe that's just the way it should be then? 4.2 won't be around forever, and it _is_ valid a signal that there are issues when using this library with 4.2.

**Comment by finestructure** [comment]
I should add that by "override" I mean a project specific config setting that gives control over the "legacy language version" setting. Specifically, this would add support for a setting like this:

```
builder:
  configs:
  - swiftVersion: '4.2'
    legacyLanguageVersion: '4.2'
```

The fix has this embedded and would take effect for the `1.11.0` tag only, because in `master` we honour the existing `.spi.yml` file. If we decide to go ahead I'll open a PR with the change to `.spi.yml` in the protobuf repo.

**Comment by daveverwer** [comment]
> However, I also thought about this a bit more this morning and I think there's one question is worth discussing: By adding this particular override we turn a lamp green that won't be green for users. The scheme overrides are different, because there we're correcting towards a situation that users of the package would normally see.
> 
> Here, on the other hand, we're tweaking a value that we know will fix the build for SPI - but users of the package won't have that same "out of the box" compile success. Should we aim to get everything green as much as possible or should we aim to replicate the common build experience users would have?

I have a strong preference for "aim to replicate the common build experience users would have".

> I lean towards the latter, not just because it'll keep the special configs minimal but also because it'll lead to "upstreaming" of fixes to get things to green, rather than pushing it into `.spi.yml` where only SPI benefits from it.
> 
> I realise that in this particular case there's no way to upstream a fix into the project. But maybe that's just the way it should be then? 4.2 won't be around forever, and it _is_ valid a signal that there are issues when using this library with 4.2.

I agree and I'm reluctant to add this override. This is what I was saying in [my comment](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/677#issuecomment-679275108), but you said it better than I could 👍

**Comment by finestructure** [comment]
Going to go ahead and close this then - I think we've tackled the main bit with iOS, tvOS, and watchOS compatibilty :) Thanks again for the help, Thomas!
