### ISSUE TITLE
Update Swift 5.3 builds to Xcode 12.2

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#679]
I believe Xcode 12.2 is the version we are waiting for.

- install on
  - [x] dev
  - [x] prod
  - [x] dtk
  - [x] ceres
- update builder
  - [x] determine matching Linux version
  - [x] update `SwiftVersion.xcodeVersion`
  - [x] update `SwiftVersion.dockerImage`
  - run test builds on all builders
    - [x] dev
    - [x] prod
    - [x] dtk
    - [x] ceres
  - [x] merge https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/41
- update server
  - [x] update Xcode version string in `SwiftVersion+Build.swift:25`
  - [x] merge https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/768
- delete 5.3 builds (in batches, to control for build volume)
  - [x] write select/delete query
  - [ ] run deletions
- remove old Xcode 12 betas
  - [x] Ceres
  - [x] DTK
  - [x] dev
  - [x] prod

Edit: review/update todos

**Comment by daveverwer** [comment]
Do we wipe 5.3 build results with this?

We definitely should when Xcode 12 final comes out, but I'm 50/50 on whether it's worth it for this upgrade.

**Comment by finestructure** [comment]
Probably just wait for GM at this point

**Comment by daveverwer** [comment]
We're down to this being the last lonely issue in [the project](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/projects/4)! 🚀

**Comment by finestructure** [comment]
Waiting for a release later than 12.0 GM due to:

![Uploading Screenshot 2020-09-23 at 09.14.59.png…]()

**Comment by finestructure** [comment]
As we finalise this, I think it's also a good time to briefly look ahead at the next upcoming version, Swift 5.4. AFAIK that'll be in spring, so it's a good few months off (although betas might be appearing in Feb/March?).

The mechanism would be the same we used for 5.3's beta:

- find a good enough version that'll work for most builds. That'll most likely mean not to jump on it immediately. We may want to give it a good few betas for things to settle down and there actually being a demand for 5.4 builds. (It'll depend a bit on what kind of changes come with it.)
- we should aim to deploy only a limited number of 5.4 versions
- not rebuilding on 5.4 changes will make this easier (as it did for 5.3 changes)
- most importantly: we should drop 4.2 the minute we add 5.4, even if it's a beta

**Comment by daveverwer** [comment]
> * find a good enough version that'll work for most builds. That'll most likely mean not to jump on it immediately. We may want to give it a good few betas for things to settle down and there actually being a demand for 5.4 builds. (It'll depend a bit on what kind of changes come with it.)

It's possible it'll be a really minor version, but in my experience people almost always use a little library to play with/test out a new language feature. Certainly, with both the SwiftPM Library and also the SPI, we had packages that relied on the new version fairly quickly.

**Comment by daveverwer** [comment]
> * most importantly: we should drop 4.2 the minute we add 5.4, even if it's a beta
>   * caveat: v4 support might be significant, so this may mean dropping a strong signal
>   * I don't think we can afford running 5.4 in addition to all other builds though, not just from a capacity point of view. It'll also mess with the version tables.
>   * Just to put it out there: perhaps there's a low 5.x version that we might want to drop instead? (Although that seems weird, too)

I think the tables will work 4.2 -> 5.4 is only as many columns as our current platforms matrix, which displays fine. Build capacity is the biggest issue for sure, and if we're running up against that then we need to make room. But, at the same time I'm not super keen to drop 4.x support just yet.

I don't have particularly strong feelings either way though, I think it's a minor issue.

**Comment by finestructure** [comment]
I'm installing 12.2rc everywhere now as `Xcode_12.2_rc.app` with a symlink from `Xcode_12.2.app` to get us started. Even if there's a change before final release this will be better than keeping running on `12_beta_4.app`.

**Comment by finestructure** [comment]
Re-opening to track post-deploy cleanup tasks

**Comment by finestructure** [comment]
I've just run the queries to get a feel for the Xcode 12b4 build count on prod.

- 34,591 builds remain having been run with Xcode 12-beta4
- 14,810 of those failed
- 30,382 are older than 30 days
- 13,158 that failed are older than 30 days

So, it looks like the vast majority of our 5.3-beta backlog is from packages that haven't seen new versions within the last 30 days, and 60% of those succeeded with 12-beta4.

Seems to me that rather than rebuild everything we should only retry the failures.

**Comment by daveverwer** [comment]
I can see the logic, in that false positives are less harmful than false negatives, but I bet there are some in there.

I agree we should do the failures first, as I think that's where we'll see the biggest impact. But let's consider doing the positives after the failure backlog is done?

**Comment by finestructure** [comment]
Follow-up in #804
