### ISSUE TITLE
Current system sorta blurs the lines between language versions and toolchain versions

### ISSUE THREAD

**Issue by thomasvl** [SwiftPackageIndex/SwiftPackageIndex-Server#680]
Re-reading https://blog.swiftpackageindex.com/posts/launching-language-and-platform-package-compatibility/, one thing I'm realizing is it talks about `swiftLanguageVersions` but goes on to talk about testing with toolchains, which really are different things.

I believe `swiftLanguageVersions` is what dialect of Swift the [library supports building as](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#swiftversion); hence it really only having enum values for the documented values for `--swift-version`.

What [toolchains are supported](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#about-the-swift-tools-version) really comes down more to the `// swift-tools-version:` within the `Package.swift` and/or the extra `Package@swift-##.swift` files.

If the intent is Swift _Toolchain_ Versions are supported (instead of what Swift _Language_ Version), you might want to slightly clarify things and/or might also need to ensure you are data mining the `Package*.swift` files correctly to extract that version info.

**Comment by daveverwer** [comment]
Thanks for this Thomas. You’re right that there’s a difference, and we do understand the limitations of the `swiftLanguageVersions` property. 

I think the best way to think about what we’d like this feature to be is as close to a real-world test of “will I be able to use this package if I am using Swift X.X”. We initially tried switching toolchains as we ran builds, but there were significant issues with this, and it’s not a very real-world test. We don’t think that’s how people who are using older versions of Swift compile their projects.

Most people who are using Swift 5.2 will still be using Xcode 11, so we do the same. We ended up using the latest release of Xcode that supported every version of Swift that we want to test with. So, for Swift 5.2, we use Xcode 11.6 and for Swift 5.1, we use Xcode 11.3.1.

I’ve clarified this in the build system FAQ [PR here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/681), but I’m not sure there’s much more we’d like to do around this. We’d be happy to consider specific changes, but this issue feels a little vague at the moment.

**Comment by thomasvl** [comment]
I think I understand what you all are after; I guess what I'd suggest/hope for is just that you don't so much say "Swift version", but instead always talk about "Toolchain version", to make it clear that's what you are attempting to provide.  "Swift version" is overloaded in that there are two "swift versions" (toolchain and language).  And some of the content you have mix the two as if they are tied.

From my reading (and past headaches), it is possible (and correct) to have 4.2 in `swiftLanguageVersions`, but fail to support the 4.2 toolchain because your sources use new toolchain specific features that didn't exist in the 4.2 toolchain time frame (you'd have a `// swift-tools-version:5` directive).  That would seem to be why `compiler()` checks got add in addition to `swift()` checks.

Slight aside - thanks to binary interop, most folks should never care about a package's `swiftLanguageVersions`, because they can write in any language version and use something written in to any language version, they just need to be on the same toolchain versions if for the binary interop to work.

**Comment by thomasvl** [comment]
ps - anyway, feel free to close this out.  Just figured I it might be worth pointing out that the current information is sort mixing distinct concepts under single terminology/concept.

**Comment by finestructure** [comment]
Thanks for the follow-up, Thomas, this is really a gnarly topic. I suspect the vast majority of users don't distinguish between swift version and toolchain version and using toolchain version would probably be _more_ confusing for them.

Let's see if the extra FAQ does the trick and re-open the issue in case it pops up again :)
