### ISSUE TITLE
Report back build time and runner

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#682]
Main incentive for this is to find packages that we need to/want to downscale.

We could also find them by looking through the GL pipelines. Unfortunately, there's no aggregate query for pipeline details meeting certain criteria, i.e. we'd need to fetch hundreds, thousands of pipeline details individually to get the duration and runner info.

On the other hand, if we report back the build time we only get the reports of those that actually completed and not the ones that timed out. We could still extrapolate from those that complete close to the timeout on the faster builders.

Task outline if we decide to do this:

- [ ] instrument builder
  - [ ] add input parameters (`--runner`, `--duration`)
  - [ ] send values from report command
- [ ] instrument build.sh
  - [ ] add parameters to report-result command
- [ ] instrument server
  - [ ] add fields
  - [ ] update API to accept values

**Comment by finestructure** [comment]
I keep coming back to this issue and wondering if it's worth doing this right now. It's not a big deal all in all but I'm just not sure we'd get that much use out of it.

We can get this info - including the pipelines that actually timed out - if we query Gitlab. I've just realised they have a [GraphQL API](https://docs.gitlab.com/ee/api/graphql/reference/index.html) as well, which would make that much simpler than via the v4 REST API (where we'd have to hit the API for each pipeline individually).

I'd say let's close this issue and go that route instead, should we need the info.

**Comment by daveverwer** [comment]
I think you're right, it's not essential. As I was thinking this through I was wondering whether it'd show anything interesting in terms of aggregating build time stats, but the fact that so many builds are running on each machine, alongside things like Docker Linux builds means those numbers are pretty meaningless.

Closing it, we can always re-open it if we change our minds!
