### ISSUE TITLE
Check if we create orphan build records when versions are deleted before builds complete

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#689]

**Comment by finestructure** [comment]
Actually, looking at this morning's rollbar where we got a FK violation on `versions`:

```
Message

server: insert or update on table "versions" violates foreign key constraint "versions_package_id_fkey" (ri_ReportViolation)

Traceback

server: insert or update on table "versions" violates foreign key constraint "versions_package_id_fkey" (ri_ReportViolation)
```

The source of this must be a race where a version is written before it's accompanying package (this happened right after adding a new package).

I believe the exact same thing would happen for builds: the write would fail, because it can't reference the (now deleted) parent version record.

**Comment by finestructure** [comment]
It'll fail even before that:

```
POST /api/versions/{version_id}/builds
```

will 404 if `version_id` does not exist anymore:

```
    struct BuildController {
        func create(req: Request) throws -> EventLoopFuture<Build> {
            let dto = try req.content.decode(PostCreateBuildDTO.self)
            return App.Version.find(req.parameters.get("id"), on: req.db)
                .unwrap(or: Abort(.notFound))
                .flatMapThrowing { try Build(dto, $0) }
                .flatMap { build in build.upsert(on: req.db).transform(to: build) }
        }
        ...
```

**Comment by daveverwer** [comment]
I'm not 100% sure I've grasped this, but as I understand it this is all fine because even if that fails, it'll just re-try the build again next time, right?

**Comment by finestructure** [comment]
Yes, that part is entirely unchanged. This was about what happens if a version is deleted during an analysis pass while there were builds pending. I was wondering if we'd create unreachable builds that we then would never clean up if a build reported back for an outdated version - but that actually can't happen.

So that particular build won't be retried, because it's not actually a build we want anymore. _And_ we're not recording it out of sync either, because the API will reject attempts to record builds for non-existing versions.
