### ISSUE TITLE
Retry building XServiceLocator on Swift 4.2 and above

### ISSUE THREAD

**Issue by nasirky** [SwiftPackageIndex/SwiftPackageIndex-Server#692]
[XServiceLocator](https://github.com/quickbirdstudios/XServiceLocator) now also supports Swift 4.2 however, SwiftPackageIndex still shows that it fails on 4.2. The commit was pushed as an amended commit to master. is there any way to build it again on Swift version 4.2 to 5.1

**Comment by daveverwer** [comment]
Hey @nasirky! Thanks for that. As soon as the build system notices the new commit on `master` it'll be built again and the new values will replace the old ones! It should take no more than a couple of hours for this to be noticed, and for everything to update.

Hope this helps!

**Comment by daveverwer** [comment]
Ohh I just noticed you said as an amended commit... I think as long as the commit hash is different, that will be fine. @finestructure am I correct there?

I presume this also means that the commit hash for 1.0.0 has also changed?

**Comment by finestructure** [comment]
Yes, if the commit hash changed, we’ll reprocess - for any revision. You can see this has already happened for `master`:

https://swiftpackageindex.com/quickbirdstudios/XServiceLocator

🙂

**Comment by nasirky** [comment]
@daveverwer @finestructure Thanks a lot for the prompt response. Yes the commit hash has changed and it is also rebuilt for master. 

Thank you very much. I will close the issue.

**Comment by daveverwer** [comment]
I'm not sure this is working correctly for tagged versions as it's several hours later, and the 1.0.0 tag has not been re-built. Opened #693 to track a fix for that.

**Comment by nasirky** [comment]
@daveverwer Yes the tagged version is not rebuilt yet. Thank you for opening an issue to fix it
