### ISSUE TITLE
Add support for git submodules

### ISSUE THREAD

**Issue by csjones** [SwiftPackageIndex/SwiftPackageIndex-Server#702]
Hi @finestructure 👋 the index of packages is looking good and super useful!

I just added my package to the index and noticed all the builds failed... 😕  https://swiftpackageindex.com/GigaBitcoin/secp256k1.swift/builds

Looking at the build log, I'm wondering if the CI is not initializing the submodules which are used to pull in a C library before mapping into swift. Version `0.0.13` was build and tested separately for both macOS and Linux here: https://app.bitrise.io/build/a56ea2ce5305f007

**Comment by finestructure** [comment]
Hi @csjones , I saw that as well - thanks for following up with some more detail.

We're issuing a simple `git clone` to pull down the repo (and `git fetch` subsequently), which is probably not enough enough when dealing with submodules.

I'll try this out in a moment but if you have the proper git command sequence to initialise (and subsequently update) a working copy of your repo to hand that'd be great.

**Comment by csjones** [comment]
Thanks for the help! I reproduced the issue locally and think the best order of commands are as follows:
```
git clone https://github.com/GigaBitcoin/secp256k1.swift
cd secp256k1.swift
git submodule update --init --recursive
swift test
```

**Comment by finestructure** [comment]
Ah, great, I'll give that a go. Once initialised with a submodule, does `git fetch` refresh it? I haven't used submodules in quite a while 😅

**Comment by finestructure** [comment]
Looks like [`git clone --recurse-submodules`](https://git-scm.com/book/en/v2/Git-Tools-Submodules) would sort out the initial clone in one go.

**Comment by finestructure** [comment]
Ok, I've deployed that and it's looking much better now: https://swiftpackageindex.com/GigaBitcoin/secp256k1.swift

I believe the remaining failures are genuine but please have a look yourself and let me know!

**Comment by csjones** [comment]
Yep! Remaining failures look normal, thank you! 🙏
