### ISSUE TITLE
Release sorting fails for double digit builds

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#706]
<img width="1364" alt="Screenshot 2020-09-07 at 17 08 02" src="https://user-images.githubusercontent.com/65520/92400881-e7eac800-f12c-11ea-9ecf-e31a23e9451f.png">

**Comment by finestructure** [comment]
I'm not sure if we have the actual date available, so we may need to deal with smarter numerical sorting.

**Comment by daveverwer** [comment]
Well spotted!
