### ISSUE TITLE
AWS SDK strangeness

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#709]
I was just looking at issue #556 when I noticed that https://swiftpackageindex.com/swift-aws/aws-sdk-swift is a 404.

Is AWS SDK gone?

What I found in its place is https://swiftpackageindex.com/soto-project/soto, which claims its github url https://github.com/swift-aws/aws-sdk-swift.git

Is something messed up with the package name we're parsing?

**Comment by finestructure** [comment]
FYI @adam-fowler

**Comment by finestructure** [comment]
Oh, I see:

> Soto is the new name for AWS SDK Swift. Amazon have asked that we don't use the name AWS SDK Swift.

We automatically transitioned over.

**Comment by adam-fowler** [comment]
@finestructure Its just been renamed, Amazon asked we rename it as we aren't affliated with them. github does the redirection for you

**Comment by adam-fowler** [comment]
Was going to push through a SPI packages change today. But wanted to make sure everything was renamed beforehand

**Comment by finestructure** [comment]
Yeah, and we detect and adopt that. All working as intended but I wonder if we should consider a redirect on our end as well.

**Comment by finestructure** [comment]
I think our nightly will pick up the redirect and update the url automatically, doesn't it @Sherlouk ?

**Comment by adam-fowler** [comment]
So I don't need to do anything?

**Comment by finestructure** [comment]
Perhaps not. There are two things that need updating: the package name and the package url. The package name change is automatically picked up - as you can see already.

I believe our nightly job "sees" the redirect and updates the package url.

Actually, I just saw that our nightly failed for some reason:


```
+ https://github.com/soto-project/soto.git
44
🚨 https://github.com/soto-project/soto.git: Dump Timed Out
45
```

I'll kick it off again and let's see what happens.

**Comment by finestructure** [comment]
I just checked: we are following redirects and updating changed package urls. So you shouldn't have to do anything, Adam.

**Comment by Sherlouk** [comment]
Aye the nightly should handle this for us 👍

**Comment by finestructure** [comment]
Ok, would be fixed in principle but we're running up against the Github API limit:

```
*******************************************************************************
** IMPORTANT ******************************************************************

During validation, problem(s) were found:

* Found "https://github.com/soto-project/ecs.git" but this redirected to "https://github.com/soto-project/soto-ecs"
* Found "https://github.com/soto-project/dynamodb.git" but this redirected to "https://github.com/soto-project/soto-dynamodb"
* The packages.json file was incorrectly sorted
* Found "https://github.com/soto-project/iam.git" but this redirected to "https://github.com/soto-project/soto-iam"
* Found "https://github.com/soto-project/cloudfront.git" but this redirected to "https://github.com/soto-project/soto-cloudfront"
* Found "https://github.com/soto-project/ec2.git" but this redirected to "https://github.com/soto-project/soto-ec2"
* Found "https://github.com/soto-project/ecr.git" but this redirected to "https://github.com/soto-project/soto-ecr"
* Found "https://github.com/soto-project/apigateway.git" but this redirected to "https://github.com/soto-project/soto-apigateway"

These problems have been automatically fixed, but you'll need to commit the
changes that this script has made before creating the pull request.

Thanks!

*******************************************************************************
ERROR: Rate Limit Exceeded /60
ERROR: Rate Limit Exceeded /60
ERROR: Rate Limit Exceeded /60
ERROR: Rate Limit Exceeded /60
ERROR: Rate Limit Exceeded /60
ERROR: Rate Limit Exceeded /60
ERROR: Rate Limit Exceeded /60
🚨 https://github.com/soto-project/soto.git: Dump Timed Out
🚨 https://github.com/soto-project/ec2.git: The data couldn’t be read because it is missing.
🚨 https://github.com/soto-project/ecs.git: The data couldn’t be read because it is missing.
🚨 https://github.com/soto-project/iam.git: The data couldn’t be read because it is missing.
🚨 https://github.com/soto-project/ecr.git: The data couldn’t be read because it is missing.
🚨 https://github.com/soto-project/apigateway.git: The data couldn’t be read because it is missing.
🚨 https://github.com/soto-project/dynamodb.git: The data couldn’t be read because it is missing.
🚨 https://github.com/soto-project/cloudfront.git: The data couldn’t be read because it is missing.

8 package(s) out of 19 failed
##[error]Process completed with exit code 1.
```

Full log: https://github.com/SwiftPackageIndex/PackageList/runs/1110828219

I suspect this will fail again tomorrow morning although I'm not sure why it did in the first place. I wouldn't expect the number of redirects detected to significantly increase the number of requests we're making? Or is it just chance that we've crept up on the API limit due to the increased number of packages?

We may need to throttle the nightly further if so.

Keeping this open to track.

**Comment by finestructure** [comment]
Failed again with the initial error (no rate limiting):

```
+ https://github.com/soto-project/soto.git
🚨 https://github.com/soto-project/soto.git: Dump Timed Out
```

and I've just realised this is in the JSON Validation step. Might be related to the library count.

**Comment by finestructure** [comment]
No idea what exactly is going on here yet. Running package dump takes 5s for soto when run directly, yet the validation script times out after the 50s deadline running `/usr/bin/swift package dump-package` - exact same command.

I'll add soto manually for now.

**Comment by finestructure** [comment]
I've added https://github.com/SwiftPackageIndex/PackageList/issues/632 to track the timeout issue

**Comment by finestructure** [comment]
The reason I'm pushing this in now is that I realised we're spending a lot of time building AWS SDK and all the derived packages - only to remove them again when the url changes. While the nightly is broken none of the name changes proceed.

I'm hoping by manually pushing soto the nightly will become unstuck and everything be updated. After another round of building everything we should be in a state were it all settles down again.

**Comment by adam-fowler** [comment]
Hey @finestructure you would be best to include the actual project url soto-project/soto instead of the old one swift-aws/aws-sdk-swift. There is a chance later on the github redirect will not work. I was going to remove the other swift-aws projects as I am going to be deprecating them on release on 5.0, do you want me to do this now?

Sorry for all this pain

**Comment by finestructure** [comment]
No worries, Adam! I have switched to the soto url now in the package list. All the other urls should sort themselves out now - fingers crossed. It's a good test to see if this shakes out automatically.

The only reason it didn't (I think/hope) was a bug in the nightly, that aborted before the updates could roll out. Let's see how it goes :)

**Comment by adam-fowler** [comment]
Ok, I'll leave the other packages in just now so you can test your systems, but probably by the end of the week I will push a change to the package list that'll remove `swift-aws/s3` etc

**Comment by finestructure** [comment]
FYI, these have been picked up now and should all be correctly updated: https://github.com/SwiftPackageIndex/PackageList/pull/635/files

**Comment by finestructure** [comment]
Soto is also updated to the new url now: https://swiftpackageindex.com/soto-project/soto

So everything should be working order now. Please let us know and re-open if we've missed any of the changes, Adam!
