### ISSUE TITLE
List the git SSH clone URL on the swift package index website. 

### ISSUE THREAD

**Issue by BrentMifsud** [SwiftPackageIndex/SwiftPackageIndex-Server#712]
**Reasoning**
Using two factor authentication on GitHub makes cloning via https a bit of a chore. It’s generally easier to deal with this by using SSH to clone a repo.

Currently the swift package index only lists the HTTPS clone url (see screenshot).

It would be nice if we could choose between https and ssh (I.e. git@github.com:user/repo).

**Screenshots**

![9A8FBC70-71B3-4FFF-9E48-C533AEEAD520](https://user-images.githubusercontent.com/18543934/93671371-679f5d80-fa70-11ea-8f3a-faa732d0077a.jpeg)

**Comment by finestructure** [comment]
Thanks for the report, Brent! You’re right, that’s definitely something we could improve. We were also considering adding a representation that can be copied into `Package.swift` and we could perhaps tackle all of these if not at the same time at least with a general mechanism/UI.

**Comment by finestructure** [comment]
Closing this for now. It's pretty straightforward to click through to the Github repo in order to obtain the SSH url as a workaround.
