### ISSUE TITLE
Outline logs

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#713]
Full logs are actually available externally already, explore loading them into the build detail page asynchronously instead of inlining all the payloads.

For instance, the following link is active for a while

```
curl "https://storage.googleapis.com/gitlab-gprd-artifacts/7b/9f/7b9f80d3b5f930797c985311a99a87f5f2011eeec5d29729a8a580eeb5601708/2020_09_19/746687576/819930104/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=B2FUQnA4OjS6MEYyC%2BvPZ7rWMbvw%2BzSTHhDQUeGo5FgdxdslwXWn7jlMqri7%0AQlo2k%2FVcdM6T2wf2yocSACVEZEIPYLaCTiBqpeXhr654vSkT3Rv00TqigKc2%0A65gRcn2IG49JMonP87c%2Fdgk5fpXgqQ0BmClURg1dXRFTp2iRkAvpat6jGk1Y%0AyIaCkgbUlwLXiVFx6KyESywtpQ04aZ88MoqxadB02%2BFozWpU2Bo2iayee0Pq%0AwmqgtuVAxCeWuw8LY4FAvmfW%2FrS9WvE8A6IQwY5qN5pvefebiDyyQHjh7vyj%0AXZGfSwSr5emVoIFM5x06alS27TWsX14co6KLP%2B6gjg%3D%3D&Expires=1600513347"
```

but expires. We should however be able to fetch the full logs via the Gitlab API.

**Comment by finestructure** [comment]
This is how we can fetch the full logs:

```
$ curl --header "Authorization: Bearer ${GITLAB_API_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/jobs/${JOB_ID}/trace"
Running with gitlab-runner 13.1.1 (6fbc7474)
  on spi-dtk-builder F4MdicTy
Preparing the "shell" executor
Using Shell executor...
Preparing environment
Running on spi-dtk.local...
Getting source from Git repository
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /Users/builder/builds/F4MdicTy/1/finestructure/swiftpackageindex-builder/.git/
Checking out 43f1b329 as main...
Removing build.log
Removing report.log
Removing spi-builder-workspace/
Skipping Git submodules setup
Executing "step_script" stage of the job script
$ ./build.sh
Clone URL: https://github.com/nalexn/ViewInspector.git
Reference: master
Cloned https://github.com/nalexn/ViewInspector.git into spi-builder-workspace
c6f3e9b7b7c22f2f227fe54ab48e520eec7b760c
SUCCESS checkout https://github.com/nalexn/ViewInspector.git at master
Selected platform:         macosSpmArm
Swift version:             v5_3
Building package at path:  spi-builder-workspace
Running build ...
env DEVELOPER_DIR="/Applications/Xcode_12_beta_4.app" xcrun swift build --arch arm64
/Users/builder/builds/F4MdicTy/1/finestructure/swiftpackageindex-builder/spi-builder-workspace
[1/66] Compiling ViewInspector HSplitView.swift
[2/66] Compiling ViewInspector HStack.swift
[3/66] Compiling ViewInspector IDView.swift
[4/66] Compiling ViewInspector Image.swift
[5/66] Compiling ViewInspector LinearGradient.swift
[6/66] Compiling ViewInspector List.swift
[7/66] Compiling ViewInspector MenuButton.swift
[8/66] Compiling ViewInspector ModifiedContent.swift
[9/66] Compiling ViewInspector NavigationLink.swift
[10/66] Compiling ViewInspector NavigationView.swift
...
[67/67] Merging module ViewInspector
✅  build complete
SUCCESS 5.3.0 macos-spm-arm
Sending result (attempt 0)
✅  Result reported
Job succeeded
```

**Comment by finestructure** [comment]
The thing I'm not sure about is how to make this load asynchronously. I mean not in principle - that would be a JS request that populates the logs text field with the result - but we can't really let the client do that, because it needs the `API_TOKEN` and we can't ship that to the client.

So I think we'd have to either give up on this being asynchronous and let the server fetch the logs as part of building the build details page (that's simple) or figure how how to do an asynchronous page refresh when the log request completes. I have no idea if that's even possible with vapor.

The only way I can think of making this work is if we ship our own build logs api that the page we ship then queries asynchronously for the log details. Which isn't something I'd want to run without a token either. So either way, we'd expose a token, but at least we could limit the one we use for our build logs api (for example via a 10min token like GL use for their log links).

I think we should just keep it simple and load the log details synchronously. It's not a frequently visited page and we could make the log details an extra step. I.e. the build details as they are (minus the logs) load fast and then you click another link for the full logs.

**Comment by finestructure** [comment]
Actually, an extra link is overkill. There's just the build command and the logs on that page anyway.

**Comment by finestructure** [comment]
I think I'll implement the sync version side by side and we can see what the latency is like.

**Comment by finestructure** [comment]
Prep PR on the builder side, to send the API-based log url: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/36

NB: this change is required in the builder because we currently don't have enough information to build the log detail url server side. The current `logUrl` is based on the `pipelineId`, not the `jobId`. These are linked (1-n or rather 1-1 in our case, since we run just a single job per pipeline) but it'd require another API request to resolve a pipeline id to a job id. It's cleaner to just send the correct url from the builder.

Once we're happy with how this is working, we can write a script to update the existing `logUrl` entries to API log urls in place without wating for them to be reprocessed.

**Comment by daveverwer** [comment]
Interesting. Given how rare access to the log pages is, I think there's probably no huge downside to it being synchronous during page load. If this was the package page, that'd be a problem, but these logs pages are rarely accessed, and only by people who have a genuine interest in the contents.

**Comment by daveverwer** [comment]
Whichever method we choose, async or sync, we should always have our server make the GL request, not only so it's service agnostic, but also because it'll allow us to process the log before sending it to the client, to strip paths, and other information, etc

**Comment by finestructure** [comment]
First part: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/37

**Comment by finestructure** [comment]
Steps:

1. Server
  - [ ] Accept job url in build report
  - [ ] merge
  - [ ] deploy
1. Builder
  * [x] impl sending logs to S3 >2020-09-21
  * [x] impl sending S3 url as log url (→ signal for "processed") >2020-09-22
  * [x] consider also keeping the job link somewhere - it is useful to be able to pull it up
  * [x] test
  * [ ] deploy
  * [ ] confirm
2. Server: log display
  * [ ] display log from S3 (in parallel to existing)
3. Log migrator (new process - command?)
  * [ ] fetch builds from db where log url is not an S3 url
  * [ ] write to S3
  * [ ] update log url to S3 url
4. Server: clean up
  * [ ] remove old log viewing mechanism
  * [ ] delete logs column from db
5.  Builder: clean up
  * [ ] stop sending logs in build report

**Comment by daveverwer** [comment]
Merged those two PRs but I have *not* tagged, so it will not deploy to prod.

**Comment by finestructure** [comment]
Cheers, I’ll sort that out tomorrow!

**Comment by finestructure** [comment]
Started process of moving the logs on staging. For ref, to monitor progress:

```sql
select count(*)
from builds
where log_url like 'https://gitlab.com%'
```

We started off at about 130k builds (staging is getting there with the backlog!).

```sh
# exec into container, for instance spi_trigger_builds_1 and run
while true ; do env AWS_ACCESS_KEY_ID="..." AWS_SECRET_ACCESS_KEY="..." ./Run migrate-logs --limit 1500 ; sleep 5 ; done
```

Picked 1500 as a batch size - with 2000 we run out of memory in the process.

**Comment by finestructure** [comment]
Just realised there's an issue to take into account here: we'll want to delete the logs from S3 when we trim builds. Otherwise we'll just keep adding to the bucket.

**Comment by finestructure** [comment]
Mmmm, this is actually quite a bit more complicated, because we're currently running a raw SQL query. In order to propagate those deletions out to the S3 bucket we need to read the `log_url`s and run S3 delete commands for all of them.

**Comment by finestructure** [comment]
So there are a couple of things that I’m really unhappy with when it comes to trimming.

- We’d need to keep Soto as a dependency to be able to issue S3 delete requests.
- We only have the `log_url`, i.e. something like `https://spi-build-logs.s3.us-east-2.amazonaws.com/B131ABFE-9ED0-42AC-8C92-BA117A7C6DED.log` but in order to issue an S3 delete request with Soto, we need the parameters `spi-build-logs` , the region, and the key, `B131ABFE-9ED0-42AC-8C92-BA117A7C6DED.log`. We’ve got all this in the url but we’d need to parse it on the server side. Yuck.

  Now we could of course send all those parameters from the builder and keep them in the `builds` table but I don’t like sticking something that’s purely an implementation detail there.

  Another option would be to see if we can send a delete request based on the full url. I’d imagine that’s possible, because I’m guessing that’s what Soto is doing under the hood.

  If we just create an HTTP DELETE with the proper signature using `log_url` we could also avoid pulling in all of Soto as a dependency. That'll be fun though, dealing with the HMAC signatures...

- It’s going to be bit fiddly to run the deletes with the trimming query. In order to avoid having to make bigger changes to the trimming query, it’d probably be best to leave the delete query as is and run a `select log_url` with the same where clause in the same transaction in order to get the urls we need to trim.

  Then "S3 delete" those before running the delete query (either via Soto or our own HTTP DELETE, see above).

  We’ll also want to add a limit so we don’t fail due to too many requests going out or something. We’ll have to be careful with ordering though if we add a limit so the sets that we operate on align.

  We’d want to avoid deleting any records without having issued the S3 deletes so we don’t lose our only handle to identify them (short of comparing all the keys in S3 against existing `log_url`s).

I’m not excited about the complexities of this.

An alternative is to just not bother about deleting any S3 objects and instead set a lifecycle to keep them for a certain amount of time - 6 months perhaps?

After all, the build logs aren’t really all that relevant except shortly after they’ve been run, or are they?

Or we just keep them in the table and abandon the S3 migration entirely.

Best have a good think about this and talk it through :)

**Comment by finestructure** [comment]
My current thinking is to a) either let the logs expire or b) roll back the S3 change. I think all the rest is not worth the complexity.

a) could also include a time so long that it's effectively unlimited (i.e. set expiry to 1 year) - that's effectively forever for all intents and purposes while storage is still technically capped. If we see the bucket getting too full, we can shorten the lifetime.

**Comment by daveverwer** [comment]
Let's discuss this on a call tomorrow in more detail, but here's some thoughts.


> * We’d need to keep Soto as a dependency to be able to issue S3 delete requests.

Is this a huge issue? I know the issues with this package, but once it's fetched/built, is it an ongoing pain?

> * We only have the `log_url`, i.e. something like `https://spi-build-logs.s3.us-east-2.amazonaws.com/B131ABFE-9ED0-42AC-8C92-BA117A7C6DED.log` but in order to issue an S3 delete request with Soto, we need the parameters `spi-build-logs` , the region, and the key, `B131ABFE-9ED0-42AC-8C92-BA117A7C6DED.log`. We’ve got all this in the url but we’d need to parse it on the server side. Yuck.
>   Now we could of course send all those parameters from the builder and keep them in the `builds` table but I don’t like sticking something that’s purely an implementation detail there.

I'm fairly indifferent on this. That URL is pretty well structured and I think the potential issues from parsing it are quite small. On the other hand, storing a few extra fields isn't a huge issue either. You know I'm a big fan of erring on the side of storing things in the database, so I'd vote for the 2nd of these options if we go ahead.

>   Another option would be to see if we can send a delete request based on the full url. I’d imagine that’s possible, because I’m guessing that’s what Soto is doing under the hood.

Or if this works then great!

> * It’s going to be bit fiddly to run the deletes with the trimming query. In order to avoid having to make bigger changes to the trimming query, it’d probably be best to leave the delete query as is and run a `select log_url` with the same where clause in the same transaction in order to get the urls we need to trim.

Would this mean we need to enumerate the files from S3 to get the difference between the ones in the DB and the ones on S3? I know enumeration queries for large buckets on S3 used to be *really* slow.

> An alternative is to just not bother about deleting any S3 objects and instead set a lifecycle to keep them for a certain amount of time - 6 months perhaps?
> 
> After all, the build logs aren’t really all that relevant except shortly after they’ve been run, or are they?

They are not, but it raises the question of what that page shows if the log is gone. It's a nice "proof" that we did the build if the log is always visible.

> Or we just keep them in the table and abandon the S3 migration entirely.

That's a possibility, but it does feel like it might need doing at *some* point as we grow.

**Comment by finestructure** [comment]
Just a couple of notes for our catch up.

> Is this a huge issue? I know the issues with this package, but once it's fetched/built, is it an ongoing pain?

Other than adding ~1-1.5 mins to the Github action (going from ~6 min to ~7.5 min), no. The good news is that it is using the same base dependencies as Vapor, i.e. it really just adds Soto libs themselves and doesn’t pull in more transient dependencies.

I think it’s fine, it’s just quite “heavy” for a single HTTP request 😅

> > Another option would be to see if we can send a delete request based on the full url. I’d imagine that’s possible, because I’m guessing that’s what Soto is doing under the hood.
> 
> Or if this works then great!

I looked into this this morning and it’s … tricky. I think our sanest bet is to try and extend Soto to create a delete request based on a URL rather than region/bucket/key parameters. I _think_ that’s possible from stepping through the code but I’m not 100% sure.

It’s quite a bit of work and the downside is if we can’t upstream that change we’ll have to maintain a branch.

Libs that offer AWS signatures pull in extra crypto dependencies, which I’d like to avoid.

Rolling our own AWS signing seems not worth the effort. TBH, if it comes to that I’d rather parse the `log_url`.

> > * It’s going to be bit fiddly to run the deletes with the trimming query. In order to avoid having to make bigger changes to the trimming query, it’d probably be best to leave the delete query as is and run a `select log_url` with the same where clause in the same transaction in order to get the urls we need to trim.
> 
> Would this mean we need to enumerate the files from S3 to get the difference between the ones in the DB and the ones on S3? I know enumeration queries for large buckets on S3 used to be _really_ slow.

No. This is what we could do if we lost the build records and needed to reconcile S3 content vs the existing builds.

This is about taking the `log_url` from records we’re about to trim and ensuring their S3 objects are deleted before we do.

Soto seems to support a batch delete request but from looking at it I’m not sure it actually works (needs testing - I don’t see how to pass in the array of keys).

So we may need to send a delete request per log. That might have cost implications.

(Fun fact: I’ve burned through 85% of our free tier yesterday when starting the upload of the logs from staging. I suspect delete requests are also billed.)

> > An alternative is to just not bother about deleting any S3 objects and instead set a lifecycle to keep them for a certain amount of time - 6 months perhaps?
> > After all, the build logs aren’t really all that relevant except shortly after they’ve been run, or are they?
> 
> They are not, but it raises the question of what that page shows if the log is gone. It's a nice "proof" that we did the build if the log is always visible.

We still show the build command on that page, so it’s not entirely empty when logs are gone. We could say something like

```
Build failed (detailed logs have expired)
```

in the log field.

> > Or we just keep them in the table and abandon the S3 migration entirely.
> 
> That's a possibility, but it does feel like it might need doing at _some_ point as we grow.

The more I think about it, the more reluctant I get doing any kind of parent-child book-keeping between Postgres and S3.

One thing we haven’t even considered: Right now, we can easily discard builds - for example to re-run 5.3 builds - by deleting the build records. With this in place we could of course still do that but we’d also leave behind all their logs unless we wrote a script to delete the logs and the records.

Eventually we’ll leak logs one way or another, it’s just not worth fiddling with that.

I think we should keep the payloads inline or detach their lifecycle from the build records (that could mean to keep them indefinitely - throw money at it - or expire them more or less aggressively).

**Comment by finestructure** [comment]
Deployed to dev ✅

**Comment by finestructure** [comment]
Deployed to prod ✅

**Comment by daveverwer** [comment]
... and the database server breathes a sigh of relief
