### ISSUE TITLE
Support Commercial Licenses

### ISSUE THREAD

**Issue by steipete** [SwiftPackageIndex/SwiftPackageIndex-Server#717]
Hi there 👋! 

We're excited that we can finally ship a SwiftPM package for PSPDFKit, since Xcode 12 now supports [binary frameworks for SwiftPM](https://pspdfkit.com/blog/2020/binary-frameworks-as-swift-packages/).

https://swiftpackageindex.com/PSPDFKit/PSPDFKit-SP

We'd love to change the red "Unknown License" badge to "Commercial License", ideally linking to our website for further details. We did look at the currently available license versions and there's nothing that would fit our commercial licensing model currently.

Happy to help or contribute code to make this work, but first I want to start a discussion if this is something that people want.

**Comment by daveverwer** [comment]
Congratulations on the release! I was happy to see it come through the PackageList as a PR.

It's an interesting problem. As I'm sure you're aware, we use the GitHub license detection for this feature. Even if GitHub wanted to start detecting commercial licenses (which I don't think they do), it would be impossible as there's no standard "commercial license" template.

So, that leaves it as a problem for us to solve. I see two ways to approach this:

## Metadata file

We're starting to add support for various bits of additional metadata in a `.spi.yml` file. It currently supports some build system settings, but we plan to use this for other metadata in the future. We've talked about adding a "license override" field into that metadata file, which could also indicate that a package is commercially licensed.

The downside to a license override is that people can set it to whatever they want, we'll report it like that, and people browsing the package index will trust that the code is licensed correctly, which it may not be. Obviously, this doesn't come into play with a commercial license, but it's worth considering the context in which we are having this discussion. The more I've been thinking about this field, the less I like it.

The alternative here is to make a special case "commercial license" flag in that file, purely for this purpose.

## Adjust the display of the "Unknown License" lozenge

The "Unknown License" lozenge is big, red, and angry. I think that's the correct colour for packages where a LICENSE file doesn't exist, but packages with an unknown license might suit an orange and slightly less angry looking lozenge. 😂

The other thing that's not great here is that the lozenge links to [the FAQ](https://swiftpackageindex.com/faq#license-problems). Again, I think that's the right place to go for unlicensed packages, but for "Unknown License" packages, we could link to the LICENSE file in the repository instead. I'd want to keep some kind of link to the FAQ next to it, as people might be confused why it says "Unknown License" but that could be linked from a little question mark icon next to the lozenge.

I think orange is probably the correct colour for a commercially licensed package, not green. The orange only indicates that there's something about the license that you'll want to pay attention to.

Opinions welcome! Also /cc @finestructure

**Comment by finestructure** [comment]
Congratulations on the release, Peter! Great to have PSPDFKit in the index :)

I was thinking of the `.spi.yml` file to steer this as well. End of the day, all the Github API does is wrap around a `LICENSE` file so I don't think we're in completely uncharted territory here providing our own take on that, linking to a commercial license.

I think the problem is rather than a "bad" license being displayed that what's in `.spi.yml` might be out of sync with what's in `LICENSE` (i.e. what is reported by Github).

We could handle that by only considering `.spi.yml` if Github reports no license.

The other thing to consider is the one signal we do take from the license attribute: App Store compliance.

How do we handle whether a license given via `.spi.yml` is compliant? Do we even deal with that? Or do we, as you suggest, Dave, do something like this:

```
# .spi.yml
...
  license:
    type: commercial
    link: http://...
    app_store_compliant: true
```

with a narrow set of of types we support (just `commercial` for now I guess?) and trust the package owner?

Could this even be abused without also entering uncertain legal territory? Do we need to worry about it?

I mean, isn’t it a bigger problem for the package author to wrongfully declare App Store compliance than for us?

What we could do is just trial it for now and if we see bad actors, we deny-list their licenses or at least ignore the App Store compliance flag.

Just a few thoughts :)

**Comment by daveverwer** [comment]
> End of the day, all the Github API does is wrap around a `LICENSE` file so I don't think we're in completely uncharted territory here providing our own take on that, linking to a commercial license.

Yea, GitHub uses the [licensee](https://github.com/licensee/licensee) gem to do it.

> I think the problem is rather than a "bad" license being displayed, that what's in `.spi.yml` might get out of sync with what's in `LICENSE` (i.e. what is reported by Github).
> 
> We could handle that by only considering `.spi.yml` if Github reports no license.

So if GitHub reports no license, that means the repository does not contain a `LICENSE` file (or `LICENSE.md`, or `LICENSE.txt`). I think we want to be really careful letting people override that as if there is no license file, it **is not** licensed as open-source, no matter what people intend.

> I mean, isn’t it a bigger problem for the package author to wrongfully declare App Store compliance than for us?

I know this is the package author's problem, not ours, but overriding the license where a LICENSE file does not exist is not something we should allow people to do. It's misleading, and in an area that many developers don't understand well (licensing in general) they may believe that setting that flag *is* licensing their code, which it is not.

> What we could do is just trial it for now and if we see bad actors, we deny-list their licenses or at least ignore the App Store compliance flag.

I wrote it as it's definitely worth discussing, but the more I think about it, the more strongly I am in favour of my second suggestion over the first.

Showing that it is an "Unknown license" in orange is correct. There's no such thing as a "Commercial license" as a defined thing, there is only what text is in the `LICENSE` file. I think that showing "Unknown license" in orange and having that link to the license file itself is the best way to deal with this.

**Comment by finestructure** [comment]
> So if GitHub reports no license, that means the repository does not contain a `LICENSE` file (or `LICENSE.md`, or `LICENSE.txt`). I think we want to be really careful letting people override that as if there is no license file, it **is not** licensed as open-source, no matter what people intend.

Not licensed as open-source - but I was thinking that's the gap we're looking to fill, isn't it? We're looking to add a way to send a license signal in general and Github only really covers the open-source case.

Right now we interpret “no LICENSE file” as “unknown license”. We _could_ allow changing that case to mean “commercial” (or any number of types) via the metadata file, as long as we ensure that open source licenses are always covered by `LICENSE` via Github.

> Showing that it is an "Unknown license" in orange is correct. There's no such thing as a "Commercial license" as a defined thing, there is only what text is in the `LICENSE` file. I think that showing "Unknown license" in orange and having that link to the license file itself is the best way to deal with this.

I’m certainly happy with just changing the “unknown license” colour to orange and add a link. I’m just not sure that really helps Peter’s use case - but let's see what @steipete thinks! :)

**Comment by daveverwer** [comment]
I think there's a bit of a misunderstanding here:

> Right now we interpret “no LICENSE file” as “unknown license”.

Not quite, we currently have four states for a package:

* No license - For example, [Corkboard](https://swiftpackageindex.com/kiliankoe/Corkboard) - The repository does not contain any license information at all, and the code is unlicensed. The license lozenge is shown in red.
* Unknown license - For example, [App Center](https://swiftpackageindex.com/microsoft/appcenter-sdk-apple) - The repository has a license, but it was not able to be matched automatically to any of the defined open-source licenses. In the case of the example, there's additional text at the top of the license that's throwing the detection off, but the PSPDFKit license is also shown with the same state. The license lozenge is shown in red.
* App Store incompatible license - For example, [Noise](https://swiftpackageindex.com/kelvin13/noise) - This is all of the GPL licenses, that are not compatible with the App Store so you should be aware of what you're doing before including them. The license lozenge is shown in orange.
* Recognised open-source license - For example, [Thingy](https://swiftpackageindex.com/bojan/Thingy) - A license file exists, and has been recognised as an open-source license. The license lozenge is shown in green.

I think we should change the behaviour to be this:

* No license - Red lozenge.
* Unknown license - Orange lozenge.
* App Store incompatible license - Orange lozenge.
* Open-source license - Green lozenge.

Also, we should make the license lozenge always link to the text of the license file, and move the link to the FAQ to a (?) icon to the side of the lozenge.

That way:

* A red lozenge means "you should not use this package" becase you really shouldn't use unlicensed code. Developers open themselves to serious legal issues in the future with unlicensed code.
* An orange lozenge means "investigate this license". Either it's not been recognised, in which case you should click through and see if it's a commercial license, a slightly mis-formatted open-source license, or something completely different.
* A green lozenge means "you're legally OK to use this code" as it's open-source.

---

The only slightly difficult bit of this ia that we don't have the path to the LICENSE file in the repository. We don't know if it's LICENSE, LICENSE.md, LICENSE.txt, etc...

**Comment by steipete** [comment]
Thanks everyone for chiming in here. This seems to be trickier than I anticipated!

@finestructure You mentioned the issue with App Store compliance. It's probably extremely likely that a commercial license is App Store compliant, but there indeed could be edge cases where such a package is only meant for internal distribution, so yes, can't be inferred automatically.

@daveverwer Changing "unknown license" to Orange would be a great improvement, as would be linking to the LICENSE file when clicking on the license. This would alleviate most of my concerns. 

Those two changes would also be quite simple fixes, whereas I'm somewhat skeptical of allowing license overrides in the definition file. I wonder if the discussion of a commercial license detection really is something that makes sense at all, given that this is difficult to detect automatically, and if so, might be something form the licensee gem to add.

**Comment by finestructure** [comment]
Thanks for confirming, @steipete ! We'll make sure to add that very soon then.

**Comment by finestructure** [comment]
Implementation note: the graphql query only gives us access to the following license url, which isn't going to be helpful:

```
      "licenseInfo": {
        "name": "Other",
        "key": "other",
        "url": "http://choosealicense.com/licenses/other/"
      },
```

So we'll have to make a query to the license API endpoint instead: https://paw.pt/fuse3gt6

That'll give us a link to the actual license file:

```json
{
  "name": "LICENSE",
  "path": "LICENSE",
  "sha": "e1f2e72bf58ff3cb39e9aa96bf67f92887da6a6b",
  "size": 209,
  "url": "https://api.github.com/repos/PSPDFKit/PSPDFKit-SP/contents/LICENSE?ref=master",
  "html_url": "https://github.com/PSPDFKit/PSPDFKit-SP/blob/master/LICENSE",
  "git_url": "https://api.github.com/repos/PSPDFKit/PSPDFKit-SP/git/blobs/e1f2e72bf58ff3cb39e9aa96bf67f92887da6a6b",
  "download_url": "https://raw.githubusercontent.com/PSPDFKit/PSPDFKit-SP/master/LICENSE",
  "type": "file",
  "content": "QWxsIGl0ZW1zIGFuZCBzb3VyY2UgY29kZSBDb3B5cmlnaHQgwqkgMjAxMC0y\nMDIwIFBTUERGS2l0IEdtYkguCgpQU1BERktpdCBpcyBhIGNvbW1lcmNpYWwg\ncHJvZHVjdCBhbmQgcmVxdWlyZXMgYSBsaWNlbnNlIHRvIGJlIHVzZWQuCgpT\nZWUgaHR0cHM6Ly9wc3BkZmtpdC5jb20vbGVnYWwvTGljZW5zZS5wZGYgaWYg\neW91IGFyZSBldmFsdWF0aW5nIHRoZSBkZW1vLgo=\n",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/PSPDFKit/PSPDFKit-SP/contents/LICENSE?ref=master",
    "git": "https://api.github.com/repos/PSPDFKit/PSPDFKit-SP/git/blobs/e1f2e72bf58ff3cb39e9aa96bf67f92887da6a6b",
    "html": "https://github.com/PSPDFKit/PSPDFKit-SP/blob/master/LICENSE"
  },
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  }
}
```

**Comment by finestructure** [comment]
The link through isn't quite working yet: #757

**Comment by daveverwer** [comment]
Reopening as we're going to make a few front-end changes to this to make it a little smoother.
