### ISSUE TITLE
Supported Swift Versions

### ISSUE THREAD

**Issue by odrobnik** [SwiftPackageIndex/SwiftPackageIndex-Server#727]
My packages have `// swift-tools-version:5.3` in the first line because that is the latest released version in Xcode 12.

You are trying to build with 5.2, 5.1, 5.0 and 4.2 but those always fail:

```
Error: ShellOut encountered an error
Status code: 1
Message: "/Users/builder/builds/pMpxem39/0/finestructure/swiftpackageindex-builder/spi-builder-workspace: error: package at '/Users/builder/builds/pMpxem39/0/finestructure/swiftpackageindex-builder/spi-builder-workspace' is using Swift tools version 5.3.0 but the installed version is 5.2.0"
Output: ""
Selected platform:         macosSpm
Swift version:             v5_2
Building package at path:  spi-builder-workspace
Running build ...
env DEVELOPER_DIR="/Applications/Xcode_11.6.app" xcrun swift build
/Users/builder/builds/pMpxem39/0/finestructure/swiftpackageindex-builder/spi-builder-workspace
${cwd}: error: package at '${cwd}' is using Swift tools version 5.3.0 but the installed version is 5.2.0
```

I propose to eliminate this extra work by not trying to build with swift versions less than the one mentioned in the package header.

**Comment by daveverwer** [comment]
Thanks for the suggestion Oliver!

We could run `swift package tools-version` during analysis (when new commits/versions are discovered) and store the tools version along with the other metadata at that point, and then just skip the build. It would also be useful to have the tools version as additional metadata.

That said, when the tools version isn't supported the build fails *really* fast, and so I'm not sure we'd actually save much time so it may not be worth the effort to implement this.

**Comment by odrobnik** [comment]
Well, with the volume of packages ever increasing cutting down the number of scheduled builds would lessen the unnecessary work on your build server.

**Comment by finestructure** [comment]
As Dave said, these fail really fast and I don’t think we want the additional complexity on the build scheduler side to shave this off. I’ll close this for now but please re-open if there are remaining issues!
