### ISSUE TITLE
Parse out the Swift tools-version during analysis

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#729]
It would be useful to get some statistics on tools version but we don't currently parse it out, let's run `swift package tools-version` during analysis and store it in the database.

**Comment by finestructure** [comment]
It’s actually part of the package dump (a field in the JSON) so it’s readily available by just extending the manifest `Codable` and adding the db field.

**Comment by daveverwer** [comment]
Of course it is! Well spotted.

When we get to this, I would like this to be stored in the database somewhere. The first thing I want to do with this data is some aggregate analysis of tools versions.
