### ISSUE TITLE
Excessive GET requests for S3 builds logs

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#734]
Looks like we're getting ~6k GET requests for S3 build logs at the moment. While not theoretically impossible given our current user traffic, it's highly unlikely everyone click through logs at that rate.

Possible reasons:

- we're issueing two many GETs somehow when passing through the logs
- a robot is crawling all the logs we publish (in which case the number would be low, I guess - unless the number is newly published builds, which would roughly match our build rate per day)
- picking up on that last point: the rate seems to mirror our build rate, so perhaps there's something in our setup that issues a GET for every log we save

**Comment by finestructure** [comment]
I've enabled access logging to a new bucket

**Comment by finestructure** [comment]
I don't think there's anything to be learned from these S3 logs:

```
4f594adbebdc54625eaff285aa1f2489d4fba09bf327a808c8972a2926208777 spi-build-logs [04/Oct/2020:10:15:18 +0000] 208.52.185.253 - 8801706BA784338F REST.GET.OBJECT 259B1689-DD8D-4BDE-9B6C-35030FECC7C6.log "GET /259B1689-DD8D-4BDE-9B6C-35030FECC7C6.log HTTP/1.1" 200 - 90000 90000 72 72 "-" "-" - r1heGvUP0hF/fgur9IFigxnSv2uLPK7SforD1q+I4vECUU7KXOwtrtDyEcAekR1AIEwqCMYbTGQ= - ECDHE-RSA-AES128-GCM-SHA256 - spi-build-logs.s3.us-east-2.amazonaws.com TLSv1.2
4f594adbebdc54625eaff285aa1f2489d4fba09bf327a808c8972a2926208777 spi-build-logs [04/Oct/2020:10:15:38 +0000] 208.52.185.253 - 8B992D671918E4E9 REST.GET.OBJECT 71BAC037-2E33-4250-AC4F-82E56B1A37E6.log "GET /71BAC037-2E33-4250-AC4F-82E56B1A37E6.log HTTP/1.1" 200 - 89510 89510 56 56 "-" "-" - J3Ohlw4l8uPQy8eT3cROEECUfAy1b1RRmdZyk2JV58oUBCGeMiZHP/K2q8nLczIj8e8kbRgChjs= - ECDHE-RSA-AES128-GCM-SHA256 - spi-build-logs.s3.us-east-2.amazonaws.com TLSv1.2
4f594adbebdc54625eaff285aa1f2489d4fba09bf327a808c8972a2926208777 spi-build-logs [04/Oct/2020:10:15:53 +0000] 208.52.185.253 - 60467E3DAFBFEFE5 REST.GET.OBJECT E29DD27E-F812-4AC3-BE09-68C16E9AAD34.log "GET /E29DD27E-F812-4AC3-BE09-68C16E9AAD34.log HTTP/1.1" 200 - 1936 1936 38 37 "-" "-" - EKlt1MybVj2RU4vAu6o2EIGA/MPjLpni9ifrqXUdvJHck8jucgkx+Ai9KDev9sGO6KPvP6RP3U8= - ECDHE-RSA-AES128-GCM-SHA256 - spi-build-logs.s3.us-east-2.amazonaws.com TLSv1.2
4f594adbebdc54625eaff285aa1f2489d4fba09bf327a808c8972a2926208777 spi-build-logs [04/Oct/2020:10:16:16 +0000] 208.52.185.253 - EX6V4PFG1Y6X1VAP REST.GET.OBJECT 59B4DC2A-B329-4D84-8D2F-E7FAEE333C4C.log "GET /59B4DC2A-B329-4D84-8D2F-E7FAEE333C4C.log HTTP/1.1" 200 - 663 663 33 33 "-" "-" - QduRWnesEMByZ5z+xVWUKH52OvGHTK8D2u8AZo3cG4GoyDF9JSCtGrneYvF4G3i3+33seNQOhEE= - ECDHE-RSA-AES128-GCM-SHA256 - spi-build-logs.s3.us-east-2.amazonaws.com TLSv1.2
4f594adbebdc54625eaff285aa1f2489d4fba09bf327a808c8972a2926208777 spi-build-logs [04/Oct/2020:10:16:27 +0000] 208.52.185.253 - ACB7AE8C410B4893 REST.GET.OBJECT 3B8C57C3-BBFC-4A01-B1E6-F4B46CBC4FD1.log "GET /3B8C57C3-BBFC-4A01-B1E6-F4B46CBC4FD1.log HTTP/1.1" 200 - 790 790 87 87 "-" "-" - ORtAbCmtl/UFMM+DNxrtmm+pZhrRiK6RhVfOv+NwBpFto0A337vXpMYoJtXkZOKGcmpuX2IxHvA= - ECDHE-RSA-AES128-GCM-SHA256 - spi-build-logs.s3.us-east-2.amazonaws.com TLSv1.2
```

**Comment by daveverwer** [comment]
Ah, of course. I was thinking the browser was loading the log file, but it's the server that loads it and pipes it into the page output. I agree those are not useful.

In one way though, that *is* useful. It shows that the requests are all being made from our server, and not elsewhere. I didn’t doubt that, but it’s good to have it proven.

I just looked at the analytics, and there's no way that those 6k/day requests are coming from humans. We don't get 6k/day visits across the *entire* site.

I just filtered the analytics, and in the last 7 days we’ve logged 215 visits to individual build pages. Limiting that to a 24 hour period, it’s more like 15-30 hits to build pages per day. Even if you discount people who have analytics blocked, that’s several orders of magnitude away from 6k.

My gut feeling says that these requests are coming from search engines. We’ve given them a huge amount of content to look at by adding these build pages.

We also don’t really want those pages to be indexed by search engines, I don’t think. I can’t see it being a useful thing we’d want to be indexed for. I’ve opened #735 to make that change.

The other advantage of this change is that it’ll also be a good indication of where these requests are coming from. If we merge that change and still see significant traffic to the logs, my theory was incorrect.

Let’s leave the logging bucket on for the time being, I’d like to have that level of detail while we continue to look at this.

**Comment by finestructure** [comment]
I'm calling this fixed. While I can't figure out where to see actual request stats, the forecast usage is dropping in line with the number having dropped to essentially zero:

![27BC0167-D4F2-4635-A67A-52144589756B](https://user-images.githubusercontent.com/65520/95162630-624b4e00-07a6-11eb-84fa-ac893e989431.png)
![894F32E6-8A3D-4946-BCD6-A0ABE678FCC1](https://user-images.githubusercontent.com/65520/95162657-6bd4b600-07a6-11eb-966e-7bd274b02854.png)
![FB39F5DE-FCC2-484F-AA7B-EF32DB24CFAD](https://user-images.githubusercontent.com/65520/95162668-71320080-07a6-11eb-8a5c-9bc18d174d1a.png)

This is over three days, according to (20k)/(number of days) * 31 - i.e. the first estimates where extrapolating from 20k/(4 days) and now it's dropping with each additional day of essentially zero additional requests.

**Comment by daveverwer** [comment]
That's great news. I'm glad it was explainable, and so easily fixable!
