### ISSUE TITLE
Suppress "duplicate key value violates unique constraint"

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#737]
Follow-up of #733 

Explore using `ON CONFLICT` raw query to avoid the underlying error being logged and obscuring other, real errors.

**Comment by finestructure** [comment]
This is what the raw query would have to look like:

```sql
-- upsert
insert into builds(id, created_at, updated_at, build_command, job_url, logs, log_url, platform, status, swift_version, version_id)
values (
        -- sample values for test purposes
	uuid_in(md5(random()::text || clock_timestamp()::text)::cstring),
	NOW(),
	NOW(),
	'build_command',
	'job_url',
	'logs',
	'log_url',
	'linux',
	'ok',
	'{"major": 5, "minor": 0, "patch": 3}',
	'a5b53602-a7f6-448a-aade-2315a5ee7c24'
)
--ON CONFLICT ON CONSTRAINT "uq:builds.version_id+builds.platform+builds.swift_version+v2" DO
ON CONFLICT (
  version_id, platform, (swift_version -> 'major'::text), (swift_version -> 'minor'::text)
) DO
   UPDATE SET
     created_at = excluded.created_at,
     updated_at = excluded.updated_at,
     build_command = excluded.build_command,
     job_url = excluded.build_command,
     logs = excluded.logs,
     log_url = excluded.log_url,
     platform = excluded.platform,
     status = excluded.status,
     swift_version = excluded.swift_version,
     version_id = excluded.version_id
;
```

We cannot use the existing named unique index `"uq:builds.version_id+builds.platform+builds.swift_version+v2"`, because the `ON CONFLICT` clause needs a constraint.

In principle, you can convert a unique index to a constraint like so:

```sql
alter table builds
add constraint "uq:builds.version_id+builds.platform+builds.swift_version+v2"
unique
using index "uq:builds.version_id+builds.platform+builds.swift_version+v2";
```

However, this doesn't work in our case:

```
ERROR:  index "uq:builds.version_id+builds.platform+builds.swift_version+v2" contains expressions
LINE 2: add constraint "uq:builds.version_id+builds.platform+builds....
            ^
DETAIL:  Cannot create a primary key or unique constraint using such an index.
```

So we've now got two warts:

- we need to spell out all the build table field (twice) and keep them in sync with the table definition
- we need to keep the unique index definition in sync with the `ON CONFLICT` clause

I'm assuming that the `ON CONFLICT` would use the unique index for lookup (pretty sure it does).

It's not great, but it's doable.

However, give all this, I think I'd prefer to add a log message around the error alerting readers that the error is genuine.

Or flip the logic around and either check for a conflict or delete always before insertion.

What do you think, @daveverwer ?

**Comment by daveverwer** [comment]
> What do you think, @daveverwer ?

Yea I think the best solution here is going to be to make sure this is well commented in the code, and to have that extra log message saying it's not anything to worry about. Let's do that.
