### ISSUE TITLE
Test Target should not get built for determining compatilibilty

### ISSUE THREAD

**Issue by odrobnik** [SwiftPackageIndex/SwiftPackageIndex-Server#742]
I have a target for normal code and one for unit tests. I found that the evaluation for watchOS fails ([example](https://swiftpackageindex.com/builds/42ECA915-BB0F-44D0-BADE-6BA832C4C5DD)) because there is no XCTest for watchOS. The test target is not referenced by the package's product.

Currently your way - when there is no package Scheme found and you remove the xcodeproject/workspace - of evaluating compatibility seems to always build all targets, including the one for testing. 

That means I face a choice: either I have the existing unit tests (and their resources) in there as well and accept that I will never get the green checkmark next to watchOS. Or I remove the unit test target, as nobody using my package would ever have any use for those tests anyway.

Is there a way you could only have those targets from the Package definition built which are referenced by the package's product definition?

**Comment by finestructure** [comment]
Yes, there is. We've got an experimental feature where you can use a `.spi.yml` metadata file in your project to override the scheme discovery process. If you have a specific scheme that builds a platform that you'd like SPI to use, you can use `.spi.yml` to drive it.

See for instance [`.spi.yml` in the Composable Architecture](https://github.com/pointfreeco/swift-composable-architecture/blob/main/.spi.yml) as an example for exactly your use case:

```yml
version: 1
builder:
  configs:
  - platform: watchos
    scheme: ComposableArchitecture_watchOS
```

**Comment by odrobnik** [comment]
@finestructure Sorry, I might have not been clear. I am talking about the automatically generated scheme. That always builds all targets, but should only build the ones that are referenced by the package's products.

**Comment by finestructure** [comment]
Yes, I know :)

This is an Xcode peculiarity in that it always builds test targets by default. As far as we're aware there's nothing we can do about it.

The only way to work around that right now is to specify a scheme that doesn't build the test target.

**Comment by finestructure** [comment]
I think this is fixed now - please reopen if there are remaining issues!
