### ISSUE TITLE
All linux builds are failing

### ISSUE THREAD

**Issue by 0111b** [SwiftPackageIndex/SwiftPackageIndex-Server#743]
It looks like a problem with docker daemon on the CI

`docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock`

https://swiftpackageindex.com/0111b/Conf/builds

**Comment by finestructure** [comment]
Thanks for reporting that, Alexandr! Looks like your builds got hit by some docker downtime - I've rescheduled them now and they should be refreshed shortly.

**Comment by 0111b** [comment]
Thanks.
I want to mention that probably all recent builds are affected. For example:

https://swiftpackageindex.com/apple/swift-system

Maybe you should restart all builds from last 24h
