### ISSUE TITLE
Don't send results if docker or requested Xcode version is unavailable

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#744]
We've had a case where a docker runner went down and all the linux builds it grabbed (and it then grabbed them quickly) resulted in lots of false negatives as reported in issue #743 

We should abort the build and not report back if that's the case so the builds can be retried with a working builder.

We'll either want to test for docker availability or for the line

```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock
```

in the logs.

**Comment by finestructure** [comment]
On that note: one advantage we're losing by moving the logs is querying on results:

```
select id from builds
where logs like '%docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock%'
limit 100
```

**Comment by finestructure** [comment]
For instance, we can easily find all Swift compiler crashes:

```sql
select id from builds
where logs like '%Stack dump:%'
limit 100
```

- https://swiftpackageindex.com/builds/bd76da2a-96df-46d4-889a-7bff557933ce

```
bd76da2a-96df-46d4-889a-7bff557933ce
2430c3c2-4382-4034-a768-df0be890cbad
563e6e98-f705-4134-b674-bbacdf4f13f1
cea88697-682d-4f1f-9f13-d57e9238b034
0abbdddd-8023-45e3-85d4-02ccaea53a52
f933ac6b-01bd-448a-ac62-b59d8dd97014
...
```

**Comment by daveverwer** [comment]
> On that note: one advantage we're losing by moving the logs is querying on results:

You're right, but I think it's worth the trade-off.

If we need to, we could write a script that would take a set of builds and download the relevant logs, and then run a grep on them.

**Comment by finestructure** [comment]
Fixed by https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/39

**Comment by finestructure** [comment]
Actually, no. We want to improve that fix and also apply it to other platforms where the expected build tools aren't available.

We need a change to differentiate between a build failure and a build infrastructure failure, reported back from the builder itself (instead of baking it into the build.sh script.

It's the better place, because this also affects other platforms: If for instance a builder doesn't have the expected Xcode version installed it'll fail the build report it up as a build error. That's wrong. We must not report those builds back.

**Comment by finestructure** [comment]
Implementing this depends on changes in `swift-argument-parser`:

- https://github.com/apple/swift-argument-parser/issues/230
- https://github.com/apple/swift-argument-parser/issues/243

**Comment by finestructure** [comment]
The fix for issue 243 has landed in swift-argument-parser's main branch: https://github.com/apple/swift-argument-parser/commit/53555a04503c175eaffcf587e4b8c380a7c41a5c 

We could move on this in principle, or wait for a tag. We don't need 230 to be closed, just adopting `CustomNSError` and setting codes should do what we need.

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/46 and deployed
