### ISSUE TITLE
Display a list of dependencies of the package on the search results page

### ISSUE THREAD

**Issue by paulpela** [SwiftPackageIndex/SwiftPackageIndex-Server#750]
For better discoverability it would be great if we could see what other packages this package depends on.

**Comment by Sherlouk** [comment]
Hey 👋 

Definitely a feature I'm also super excited for!

I think this is being tracking under https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/307 so this might be a duplicate - do you agree?

**Comment by finestructure** [comment]
Thanks for raising the issue, Paul. That's definitely something we're looking to do and as James points out, issue #307 is tracking it. I'll be closing this but please let us now in issue #307 if you have thoughts and suggestions!

**Comment by finestructure** [comment]
I just noticed you mentioned the "search results page" in the title while the other issue is about the package page. I think once we have dependency info we'll certainly look to be using it throughout the site. It's an important metric and we've also discussed how search should display an intermediate page with room for more detail. So rest assured this will surface one way or another :)
