### ISSUE TITLE
Don't retry build report sends that 404

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#752]
We're wasting time here, the builds have been garbage collected in the meantime. Example: https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/801551392

**Comment by daveverwer** [comment]
I need a bit more context here. I see a build report that's presumably receiving a 404 because we've deleted the build? Is that because a new version has been released or maybe some other churn on version records?

**Comment by finestructure** [comment]
Yes, I quickly chucked that in here so it's not lost. The issue is that a version has been deleted. I initially thought it's the specific build that's gone but we don't report back by build id but rather by version id. So it's not as frequent an issue as I initially thought.

I'll leave it open for now but it might not be worth addressing.

**Comment by finestructure** [comment]
Not worth dealing with for now, closing.
