### ISSUE TITLE
Build monitoring

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#754]
The last couple of days we're been hovering at our max build threshold longer than usual. *)

This effectively looks like we're barely able to keep up with builds at the moment. I believe this isn't quite the case, however. For one, we've had issues with prod that made us lag and it looks like yesterday has been unusually busy with builds.

There are too things that are concerning however:

- The CI stats view on Gitlab doesn't seem to be working anymore for us, probably because we have too many builds now. That means we do not know how busy our build system is, other than me having the build monitor app running and eyeballing the status. That's not great.

- We seem to be having more builds pending in Gitlab than are pending in the db. Right now, it's 307 vs 76 (both prod and dev combined). I believe the reason this is happening is that we've got builds older than 4 hours in the queue and the backend has come around and deleted the corresponding pending builds in the db. That's a problem, because they will now be rescheduled and we do double work.

  I removed Ceres as a linux builder on Monday and by the looks of it the delta of 200 is due to a Linux backlog. That would make sense, because this morning dev wasn't picking up Linux builds and it was down to a single Linux queue on prod to do all the processing. Also, we've probably had some backlog there in particular, due to the downtime on Monday.

  Ceres is back at it now but I think there's a few things we need to address soon:

- we need build monitoring, in particular
  - builds per day
  - ideally also per platform
  - if possible also duration
- we may need to increase the build trimming grace period from 4 hours
- we may need a little more headroom with build capacity soon (but best to get a view first)

*) by that I mean the 300 pending in the queue beyond which we don't schedule new builds. I.e. the closest we get to our hard limit of 500 is when we're at 299 and schedule a package with the maximum number of 96 builds

<img width="312" alt="Screenshot 2020-10-22 at 11 18 55" src="https://user-images.githubusercontent.com/65520/96851498-60e17d00-1458-11eb-8d06-1cd4d81e26c8.png">

**Comment by daveverwer** [comment]
Yea, this is quite serious and we need to keep on top of it. Let's spend some time talking about it tomorrow and figuring out a few things we can do to push this in the right direction. Ceres has been very helpful, but it's not right that we should *need* it to be part of our infrastructure.

Also, +1 on the monitoring. I'm *still* on Catalina, so can't even run that little tool. I think it should be a page (available to everyone, but not heavily linked/advertised) as I'd love to see a dashboard of what's going on with builds.

**Comment by finestructure** [comment]
This PR should get us all the required info (or make it easy to extend). The build pressure has been better since I've raised this issue and reset the builds but this should allow us to make informed decisions as to where we are with the builds.
