### ISSUE TITLE
Builds hang with certain packages

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#760]
We've observed this in the past but never documented it, nor was it 100% resolved I believe but I've now definitely reproduced an issue that can mess up the runners.

## What happened

All our builders started topping out at 100% usage and a package timed out after building for 60 mins per queue.

## How to reproduce

```
./builder checkout -c https://github.com/j-nguyen/investinginmeapi.git -r 0.4.1 -f
./builder build -s 5.0 -p macos-spm
```

This will lock up a machine, getting stuck after checking out dependencies:

```
...
Fetching https://github.com/vapor/jwt.git
Fetching https://github.com/vapor/fluent.git
Fetching https://github.com/vapor/random.git
Fetching https://github.com/vapor/service.git
Fetching https://github.com/vapor/async.git
```

I recall mentioning this observation to Boris a while back and he was pretty sure it's the resolver getting stuck.

## How to resolve

The problem with this issue is that it isn't recoverable. Even though the jobs time out, they are not collected. The machine remains stuck untill it is either rebooted or all `xcodebuild` and `swift-build` jobs are killed manually.

Luckily the only repos causing this that I've seen so far are old projects using Vapor built with Swift < 5.2, so it's pretty rare. Also, since these project don't see changes it shouldn't be reocurring one we've processed them for the first time. (Although I'm unsure how they got reported as failing if the process is stuck.)

Example: https://swiftpackageindex.com/j-nguyen/InvestingInMeAPI

**Comment by finestructure** [comment]
Just recording this issue for reference. There's probably not much we can do except downscale these projects to 0 in the builder.

**Comment by finestructure** [comment]
I've set `BUILD_DOWNSCALING` for the package in question to 0:

```
{"https://github.com/swift-aws/aws-sdk-swift.git": 0.2, "https://github.com/soto-project/soto.git": 0.2, "https://github.com/susandoggie/doggie.git": 0.4, "https://github.com/j-nguyen/investinginmeapi.git": 0.0}
```

**Comment by daveverwer** [comment]
Looking at this project, I think there's a case for just removing it from the package index. Technically it is a package, but it's not a package that anyone could/would use as it's a full Vapor app from the look of it.

I don't think we have an explicit rule against that kind of thing being added to the index, but it's certainly not what the index is about.

**Comment by finestructure** [comment]
Closing - I think we’ve taken all the actions we can on this for now.
