### ISSUE TITLE
Package release is not handled

### ISSUE THREAD

**Issue by 0111b** [SwiftPackageIndex/SwiftPackageIndex-Server#762]
Package: https://swiftpackageindex.com/0111b/UIPreview

At least 2 version of the package are skipped

> The latest stable release is 0.0.1. Released 9 days ago.
> The last commit to master was 9 days ago.

Where actual version is 0.0.3 

And at the same time there are some new items on the main page recent releases section

**Comment by finestructure** [comment]
Hi Alexandr, thanks for raising the issue. I've spotted that this morning as well, it's tracked in #761. We've got a fix and will roll it out this morning.

I'll close this as duplicate - thanks again!
