### ISSUE TITLE
Add whitespace after title in RSS feed

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#774]
Not sure if this displays similarly in other RSS readers but we could tack on a ` ` after the version number to separate these.

![516382A9-5454-413C-9CDD-C48C8EF8C29F copy](https://user-images.githubusercontent.com/65520/98204736-df4d1d00-1f36-11eb-9b9b-009cec819a93.png)

**Comment by daveverwer** [comment]
This feels a bit like a rendering bug in Reeder. There is an HTML element break in the content that's being rendered, which really should be rendered as whitespace in the preview.

I use Reeder too, so I also see it. But looking at the preview in NetNewsWire, it's rendering correctly.

![Uploading Screenshot 2020-11-05 at 09.21.26@2x.png…]()

**Comment by finestructure** [comment]
Yeah, probably. However, none of my other feeds show that - they all have proper line breaks. Might be something small we can do to make that look better.

**Comment by finestructure** [comment]
Actually - why do we even repeat the `Package - 1.2.3` string? It's already in the title.

**Comment by finestructure** [comment]
And I think the links in our description are incorrect. We've got:

```xml
<item>
	<guid isPermaLink="true">https://swiftpackageindex.com/laevandus/IndexedDataStore#0.1.1</guid>
	<title>IndexedDataStore - 0.1.1</title>
	<link>https://swiftpackageindex.com/laevandus/IndexedDataStore#0.1.1</link>
	<pubDate>Thu, 12 Nov 2020 10:25:22 +0000</pubDate>
	<description><![CDATA[<p><a href="https://swiftpackageindex.com/laevandus/IndexedDataStore#0.1.1">IndexedDataStore</a><small> – 0.1.1</small></p><p></p><small><a href="https://swiftpackageindex.com/laevandus/IndexedDataStore#0.1.1">laevandus/IndexedDataStore</a></small>]]></description>
</item>
```

But those anchors don't exist. I believe we intended to (and should) link to the actual release, i.e. `https://github.com/laevandus/IndexedDataStore/releases/tag/0.1.1`.

**Comment by daveverwer** [comment]
What I want out of this is a link to the SPI page for that package, so I don't think it should be *only* a link to the GitHub release. So, if we do want to include a link to the GitHub release, we should add that as a separate link around the version number.

**Comment by finestructure** [comment]
We'll have that. In fact we already have a link to the SPI package in there as well. I'm mostly done with that change and will roll this all into one PR and we can look where we put what link exactly.

**Comment by daveverwer** [comment]
I'll wait to see the diff then! 👍

**Comment by finestructure** [comment]
Looks like Reeder can't be fixed to keep whitespace between elements (at least not if it's a simple `" "`) but the version string pushes that out of the view at least 😅 

<img width="811" alt="Screenshot 2020-11-16 at 11 17 43" src="https://user-images.githubusercontent.com/65520/99241130-b9106280-27fd-11eb-95ae-f071a1921730.png">
