### ISSUE TITLE
LeftPad not showing up in Recent Releases on staging (nor on prod)

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#798]
<img width="1227" alt="Screenshot 2020-11-19 at 14 31 47" src="https://user-images.githubusercontent.com/65520/99690023-f2f49980-2a87-11eb-93e5-37813c5b24e4.png">

It's clearly been parsed though, because we've tweeted:

<img width="656" alt="Screenshot 2020-11-19 at 16 54 18" src="https://user-images.githubusercontent.com/65520/99690062-fee05b80-2a87-11eb-8112-aebda03df8c3.png">

It's also not in the RSS feed (on prod):

<img width="301" alt="Screenshot 2020-11-19 at 16 55 41" src="https://user-images.githubusercontent.com/65520/99690122-115a9500-2a88-11eb-9f9d-e11004b77fd6.png">

Which is consistent, because the front page and the RSS feed are fed by the same "recent releases" materialized view. Might just be something about the `LeftPad` metadata that's excluding it from the view's query.

**Comment by finestructure** [comment]
Prod hasn't indexed the new version yet, so that explains why it's not in the RSS feed or on the main page there (at least for now).

**Comment by daveverwer** [comment]
I bet I know what the problem is. When you asked me to tag a release in LeftPad, that's what I did. What I didn't do is push a commit, I just tagged an existing commit and pushed it.

I wonder if we're not looking for tags unless we see the latest commit hash change? Although, I do think we enumerate all tags, right? So maybe I'm wrong.

**Comment by finestructure** [comment]
Pretty sure that's not it, because the version has been detected on dev, nor do we rely on commits if memory serves. Will debug it through tomorrow!

**Comment by finestructure** [comment]
Oooh, I see. It's because the tag is on an old revision: `2019-08-11 08:10:54+00`. That's what we see as the release date. It's a manifestation of #414 

So you're right: it's because you didn't create a new commit but it didn't prevent us from seeing the tag: it's just sorted so far back in the "recent releases" materialised view that it doesn't make the front page.

I guess in a sense the twitter feed "fixed" that, although for the purposes of the materialised view we'll probably still want to look at the GH release dates at some point. Will close this in favour of #414 where we track this.
