### ISSUE TITLE
Consider using package name instead of repo name in tweets

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#799]
<img width="192" alt="Screenshot 2020-11-20 at 06 24 02" src="https://user-images.githubusercontent.com/65520/99762607-376c4d80-2af9-11eb-8b62-d81096a9fa6c.png">

vs

<img width="460" alt="Screenshot 2020-11-20 at 06 24 12" src="https://user-images.githubusercontent.com/65520/99762683-5834a300-2af9-11eb-9a9a-673740756444.png">

If it wasn't for "Optimizely" being mentioned in the summary it'd be a pretty obscure tweet.

**Comment by daveverwer** [comment]
Yea we should absolutely use the package name rather than the repo name, I actually thought we were already!
