### ISSUE TITLE
Package.isNew not behaving as expected

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#802]
<img width="656" alt="Screenshot 2020-11-21 at 09 42 55" src="https://user-images.githubusercontent.com/65520/99871860-ff8b0600-2bdd-11eb-8ef1-24722c1bec9c.png">

**Comment by finestructure** [comment]
I think I know what's happening. We're tweeting inside analysis, before the new processingStage is applied. So technically, it's still on the previous stage. Need to either pull back the tweeting until after the stage is finished or revisit how we derive `isNew`. The former seems cleaner but might be tricky.

**Comment by finestructure** [comment]
As an aside, the issue with tweetig about multiple tags is clearly fixed. Last night, we ingested the new package AppBoy iOS SDK with 117 releases:

<img width="661" alt="Screenshot 2020-11-21 at 10 11 00" src="https://user-images.githubusercontent.com/65520/99872483-395e0b80-2be2-11eb-914e-e882e222fab6.png">

<img width="501" alt="Screenshot 2020-11-21 at 10 11 40" src="https://user-images.githubusercontent.com/65520/99872484-40851980-2be2-11eb-8ecc-d2d7f385c114.png">

That prompted only a single tweet:

<img width="656" alt="Screenshot 2020-11-21 at 10 14 13" src="https://user-images.githubusercontent.com/65520/99872506-63173280-2be2-11eb-91ff-3227e03038a7.png">

So if `isNew` is proving problematic, we can perhaps make it a tweet that works for both new and existing packages and avoid the distinction.

**Comment by finestructure** [comment]
The issue is that it's currently just not possible to tell from within any stage after reconciliation whether a package is new. I've updated the tests exposing the issue.

The problem with the `isNew` test that I'd added was that I'd not properly advanced the ingestion clock, meaning that the second cycle didn't actually take effect. Once it's added, it shows that `isNew` gets reset on the next ingestion, because it has no history.

When I worked on that yesterday got confused and thought we do

1. reconciliation
2. ingestion
3. analysis
4. go to 3 - analysis

when it's actually

1. reconciliation
2. ingestion
3. analysis
4. go to 2 - ingestion

The best way to fix this is probably to introduce a proper `isNew` flag on `Package` that we manage as we go through the stages, perhaps setting it to `false` once we complete analysis for the first time.

Alternatively, for the purpose of just tweeting, a simpler fix is to drop `isNew` for now and compose a message that works for both cases.

**Comment by daveverwer** [comment]
If it's any help with making the decision, one thing I've been thinking about for the front page is that we could combine the new releases and new packages lists into one "timeline" of stuff, giving us some space for more stuff on the home page. No firm plans yet, but it's been on my mind and it strikes me that a good decision here might make pulling that data easier.

**Comment by Sherlouk** [comment]
Sounds like adding a `isNew` flag would offer us the most potential and flexibility down the line, but requires more work!
