### ISSUE TITLE
Delete outdated Xcode12b4 builds for reprocessing

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#804]
Follow-up from #679

**Comment by finestructure** [comment]
Nov 12:

- 34,591 builds remain having been run with Xcode 12-beta4
- 14,810 of those failed
- 30,382 are older than 30 days
- 13,158 that failed are older than 30 days

Nov 23:

- 32,622 beta4
- 13,942 beta4 failed

**Comment by finestructure** [comment]
We've got some idle time today, so I'm starting to delete failed beta4 builds now

**Comment by daveverwer** [comment]
We still have quite a number of these in the builds table.

Jan 4th

* 3,734 beta 2 failed
* 3,464 beta 2 passed
* 12,042 beta 4 failed
* 16,462 beta 4 passed

**Comment by finestructure** [comment]
I'd recommend we abandon this as we don't really have the capacity to catch up on these builds.

I think our process should simply be if there's a report of a false negative from a beta build we'll reprocess that specific package. All actively maintained packages pretty much auto-update anyway by way of releases and changes to their default branch.

**Comment by finestructure** [comment]
I'm going to go ahead and close this. I've deleted a few more batches of 1000 beta builds to day and takes about 2h to build them. We've still got 19k beta builds left and it's quite tedious to keep deleting the batches off and on, when we we don't really have indication that 12b4 had any issues.

It'd be easy if we could just delete them all in one go but that'd then interfere with normal operations (i.e. we'd end up with new releases showing "pending" until we're caught up).
