### ISSUE TITLE
Display on a package page that it is archived

### ISSUE THREAD

**Issue by mackoj** [SwiftPackageIndex/SwiftPackageIndex-Server#806]
Hi,

Thanks for making the index.

It would be great if we could see on a Package page if it is archived.
Like this one for example https://github.com/Fitzafful/BillboardSwiftLibrary.

Thanks,

**Comment by Sherlouk** [comment]
Thanks for the suggestion Jeffrey!

I believe this is a duplicate of https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/552? 😄

**Comment by mackoj** [comment]
Sorry I didn't see the previous issue I will close this one.

**Comment by daveverwer** [comment]
Don't worry about it, Jeffrey! Thanks so much for the suggestion.
