### ISSUE TITLE
Builder issue

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#815]
https://gitlab.com/finestructure/swiftpackageindex-builder/-/issues/15

**Comment by finestructure** [comment]
Fixed and deployed

**Comment by daveverwer** [comment]
Is this so vague because of the implications of the issue? This could be the best bug report I've ever seen 😂

**Comment by finestructure** [comment]
Sir, there's nothing to see here. Please move right along.

😇

**Comment by daveverwer** [comment]
There really is nothing to see here 😂
