### ISSUE TITLE
Trailing hyphen in Firehose tweets

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#819]
https://twitter.com/PackageFirehose/status/1331644360761413638

We do have code to try and avoid this:
https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/Sources/App/Core/Twitter.swift#L63-L69

My best guess (without debugging) is that summary exists but is an empty string (or purely contains whitespace). We might need to do something like

```
guard let summary = summary?.trimmingCharacters(in: .whitespacesAndNewlines), 
      summary.isEmpty == false 
else {
  return ""
}
```
(might not compile but you get the picture)

**Comment by daveverwer** [comment]
Thank you James, I'm sure that the issue is something like that 👍

**Comment by finestructure** [comment]
That's what I thought, too, but when I checked the db for the package you mentioned in Slack yesterday it showed `summary = NULL`. Weird! I guess there's a very small chance that it _was_ `""` yesterday and `NULL` this morning but that's a stretch.

Def a good idea to trim as well but I'll need to check against a db copy to see if there's something else going on with that particular package.

**Comment by Sherlouk** [comment]
for what it's worth, doesn't seem like an entirely isolated issue:
https://twitter.com/PackageFirehose/status/1331851117119074304

For what it's worth it's showing as an empty string inside the description <p> tag on SPI - but this would happen if the 'unwrap' fails too (insinuating either nil or empty)

It couldn't be some sort of infrequent race condition between ingest and analyse could it?

**Comment by finestructure** [comment]
It's actually not that big a mystery 🤣 

```swift
                    : versionUpdateMessage(packageName: packageName,
                                           repositoryOwner: owner,
                                           url: url,
                                           version: semVer,
                                           summary: repo?.summary ?? "")
```

**Comment by finestructure** [comment]
But I'll also trim whitespace and deal with empty strings.
