### ISSUE TITLE
Create search API

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#82]
JSON API to return the following information for a search query:

* Package name
* Repository ID (username/reponame)
* Summary

This API could one day become a proper search API, but for now it just needs these fields.

**Comment by finestructure** [comment]
Here's a working query that returns 27 rows, including the "hit":

```
-- Brandstetter recommends ~ over SIMILAR TO
-- https://dba.stackexchange.com/questions/10694/pattern-matching-with-like-similar-to-or-regular-expressions-in-postgresql/10696#10696
select v.package_name, r.summary, r.name, r.owner from packages p
join repositories r on r.package_id = p.id
join versions v on v.package_id = p.id
where v.reference ->> 'branch' = r.default_branch
  and v.package_name || ' ' || r.summary || ' ' || r.name || ' ' || r.owner
  ~* '(publish|sundell)'
;
```

This has the following plan without any extra indexes:

```
Nested Loop  (cost=136.28..2037.59 rows=1 width=92) (actual time=7.039..52.376 rows=27 loops=1)
  Join Filter: (r.package_id = p.id)
  ->  Hash Join  (cost=136.00..2037.28 rows=1 width=124) (actual time=7.025..52.201 rows=27 loops=1)
        Hash Cond: ((v.package_id = r.package_id) AND ((v.reference ->> 'branch'::text) = r.default_branch))
        Join Filter: (((((((v.package_name || ' '::text) || r.summary) || ' '::text) || r.name) || ' '::text) || r.owner) ~* '(publish|sundell)'::text)
        Rows Removed by Join Filter: 2453
        ->  Seq Scan on versions v  (cost=0.00..1704.36 rows=36636 width=137) (actual time=0.005..9.414 rows=36637 loops=1)
        ->  Hash  (cost=98.80..98.80 rows=2480 width=104) (actual time=1.624..1.625 rows=2480 loops=1)
              Buckets: 4096  Batches: 1  Memory Usage: 357kB
              ->  Seq Scan on repositories r  (cost=0.00..98.80 rows=2480 width=104) (actual time=0.007..0.779 rows=2480 loops=1)
  ->  Index Only Scan using packages_pkey on packages p  (cost=0.28..0.30 rows=1 width=16) (actual time=0.005..0.005 rows=1 loops=27)
        Index Cond: (id = v.package_id)
        Heap Fetches: 25
Planning Time: 0.496 ms
Execution Time: 52.447 ms
```

I'm not an expert when it comes to SQL execution plans but AFAICT it doesn't look terrible. There's probably some room to improve this with indexes on the filter fields but I think it's fine for the start.

**Comment by finestructure** [comment]
Regarding the search extensions like `name:foo`, `description:bar`, `owner:baz` - we could either post-filter on those vapor-side or run separate SQL queries. I don't think it matters performance wise and they're probably rare enough.

I general, I think it's a simpler design to run with a single, broader query and do some post-filtering/sorting than try and get the SQL perfect.

It's also more easily testable vapor-side and keeping most of the logic there seems like a sensible choice.

**Comment by finestructure** [comment]
I've also tested this query with search terms casting a large net, like `test|network|ios|mac` returning 363 and it's fast enough. We just need to make sure we only pull in the fields we need (i.e. pulling `summary` for all of those would be detrimental).

**Comment by daveverwer** [comment]
I'm no expert on SQL performance either, so let's see how it performs when there's the full data set in there. It seems fine for now.

The only thing that stood out to me here is:

> We just need to make sure we only pull in the fields we need (i.e. pulling summary for all of those would be detrimental).

It looks to me like (and from my tests yesterday) the query *does* search inside summary. Certainly, [this query](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/82#issuecomment-631271903) seems to search that field. I think it's essential that the summary field is part of the search.

**Comment by daveverwer** [comment]
Also, when you say a query like `test|network|ios|mac`. Is that doing an OR? The way that search works on the SwiftPM Library multiple fields work as an AND rather than an OR. For example:

https://swiftpm.co/?query=sundell+publish

Compared to:

https://swiftpm.co/?query=sundell

**Comment by finestructure** [comment]
Quick update, the joined fields need to be

```
and coalesce(v.package_name) || ' ' || coalesce(r.summary, '') || ' ' || coalesce(r.name, '') || ' ' || coalesce(r.owner, '')
```

so they don't collapse to `null` if any of the fields is `null`.

Re: summary - I meant just to be conscious of what we use as the field selection. I.e. just do `select v.package_name, p.url from ...` if all we need is a list of package names with urls. Even if we chose `summary` here (perhaps with a cutoff) it wouldn't be a huge problem, I think.

Re: and/or - it is indeed an "or" right now. Let me see what an "and" would look like.

**Comment by finestructure** [comment]
Right, there's perhaps a more concise way of doing this but I think I'm just going to go with expanding the regex `and` clause per term:

```
select
v.package_name, r.name, r.owner, r.summary
from packages p
join repositories r on r.package_id = p.id
join versions v on v.package_id = p.id
where v.reference ->> 'branch' = r.default_branch
  and coalesce(v.package_name) || ' ' || coalesce(r.summary, '') || ' ' || coalesce(r.name, '') || ' ' || coalesce(r.owner, '') ~* 'sundell'
  and coalesce(v.package_name) || ' ' || coalesce(r.summary, '') || ' ' || coalesce(r.name, '') || ' ' || coalesce(r.owner, '') ~* 'publish'
```
