### ISSUE TITLE
Archived clause not taking effect?

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#820]
According to the `dev` db, this package is archived: https://staging.swiftpackageindex.com/vapor/template-kit (and it _is_: https://github.com/vapor/template-kit

Yet the page doesn't reflect this:

<img width="625" alt="Screenshot 2020-11-26 at 11 52 24" src="https://user-images.githubusercontent.com/65520/100342145-dbfcfc80-2fdd-11eb-83c4-ead17f7c53f6.png">

**Comment by Sherlouk** [comment]
Is there a way to `make ingest` on a particular package so I can update it's metadata? 🤔 

Plausible I missed one link in the pipeline

**Comment by finestructure** [comment]
You can run

```
swift run Run ingest --id <package id>
```

**Comment by finestructure** [comment]
but note that the db is updated correctly, so I don't think it's ingestion that's going wrong

**Comment by Sherlouk** [comment]
Was more that my copy of the DB doesn't have any archived packages in it!

**Comment by finestructure** [comment]
You can always just run `make ingest` and flip the bool in the db - that's what I'm going to do ;)

**Comment by Sherlouk** [comment]
Smart boy 😉  I'll get on that today 👍

**Comment by finestructure** [comment]
ah bugger, I missed that in review:

```
    readme_url text,
    is_archived text
);
```

That field should have been

```
            .field("is_archived", .bool)
```

**Comment by finestructure** [comment]
That why reading it back always returns a nil and then defaults to `false`.

**Comment by finestructure** [comment]
I'll roll back dev and patch up the migration so we don't need to migrate again.

**Comment by Sherlouk** [comment]
🤦  well now I feel like a goof
that's what I get for copy pasting I suppose

Huge apologies!

**Comment by finestructure** [comment]
No worries, that's what code review is for! It's clearly Dave's fault 😬 

Was also a good opportunity to test db migration roll-backs so we can avoid keeping that faulty migration around (which worked fine). It's all good :)

**Comment by daveverwer** [comment]
Always Dave's fault 😬

**Comment by finestructure** [comment]
Ok, it's working now: https://staging.swiftpackageindex.com/guseducampos/JustNetworking

(don't look at the original link up top yet - it needs to be re-ingested first)

**Comment by finestructure** [comment]
Looking at that page I wonder if we should make it more prominent. I have to say I'd immediately move on if I was on that page for the primary purpose of finding a dependency. So I feel this should perhaps come with a ⚠️ or something.

**Comment by daveverwer** [comment]
I know what you mean. I think that whole area at the top fades into insignificance a bit now we have the very pretty and colourful build matrices below it. 

I think this is good to deploy for now, but I'll bear this in mind as I look at the page re-shuffle/re-design that will come after README files are in.
