### ISSUE TITLE
Production setup

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#83]
- cloudflare (TTL, invalidation)
- api access / auth? / rate limiting?
- DNS

**Comment by daveverwer** [comment]
In terms of API, not for the initial launch. The SwiftPM Library API isn't going to break immediately.

**Comment by daveverwer** [comment]
I've split this ticket into several tasks, and moved all non-development tasks out of the "Launch" project and into a new project, "[Launch Process](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/projects/2)". Closing this in favour of #222 and #223.
