### ISSUE TITLE
Syntax highlighting affects build logs

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#830]
It's nice and colourful but I don't think we want that really :)

<img width="1125" alt="Screenshot 2020-11-30 at 09 34 51" src="https://user-images.githubusercontent.com/65520/100586406-651e7700-32ef-11eb-94c7-27b5bd0f1f06.png">

**Comment by daveverwer** [comment]
At first I was with you, but after looking at it I'm not sure I agree. Looking through logs with this on makes them much more readable to me. Especially examples like this:

<img width="813" alt="Screenshot 2020-11-30 at 09 42 14@2x" src="https://user-images.githubusercontent.com/5180/100593464-5a181680-32f0-11eb-85f6-7f7006b90423.png">

It's identifying the language as `bash` which we could/should force, if we keep it. We can force it by adding a `class` of `bash` to the `code` element.

<img width="383" alt="Screenshot 2020-11-30 at 09 38 14@2x" src="https://user-images.githubusercontent.com/5180/100593010-c9413b00-32ef-11eb-960f-d3aced75af15.png">

If we decide not to highlight, we can disable it by adding a `class` of `nohighlight` to the `code` element, but I really am not sure it's something we want to disable.

**Comment by finestructure** [comment]
Yeah, I should have qualified that: if we highlight, it should be some "language" that makes sense for logs. It's a bit weird and (I find) distracting when it highlights swift keywords.

Picking out string literals etc is indeed a big plus!

**Comment by daveverwer** [comment]
But it's detecting the language as bash already.

I think it'd be better for us to force it, but that screenshot of the class showing as `bash` was without any modification by me.

**Comment by finestructure** [comment]
Yes, but I find identifying bash keywords a bit distracting (I had written "Swift" at first but went back to edit my comment when I realised it was "bash"). It mostly works and is an improvement in some cases but I don't feel it is universally so. I don't think bash syntax highlighting is an ideal match for logs, it's just happens to work ok sometimes.

Ideally we'd be able to define a set of rules that don't highlight `in` etc. Does the highlighter allow that?

**Comment by daveverwer** [comment]
Yes, we could write a custom language syntax for highlight.js. I'd say for the number of people who look at this it should be a fairly low priority, but if you fancy having a crack at it, here are the docs:

https://highlightjs.readthedocs.io/en/latest/language-guide.html

**Comment by finestructure** [comment]
I've had a quick look and I think if we pick something without keywords like `YAML`, we should get a decent result without any "language noise": http://jsfiddle.net/pwhudnxz/1/
