### ISSUE TITLE
`.macosXcodebuildArm` builds are broken

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#835]
Just noticed this when running tests on M1 but it's also affecting the DTK builds:

https://swiftpackageindex.com/builds/C4B45E48-2B1E-45A7-81A9-8FF797F1671E

This must have been a change from beta4 → release and we didn't catch it, because the builder tests on run on Intel.

Apparently, `-destination generic/platform=macos,arch=arm64` needs to be replaced with just `-arch arm64`.

This also works for Intel, via `-arch x86_64`, so we could change both.

Confirmed to work on M1 for both but double check on Intel:

```

❯ /Applications/Xcode_12.2.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=$PWD/.dependencies -derivedDataPath $PWD/.derivedData build -scheme SemanticVersion-Package -arch arm64
...

❯ file /Users/sas/Projects/spi-builder/checkout/.derivedData/Build/Products/Debug/SemanticVersion.framework/Versions/A/SemanticVersion
/Users/sas/Projects/spi-builder/checkout/.derivedData/Build/Products/Debug/SemanticVersion.framework/Versions/A/SemanticVersion: Mach-O 64-bit dynamically linked shared library arm64
```

```

❯ /Applications/Xcode_12.2.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=$PWD/.dependencies -derivedDataPath $PWD/.derivedData build -scheme SemanticVersion-Package -arch x86_64
...

❯ file /Users/sas/Projects/spi-builder/checkout/.derivedData/Build/Products/Debug/SemanticVersion.framework/Versions/A/SemanticVersion
/Users/sas/Projects/spi-builder/checkout/.derivedData/Build/Products/Debug/SemanticVersion.framework/Versions/A/SemanticVersion: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by finestructure** [comment]
Actually, just dropping the "generic" part works:

```
-destination "platform=macos,arch=x86_64"
```

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/47

We could technically now cross-compile in both directions - i.e. any builder can build arm64 and x86_64 and vice versa. In case we stumble into some M1 Macs :D

**Comment by daveverwer** [comment]
> We could technically now cross-compile in both directions - i.e. any builder can build arm64 and x86_64 and vice versa. In case we stumble into some M1 Macs :D

Yea this is great, let's see what happens when the DTK needs returning before we decide what to do with this.

**Comment by finestructure** [comment]
Deployed

**Comment by finestructure** [comment]
Confirmed fixed: https://swiftpackageindex.com/builds/FC8CD7DB-44FD-4F71-B814-594620085B59
