### ISSUE TITLE
Support relative links in READMEs

### ISSUE THREAD

**Issue by mattpolzin** [SwiftPackageIndex/SwiftPackageIndex-Server#857]
The complexity to payoff ratio here is a bit unfortunate, but so is the lack of support for relative links.

I'll point out an example in my README just because the example is handy; The OpenAPIKit README found [here](https://swiftpackageindex.com/mattpolzin/OpenAPIKit) has a few broken links, including one to `./documentation/validation.md` which gets expanded to `https://swiftpackageindex.com/mattpolzin/documentation/validation.md` which does not exist.

This comes up when a repository README has relative markdown links in it so that it can reference other documentation pages in the same repository without needing to pin down the full URL (especially useful to support links that do not hardcode the main branch & repository domain into their path).

A couple of ideas to throw out there, neither of which sounds trivial:
1. Scan for links in README and pull in the related documentation pages.
2. Scan for relative links and replace them with fully qualified links.

**Comment by Sherlouk** [comment]
Hey Mathew!

Relative lives within the README is something that has been discussed and worked on previously but I do realise we missed a requirement here.

We have some JavaScript code here: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/Public/javascripts/readme_processor.js - this allows relative links to work for images only (currently). We might be able to rework some of this to also work for relative links.

This would require a different "data-readme-base-url" though, as that currently points to the 'raw' URL.

---

Linking to #825 (added image relative URLs) and #410 (mentions this bug too) for future reference.

**Comment by daveverwer** [comment]
> This would require a different "data-readme-base-url" though, as that currently points to the 'raw' URL.

Or some truly brittle code that very much relies on everything being hosted on GitHub, which is the case right now. This is the mechanism I've chosen for this fix, as I don't think we have an easy way to get a correct base URL for the `blob` style URLs from the GitHub API.

**Comment by finestructure** [comment]
We're already doing some provider specific URL fiddling: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/b4942a52f30c79218351949a3095f9de9a38ccc1/Sources/App/Models/Package.swift#L164

Is this perhaps something we could extend to cover those URL and make it a bit less GH specific or at least have a place where it could be centralised?

**Comment by daveverwer** [comment]
Yea it would be great if we could prepare this centrally on the server and pass down two URLs instead of one. I'd suggest:

* `data-readme-base-raw-url` would contain the current `data-readme-base-url`, for example `https://raw.githubusercontent.com/mattpolzin/OpenAPIKit/master/`.
* `data-readme-base-url` would contain the base URL to the "formatted" documents, for example `https://github.com/mattpolzin/OpenAPIKit/blob/master`.

I think we should probably merge this, and I'll raise an issue for that change separately.

**Comment by mattpolzin** [comment]
Thanks everyone! This index has gained such an impressive set of nice features.
