### ISSUE TITLE
Display release information on the package page

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#863]
Now that we have the release information in the database (#414), we should visualise it better, including release notes on the package page.

This is being tackled as part of the package page design changes but needs tracking.

**Comment by Sherlouk** [comment]
> This is being tackled as part of the package page design changes

Did you have some ideas on how this should be approached Dave?

**Comment by daveverwer** [comment]
It didn't make it as part of that design change, but predictably, I do have thoughts on it!

Very roughly, what I'm thinking is that we would have a "tab bar" approach to the current README section. The README itself would be shown by default and the release notes being shown when switching tabs. We may want to pre-load both tabs for Google to see, but that's an implementation detail.

My thought was that we'd use approximately the "button" design that we're using in the sidebar for the tabs, and that in some ways it would make the README more obvious as it's currently untitled. However, I think we need to mock this up in a design tool before deciding for sure as sometimes what sounds like a good idea turns out to be 🤢.

In terms of the technicals, we'd render the release notes as a partial turbo frame, as we do with the README.
