### ISSUE TITLE
Presence of Xcode project causing builds to fail

### ISSUE THREAD

**Issue by macdrevx** [SwiftPackageIndex/SwiftPackageIndex-Server#873]
https://swiftpackageindex.com/GEOSwift/GEOSwift/builds has builds that are failing because xcodebuild is seeing the Xcode project in the repo root. We keep that there in order to support Carthage. What we do in our CI pipelines is delete the xcodeproj before building the Swift package with `xcodebuild`. It's a bit of a hack, so if there are better ways to do this, I'm definitely open. I'd love for our project to show more green on the package index though.

**Comment by finestructure** [comment]
Hi Andrew, we've got a process in place to direct our build system to pick up schemes defined in an Xcode project file (see details here:
https://blog.swiftpackageindex.com/posts/the-swift-package-index-metadata-file-first-steps/)

So I think we could pick up those schemes without having to introduce a workaround to ignore your project file if you added a `.spi.yml` file like the following:

```yml
version: 1
builder:
  configs:
  - platform: macos
    scheme: GEOSwift-macOS
  ...
```

If that doesn't work for your case I think we could extend this file with an attribute to ignore the project file for a given (or all) platforms.

**Comment by macdrevx** [comment]
Our Xcode project is configured for Carthage (not generated by SPM) and for it to build, you have to run `$ carthage update` after cloning to build the dependencies.

One question I do have is about this bit from the [Builds FAQ](https://swiftpackageindex.com/docs/builds#built-how):

> How are packages built?
>
> The build system runs either xcodebuild or swift build depending on the platform and specified Swift versions.
>
> When running xcodebuild, we apply some heuristics to find the correct scheme to build. If a package contains a single scheme (as reported by xcodebuild -list), the build system will use that scheme. If xcodebuild -list reports multiple schemes, the build system will choose the one ending in -Package. Otherwise, it will try removing any Xcode project and workspace files and rely on SPM’s scheme discovery to autogenerate a package scheme.

From what I can tell from [this log](https://swiftpackageindex.com/builds/01C5D2E0-53BB-47AC-A079-A12291DBFBB4), for example, the build system indicates that it did not find any scheme ending in `-Package`, but I can't tell whether it tries the part in that final sentence about removing the Xcode project and workspace files. That's exactly what would be required, so I'm not sure why it'd be failing.

**Comment by finestructure** [comment]
Right, I was thinking it might take more than just picking the right scheme.

You're right that the deletion should kick in but there might be some other condition interfering. I'll take a closer look!

**Comment by finestructure** [comment]
Turns out `rm -rf "*.xcodeproj"` does not delete the project folder. TIL that double quotes don't glob and I cannot believe in almost three decades of Unix use I've not encountered this 😮

It needs to be `rm -rf *.xcodeproj`.

I always thought `'` doesn't glob while `"` does - but the difference is only `$` expansion, not globs.

Will push the fix shortly and rebuild your packages. Thanks a lot for spotting this!

**Comment by finestructure** [comment]
Looks like it's all working now:

<img width="693" alt="CleanShot 2021-01-11 at 14 13 33@2x" src="https://user-images.githubusercontent.com/65520/104186804-3d0a5380-5417-11eb-9008-91597bbbc8df.png">

https://swiftpackageindex.com/GEOSwift/GEOSwift/builds

Thanks again for the report!

**Comment by macdrevx** [comment]
Very interesting. Thanks for the fix!

**Comment by macdrevx** [comment]
Another question — 2 related repos are suffering from the same problem ([geos](https://swiftpackageindex.com/GEOSwift/geos/builds), [GEOSwiftMapKit](https://swiftpackageindex.com/GEOSwift/GEOSwiftMapKit/builds)). Is there a way for me to rerun the builds without pushing any changes?

**Comment by finestructure** [comment]
Other than by pushing changes and/or releases, we currently don't support that, no. But I'll just reset those builds for you and they should be refreshed in a couple of hours.

**Comment by macdrevx** [comment]
Thank you
