### ISSUE TITLE
Nightly package list script PR action does not complete

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#883]
The nightly job itself finishes and creates a PR but the validation job running on that newly created PR does not seem to complete.

https://github.com/SwiftPackageIndex/PackageList/pull/869#pullrequestreview-567908891

This is the second or third time I've observed this.

**Comment by finestructure** [comment]
Might be related to this https://github.com/actions/virtual-environments/issues/1814#issuecomment-759332761

**Comment by daveverwer** [comment]
Do we want to just move away from the GH Actions macOS issues and run this one on Linux too?

**Comment by finestructure** [comment]
Just closing and re-opening the PR fixes it, see: https://github.com/SwiftPackageIndex/PackageList/pull/875#issuecomment-762653361

**Comment by finestructure** [comment]
> Do we want to just move away from the GH Actions macOS issues and run this one on Linux too?

Missed that, sorry. As suspected, this doesn't seem to be an issue related to the platform, or at least there's a good enough chance it isn't that it's probably not worth the effort (for now).
