### ISSUE TITLE
Package collections license handling

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#890]
The authoritative field on `License` is the `url` and we should `nil` out the whole license if it is `nil`.

Currently, we're skipping a whole version or package if that's the case.

**Comment by daveverwer** [comment]
> Currently, we're skipping a whole version or package if that's the case.

Just so I'm clear, we were skipping it only in the package collection?

**Comment by finestructure** [comment]
Yes, this is all for package collection generation.
