### ISSUE TITLE
Log build details

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#892]
In order to better optimise our build capacity, we need to log more build package details in a parsable format.

We need

- timestamp
- package name
- revision

**Comment by finestructure** [comment]
We don't have the package name readily available, the best we can do is log the package id and resolve it during analysis. For the purpose of the analysis the name isn't really all that relevant anyway, I suppose.

**Comment by finestructure** [comment]
We also don't have version references, just `version.id`. There's no ideal way to report this out, just more or less intrusive ways.

For starters, I'll report out (package.id, version.id) pairs which we can start clustering. If we see a lot of churn in particular version ids we can map them to tag/branch references after the analysis.

**Comment by finestructure** [comment]
This won't really work for the following reason:

We want to see if branch version rate of change is something we could mitigate. However, because branch versions get deleted on change, we won't be able to associate version ids back to a package once that's happened. (Our db snapshots wouldn't be granular enough to "catch" all passing branch versions even if we wanted to try that.)

So we _do_ need to log package ids and references somehow.

**Comment by daveverwer** [comment]
If this is a big problem, then we could write a little script that fetches 24h of the build logs from S3 and parse out this information from the first 2 lines. That's obviously not ideal, but if it's a big problem it would work.

**Comment by daveverwer** [comment]
Hah, as I click send on this the PR comes in 😂

**Comment by finestructure** [comment]
Fixed in #893
