### ISSUE TITLE
Unexpected build failure

### ISSUE THREAD

**Issue by nbasham** [SwiftPackageIndex/SwiftPackageIndex-Server#913]
This is a non pressing issue, I understand you probably have lots to do, so don’t feel compelled to address this.

My package BlackLabsSwiftUIColor reports build failures in code that builds and works fine in the wild. I looked at other SwiftUI packages and noticed that one person had commented they added the following to their Package.swift file to fix build errors.

```swift
    platforms: [
        .iOS(.v13)
    ],

```
This fixes the build errors for me too, but when I try to import the package into a project, Xcode reports "Workspace Integrity" error "Couldn't load project". The build errors I’m seeing are suspect as they occur immediately in the following code:

```swift
import SwiftUI

@available(iOS 13.0, *)
public extension Color {
   
...
```
 
Stating that `Color` is not defined.

I didn’t see anything in the FAQ about this.

Norman

**Thank you for this awesome site!**

**Comment by finestructure** [comment]
Hi @nbasham , thanks for raising the issue.

I've just had a look and indeed you're right - constraining the platform fixes the build, both in SPI as well as for me locally in Xcode.

So from my perspective, SPI is correctly flagging the build problem.

If I understand correctly, this change causes an issue when embedding your package inside other projects? Could it be that these projects aren't correctly setting the minimum version?

I.e. I would suspect they need the same `platforms:` clause or a minimum deployment target of iOS 13 in their project settings. After all, your package cannot be deployed to anything older than that.

Does that make sense or am I misunderstanding your issue?

**Comment by finestructure** [comment]
PS: thanks a lot for your kind words about the site :)

**Comment by nbasham** [comment]
What you’re suggesting makes sense and seems obvious in retrospect. It appears that Xcode may be having some problems about the compile order of a project and it’s packages and that may have added to the confusion. developer.apple.com suggests using 

platforms: [
	.macOS(.v10_14), .iOS(.v13), .tvOS(.v13)
],


to support SwiftUI.

Hope I didn’t take too much of your time. I suspect others may wonder why their SwiftUI packages have build failures.

Thank you very much for your help,
Norman

**Comment by finestructure** [comment]
Hi Norman, no problem at all, good to know it's clearer now what's happening. I'll go ahead and close the issue now, please reopen in case you're still seeing issues!
