### ISSUE TITLE
App should prompt for a file/folder location when generating a playground

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#939]
When clicking "Create Playground" the app should prompt for a file/folder name to create rather than assuming one.

The default could be a new folder with the same name as the package, in the last directory that the user selected (default to "Desktop" on first run?) but the final destination/name should be user defined.

**Comment by finestructure** [comment]
Fixed in https://github.com/SwiftPackageIndex/SPI-Playgrounds/pull/3
