### ISSUE TITLE
Recent list indentation weird in mobile

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#943]
Not sure if it's easily fixable but the recent list alignment is a bit off in mobile:

<img width="199" alt="CleanShot 2021-02-17 at 14 30 35@2x" src="https://user-images.githubusercontent.com/65520/108211321-d6bad400-712c-11eb-9e32-9eb9bda8b277.png">

**Comment by daveverwer** [comment]
This is "working as intended" but that long `swift-tools-support-async ` package is pushing the centred alignment too far left so it looks weird.

They should probably be left-aligned, although that can look strange if it's all short package names.

**Comment by finestructure** [comment]
Yeah, I agree that they should be left-aligned in single column mode. I.e. if it all laid out like the bottom list then it'd look fine. The subtitle should give all of them a good amount of default width.

**Comment by finestructure** [comment]
Going to go ahead and close this as we're likely to make bigger changes to the home page soon anyway.
