### ISSUE TITLE
Improve badge message when builds are pending

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#953]
Stephen just pinged me, the badges seem to be broken:  https://swiftpackageindex.com/pointfreeco/swift-composable-architecture

![82FF5B9A-265B-4B9B-82FA-62125B702978](https://user-images.githubusercontent.com/65520/108906798-932b0300-7621-11eb-97fa-53e0dfb11cc3.jpeg)

**Comment by finestructure** [comment]
Weird, looks ok for Arena: https://swiftpackageindex.com/finestructure/Arena

![609239B9-9945-41C3-8FD1-B5B0D67C503D](https://user-images.githubusercontent.com/65520/108907101-f74dc700-7621-11eb-9e76-d359597f8664.jpeg)

**Comment by finestructure** [comment]
Right, this is because all builds are currently pending:

![33FDF5CF-476A-4937-9F3E-B1082B442532](https://user-images.githubusercontent.com/65520/108907590-91ae0a80-7622-11eb-8a59-cbf7eccda16d.jpeg)

We may want to change the text to reflect that.

**Comment by finestructure** [comment]
fyi @stephencelis

**Comment by finestructure** [comment]
This is more likely to happen at the moment as we're having a pretty significant build backlog.

**Comment by stephencelis** [comment]
Makes sense, thanks @finestructure! I'm not sure I know what the best solution would be. Using the most recently completed build could be a good fix but it also means it may be inaccurate for a period of time.

**Comment by daveverwer** [comment]
I think setting it to `pending` is probably the best idea, given the potential complexity of having to go back in history too.

As Sven mentioned, we're dealing with a few issues around build times at the moment. The fixes for that (container ships full of servers 😂) are in progress. We've also just finished some work on [making sure we only build what we need to build](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/954). We're hopeful that once the new hardware is online and the queues are back down, there should only be a `pending` status for a short amount of time (maybe a couple of hours) after a tagged release.

**Comment by Sherlouk** [comment]
Looks like we can use `allSignificantBuilds` in the `Package+Badge.swift` to check if all items (some items?) satisfy a status of `.pending` to change the message. 

I'm thinking we convert the response of `swiftVersionCompatibility` and `platformCompatibility` to be an enum containing cases for `available([values])`, `empty` and `pending` which will make it easy to switch on for the message function.
