### ISSUE TITLE
Implement a basic search scoring algorithm

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#96]
This search score should be used as the ORDER BY for the search API, and will be an initial version of the package quality score.

**Comment by daveverwer** [comment]
This is the search scoring algorithm currently in use in the SwiftPM Library:

<img width="661" alt="Screenshot 2020-05-20 at 13 39 02@2x" src="https://user-images.githubusercontent.com/5180/82446909-66006180-9a9f-11ea-86f6-79c5c82d0aca.png">

We could start with a recreation of this, and work from there?

`supports_latest_major_swift_version?` returns `true` if the project supports the latest major Swift version, for example, Swift 5.2 would pass this, as would Swift 5, but Swift 4.2 would not.

`oss_license?` returns is the equivalent of `isCompatibleWithAppStore` in our current `License` model enum.

**Comment by finestructure** [comment]
The first criterion, "supports latest swift version" brings up a topic I wanted to address: we're currently taking swift version as plain strings. Looking at the distinct set of values, we've got the following in our:

```
3
3.0
4
4.0
4.1
4.2
5
5.0
5.0.0
5.1
```

We could leave it at that and parse the raw values we've got in here when we compute the score. But it might be better also for other times when we're looking at swift versions to parse this into proper swift versions when populating the table, i.e. making it a proper type, just like `Platform`:

```
    @Field(key: "supported_platforms")
    var supportedPlatforms: [Platform]

    @Field(key: "swift_versions")
    var swiftVersions: [SwiftVersion]
```

If we were to do that, we'd need to decide what to do with `5` vs `5.0` and the like. Are they the same? I'm leaving it as is for now and will try to deal with the variants inside the scoring function.

**Comment by daveverwer** [comment]
So the way I handle this in the SwiftPM library is that I convert Swift versions into full semantic versions as I parse the Package.swift dump, and the *only* type of Swift version that gets stored.

Then, at display time, I just knock off .0's from the semantic version until there's none left, because Apple *don't* use semantic versions to refer to Swift versions.

<img width="329" alt="Screenshot 2020-05-24 at 21 42 18@2x" src="https://user-images.githubusercontent.com/5180/82764559-95003580-9e07-11ea-8408-5af8e29c1e2b.png">

**Comment by finestructure** [comment]
I’d prefer that over storing `String`! How about I do that as a refinement follow-up of the scoring PR? I don’t want to stick too much in it and the change won’t affect the scores itself.

**Comment by finestructure** [comment]
Swift versions change follow up here: #144
