### ISSUE TITLE
Why do Parser builds take so long (4.5mins), even on prod?

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#965]
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1064040292
- https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1064040314
- might be resolver in 5.0 and earlier
- Kitura manager also taking ages (40m and counting), resolver issue? https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1069330985

**Comment by finestructure** [comment]
Need to review the whole build process in detail but it can't be due to the compile step. See https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1072802375, which took 4.5m on spi-prod but when run manually on the same machine this fails very fast:

```
builder@spi-prod ~/Downloads> ./builder checkout -c https://github.com/apple/swift-numerics.git -r main -f
Clone URL: https://github.com/apple/swift-numerics.git
Reference: main
Initialized empty Git repository in /Users/builder/Downloads/checkout/.git/
From https://github.com/apple/swift-numerics
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
HEAD is now at 9f55a78 Merge pull request #175 from stephentyrone/eighty-columns-wide-my-father-lies
Cloned https://github.com/apple/swift-numerics.git into ./checkout
9f55a78685ca4787e217f179b29ab8c87306512d
builder@spi-prod ~/Downloads> time ./builder build -p ios -s 4.2.3
Selected platform:         ios
Swift version:             v4_2
Building package at path:  ./checkout
User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/builder/Downloads/checkout/.dependencies

xcodebuild: error: The directory /Users/builder/Downloads/checkout does not contain an Xcode project or workspace.

Error: ShellOut encountered an error
Status code: 66
Message: "xcodebuild: error: The directory /Users/builder/Downloads/checkout does not contain an Xcode project or workspace.
"
Output: "User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/builder/Downloads/checkout/.dependencies
"

________________________________________________________
Executed in    2.34 secs   fish           external
   usr time  548.05 millis   94.00 micros  547.96 millis
   sys time  717.57 millis  425.00 micros  717.14 millis
```

**Comment by finestructure** [comment]
Kitura-manager seems to have taken 4:09 to clone:

<img width="733" alt="CleanShot 2021-03-04 at 13 37 10@2x" src="https://user-images.githubusercontent.com/65520/109965174-e589b500-7cee-11eb-8a8b-e19be51795ac.png">

https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1072498939

**Comment by finestructure** [comment]
Actually, that's the clone of the builder repo, inside which we're then running the checkout (line 29). The builder binary is almost 50mb and I wonder if we're seeing these slow builds when the builder is updated (and only then) when the builder binary comes down in the step on line 9.

It shouldn't take 4m to fetch a 50mb git repo but Gitlab can be a bit slow at times.

**Comment by daveverwer** [comment]
I just tried a fresh clone of the builder to see if this was a problem for me, and it's not. The repo size is ~150Mb and it cloned in under a minute for me.

**Comment by finestructure** [comment]
I've just run the complete build script on spi-prod for the same job config as [for Parser (linked above)](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1064040292) and it completes in less than 10s:

```sh
#!/bin/sh

export API_BASEURL=https://staging.swiftpackageindex.com/api
export AWS_ACCESS_KEY_ID=blank
export AWS_SECRET_ACCESS_KEY=blank
export BUILDER_TOKEN=blank
export BUILD_PLATFORM=watchos
export CLONE_URL=https://github.com/finestructure/Parser.git
export REFERENCE=0.2.0
export SWIFT_VERSION=5.1.5
export VERSION_ID=18934AF0-A02A-49C5-AA65-D4EDAABA7A28

export CI_JOB_URL=blank

time ./build.sh
```

**Comment by finestructure** [comment]
It must be the git clone stage. Here's [another job](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1073017543) from just a moment ago:

<img width="917" alt="CleanShot 2021-03-04 at 15 59 29@2x" src="https://user-images.githubusercontent.com/65520/109982979-b2e9b780-7d02-11eb-9125-3d2b735dd225.png">

Again, 4.5m just to clone the builder. Note the `Reinitialized existing Git repository ...`. It _should_ be fetching diff and really do nothing if the builder hasn't changed.

**Comment by finestructure** [comment]
Some for a [job on spi-dev](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1073017553):

<img width="914" alt="CleanShot 2021-03-04 at 16 02 41@2x" src="https://user-images.githubusercontent.com/65520/109983411-170c7b80-7d03-11eb-851f-6fe3c57eab48.png">

So it's probably not a machine/network issue.

**Comment by finestructure** [comment]
What's notable is that this only seems to be happening on jobs running on spi-dev and spi-prod, which are on `gitlab-runner 13.1.0`. The new machines are on `gitlab-runner 13.9.0`. I'll bump the runner on spi-prod to see if that makes a difference.

**Comment by finestructure** [comment]
Issue persists on both spi-prod and spi-dev even after updating `gitlab-runner`. The DTK is on 1.1.1 and doesn't seem to be having this issue. Another difference: spi-dev and spi-prod are on Catalina.

**Comment by finestructure** [comment]
As discussed, we'll test for those two scenarios when moving the Linux runners to new hosting and resetting spi-prod.

**Comment by finestructure** [comment]
Mmmm, now I'm seeing this in a current job:

<img width="926" alt="CleanShot 2021-03-05 at 11 10 41@2x" src="https://user-images.githubusercontent.com/65520/110101154-833ebc00-7da3-11eb-8a30-4cc2e51470ba.png">

**Comment by finestructure** [comment]
Ah, Finder permissions for the runner after the update...

**Comment by finestructure** [comment]
Doesn't seem to be a universal problem. There are two jobs for the same package, tvOS and iOS, both run on `spi-dev`

- [tvOS: 2m58s](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1075548653)
- [iOS: 40s](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1075548911)

<img width="1115" alt="CleanShot 2021-03-05 at 11 15 17@2x" src="https://user-images.githubusercontent.com/65520/110102067-9dc56500-7da4-11eb-8c33-71d22bd01b7e.png">
<img width="1111" alt="CleanShot 2021-03-05 at 11 15 36@2x" src="https://user-images.githubusercontent.com/65520/110102094-a4ec7300-7da4-11eb-86ab-04d3de4c2d7b.png">

**Comment by finestructure** [comment]
Ok, I think I'm getting closer. I just had an idea to cd into the build directory and try a git command to see if something's up. It turned out that *cd'ing into the directory*

```
cd /Users/builder/builds/x2J62p_Y/0/finestructure/swiftpackageindex-builder
```

on `spi-dev` took *57 seconds*. Clearly something is busted here. I suspect it's the same for prod, although it's not clear how that would happen on two machines.

Might try deleting the directories.

**Comment by daveverwer** [comment]
We broke `cd`? 😅

That's impressive!

**Comment by finestructure** [comment]
Same on prod, also the `0` entry. I've deleted `~/builds` on dev. Should be recreated when new jobs come online but I'll wait to confirm before deleting on prod.

**Comment by finestructure** [comment]
`builds` has been recreated and a job now ran in 18s: https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1083244773

Deleting on prod and then closing.
