### ISSUE TITLE
Fetch the URL for the account/organisation along with the GitHub metadata

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#975]
Ideally via the GraphQL request, I think it's the [`avatar_url`](https://docs.github.com/en/rest/reference/users) property we need.

Basically, this image here:

<img width="393" alt="Screen Shot 2021-03-05 at 17 33 28@2x" src="https://user-images.githubusercontent.com/5180/110151884-ea2a9800-7dd8-11eb-8fe6-9cf0b36e8262.png">

**Comment by daveverwer** [comment]
We should also fetch the organisation/account full name while we do this to make #980 possible

**Comment by elfenlaid** [comment]
I'll have a look at it and #980 if everyone is okay with that

**Comment by elfenlaid** [comment]
By the way, what are the next steps for the issue after the data is collected?

I assume the avatar should appear somewhere alongside the package's name at the package's page header?

**Comment by daveverwer** [comment]
> By the way, what are the next steps for the issue after the data is collected?

#980 follows on from this for the organisation name. The avatar is a little different and doesn't currently fit well into the site design. I have a couple of ideas where we could use it, but no plans immediately for that info.

**Comment by elfenlaid** [comment]
> > By the way, what are the next steps for the issue after the data is collected?
> 
> #980 follows on from this for the organisation name. The avatar is a little different and doesn't currently fit well into the site design. I have a couple of ideas where we could use it, but no plans immediately for that info.

Ah, got it. So we can probably close this issue at this point or otherwise rename it 🤔

**Comment by daveverwer** [comment]
Yep, this one is done! Thanks @elfenlaid
