### ISSUE TITLE
Use the GitHub organisation title when available

### ISSUE THREAD

**Issue by helje5** [SwiftPackageIndex/SwiftPackageIndex-Server#980]
Small feature request. The index currently uses the organisation part of the repository URL as the organisation "title". For example "Macro-swift" in here (but also appears in other contexts):

![Screenshot 2021-03-08 at 17 40 58](https://user-images.githubusercontent.com/7712892/110351759-73d6a180-8035-11eb-81f1-0c0f8ef598c9.png)

It would be cool if those places would actually use the GitHub organisation name, when available. E.g. "Macro.swift" in this case: https://github.com/Macro-swift:

![Screenshot 2021-03-08 at 17 42 29](https://user-images.githubusercontent.com/7712892/110351985-a8e2f400-8035-11eb-8b7c-4419287d0f41.png)

(the two usually differ if the organisation name uses character which are not allowed in the GH backend, e.g. the `.` in this case).

**Comment by daveverwer** [comment]
Great idea. We'll collect that information as part of #975. Thanks Helge

**Comment by elfenlaid** [comment]
It's hard to find all the appropriate places. Though, here's what I've got after a search for `model.owner` field usage and following the discussion:

- The author's (organization) page:
    - https://swiftpackageindex.com/Macro-swift
- The package's page
    - "More packages from this author" -> "More packages from <organization>"?

What do you think about truncating long organization names?

- The author's page 
![Screenshot 2021-05-25 at 14 55 25](https://user-images.githubusercontent.com/765790/119509353-3dc5d580-bd79-11eb-80fe-94bf9cbb6bf7.png)
- The package's page
![Screenshot 2021-05-25 at 16 47 17](https://user-images.githubusercontent.com/765790/119509329-38688b00-bd79-11eb-9f12-31eb515e69ae.png)

**Comment by daveverwer** [comment]
This is great progress. Some things to note:

* Looking at the real-world data we've gathered, better test data would include spaces. There are some long owner names, up to 38 characters to be specific, but they all have several spaces in them. I'd imagine wrapping will work better than truncation.
* There may be some extreme cases in the future where we get a very long owner name without spaces. I'd suggest we cope with this as and when it happens as I don't think it's likely to be a big problem.
* We should fallback to the owner username when the owner name is blank, there are 102 owners with a `NULL` owner_name

I've attached a CSV file of the longest owner names. I've also DMed you a copy of the latest database so you can test with real-world data.
