### ISSUE TITLE
Add the SPI logo and colours to the shields.io badges

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#993]
`?logo=data:image/png;base64,…`

> Insert custom logo image (≥ 14px high). There is a limit on the total size of request headers we can accept (8192 bytes). From a practical perspective, this means the base64-encoded image text is limited to somewhere slightly under 8192 bytes depending on the rest of the request header.

from https://shields.io

**Comment by Sherlouk** [comment]
What's probably more appropriate than base64 encoding the logo, would be to update the endpoint which we define.

Documentation: https://shields.io/endpoint

We can provide a new value called `logoSvg` which can be equal to the "logo.svg" file. This also doesn't have the same length restriction as the URL (not that it's a particular issue given the SVG is small but good to know)

**Comment by daveverwer** [comment]
The important thing with this is to use the simpler version of the logo `logo-simple.png` in the `Public/images` directory rather than `logo.png`.

**Comment by Sherlouk** [comment]
Is there a SVG version of that simplified version @daveverwer? 

The PNG (base64) route is seemingly reserved for URL concatenation only, whereas the endpoint JSON prefers to use SVG instead. I believe the SVG route offers a better experience for users, and means all existing badges will automatically update without markdown needing to be updated.

**Comment by daveverwer** [comment]
[logo-simple.svg.zip](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/files/6689745/logo-simple.svg.zip)
